#!/usr/bin/env python3
"""Build the indexable landing pages and the sitemap.

Theraglee's tools, quizzes and articles live in the database and are drawn by
JavaScript from a `?slug=` query string, so a search engine arriving at one of
them sees an empty shell. These pages are the readable front door: real HTML,
served at a descriptive URL, with the intro and the links already in the
markup.

    python3 tools/build_seo_pages.py

Source rows are in `data/seo-pages.json`. Output is `site/<path>/index.html`
for each row, plus `site/sitemap.xml` covering those pages and the public
pages at the site root. Never hand-edit the output; change the source row or
this script and run it again.

A folder holding an `index.html` is served at the folder's own path, so
`site/tools/anxiety-quiz/index.html` answers to `/tools/anxiety-quiz` with no
redirect and no change to `vercel.json`.
"""

from __future__ import annotations

import html
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "data" / "seo-pages.json"
SITE = ROOT / "site"

# Public pages at the site root that belong in the sitemap. Anything behind a
# sign-in, anything about one member's own account, and the 404 are left out.
PUBLIC_ROOT_PAGES = [
    ("index.html", "1.0"),
    ("therapists.html", "0.9"),
    ("for-therapists.html", "0.9"),
    ("articles.html", "0.8"),
    ("pricing.html", "0.7"),
    ("discover.html", "0.7"),
    ("explore.html", "0.6"),
    ("challenges.html", "0.6"),
    ("founding-members.html", "0.5"),
    ("signup.html", "0.5"),
    ("therapist-signup.html", "0.5"),
    ("privacy.html", "0.3"),
    ("terms.html", "0.3"),
]

GENERATED_BANNER = (
    "<!-- Generated by tools/build_seo_pages.py from data/seo-pages.json. "
    "Do not edit by hand. -->"
)


# Hand-maintained pages whose FAQ structured data is derived from the questions
# a visitor can actually read on them: (file, canonical url, heading to read
# the questions after). Google requires the markup to match visible content, so
# it is generated from that content rather than written twice.
FAQ_PAGES = [
    ("index.html", "https://theraglee.com/", "<h2 style=\"text-align:center\">Common questions</h2>"),
    ("for-therapists.html", "https://theraglee.com/for-therapists.html", "<h2>Questions</h2>"),
]

FAQ_START = ("<!-- faq-jsonld:start \u2014 generated by tools/build_seo_pages.py from the "
             "questions visible on this page. Do not edit by hand. -->")
FAQ_END = "<!-- faq-jsonld:end -->"

CARD = re.compile(
    r'<div class="card"><h3>(.*?)</h3>\s*<p class="muted"[^>]*>(.*?)</p></div>', re.S)


def plain(fragment: str) -> str:
    """The words a visitor reads, with the tags and line wrapping taken out."""
    return html.unescape(re.sub(r"<[^>]+>", "", " ".join(fragment.split()))).strip()


def sync_faq_jsonld(filename: str, url: str, heading: str) -> int:
    """Rewrite one page's FAQPage block from the questions printed on it."""
    path = SITE / filename
    text = path.read_text(encoding="utf-8")
    if heading not in text:
        print(f"error: {filename} has no {heading!r} section", file=sys.stderr)
        return -1
    start = text.index(heading)
    end = text.index("</section>", start)
    pairs = [(plain(q), plain(a)) for q, a in CARD.findall(text[start:end])]
    if not pairs:
        print(f"error: {filename} has no question cards to describe", file=sys.stderr)
        return -1

    block = json_ld({
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntityOfPage": url,
        "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in pairs],
    })
    i, j = text.index(FAQ_START), text.index(FAQ_END)
    path.write_text(
        text[:i] + FAQ_START + "\n" + block + "\n" + text[j:], encoding="utf-8")
    return len(pairs)


def esc(text: str) -> str:
    return html.escape(text, quote=True)


def page_html(page: dict, site: str) -> str:
    """One landing page: static content first, the site's own chrome after."""
    url = f"{site}/{page['path']}"
    blocks = "\n".join(
        f'      <section class="seo-block">\n'
        f'        <h2>{esc(b["h2"])}</h2>\n'
        f'        {b["html"]}\n'
        f'      </section>'
        for b in page.get("blocks", [])
    )

    related = ""
    rel = page.get("related")
    if rel:
        items = "\n".join(
            f'          <a class="tile" href="{esc(i["href"])}">\n'
            f'            <strong>{esc(i["label"])}</strong>\n'
            f'            <span class="muted">{esc(i["note"])}</span></a>'
            for i in rel["items"]
        )
        related = (
            f'      <section class="seo-block">\n'
            f'        <h2>{esc(rel["h2"])}</h2>\n'
            f'        <div class="seo-tiles">\n{items}\n        </div>\n'
            f'      </section>'
        )

    faq_html = ""
    faq_ld = ""
    if page.get("faq"):
        rows = "\n".join(
            f'          <details class="seo-faq">\n'
            f'            <summary>{esc(f["q"])}</summary>\n'
            f'            <p>{esc(f["a"])}</p></details>'
            for f in page["faq"]
        )
        faq_html = (
            f'      <section class="seo-block">\n'
            f'        <h2>Common questions</h2>\n{rows}\n'
            f'      </section>'
        )
        faq_ld = "\n" + json_ld(
            {
                "@context": "https://schema.org",
                "@type": "FAQPage",
                "mainEntity": [
                    {
                        "@type": "Question",
                        "name": f["q"],
                        "acceptedAnswer": {"@type": "Answer", "text": f["a"]},
                    }
                    for f in page["faq"]
                ],
            }
        )

    article_ld = json_ld(
        {
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": page["h1"],
            "description": page["description"],
            "mainEntityOfPage": url,
            "author": {"@type": "Organization", "name": "Theraglee", "url": site},
            "publisher": {
                "@type": "Organization",
                "name": "Theraglee",
                "url": site,
                "logo": {"@type": "ImageObject", "url": f"{site}/assets/apple-touch-icon.png"},
            },
        }
    )

    return f"""<!doctype html>
<html lang="en">
{GENERATED_BANNER}
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<base href="/">
<title>{esc(page['title'])}</title>
<meta name="description" content="{esc(page['description'])}">
<link rel="canonical" href="{esc(url)}">
<meta property="og:type" content="article">
<meta property="og:title" content="{esc(page['title'])}">
<meta property="og:description" content="{esc(page['description'])}">
<meta property="og:url" content="{esc(url)}">
<meta name="twitter:card" content="summary">
<link rel="icon" href="/assets/favicon.svg" type="image/svg+xml">
<link rel="alternate icon" href="/assets/favicon.png" sizes="48x48">
<link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Outfit:wght@200;300;400;500;600&family=Instrument+Serif:ital@0;1&display=swap">
<link rel="stylesheet" href="/assets/styles.css">
<style>
  .seo-wrap{{max-width:760px;margin:0 auto;padding:44px 0 72px}}
  .seo-wrap h1{{font-size:clamp(1.9rem,4vw,2.7rem);font-weight:300;letter-spacing:-.03em;margin:0 0 .5em}}
  .seo-lede{{font-size:1.08rem;color:var(--muted);margin:0 0 6px}}
  .seo-block{{margin-top:34px}}
  .seo-block h2{{font-size:1.28rem;font-weight:500;margin:0 0 .6em}}
  .seo-block p{{margin:0 0 .9em}}
  .seo-block ul,.seo-block ol{{margin:0 0 .9em;padding-left:1.25em}}
  .seo-block li{{margin:0 0 .45em}}
  .seo-tiles{{display:grid;gap:12px;grid-template-columns:repeat(auto-fit,minmax(240px,1fr))}}
  .seo-tiles .tile{{display:flex;flex-direction:column;gap:4px}}
  .seo-faq{{border-top:1px solid var(--hair);padding:12px 0}}
  .seo-faq summary{{cursor:pointer;font-weight:500}}
  .seo-faq p{{margin:.6em 0 0;color:var(--muted)}}
</style>
{article_ld}{faq_ld}
</head>
<body>
<main>
  <div class="wrap">
    <article class="seo-wrap">
      <h1>{esc(page['h1'])}</h1>
      <p class="seo-lede">{esc(page['intro'])}</p>
{blocks}
{related}
{faq_html}
    </article>
  </div>
</main>

<script type="module">
import {{ chrome }} from '/assets/app.js';
await chrome();
</script>
</body>
</html>
"""


def json_ld(obj: dict) -> str:
    body = json.dumps(obj, indent=2, ensure_ascii=False)
    # A closing tag inside JSON would end the script element early.
    body = body.replace("</", "<\\/")
    return f'<script type="application/ld+json">\n{body}\n</script>'


def sitemap(site: str, paths: list[str]) -> str:
    urls = []
    for page, priority in PUBLIC_ROOT_PAGES:
        # The homepage canonical is the bare domain with a slash; match it here.
        loc = f"{site}/" if page == "index.html" else f"{site}/{page}"
        urls.append((loc, priority))
    for path in paths:
        urls.append((f"{site}/{path}", "0.8"))
    entries = "\n".join(
        f"  <url>\n    <loc>{esc(loc)}</loc>\n"
        f"    <priority>{priority}</priority>\n  </url>"
        for loc, priority in urls
    )
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!-- Generated by tools/build_seo_pages.py. Do not edit by hand. -->\n'
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
        f"{entries}\n</urlset>\n"
    )


def main() -> int:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    site = data["site"].rstrip("/")
    pages = data["pages"]

    seen = set()
    for page in pages:
        path = page["path"]
        if not re.fullmatch(r"[a-z0-9]+(?:[-/][a-z0-9]+)*", path):
            print(f"error: path {path!r} is not a clean lowercase URL", file=sys.stderr)
            return 1
        if path in seen:
            print(f"error: duplicate path {path!r}", file=sys.stderr)
            return 1
        seen.add(path)

        out = SITE / path / "index.html"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(page_html(page, site), encoding="utf-8")
        print(f"wrote site/{path}/index.html")

    for filename, url, heading in FAQ_PAGES:
        count = sync_faq_jsonld(filename, url, heading)
        if count < 0:
            return 1
        print(f"synced site/{filename} FAQ structured data ({count} questions)")

    (SITE / "sitemap.xml").write_text(sitemap(site, [p["path"] for p in pages]), encoding="utf-8")
    print(f"wrote site/sitemap.xml ({len(PUBLIC_ROOT_PAGES) + len(pages)} urls)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
