// Generates the migration that seeds public.discover_tools from the browser's
// own copy of the tool list, so the weekly email and the site can never drift
// apart on what a tool is called.
//
//   node tools/discover_tools_sql.mjs
//
// Writes supabase/migrations/20260921050100_discover_tools_seed.sql. The
// statement is an upsert on slug, so applying it twice is harmless. Re-run it
// whenever site/assets/discover-tools.js gains or loses a tool.
import { writeFileSync } from 'node:fs';
import { TOOLS } from '../site/assets/discover-tools.js';

const OUT = new URL('../supabase/migrations/20260921050100_discover_tools_seed.sql', import.meta.url);
const q = (v) => v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`;

const rows = TOOLS.map((t, i) => {
  for (const f of ['slug', 'title', 'description', 'topic', 'kind']) {
    if (!t[f]) throw new Error(`tool ${t.slug || i} is missing ${f}`);
  }
  return `  (${q(t.slug)}, ${q(t.title)}, ${q(t.description)}, ${q(t.topic)}, ` +
         `${q(t.kind)}, ${Number(t.minutes) || 5}, ${i})`;
});

const sql = `-- =============================================================================
-- The free discovery tools, as the weekly email sees them.
-- -----------------------------------------------------------------------------
-- Generated by tools/discover_tools_sql.mjs from site/assets/discover-tools.js.
-- Do not edit by hand: change the tool in that file and run the generator.
--
-- Every row here is free and needs no account, which is what the Sunday email
-- promises. The email reads title, description and minutes, and links to
-- /discover.html?slug=<slug>.
-- =============================================================================

insert into public.discover_tools (slug, title, description, topic, kind, minutes, position)
values
${rows.join(',\n')}
on conflict (slug) do update set
  title       = excluded.title,
  description = excluded.description,
  topic       = excluded.topic,
  kind        = excluded.kind,
  minutes     = excluded.minutes,
  position    = excluded.position;
`;

writeFileSync(OUT, sql);
console.log(`wrote ${TOOLS.length} tools to supabase/migrations/20260921050100_discover_tools_seed.sql`);
