-- Five articles published 2026-10-01. Generated by:
--   python3 tools/articles_sql.py --since 2026-10-01
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('when-siblings-disagree-about-a-parents-care', 'When Siblings Disagree About a Parent''s Care', 'One of you does the driving and the laundry, another has opinions from three states away. How to handle the old family patterns that surface when a parent needs help.', 'You are the one who takes the calls from the hospital. Your brother thinks the doctors are being too cautious. Your sister has looked something up and thinks you should both be doing it differently.

None of you is wrong exactly, and all of you are frightened. But what comes out is a fight about a medication schedule.

Caring for an aging parent puts a family back into its oldest shapes. Whoever was the responsible one is responsible again. Whoever was protected is still being protected. And nobody has agreed to any of this out loud.

The fight is usually not about the thing

Arguments between siblings in this situation tend to be about logistics on the surface and something else underneath.

Underneath there is often fear, which comes out as urgency or as criticism. There is guilt from whoever lives furthest away, which can look like second-guessing the person doing the work. There is resentment from whoever is doing the most, which can look like refusing help when it is finally offered. And there is grief, early and unnamed, because you are all watching the same person change.

Knowing that does not settle a disagreement, but it changes how you hear one. Your brother questioning the care plan may be the only way he can say he is scared.

Separate the three things you are actually deciding

Most care disputes are three separate conversations tangled together, and untangling them helps enormously.

What is best for your parent, as far as anyone can tell. Who does what, practically. And who pays for what.

Try to take them one at a time, in that order, and say which one you are on. Half of these arguments are two people answering different questions in the same sentence.

Make the invisible work visible

The person doing the day-to-day care is usually carrying far more than anyone else can see: the appointments, the phone calls with insurers, the prescriptions, the laundry, the worrying at two in the morning.

If that is you, write it down. Not as an accusation, as a list. Hours, tasks, who it falls to. A list is harder to dismiss than a feeling, and it turns I am doing everything, which invites argument, into here is what there is, which invites help.

If it is not you, assume the list is longer than you think, and ask for it rather than for a summary. Then take something specific off it, permanently rather than once.

Ask for tasks, not for help in general

Help in general is what people offer and nobody delivers. A named task with a day attached is what actually moves.

So be concrete in both directions. Can you handle all the insurance calls from now on. Can you take Sunday afternoons. Can you be the one who talks to the pharmacy. Can you make the decisions about the house.

And accept that distant siblings can do real work remotely: paperwork, research, bills, scheduling, chasing. Somebody who cannot drive your mother to an appointment can still own everything that happens on a phone.

Hold one meeting, with an agenda

Care decisions made in group chats and in hospital corridors go badly. One scheduled conversation, with everyone on it, does better.

Keep it short and have three or four items. Start with what you all agree on, which is usually more than it feels like. Write down what was decided and send it round afterward, because people remember these conversations differently.

If it goes straight into old grievances every time, bring in a third party: a social worker attached to your parent''s care, a geriatric care manager, or a mediator who works with families. That is not a failure. For many families it is the thing that finally allows a decision.

Remember whose life it is

The person most often left out of these arguments is the parent. If your mother can say what she wants, her view outranks all of yours, including when you think she is wrong.

Ask her directly and separately, away from the sibling with the loudest opinion. Ask what matters most to her rather than only what she will accept: staying in her house, not being a burden, keeping her routine, being near the grandchildren.

Where her choices carry real risk, the conversation is about reducing risk within what she wants, not about overruling her. And if her judgment is genuinely failing, that is a medical and legal question, with a formal process behind it, rather than something siblings should settle among themselves.

Accept that it will not be equal

It almost never is. Geography, work, money, and old history mean one person usually does more, and often that is the person it was always going to be.

You can get it fairer, but you probably cannot get it even. What helps most is having it said out loud: I am doing most of this, and I need two specific things from you. Unacknowledged imbalance is what turns into years of resentment; acknowledged imbalance is survivable.

And if a sibling will not help at all, you will get further planning around them than fighting for a version of them that does not exist. That is a loss worth grieving separately, with someone other than them.

When to bring in support

If the disagreements are constant, if you are not sleeping, or if the caring has taken over your own life, this is worth real support rather than endurance. A therapist can help with both the caregiving load and the family patterns underneath it, and many areas have free caregiver support groups where people are dealing with exactly these arguments. A doctor is also the right place to go if your own health has slipped while you have been looking after someone else''s.', array['Caregiving', 'Family']::text[], 0, '2026-10-01T14:00:00+00:00'::timestamptz),
  ('how-to-help-someone-having-a-panic-attack', 'How to Help Someone Having a Panic Attack', 'Someone you care about is panicking in front of you. What to say, what to avoid, and why doing less is usually more useful than trying to fix it.', 'Someone you love is sitting on the edge of a chair, breathing fast, telling you they cannot breathe, and asking if they are having a heart attack.

Your instinct is to do something: reassure them, find a solution, get them out of there. Some of those instincts help. A few of them make it worse.

The good news is that the useful version is simpler than it looks, and it mostly involves being calm and staying put.

What is happening to them

A panic attack is an alarm system firing when there is no emergency. Adrenaline floods the body, the heart speeds up, breathing gets fast and shallow, and the whole system prepares to run from something that is not there.

It peaks and then comes down on its own, usually within several minutes, because the body cannot sustain it. That matters for you, because it means your job is not to stop it. Your job is to be a steady presence while it passes.

The fear of the panic is often the larger part, especially the fear of losing control or being humiliated. That is the part you can actually affect.

The first thing to do is slow yourself down

Panic is catching. If your voice goes up and you start moving quickly, their alarm reads that as confirmation that something is genuinely wrong.

So drop your own volume and pace. Breathe slowly yourself, visibly. Sit down rather than standing over them. Keep your hands still.

You are not performing calm for their benefit so much as giving their nervous system something quieter to sync with, which it does more than people expect.

What to say

Short sentences. Simple words. Nothing clever.

I am here. This is a panic attack. It will pass. You are safe. Breathe out with me, slowly.

Then stop talking and let there be quiet. A stream of reassurance is hard to process in that state, and silence with someone next to you is often the most useful thing in the room.

If they can manage it, breathe with them: in for four, out for six or seven, with the out-breath longer. Do it out loud and let them follow. Do not tell them to take a deep breath; people in panic usually have too much air, not too little, and gasping makes the dizziness worse.

Give them something physical and dull to do: feet pressed into the floor, something cold to hold, naming five things they can see.

What not to say

Calm down. There is nothing to worry about. Why are you like this. You were fine a minute ago. Just relax.

All of these say the same thing underneath: your reaction is wrong. That adds shame to panic, and shame makes the next one more likely and harder to admit to.

Also avoid interrogating them about why it started. That can come later if they want it to. Mid-wave, explaining is one more demand on a system that is already overloaded.

Ask before you touch

A hand on the back helps some people enormously and makes others feel trapped. You cannot tell by looking.

So ask plainly: would it help if I held your hand, or would you rather I just sit here. Either answer is fine, and asking itself gives them a small piece of control back at a moment when they feel they have none.

The same goes for leaving. Do you want to go outside, or stay here. Shall I stay or give you a minute. Let them choose.

Do not rush them out of the situation

This one is subtle. Getting someone out of a crowded room can be a kindness, and it can also teach both of you that escape is the only thing that works.

If they want to leave, help them leave; this is not the moment for exposure practice. But if they can stay, stay with them, and afterward notice out loud what happened: it came, it peaked, it passed, and you got through it here.

Over time that is the thing that shrinks panic. Being rescued every time tends to make the world smaller.

Afterward

People are often exhausted and embarrassed once it passes. Both are worth answering.

Keep it light and matter-of-fact. Something like: that looked rough, I am glad I was here, do you want a glass of water. No big debrief unless they start one.

Later, when things are ordinary again, ask what they want next time: what helped, what did not, whether there is a phrase they want you to use. A plan made in a calm moment is worth a great deal in a bad one.

When it is more than panic

Panic itself is not dangerous, but a few things need medical attention. If this is the first time anything like it has happened, if there is chest pain spreading to the arm or jaw, trouble breathing that does not ease as the panic settles, fainting, or confusion, treat it as a medical emergency and call for help rather than assuming it is panic.

And if panic is happening regularly, encourage them to see a doctor or a therapist; it responds very well to treatment, often in a short course of therapy. If they ever tell you they do not want to be here anymore, take it seriously, stay with them, and help them reach someone that day. In the US you can call or text 988 at any time.', array['Panic', 'Relationships']::text[], 0, '2026-10-01T14:00:00+00:00'::timestamptz),
  ('doing-fewer-things-on-purpose', 'Doing Fewer Things on Purpose', 'Six half-started projects produce less than one finished. How to choose what to drop, what to formally pause, and how to hold the single thing you keep.', 'You have the language course, the side project, the fitness plan, the book you are writing, the room you are redecorating and the thing you promised a friend.

None of them is finished. All of them are open. And each one, in its own small way, is on your mind every day, which is why you can be busy from morning to night and still end the month feeling as though you did nothing.

The problem here is not laziness or a lack of discipline. It is arithmetic.

Open things cost something even when you are not doing them

An unfinished project is not neutral while it waits. It takes up a small amount of attention continuously: a flicker of guilt when you see it, a decision every day about whether today is the day, a bit of mental filing to keep it alive.

Six of those is a constant low drain, and it comes out of the same supply you need for the one thing you actually care about most.

This is why dropping things can feel like relief out of all proportion to the work involved. You are not just saving the hours; you are turning off the background noise.

Progress is not divisible the way you hope

People imagine that splitting your effort splits your progress proportionally. It rarely does.

Most worthwhile things need a run at them: enough consecutive attention to get past the awkward early part and into the bit where it starts to work. Spread thin, you keep paying the start-up cost and never arrive at the part that pays you back.

Which means one thing done properly for three months will usually beat four things done at a quarter strength for a year, and it will feel completely different to live through.

How to choose what stays

Pick the one that fits two conditions: it matters to you, not to an imagined version of you, and you would still want it if nobody ever knew you did it.

That second test is useful. A surprising number of open projects are there because they belong to a self we think we should be: the person who speaks Italian, the person who runs. If the only reward is being seen to have done it, that is worth knowing before you give it another year.

If two things tie, pick the one with a nearer end. Finishing something is a skill and a tonic, and it makes the next choice easier.

Drop, pause, and park are three different things

Be specific about what happens to the rest, because vagueness is what keeps them half-alive.

Dropped means it is over. Say so out loud, delete the file, cancel the subscription, tell whoever needs to know. A dropped project is a decision, not a failure.

Paused means a date. Not someday: a month. Put it in the calendar, write one line about where you left it, and close it. Paused with a date can sit quietly; paused with no date keeps asking.

Parked means it stays, but at an honest level. Twenty minutes a week, no expectation of progress. This is the right answer for things you enjoy and will never finish, which is a completely respectable category.

Tell the people involved

Half-finished things often have other people in them: a friend you said you would help, a group you joined, someone waiting on a draft.

Those need a sentence, and the sentence is easier than you think. I am not going to get to this, I am sorry, and I did not want to leave you waiting. Nearly everyone would rather have that than a vague, slowly dying thread.

Leaving it unsaid is what makes it heavy. The guilt is almost never about the task; it is about the unsent message.

What to do with the space

Expect a strange flatness after you clear things out. Open projects are also a form of hope, and letting several go can feel like shrinking.

So give the space to the thing you kept, and give it a shape: a time of day, a fixed amount, a next step small enough to start. Doing fewer things only pays off if the one you kept actually gets the attention; otherwise you have just made a tidier version of the same month.

And be careful about refilling. The first time a new idea arrives, write it somewhere and leave it there for a month. Most of them do not survive the wait, and the ones that do will still be there when you have finished.

When this is less about priorities

If you cannot finish anything and never could, if every project collapses at the same point, or if the unfinished things are piling up alongside a flatness that does not lift, something else may be going on.

Difficulty starting and sustaining things has several causes, including exhaustion, long-running low mood, and the ways attention works differently for some people. Those are worth a conversation with a doctor or a therapist rather than another round of trying harder, especially if the pile has started to feel like evidence about who you are.', array['Goals', 'Values']::text[], 0, '2026-10-01T14:00:00+00:00'::timestamptz),
  ('cooking-when-you-have-no-energy-to-cook', 'Cooking When You Have No Energy to Cook', 'On a flat or exhausted day, cooking can be the thing that does not happen. A lower bar, a shorter list, and a way to eat that does not require you to be at your best.', 'It is eight in the evening. There is food in the house. You have been standing in the kitchen doorway for a while, and the gap between what is in the fridge and anything you could call a meal feels unbridgeable.

So you have toast, or you have nothing, and then you feel bad about that too.

This is one of the most common and least discussed parts of a hard week. Cooking is not just effort; it is a chain of about fifteen small decisions and actions, and on a depleted day a chain is exactly the thing you cannot hold.

What is actually hard about it

It helps to see the parts. Deciding what to eat. Checking what is there. Working out what is missing. Standing up. Chopping. Watching something. Timing two things. Washing up afterward.

Each one is minor. Together they are a project, and the deciding is often the heaviest part, not the cooking.

Which tells you where to aim. Most of what follows is about removing decisions rather than finding easier recipes.

Lower the bar to eating, not to cooking

The first move is to separate two goals that get tangled. One is to eat something. The other is to make a meal.

On a bad day, pick the first. Cereal counts. Toast with cheese counts. A tin of soup counts. Fruit and a handful of nuts counts. Food from a shop that someone else assembled counts.

There is no version of this where not eating is the better outcome. Getting something into you is the whole job, and it is worth doing badly.

Have three no-decision meals

Decide now, while you have the capacity, what you will eat on the days you cannot decide. Three is enough.

Pick things with four ingredients or fewer, all of which keep. Beans on toast. Pasta with butter and whatever cheese is in the fridge. Eggs and bread. Rice from a packet with a tin of something. Soup and a hunk of bread.

Write the three on a piece of paper and put it inside a cupboard door. The list is not for inspiration; it is so that on a flat evening you do not have to produce an idea from nothing. You just read it.

Then keep those specific ingredients in, permanently, as a kind of insurance. A cupboard with the makings of your three meals is worth more on a bad week than a fridge full of ambitious vegetables.

Make the easy version easy to reach

Small physical arrangements help more than resolve.

Keep the tin opener somewhere obvious. Buy the pre-chopped onions or the frozen vegetables without apology. Have one pan you like using. Fill the kettle after you use it. Keep a bowl and a fork clean rather than in the pile.

Every one of those removes one step from the chain, and on the days you have four steps in you, that is the difference between eating and not.

Cook once, eat twice

If you have one good evening in the week, use it to make tomorrow easier rather than to make tonight special.

Double whatever you are cooking and put half aside. Boil extra rice. Roast a tray of something that can sit in the fridge. The point is to put a meal into the future, where your tired self will find it already decided.

A portion in the freezer is one of the kindest things you can do for someone, including yourself.

Mind the washing-up trap

Plenty of people cannot start cooking because the sink is already full, and the full sink is a bigger obstacle than the meal.

Two options. Wash only what you need for this one meal and leave the rest; one pan and one plate is a small enough job to do. Or use something disposable for a few days and let that be fine.

Neither is a failure of standards. It is choosing eating over tidiness on a day when you only get one of them.

Eating alone, and the other part of this

For a lot of people the flatness is not really about the cooking. It is about making a meal for one person when it feels like it is not worth the trouble.

If that is the shape of it, change the setting rather than the recipe. Eat with something you like on in the background. Put it on a real plate and sit somewhere other than the kitchen counter. Eat on the phone with someone once a week. Keep one thing in the house that you genuinely look forward to.

You are allowed to make the experience nicer without making the food harder.

When it has gone on a while

Not being able to feed yourself is often one of the first signs that you are running very low, and it tends to travel with other things: sleeping badly, not seeing anyone, everything feeling like too much.

If you have been living on toast for weeks, if you are skipping meals without noticing, if food has become something you are frightened of or fighting with, or if you have lost interest in eating altogether, that is worth saying to a doctor or a therapist. It is a concrete, practical thing to bring up, and it usually says something useful about how heavy the rest of your load has become.', array['Food', 'Self-Care']::text[], 0, '2026-10-01T14:00:00+00:00'::timestamptz),
  ('moving-somewhere-you-know-no-one', 'Moving Somewhere You Know No One', 'A new city, an empty calendar, and nobody to call. What the first six months usually feel like, and what actually builds a life somewhere new.', 'The boxes are unpacked. The job has started. It is Saturday morning, and you realize there is nobody in this city you could text about getting a coffee.

You chose this. It may even have been the right choice. And it can still feel, in the second month, like you have made a terrible mistake.

Almost everyone who moves somewhere new goes through this. It is not a sign that the move was wrong or that you are bad at making friends.

What you actually lost

It is worth being precise about it, because people underestimate the second half of this list.

You lost your friends, which you expected. You also lost all the background familiarity: the route, the shop where they know you, the gym, the doctor, where to go when something breaks. And you lost the accidental contact that came with all of it, the dozens of small unplanned interactions a week that made you feel situated.

That second kind takes effort to rebuild and nobody warns you about it, which is why the tiredness of a new city surprises people. Everything is a decision for a while.

The shape of the first six months

For most people it goes roughly like this. The first few weeks are busy and strangely fine, because setting up a life is a project. Somewhere around weeks six to ten the project ends and the quiet arrives, and that is usually the worst stretch.

Then, if you keep putting yourself in rooms, things slowly start to repeat. You see the same faces. Somebody remembers your name. By around six months you have acquaintances, and somewhere past a year you have friends.

Knowing the timeline helps, because the low point is not a verdict, it is a stage. The month three version of you is not the one to ask whether the move was a mistake.

Repetition beats effort

Here is the single most useful thing about making friends somewhere new: closeness comes from running into the same people repeatedly, far more than from any individual good conversation.

Which means your best move is not to be interesting at parties. It is to join things that meet on a schedule, with the same people, and then keep turning up.

A class with a fixed term. A team, at any standard. A choir. A volunteer shift. A run club. A language exchange. A regular night at the same bar or library or community center. The subject matters much less than the fact that it repeats.

And then give it longer than feels natural. Most people quit a group at week three, which is one week before they would have started recognizing anyone.

Make the small, specific ask

At some point, acquaintance has to turn into something else, and that nearly always takes someone being slightly brave.

The ask that works is small and specific. A coffee after the class. A walk on Sunday. Coming along to the thing you were already going to. Not a dinner party, not a big plan.

Say yes to everything for the first few months, including things you would normally decline. Not forever, just while you are building the first layer. And expect to extend invitations more often than you receive them for a while, which is not a sign of being unwanted; it is a sign of being new.

Some will not go anywhere. That is the normal rate, not a failure.

Keep the old people, but not instead of this

Call your old friends. They are a comfort and you should not drop them.

But watch for the version where you spend every evening on the phone with another city and none of them in this one. Contact that keeps you going is good; contact that lets you avoid building anything here will quietly stretch the hard stretch out for years.

Visits help if they are two-way. If you go home every weekend, you never get a Saturday here, and Saturdays here are what eventually make it yours.

Build the boring infrastructure on purpose

A good deal of feeling settled is just knowing things.

Find your doctor, your dentist, a barber, the supermarket you like, the walk you do without thinking, somewhere to sit outside. Go to the same cafe until they recognize you.

None of that is friendship and all of it helps enormously. It turns a place where you happen to live into somewhere you know.

Be careful with the first-year story

Two unhelpful conclusions tend to arrive around month three. One is this city is cold and unfriendly. The other is I must be harder to like than I thought.

Both are the loneliness talking, and both are worth holding loosely. Some cities are genuinely harder to break into than others, but almost all of them take longer than people expect, and the number of people in your situation in any given city is enormous.

When it is more than the usual hard

Give it six months of actually trying before judging the move. But if you are not sleeping, if you have stopped going out at all, if the low mood has stopped lifting, or if you are drinking more to get through the evenings, that is worth taking seriously now rather than waiting it out. A doctor or a therapist is the right place to start, and therapy by video means you can often keep someone you already trust while you build the rest of a life somewhere new.', array['Life Transitions', 'Loneliness']::text[], 0, '2026-10-01T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
