-- Five articles published 2026-10-06. Generated by:
--   python3 tools/articles_sql.py --since 2026-10-06
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('assuming-you-know-what-they-are-thinking', 'Assuming You Know What They Are Thinking', 'A short reply, a flat tone, a text left unanswered, and you have already decided what it means. Why mind reading feels like insight, and how to catch it in time.', 'Your message has been read and not answered. By the afternoon you know exactly what is going on: they are annoyed about yesterday, they have decided you are too much, and this is the beginning of them pulling away.

None of that was in the silence. All of it is in your head, and it feels completely factual.

This is one of the most common and most expensive habits of thought there is. It is sometimes called mind reading: treating a guess about what someone thinks as information you have.

Why it feels like knowing rather than guessing

Reading other people is a real skill, and you do have it. You pick up tone, timing, a pause, a face. The problem is not that you read; it is the confidence that comes with it.

Your mind produces an interpretation instantly and then presents it without the label. There is no gap between they took four hours to reply and they are annoyed with me. The second one arrives dressed as the first.

It also tends to run in one direction. The guesses people make about themselves are rarely generous: he thinks I am boring, she is regretting hiring me, they are being polite about it. Mind reading nearly always picks the version where you come out badly.

And the one piece of information that would settle it — what the person actually thought — is the one piece you do not have.

What it costs

The thought would be harmless if it stayed a thought. It usually does not.

You respond to the imagined version. You go cold, or over-explain, or apologize for something nobody mentioned, or send a message with an edge in it. Then they respond to that, and now there genuinely is something between you.

That is the real cost: mind reading creates the situation it predicted. A perfectly ordinary silence turns into a bad evening because one person acted on a story and the other had to react to it.

It also exhausts you. Running interpretations of everyone''s expressions all day is heavy work, and none of it is checkable.

Catch it at the words

The habit is hard to argue with in the abstract and easy to interrupt in the specific. The way in is to notice the sentence.

Mind reading has tell-tale grammar: he thinks, she has decided, they feel, nobody wants. Any sentence about someone else''s inner state, stated as fact, is a candidate.

When you catch one, do not try to replace it with a cheerful version. Just relabel it: that is my guess, not something I know. That one move takes most of the force out of it, because a guess does not require an immediate response.

Then ask what you actually observed. They replied in four words. She did not look up. He said fine. Those are the facts, and they are much thinner than the story built on them.

Count the other explanations

For any behavior you have interpreted, make yourself list three other reasons someone might have done it.

The short reply: they were driving, they were in a meeting, they type short messages to everyone, they are having a bad day about something unrelated, they answered in their head and forgot.

Most people find the list is easy to produce and that their original interpretation is not obviously the most likely one; it was just the fastest and the most familiar.

You are not trying to prove the kind version. You are trying to get back to honest uncertainty, which is where you actually are.

Ask, in a way that can be answered

Eventually, the only real fix is checking. The quality of the asking matters.

A bad version carries the accusation inside it: are you annoyed with me, you have been off with me all week. That invites denial and then an argument about whether they were off with you.

A better version is small, specific and low-stakes. You went quiet after the meeting, was something up. I could not tell how you took that, what did you think. I noticed I have been guessing what you are thinking, so I thought I would just ask.

Then believe the answer rather than scanning it for the real message. If you ask and then decide they are hiding something, you have asked nothing.

Where the guessing comes from

Mind reading tends to be strongest in people who had to be good at it. If you grew up having to read a mood from the sound of a door, you got very practiced at it, and the practice does not switch off when it is no longer needed.

That is worth knowing because it reframes the habit. It is not stupidity or vanity; it is an old safety behavior that is now producing false positives in rooms where nobody is dangerous.

It also means it will not disappear by being told off. It responds to being noticed and tested, repeatedly, in low-stakes moments.

Test it on purpose, in small ways

Pick one guess a week and check it, especially a mild one.

Ask what someone thought of the thing you were worried about. Send the ordinary message you have been drafting carefully. Reply to the short reply with a short reply and see what happens.

Keep a short note of what you predicted and what came back. Over a few weeks, that record does more than any amount of reasoning, because it is evidence you collected rather than reassurance someone offered.

When it is bigger than a habit

If you are reading threat into most interactions, if a short message can take out your whole day, or if the guessing is shaping how much of your life you are willing to risk, that is worth working on with someone.

This is standard, well-trodden ground in therapy and it moves, often faster than people expect. A therapist can also help with the part underneath, where the habit started, which is usually what keeps it switched on. And if the uncertainty has become unbearable rather than irritating, a doctor or a therapist is the right place to take that.', array['Thinking Traps', 'Relationships']::text[], 0, '2026-10-06T14:00:00+00:00'::timestamptz),
  ('going-to-something-alone', 'Going to Something Alone', 'The class, the talk, the party where you know one person. How to walk in on your own without the twenty minutes of standing by the wall deciding to leave.', 'You have the details. You said you would come. And now it is forty minutes before, you are thinking about the part where you walk in and do not know anyone, and the evening at home is looking better by the minute.

Going somewhere alone is a specific hurdle, separate from whether you want to be there. Plenty of people who like the thing still do not go, because the entrance is the hard part and there is nobody to do it with.

What is actually frightening

It is rarely the event. It is the first ten minutes.

Walking in and having nobody to stand beside. Not knowing where to put yourself. Being visibly alone, which feels like being visibly unwanted. And the fear of the specific moment where you are standing with a drink, looking at your phone, aware of yourself.

Notice that all of that is about the arrival. Once something has started — the class, the talk, the game — there is a structure and you are fine. So the whole problem is about twenty minutes, and twenty minutes can be planned for.

Arrive at the useful time

Most people arrive right on time, which is the worst moment: the room is full, groups have formed, and you have to break into one.

Arriving five or ten minutes early is much easier. The room is half empty, nobody is established, the only other people there are also standing around, and talking to someone next to you is the obvious thing rather than an intrusion.

The organizer is usually there early too, and they are the single easiest person to talk to, because welcoming people is their job for the evening.

Pick something with a structure

If going alone is hard, the kind of event matters enormously.

Classes, courses, teams, choirs, volunteering, run clubs, workshops, book groups: all of these give you something to do, a reason to be there, a shape to the time, and natural conversation about the activity. They also repeat, which means you do not have to achieve anything tonight.

Open-ended parties and mixers are the hardest version, because the only activity is socializing. If you are building up to things, do not start there.

Have your first three sentences ready

The dread is mostly about not knowing what to say, so decide in advance and stop rehearsing.

An opener that works almost anywhere: is this your first time here. Then, how did you find out about it, and have you done this sort of thing before.

Those three cover the first few minutes with anyone, and they share one useful feature: they are about the situation you are both in, which is the easiest subject available.

If you prefer a job to a script, take one. Offer to help set up chairs, hand out papers, carry something. Doing anything at all removes the standing-around problem completely, and it puts you next to people with a reason to talk.

Give yourself an exit and a minimum

Two decisions, made before you go, that make the whole thing easier.

A minimum: I will stay thirty minutes. That is short enough to agree to and long enough that you almost always stay longer.

An exit: how you will leave, what you will say, whether you need to tell anyone. Knowing you can go, cleanly, is often the thing that lets you walk in at all.

And decide both in advance, because deciding at the door always comes out as going home.

What to do in the awkward gap

There will be a stretch where you are standing alone. Expect it rather than treating it as a failure.

Put the phone away, because it is the one thing that makes you unapproachable. Instead: get a drink, read the notice board, look at whatever is on the walls, go and look at the equipment or the books or the food. Moving with a small purpose reads completely differently from standing still.

Then join the nearest pair rather than a group of five. Two people talking is easy to stand near; a circle of five is a closed shape.

And know that almost nobody is watching. The feeling of being conspicuous is the least accurate feeling in the room.

Afterward, score it honestly

The temptation is to come home and audit your own performance. That is what makes the next one harder.

So judge it on two things only: did you go, and would you go again. Not whether you were charming, not whether you made a friend.

Going four times to the same thing beats one brilliant evening somewhere you never return to. Familiarity is what eventually turns a room of strangers into people who say your name when you arrive, and it only comes from repetition.

Make the second time easier than the first

Book or commit to the next one before you leave the building, if you can. Momentum after a reasonable evening is worth a great deal.

And if you spoke to one person you liked, it is completely normal to say: I will probably come again next week, are you coming. That sentence is how most adult acquaintances start.

When the barrier is bigger than nerves

If the thought of walking in alone brings real dread, if you have been turning down invitations for months, or if you have stopped going to anything where you might be observed, that is worth treating rather than willing yourself through.

Social anxiety responds very well to practical therapy, often in a fairly small number of sessions, and a therapist can help you build up to the hard version rather than failing at it repeatedly. If avoiding things has left you isolated, or if the loneliness underneath has started to feel heavy, a doctor or a therapist is the right place to start.', array['Social Anxiety', 'Loneliness']::text[], 0, '2026-10-06T14:00:00+00:00'::timestamptz),
  ('getting-moving-again-after-illness-or-injury', 'Getting Moving Again After Illness or Injury', 'Your body is not where it was and the gap is demoralizing. How to restart movement after being laid up, at a pace that works and without measuring against your old self.', 'You were off your feet for six weeks. Now you are cleared to move again, and the first walk tells you something you did not want to know: you are nowhere near where you were.

That gap is the hard part. Not the discomfort, not even the slowness, but the feeling of having gone backward while everyone else stayed where they were.

Start below where you think you should

The most common way a comeback fails is doing too much on a good day.

You feel better, you do forty minutes, and you lose the next three days. Then you conclude your body is unreliable, when the actual problem is the pacing.

So begin at a level that feels almost silly, and judge it by the next day rather than by how it felt at the time. If you are fine the following morning, add a little. That is the whole method, and the slow version gets you there much faster than the heroic one.

If you have been given a plan by a physical therapist, their numbers beat your instincts, especially on the days you feel good.

Use time, not distance

Early on, measure in minutes rather than miles or reps. Ten minutes of walking, three times a week. Then twelve. Then fifteen.

Time is easier to hold steady when your capacity is moving around, and it stops you unconsciously racing yourself.

The useful increase is about ten percent a week, which feels maddeningly slow and is the thing that keeps you from a setback. People who add more than that are the people who end up starting again.

Expect good days and bad days to be uneven

Recovery is not a line. It goes up, then sideways, then slightly down, then up again.

That unevenness is the part that demoralizes people, because a bad week reads as proof the recovery has stalled. Usually it is just the shape of recovery.

A practical move: keep a very short log. Date, what you did, how you felt the next day. Three words a time. On a bad week, the log is the only thing that will show you the trend, because your memory will insist nothing has changed.

Separate pain from damage

This distinction matters enormously and it is worth asking your doctor or physical therapist about directly for your own situation.

In general, after many injuries, some discomfort while moving is expected and not a sign of harm. Sharp pain, new swelling, pain that lasts well into the next day, or anything that changes how you walk is different, and it is information to take back to whoever is treating you.

Being frightened of your own body is one of the most common and least discussed parts of this. Asking plainly what should hurt and what should not takes a surprising amount of weight off, and it is a completely ordinary question.

Rebuild the thing you actually need

What you need back is probably not the thing you used to measure. You need stairs, carrying, standing for an hour, getting up off the floor, sleeping through the night.

So aim at those. If you cannot manage the stairs, practice two steps. If standing is the problem, practice standing. Specific, boring and useful beats generic fitness, and it gives you progress you notice in your week rather than on a screen.

Strength matters as much as stamina here, and it usually comes back fastest. Short sets of simple movements, a few times a week, do more for ordinary life than long sessions of anything.

Stop comparing yourself to the before version

This is the real work, and it is psychological rather than physical.

Your old numbers are a fact about a person who had not been ill. Measuring every session against them guarantees that each one is a disappointment, which is a reliable way to stop going.

So move the comparison. Compare to last week, or to the first week back. Write down where you started, because within a month you will have forgotten how little you could do, and that forgetting robs you of the only encouraging evidence available.

And accept that for some conditions, the destination is a different body rather than the old one. That is a loss worth grieving honestly rather than out-training.

Mind the other side of it

Being laid up does things beyond the physical. Sleep gets strange. Mood drops. You lose the structure of your days, the people you saw, the thing you did that made you feel like yourself.

So treat the return as more than exercise. Get outside, in daylight, even for ten minutes. Get back in touch with one person you stopped seeing. Put something back in the diary.

Movement helps mood for real, and in recovery the mood often lifts before the fitness does, which is a useful thing to notice when the numbers are still poor.

When to check in with someone

Check with your doctor or physical therapist before adding anything new if you had surgery, a heart or lung problem, a fracture, a long illness, or if you are on medication that affects your heart rate or balance. Go back to them if pain is increasing week to week rather than easing, or if something new appears.

And if the stuck part is not your body — if you cannot face starting, if you are frightened of moving at all, or if the low mood that came with being ill has not lifted since — that is worth taking to a doctor or a therapist. It is a common part of recovery and treating it tends to do more for the comeback than another training plan.', array['Movement', 'Resilience']::text[], 0, '2026-10-06T14:00:00+00:00'::timestamptz),
  ('starting-something-you-will-be-bad-at', 'Starting Something You Will Be Bad At', 'Learning anything new as an adult means being visibly incompetent for a while. Why that is so much harder now, and how to get through the beginner stretch.', 'You have wanted to learn it for years. The language, the instrument, the drawing, the swimming, the dancing. You have looked up classes twice and not booked one.

The obstacle is rarely time. It is that you would have to be bad at it, in front of people, for a while, and you are forty-three and have not been bad at anything on purpose since school.

Why beginning is harder than it used to be

As a child you were a beginner at everything, constantly and without comment. Adults are not. You have spent two decades becoming someone who knows what they are doing, and competence becomes part of how you are seen and how you see yourself.

So being a beginner is not just uncomfortable, it is a temporary loss of identity. For an hour a week you are the worst person in the room, and nobody is impressed by anything you do.

There is also simple exposure. You have more to lose in your own eyes, and nobody to tell you that being clumsy at a new thing is normal, because every adult around you is doing things they are already good at.

The beginner stretch is shorter than you think

Here is the thing worth knowing: the genuinely humiliating part is brief.

For most skills, there are a few weeks of being obviously terrible, then a long stretch of being unremarkable, which is much easier to live inside. The painful part is the first bit, and it passes faster than the dread suggests.

So the task is not to tolerate years of incompetence. It is to get through about six sessions.

Pick the setting deliberately

Where you learn matters more than how dedicated you are.

A beginners'' class, explicitly labeled as such, is far easier than joining a mixed group. Everybody there is in the same position, nobody is watching you, and the teacher expects nothing.

A class where you know nobody is often easier than one where you do, because being bad in front of strangers costs less than being bad in front of someone who knows you as competent.

And a teacher who is good with beginners is worth more than a brilliant practitioner. Ask directly when you sign up: do you teach a lot of people starting from nothing.

Decide in advance how long you are giving it

The most common failure is quitting in week two for reasons you would not accept on reflection.

So commit to a number of sessions rather than to the activity: six classes, or eight weeks, or ten sessions. Pay for them up front if that helps. Then you are not deciding each week whether you are the sort of person who does this.

At the end of the commitment, decide properly. By then you will know whether you dislike the thing or only disliked not being good at it, and those are very different answers.

Change what you are measuring

If you measure output, you will be miserable. The output is bad; that is the definition of a beginner.

So measure attendance and small specifics instead. I went. I can say four sentences. I did not stop in the middle this time. I got the first bar right.

Keep a two-line record of those, because progress at the beginning is invisible from inside and extremely clear in a log four weeks later.

What to do with the self-conscious feeling

It will arrive, usually in the first ten minutes, and the useful response is not to argue with it.

Name it briefly and keep going: this is the part where I am bad at it. That sentence is more effective than reassurance, because it is accurate and it does not require you to feel differently.

It also helps to notice what is actually happening in the room. Everyone else is thinking about their own hands. The attention you feel on you is almost never there, and in a beginners'' class absolutely nobody has spare capacity to judge you.

And if you make a mistake in front of people, the recovery is simply to carry on. Apologizing at length for being a beginner draws more attention than the mistake did.

Be careful with the two shortcuts

Studying it alone first, until you are good enough to go to a class, is the most common one. It sounds sensible and it usually means you never go, because the bar keeps moving.

And doing it only in private, forever, is the other. For many things that is fine. But if you want to play with people, speak to people, or swim in the sea, at some point the public version has to happen, and it is easier early than after years of avoiding it.

What it gives you beyond the skill

Most people who get past the beginner stretch report something they did not expect: being bad at something gets easier in general.

The tolerance you build transfers. It becomes easier to ask basic questions at work, to try things with your children, to be new in other rooms. That is a bigger return than the instrument.

When the block is bigger than nerves

If the idea of being seen as incompetent is intolerable rather than uncomfortable, if you only do things you already excel at, or if you have given up on a long list of things you genuinely wanted because of how the early part felt, that pattern is worth working on with someone.

It is common ground in therapy and it moves. A therapist can help with the part underneath, where being good at things and being acceptable got tied together, and that tends to free up far more than any individual class.', array['Perfectionism', 'Motivation']::text[], 0, '2026-10-06T14:00:00+00:00'::timestamptz),
  ('when-someone-takes-their-anger-out-on-you', 'When Someone Takes Their Anger Out on You', 'Their day was terrible and you are the one standing there. How to respond to misdirected anger without absorbing it, escalating, or pretending it did not happen.', 'They came in and the first thing out of their mouth had an edge on it. The second thing had more. Nothing you did caused it, and you are now standing in a kitchen holding a mug while somebody''s bad day gets pointed at you.

There are two unhelpful instincts here, and most people have one of them. Match it and escalate, or absorb it and say nothing. Neither works, and the second one works least over time.

Spot it for what it is

Misdirected anger has a recognizable shape. The size does not fit the trigger. It arrives at a particular time of day. It is about the dishwasher, or the route you took, or something you did three weeks ago.

Recognizing that early matters, because it changes what you are responding to. You are not in an argument about the dishwasher; you are standing in front of someone with more pressure than they can hold.

That is not an excuse for how they are speaking to you. It is useful information about what will and will not help in the next two minutes.

Do not take delivery of it

You can hear someone without accepting the charge.

In practice that means not defending yourself against an accusation that is not really about you, and not conceding to make it stop. Both responses treat the content as the point, and the content is not the point.

What works better is a short, calm, specific line. I can hear you have had a rough day. I am not going to be shouted at. Let us do this in ten minutes.

Say it once, in a flat voice, and then do what you said. Repeating yourself at increasing volume is how you end up in the fight.

Leave the room properly

Walking out gets confused with sulking, so do it in a way that cannot be read that way.

Say where you are going and when you are coming back. I am going to put the shopping away and I will come back in ten minutes. Then return, and return calm.

That is not avoidance; it is removing the audience from a surge that will drop on its own within a few minutes. Most misdirected anger cannot sustain itself without someone to aim at.

Keep your own temperature down

Your body will want to match theirs. Breathe out longer than you breathe in. Drop your shoulders. Lower your volume rather than raising it. Keep your hands still.

Volume is contagious in both directions, and being the quieter person in the room is the single most effective thing you can do, as long as it is genuinely calm rather than cold and pointed.

And watch for the sentence you will regret. If you can feel it forming, that is the moment to use the ten-minute line.

Come back to it when it is over

This is the part people skip, and skipping it is what lets the pattern continue.

Later the same day, when both of you are level, name it briefly and without a case file. When you came in and spoke to me like that, it was not okay, and I would rather know you have had a bad day than be the place it lands.

One sentence. No list of previous occasions, no demand for a long apology. The aim is not to win the point; it is to make the pattern visible, because unnamed it will repeat.

Then, if you can, offer the alternative: tell me it was a terrible day and I will leave you alone for half an hour. Most people would rather have that than the version where they snap and feel awful afterward.

Notice if you are the designated target

Some people absorb this because they always have. If you grew up managing somebody''s moods, being the place anger lands can feel almost normal, and you may find yourself apologizing automatically or working out what you did wrong.

That reflex is worth catching. Ask the plain question: did I actually do something here, or am I doing the thing where I assume I must have.

Being reliably easy to shout at is not a kindness to either of you. It removes the one consequence that would prompt them to handle it differently.

When it is not a bad day

A single rough evening is one thing. A pattern is another, and the line matters.

If this happens often, if you are adjusting your behavior around their moods, if you feel nervous before they come home, or if the anger involves threats, intimidation, anything physical, or anything frightening, that is not misdirected stress. That is a safety issue and the advice above does not cover it.

In that case, please talk to someone outside the situation: a doctor, a therapist, or a domestic abuse helpline, which exists for exactly this and will talk to you about options without pushing you into any of them. In the US, the National Domestic Violence Hotline is reachable at 1-800-799-7233.

When to bring in help

If this is a recurring pattern in a relationship you want to keep, a couples therapist can help more than either of you managing it alone, and the person with the anger may need their own support for whatever is generating it.

And if being on the receiving end of it has left you walking on eggshells, sleeping badly, or doubting your own read on what is reasonable, please talk to a doctor or a therapist about that part. It is not an overreaction to want help with it.', array['Anger', 'Boundaries']::text[], 0, '2026-10-06T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
