-- Five articles published 2026-10-09. Generated by:
--   python3 tools/articles_sql.py --since 2026-10-09
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('the-week-after-you-lose-your-job', 'The Week After You Lose Your Job', 'However it happened, the first week is its own problem. What to do in the first few days, what to leave alone, and why this hits harder than the money explains.', 'It is Tuesday morning and there is nowhere to be. You have told a few people and not others. You are oddly calm, and then you are not, usually somewhere around four in the afternoon.

Losing a job is treated as a financial event. It is that, and it is also a loss of structure, status, daily company and a large part of how you answer the question of who you are. All four arrive at once.

Why it hits harder than the arithmetic

The money is often the smallest part of the first week.

What goes with a job is the shape of your day, the people you spoke to without arranging it, the sense of being useful, and the plain fact of being chosen. Losing those at the same time is why people feel shaky even when they have savings, and even when they disliked the job.

If it was a dismissal or a restructuring where you were picked and others were not, there is usually shame on top, and shame makes people hide exactly when they most need other people.

The first week: do these, and little else

Protect the shape of your days. Get up at your usual time, get dressed, go outside once. That sounds trivial and it is the single thing that most reliably keeps the first two weeks from unravelling.

Handle only the urgent paperwork. File for unemployment benefits or whatever applies where you live, because those have waiting periods and the clock starts when you file. Find out exactly what you are owed: notice, unused leave, final pay, any severance.

Do not decide anything large. Not moving, not a career change, not a confrontation. Decisions made in the first week are made by somebody who has just been winded.

And tell two or three people properly. Not a broadcast, two or three. The urge to wait until you have a plan is strong and it costs you the support you need to make one.

Get the facts on paper

Vagueness is what produces the three-in-the-morning version of this, so spend an hour on the numbers.

What is coming in: final pay, any severance, benefits you are entitled to, anything from a partner. What is going out that cannot change. How many months that gives you, roughly.

Most people find the runway is longer than the panic implied. Some find it is short, which is unwelcome and far better known than guessed, because short runways have specific actions attached: calling the lender, asking about hardship arrangements, cutting the big recurring costs first.

Be careful what you do with the time

Two opposite errors dominate the first weeks.

Filling every hour with frantic applications, usually badly targeted, which burns you out by week three and produces little. Twenty tailored applications will beat two hundred generic ones, and you cannot write twenty good ones in a week.

Or disappearing: staying in, sleeping late, losing the days. That feels like rest and behaves like a slide, because the structure is what holds your mood up.

The version that works is boring: a few hours of job work a day, in a fixed slot, and the rest of the day deliberately used for something else, including something physical and something with people in it.

What to say to people

You will be asked constantly, so decide one sentence and reuse it. I was made redundant in a restructure and I am looking for something in X. Or: my role was cut, and I am taking a few weeks to work out what is next.

Short, neutral, no apology, no case for the defense. You do not owe anyone the full account, including family.

If you were dismissed in a way you believe was unfair, keep the details for the people who can actually help: a lawyer, a union, a labor board. Explaining it repeatedly to acquaintances tends to leave you more upset and no further forward.

Expect the mood to move around

The first week is often numb, or even oddly light. The hard part frequently arrives in weeks two to four, when the novelty has gone and the first rejections land.

Rejections are the part people are least prepared for, because job hunting has a terrible ratio and each no arrives personally addressed. It helps to count applications rather than outcomes, and to decide in advance how many nos a week is simply the cost of looking.

And notice what the thoughts do. Unemployment is extremely good at producing sentences like I am unemployable, nobody will take me at my age, I have wasted ten years. Those are mood talking, and they get louder in the afternoon and quieter after a walk.

Use the one advantage you have

For most people this is the first unstructured stretch in years, and it is worth not spending all of it on applications.

Three things repay the time: one honest conversation with someone in a field you are curious about, one skill or certificate that is actually required by the jobs you want, and a serious look at whether the work you were doing is the work you want to go back to.

Not as a reinvention project. Just enough that the next job is a choice rather than the first thing that said yes.

Keep the people, deliberately

The job provided your social contact, and losing it quietly removes most of it.

So put two or three fixed things in the week that involve other people: a standing coffee, a class, a volunteer shift, a sport. Volunteering in particular does double duty, because it provides company, structure and something true to say about what you have been doing.

When to get help

If you are not sleeping, drinking more, unable to get out of the house, or finding that the low mood has not lifted at all after a few weeks, please take it to a doctor or a therapist. Job loss is one of the more common reasons people end up in treatment, and that is not a sign of weakness; it is one of the larger losses adults face.

Free employment services, nonprofit debt advice and benefits advisers all exist and are badly underused. And if things get dark enough that you are thinking about not being here, please tell a doctor or someone you trust that day. In the US you can call or text 988 at any time.', array['Loss', 'Life Transitions']::text[], 0, '2026-10-09T14:00:00+00:00'::timestamptz),
  ('when-your-child-does-not-want-to-go-to-school', 'When Your Child Does Not Want to Go to School', 'Stomach aches at breakfast, tears at the gate, or a flat refusal to get in the car. What is usually going on, and what actually helps mornings get easier.', 'It starts with a stomach ache on Monday. By Thursday there are tears at the gate, and by the following week you are standing in the hallway at eight fifteen negotiating with a child who will not put their shoes on.

This is one of the most stressful situations in family life, partly because it happens at the worst hour of the day and partly because every option feels wrong: pushing them in feels cruel, keeping them home feels like the start of something.

Rule out the obvious things first

Before treating it as anxiety, check what might be underneath.

Is something happening at school? Bullying, a friendship that collapsed, a teacher they are frightened of, work that has become too hard, something that happened in a changing room or a bathroom. Children often report none of this directly and all of it sideways.

Is there a physical explanation? Vision, hearing, sleep, constipation, headaches, an undiagnosed difficulty with reading or attention. Children who cannot keep up often become children who cannot bear to go.

Has something changed at home? A separation, a new baby, an illness, a move, a parent under strain. Reluctance to leave the house is often about what they are leaving rather than where they are going.

Ask about all of it, in a low-key way, not at eight fifteen.

What the stomach aches usually are

Most school refusal that is not about a specific event is anxiety, and anxiety in children is largely physical.

Stomach pain, nausea, headaches, needing the toilet, feeling hot. Those are real sensations produced by a real alarm response, not performances, and telling a child there is nothing wrong with them rarely lands because something plainly is.

The useful framing, for them and for you, is: your body is doing the frightened thing, and it is uncomfortable, and it is not dangerous.

Why avoidance makes it worse

Here is the mechanism that matters most. Each morning they stay home, the relief is enormous and immediate, and that relief teaches the alarm that school is genuinely dangerous and that staying home is the escape.

So the following morning is harder, not easier. A week off is often what turns a difficult couple of weeks into a months-long problem.

That is why the general principle, for ordinary anxiety with no safeguarding concern, is that going in some form beats staying home, even a reduced form.

Make going smaller rather than optional

The choice is not all-or-nothing, and partial attendance is far better than none.

Going in for two lessons. Going in late, after the crowded entrance. Spending the first twenty minutes in the office or with a particular teacher. Being collected at lunch for a few days. Sitting in the library during the lesson they dread.

Agree a specific, written plan with the school, with a date to review it. Most schools have seen this many times and have a point of contact for exactly it; asking what you do for children who are finding mornings hard usually produces more than you expect.

The morning itself

Keep it short, warm and matter-of-fact. The longer the negotiation, the worse the outcome, because the discussion itself becomes part of the anxiety.

Decide the night before: clothes out, bag packed, breakfast known. Reduce the number of decisions in the hour.

Do not interrogate how they are feeling at breakfast; it tends to turn attention inward and raise the volume. Talk about anything else.

At the gate, keep the handover brief. A long, tearful goodbye prolongs the hardest moment. Say the same short line every day: I know this is hard, you can do it, I will be here at three.

And if another adult can do the drop-off, let them. It is often dramatically easier with someone who is not the person they want to stay with.

What to say and what to avoid

Useful: your body feels awful and it will settle once you are in. You do not have to feel brave. I will always come back. Let us see what the first lesson is like.

Less useful: there is nothing to worry about, which contradicts what they feel. Everyone else manages, which adds shame. And promises you cannot keep, like you can come home if you hate it, unless that is genuinely the agreed plan.

Notice too how much of your own fear is in the room. Children read their parents closely, and a parent who is visibly dreading eight fifteen confirms that something dreadful is happening.

Afterward, point at the evidence

When they come home having managed it, say what happened plainly: you went in, it was hard at the start, and you got through the day. That is the sentence that does the long-term work, and it needs saying out loud rather than being assumed.

Keep it proportionate. Enormous celebration can make going to school feel like a feat, which is its own kind of pressure.

When to take it further

Please involve your child''s doctor or school if this has gone on more than a couple of weeks, if they are missing whole days, if there are physical symptoms you have not had checked, or if their mood has dropped alongside it.

Anxiety in children responds very well to treatment, and the earlier it is addressed the shorter the work tends to be. A school counselor, a pediatrician, or a therapist who works with children are all reasonable starting points.

And treat it as urgent rather than ordinary if your child is being hurt or threatened at school, if they are harming themselves, or if they talk about not wanting to be here. In those cases speak to a doctor the same day rather than working on mornings.', array['Anxiety', 'Parenting']::text[], 0, '2026-10-09T14:00:00+00:00'::timestamptz),
  ('exercising-when-your-heart-rate-frightens-you', 'Exercising When Your Heart Rate Frightens You', 'If a fast heartbeat sets off alarm, exercise becomes something to avoid. Why that happens, and how to get moving again in a way that teaches your body the opposite.', 'You walk up the hill, your heart picks up, and something in you reads it as the start of something. By the top you are checking your pulse, and the next day you take the flat route.

This is extremely common and almost never discussed. If you have had panic attacks, or a frightening physical episode, the ordinary sensations of exertion stop being neutral. A fast heartbeat is a fast heartbeat whether you are running or panicking, and your alarm system cannot always tell which one it is looking at.

Why exercise becomes the thing you avoid

Panic teaches a specific lesson: certain body sensations mean something terrible is happening.

Exercise produces exactly those sensations on purpose. Racing heart, breathlessness, sweating, a hot face, sometimes light-headedness or a shaky feeling afterward.

So you climb some stairs, the sensations arrive, your mind asks is this panic or is this a problem, and the asking adds adrenaline, which adds more sensation. People end up with a panic attack that started as a brisk walk, and then avoid the walk.

Avoiding it also means losing fitness, which means the same hill produces more symptoms next time, which confirms the fear. That loop is the real problem, and it is fixable.

First, get it checked once

Before you treat this as anxiety, see a doctor and say exactly what happens, especially if it is new, if you have risk factors, or if the sensations come on with exertion in a consistent way.

Chest pain brought on by effort and relieved by rest, fainting during exercise, a very irregular heartbeat, or breathlessness far beyond what the effort explains all deserve medical assessment rather than reassurance from an article.

Getting that done matters for two reasons. The obvious one, and the fact that mid-exercise reassurance works badly when a real question is still open.

The counterintuitive part: the sensations are the treatment

Once you have been cleared, the useful approach is the opposite of avoidance.

Deliberately producing the sensations in a safe setting, repeatedly, is how the alarm learns they are not dangerous. Clinicians sometimes do this formally; you can do a gentler version of it yourself, and movement is the most natural version there is.

The aim is not to be calm while your heart races. The aim is to feel your heart race, stay with it, and have nothing bad happen, over and over, until the sensation stops meaning what it currently means.

How to build it up

Start low enough that it is comfortable, then raise it deliberately rather than avoiding the symptoms.

Week one: walk for twenty minutes at a pace where you notice your heart but can talk easily. Do that until it is boring.

Then add something that clearly raises your heart rate for a short period: one hill, one flight of stairs, thirty seconds faster, two minutes on a bike. Short on purpose, so the rise happens and then passes.

When the surge arrives, do not stop immediately. Keep going at a gentler pace and let it come down while you are still moving. Stopping dead at the first sensation teaches escape; continuing teaches that it settles.

Then repeat the same thing for a week before adding more. Boredom is the sign of success here.

What to do with the frightening moment

Three things, and they are all small.

Keep breathing out slowly rather than gulping air. Over-breathing is what produces the tingling and the unreal feeling that frighten people most.

Say something accurate rather than reassuring: this is exertion, my heart is doing what it is supposed to do, it will come down in a few minutes. Flat and factual beats positive.

And resist the checking. Taking your pulse, timing it, watching a monitor: all of it narrows your attention onto the sensation and amplifies it. If you wear a tracker and find yourself staring at the number, take it off for a few weeks.

Pick activities that help the learning

Anything rhythmic and controllable, where you can change pace easily: walking, cycling, swimming, rowing, dancing in the kitchen.

Early on, familiar places and company help. Later, deliberately do some of it alone and some further from home, because the fear often attaches to being far from help, not to the exercise itself.

Avoid two things at the start: the fasted early-morning session, which produces more light-headedness, and exercising after a bad night or a lot of caffeine, both of which raise your resting arousal and make everything feel worse.

Normal versus not

It helps to know what ordinary exertion feels like, because many people in this loop have forgotten.

Normal: heart beating hard, breathing fast, warm, legs heavy, a flushed face, a shaky feeling after something hard, taking a few minutes to come down.

Worth stopping for and taking to a doctor: chest pressure, pain radiating to the arm or jaw, fainting or near-fainting, a heartbeat that stays very high long after you stop, or breathlessness wildly out of proportion to the effort.

Knowing the second list makes the first list much easier to sit with.

When to get help with it

If panic is happening regularly, if you have stopped moving much at all, or if you have been avoiding exercise for months because of what it does to your body, this responds very well to treatment.

Cognitive behavioral therapy for panic does exactly this work in a structured way, usually in a small number of sessions, and a therapist can take you through the sensations faster and more thoroughly than you will manage alone. A doctor is the right first stop for the physical check and can refer you.

And if things have become dark enough that you are not sure you want to be here, please tell a doctor or someone you trust that same day. In the US you can call or text 988 at any time.', array['Panic', 'Movement']::text[], 0, '2026-10-09T14:00:00+00:00'::timestamptz),
  ('the-last-ten-percent', 'The Last Ten Percent', 'The thing is nearly done and has been for weeks. Why finishing is its own distinct problem, separate from starting, and how to get something over the line.', 'The draft is written. The room is painted except for the trim. The application is complete apart from one form. The course has two modules left.

Nothing is stopping you. And it has been like this for three weeks, and every day it quietly costs you something.

Finishing is a separate skill from starting, and almost nobody is taught it.

Why the end is harder than the middle

Several things change as you approach the finish, and all of them push against completion.

The work gets less interesting. The last ten percent is nearly always the boring ten percent: the formatting, the trim, the admin, the second coat, the references.

The feedback stops. In the middle you could see progress. At the end you are grinding through small items that make no visible difference.

And, most importantly, finishing makes the thing real. While it is unfinished it is still potentially excellent. Once it is done it becomes a specific object that can be judged, and some part of you knows that.

That last one explains most stalled projects better than laziness does.

Name what finishing exposes

If a nearly complete thing has sat for weeks, it is worth asking plainly: what happens when this is done?

Someone reads it. The room is judged. The application gets an answer, possibly a no. The course ends and you have to decide what is next. People find out whether you are good at this.

Often the stall is not about the remaining work at all; it is a way of staying in the state where nothing has been decided. Naming that does not make it disappear, and it does make it much easier to act anyway.

Write down exactly what is left

A vague remainder expands. A written list shrinks it.

List every actual item, in physical terms, however small: find the receipt, write the covering email, buy a small brush, print one page, email two referees, delete the placeholder paragraph.

Most people discover the real remainder is six items and about ninety minutes, not the vast unspecified thing it felt like. That discovery is usually the turning point.

Then do them in order of size, smallest first, because momentum matters more than logic at this stage.

Define done, in advance

Half of all unfinished things are unfinished because nobody decided what finished means.

So write the definition before you resume: this is done when the trim is painted and the brushes are cleaned. When the form is submitted. When the draft has been read once for typos and sent.

Make it a standard you can actually hit. Done is not perfect; it is the agreed line. And having a line stops the last ten percent from quietly becoming another forty.

Set a deadline with a witness

A deadline you set alone is a preference. A deadline somebody expects is a different thing entirely.

So tell one person: I am sending this on Thursday. Book the appointment that requires the form. Invite someone to see the room on Saturday. Ask a colleague to expect the draft.

If nobody is available, make it costly in some other way: buy the tickets, book the collection, schedule the thing that only works if this is done.

External structure is not a weakness; it is the normal way adults finish things.

Use one unglamorous session

Set aside one block, ninety minutes, with the list in front of you, and do the remaining items badly rather than well.

The last ten percent rarely rewards care. The references do not need to be beautiful. The email does not need a fourth draft. The trim needs one decent coat.

If you catch yourself improving something that was already finished, stop; that is avoidance dressed as craft. Polishing the parts you enjoy while the admin sits undone is the most common way the end of a project dies.

Expect the flatness afterward

Finishing something often does not feel the way people expect. There is a drop: relief, then a strange emptiness, sometimes a day or two of feeling at a loose end.

That is normal, and it is one reason people avoid finishing things without knowing it. The unfinished project was also a companion and a source of identity.

So plan the hour after. Tell someone. Do something ordinary and pleasant. And do not immediately start the next large thing out of discomfort with the gap.

When the thing genuinely should not be finished

Sometimes the stall is information. The project no longer matters, the situation changed, or you have learned something that makes the original plan wrong.

That is a legitimate answer and it deserves a decision rather than a drift. Either finish it to the agreed line, or end it deliberately and say so, which costs far less than another year of a nearly-done thing sitting there.

What is not a legitimate answer is leaving it at ninety percent indefinitely, because that keeps all of the cost and delivers none of the benefit.

When this is a pattern rather than a project

If almost nothing gets finished, if you have a long history of things abandoned near the end, or if the dread around completion is strong enough to keep you from work you care about, that is worth looking at with someone.

Fear of being judged, perfectionism, and the ways attention and follow-through work differently for some people all produce exactly this, and all of them are workable. A doctor or a therapist is the right place to start, especially if the pile of unfinished things has begun to feel like evidence about who you are.', array['Motivation', 'Goals']::text[], 0, '2026-10-09T14:00:00+00:00'::timestamptz),
  ('when-someone-keeps-refusing-help', 'When Someone Keeps Refusing Help', 'They need support and will not accept it. What tends to be behind the refusal, what to stop trying, and how to stay in their life without wearing yourself out.', 'You have offered a cleaner, a lift, a doctor''s appointment, a hand with the stairs. You have found the number, written it down, and offered to make the call yourself.

They say they are fine. They say they will think about it. Nothing happens, and you are left watching something get slowly worse while being told there is no problem.

This is one of the most frustrating positions there is, and the way out of it is usually not more persuading.

What the refusal is usually about

It is almost never about the help itself.

Accepting help means admitting something has changed. For an older parent, agreeing to a grab rail is agreeing that they are the sort of person who needs one, which is a much bigger concession than it looks.

It also means letting someone in. A cleaner sees the state of the house. A nurse sees the body. A social worker asks questions. For someone private, or ashamed, that cost can outweigh the benefit.

There is loss of control, too. Help usually arrives with other people''s schedules attached, and losing control over your own day is a real thing to resist.

And sometimes refusal is fear. If accepting help is the first step on a path toward a care home, or toward a diagnosis they do not want confirmed, then refusing is a way of holding the path shut.

Stop making the case

Repeating the argument is the most natural response and the least effective one. People do not accept help because the argument got better on the fifth attempt; they usually dig in.

Worse, repetition turns you into the person who always raises it, which means they brace when you arrive and the subject becomes the whole relationship.

So try a different move: ask instead of advocating. What worries you about having someone come in? What would make it bearable? What would you want if it got harder than this?

You will often hear something you did not expect, and it is usually the actual obstacle: a stranger in the house, the money, not wanting to be seen, a bad experience years ago.

Make the help smaller and less official

Most refusals are of the big version. The small version is often accepted.

Not a cleaner, someone to do the windows once. Not meals on wheels, a casserole you made too much of. Not a care assessment, a chat with the nurse who is coming anyway. Not giving up the car, not driving at night.

Trials work too, because they are not permanent. Could we try it for a month and then decide. A reversible version is far easier to say yes to than a commitment.

And reframe it where you honestly can: not help for them but help for you. It would make me worry less. It would mean I can stop asking. Many people who will not accept support for themselves will accept it as a favor.

Pick your two things

You cannot win every item, and treating them all as equally urgent is what exhausts people and wrecks relationships.

So decide what actually matters most, usually on safety grounds: the stairs, the medication, the driving, the stove, the money. Two things.

Let the rest go, visibly. Telling them plainly — I am going to stop going on about the shopping, but I am not going to stop about the stairs — gets you taken more seriously on the two, because you are evidently not just managing them.

Their right to decide, and where it ends

This is the hard part. An adult with capacity is allowed to make choices you consider unwise, including living in a way you find upsetting. That remains true when it is painful to watch.

Where it changes is when they genuinely cannot understand or weigh the decision, when someone is being neglected or exploited, or when there is immediate danger. Those are not arguments to win at the kitchen table; they are reasons to involve a doctor, a social worker, or adult protective services.

If you are unsure which situation you are in, that is itself a reason to ask a professional rather than carrying the judgment alone. A call to a doctor or a local social services line to describe what you are seeing is a reasonable, ordinary thing to do.

Stay in their life anyway

The temptation, after enough refusals, is to withdraw, or to turn every visit into the same conversation.

Neither helps. What tends to help is remaining present and pleasant, and being the person who is still there when they are finally ready, which often happens after a fall, an illness, or a bad week rather than after a good argument.

So keep visiting. Talk about other things. Do the small practical things you are allowed to do without asking permission for them.

And say, once, clearly: I think you need more help than you are getting, and I will arrange it the moment you want it. Then leave the door open rather than standing in it.

Look after your own part of this

Watching someone refuse help is its own strain, and it tends to be carried silently.

Say it out loud to someone: a friend, a support group for families in the same position, a therapist. Caregiver groups are full of people who have had exactly this standoff and they are far better company than advice.

Write down what you have offered and when, if the situation is heading toward formal involvement. And accept that you may not be able to prevent what you can see coming, which is a grief rather than a failure.

When to bring in help for yourself

If this has you lying awake, dreading visits, arguing constantly, or feeling guilty whatever you do, that is worth taking to a doctor or a therapist. Carrying responsibility you cannot act on is one of the heavier things people do quietly.

And if you are worried about someone''s immediate safety, or you suspect neglect or abuse, call the relevant service rather than waiting for permission. Professionals would far rather look into something early than be told afterward.', array['Caregiving', 'Boundaries']::text[], 0, '2026-10-09T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
