-- Five articles published 2026-09-26. Generated by:
--   python3 tools/articles_sql.py --since 2026-09-26
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('walking-when-you-do-not-want-to-be-in-your-head', 'Walking When You Do Not Want to Be in Your Head', 'Not exercise, not a step count. A walk taken specifically because thinking has stopped being useful. How to use one deliberately when you are stuck, spiraling, or flat.', 'There is a particular state where thinking has stopped helping. You have been over the problem eleven times. You are not analyzing anymore, you are just circling, and every lap leaves you slightly worse. Sitting still with it makes it louder.

A walk is unreasonably good for this, and not for the reasons walks usually get recommended. Forget fitness and step counts. This is about using movement as a tool for a mind that has gotten stuck inside itself.

Why it works when sitting does not

A few things happen at once. Your visual field starts moving, which occupies the part of your attention that was being spent on the loop. Your body has a rhythm to attend to. The world supplies input that is not you: weather, dogs, a delivery truck, a tree that has started turning.

Walking also changes the shape of your thoughts rather than only their volume. People often find that a problem they could not hold still enough to see becomes clearer at minute fifteen, and that it arrives sideways rather than as the result of effort.

And it gives a body full of stress hormones something to do with them. Worry is a physical state as much as a mental one, and standing up and moving is one of the few things that reliably discharges it.

Go without a destination

This is the main instruction. A walk to the store is an errand; your mind stays on the errand. A walk with no purpose lets your attention loosen, which is the whole point.

Pick a direction and go. Ten minutes out, ten minutes back. You do not need a route, a park, or good weather. A dull suburban loop works.

Leave the headphones out, at least sometimes

A podcast makes the walk pleasant and fills the space you were trying to open. If your mind is circling hard, try one walk with nothing in your ears. It will be uncomfortable for the first few minutes. That discomfort is the loop not getting what it wants, and it usually passes around the ten-minute mark.

On flat, heavy days, music is different. Something you like can lift a low mood in a way silence will not. Save the silence for the spiraling days.

Use your eyes on purpose

If the circling is loud, give your attention a job outside your head. Name what you see as you pass it, in the plainest terms. Red door. Cracked pavement. Two crows. Somebody''s wet laundry.

This sounds childish and it is the single most effective thing in this article. Naming what is in front of you is not compatible with rehearsing an argument, and doing it for two minutes often breaks the loop entirely.

Let the pace match the state

If you are agitated, start fast. Walk it out, hard enough that your breathing changes, for the first five minutes, then let it settle. Trying to stroll calmly while your body is full of adrenaline rarely works; meeting the energy and then letting it fall is easier.

If you are flat and heavy, the opposite. Slow, short, no standard to meet. Getting to the end of the street counts as the whole walk.

Take the same walk repeatedly

There is a benefit to a route you know by heart: you do not have to navigate, so more attention is free. A familiar loop also becomes a place your mind associates with settling, which means it starts working faster over time. Many people build up one walk they do most days, in all weather, and come to rely on it.

Do it before the decision, not after

If something needs deciding, walk first and decide after, rather than walking to talk yourself into something. Thinking done while moving tends to be less rigid and less fearful, and you will often find your actual preference somewhere in the second half of the walk.

If you have a phone in your pocket, that is fine; leaving it in your pocket is what matters. A walk spent scrolling is a different activity.

Bring someone, sometimes

A walk with a friend is one of the best-designed conversations there is: side by side rather than face to face, with something to look at, no bill arriving, and a natural end. Hard things get said on walks that would not get said across a table. If you have something you have been avoiding telling someone, try telling them while walking.

And take the dog, if there is one. The requirement to go out regardless of your mood is doing more for you than the dog knows.

When a walk is not enough

Movement helps a great deal and it is not treatment. If your mind is circling constantly, if worry is running your days, if you are flat for weeks rather than an afternoon, or if you cannot get out of the house at all, please talk to your doctor or a therapist. A walk is a good tool and a poor substitute for help with something that has settled in. And if you ever find yourself hopeless or thinking of harming yourself, reach out that day. In the US you can call or text 988 at any time. Meanwhile, on an ordinary bad afternoon, putting your shoes on and going outside is still one of the most reliable things available to you.', array['Movement', 'Grounding']::text[], 0, '2026-09-26T14:00:00+00:00'::timestamptz),
  ('when-an-urge-feels-impossible-to-sit-with', 'When an Urge Feels Impossible to Sit With', 'You want to send the message, open the bottle, quit on the spot, or do the thing you will regret. What to do in the twenty minutes when the pull is at its strongest.', 'The urge has arrived and it is enormous. Send the message that will end it. Open the bottle. Say the cruel thing you have ready. Quit, walk out, delete everything. Whatever your particular version is, it feels less like a choice than like a pressure that has to be released.

You know from experience that acting on it will make things worse. You also know that in this state, knowing that does not help much.

Here is what actually works in the twenty minutes that matter.

The urge has a shape

The most useful fact about urges is that they rise, peak, and fall. They do not increase forever, though they always feel as though they will. Most peak within about twenty minutes and then drop noticeably, whether or not you do anything about them.

That means your only job is to get to the other side of the peak without acting. Not to resist forever. Not to stop wanting it. Just to outlast one wave.

Say the wave out loud

Name it as it happens. This is an urge. It is at about a nine. It will come down. I do not have to do anything yet.

Naming an urge as a wave rather than an instruction changes what you are dealing with. You are no longer in an argument about whether to send the message; you are waiting out a weather event.

Put time between you and the action

Everything else in this article is a way of buying twenty minutes.

Make it physically harder. Put the phone in another room. Hand your keys to someone. Pour the drink down the sink. Leave the house. Close the laptop and take it somewhere else. The friction only has to hold for a short while.

Write it instead of sending it. Type the whole message, every word of it, in a notes app. Do not put it in the thread. Most people find the writing discharges a surprising amount, and the unsent version reads very differently an hour later.

Set a timer. Twenty minutes. Tell yourself you can revisit it when the timer goes, which is true. Almost nobody wants to, once it does.

Change your body, hard

Urges live in an activated body, and the fastest way to bring the intensity down is physical rather than mental.

Cold works better than almost anything. Cold water on your face, a cold shower, an ice cube held in your hand, stepping outside without a coat. It produces a genuine physiological shift within a minute or two.

So does intense exertion. Sprint to the end of the street. Twenty press-ups. Take the stairs fast. The goal is to spend the charge, not to exercise.

Slow breathing helps once the peak has passed, and is often too subtle during it. Out-breath longer than the in-breath, for a minute.

Occupy your hands and your attention

A fully occupied mind cannot hold the urge at full volume. It needs to be something demanding, though: scrolling is not enough, because it leaves plenty of room.

Something with your hands and some difficulty in it: cooking something that needs following, a puzzle, an instrument, cleaning a specific thing thoroughly, a video game that requires attention, counting backward from a hundred in sevens. Make it absorbing rather than pleasant.

Tell one person, in the moment

Text someone: I am about to do something stupid, talk to me for ten minutes. You do not need advice; you need company while the wave passes. Anyone who has ever done this for you will do it again.

If you have nobody available at that hour, a helpline serves the same purpose, and that is a completely legitimate use of one.

Afterward, look at what it was about

Once the wave has passed, and not during, ask what the urge was trying to do. Urges are usually trying to end an unbearable feeling: loneliness, shame, rage, fear, boredom that has something underneath it.

That feeling is the actual thing to work on, and it is much easier to see from the far side. Write down what happened, what set it off, and what you did instead. Over time that record shows you your own pattern, which is what lets you catch the next one earlier, when it is a four rather than a nine.

Plan for the next one now

The worst time to invent a strategy is mid-urge. So write your plan on a card while you are calm: the three physical things that work for you, the person you will text, where the phone goes. Then follow the card rather than deciding.

Count the ones you got through

Every wave you outlast makes the next one slightly less convincing, because you accumulate evidence that it passes. That evidence is the real mechanism here. Keep a tally if it helps.

When to get help

Please talk to a therapist if the urges are frequent, if they involve harming yourself, drinking or using, or actions that keep damaging your relationships or your work. There are therapies built specifically for this, and they teach a fuller version of what is above, with someone helping you practice. And if the urge is ever to hurt yourself, please treat it as the emergency it is and reach out immediately. In the US you can call or text 988 at any time. You do not have to win an argument with the urge. You only have to be slower than it is.', array['DBT', 'Emotion Regulation']::text[], 0, '2026-09-26T14:00:00+00:00'::timestamptz),
  ('when-a-friend-owes-you-money', 'When a Friend Owes You Money', 'You lent it months ago and they have not mentioned it since. Why money between friends goes wrong so easily, how to actually ask, and how to decide whether to let it go.', 'You lent them the money because they needed it and you had it. No paperwork, no date, just a transfer and a thank you. That was four months ago. They have been out to dinner twice since, they have not mentioned it, and you think about it every time you see them.

And you have not said anything, because the thought of raising it makes you feel small and grasping, which is a strange thing to feel when you are the one who is owed.

Why this goes wrong so predictably

Money and friendship run on different rules, and a loan puts them in the same room. Friendship works on rough reciprocity that nobody counts. A loan is a specific debt with an amount. Once one exists, the friendship has a ledger in it, and ledgers change how people behave.

It also creates an imbalance that neither of you chose. They are now in the position of owing, which is uncomfortable enough that many people cope by avoiding the subject entirely. Their silence is much more often avoidance than bad faith, though from your side the two look identical.

And the amount is rarely the real problem. What bothers most people is the not-mentioning: the sense that something owed to them has been quietly dropped, and that raising it would make them the difficult one.

Get clear on what you actually want

Before any conversation, decide which of these you want, because they need different approaches.

The money back, in full. Then you need a plan and a date.

The money back over time. Then you need a schedule that suits their situation.

Not the money, but an acknowledgment. Many people find this is the real thing. They want to hear that it is remembered.

To let it go entirely, and be free of thinking about it. That is a legitimate choice, and it takes a deliberate decision rather than drifting.

Ask plainly and early

The conversation is easier than the dread suggests, and much easier at four months than at two years. The keys are to be direct, to be warm, and not to apologize for asking.

Hey, I wanted to check in about the money I lent you in May. What would work for paying it back?

That is all. Not, I hate to bring this up, sorry, I know things are hard. Softening it invites more delay, and it signals that you feel you are doing something wrong, which you are not.

Then be quiet and let them answer.

Make it easy to say the true thing

Most of the time the honest answer is that they cannot pay it right now. Leave room for that: if it is not possible at the moment, tell me and we will figure out a plan.

Then make an actual plan, with numbers and dates, even small ones. Fifty a month starting in October, said out loud, resolves this better than a vague promise, and it lets them stop avoiding you.

If they say yes and then nothing happens

Follow up once, in writing, without heat: just checking, are you still able to start that in October? A written record is not aggressive; it is how adults handle money, and it removes the ambiguity that lets it drift again.

If it keeps not happening after that, you have learned something real. At that point the question changes from how do I get this back to what do I want this friendship to be.

Decide whether to let it go

Sometimes the most self-respecting choice is to write it off. Not out of resentment, and not silently while keeping score forever. An actual decision: this money is gone, I am not going to think about it again, and I am not going to lend to this person again.

That last clause is the important one. Letting go of the amount without changing the pattern means you will be here again.

If you do decide to release it, say so if it helps: let us call it a gift, I would rather have you than the money. Then mean it, and stop mentioning it.

Watch what it is doing to the friendship

Unspoken money sits in the middle of a relationship and slowly changes it. You start noticing what they spend on. You feel a flash of something when they order the expensive thing. They feel watched, and they start seeing you less.

Whichever route you pick, the point of picking one is to get the ledger out of the friendship. Almost any resolution beats another year of quiet accounting.

Next time, decide in advance which it is

The most useful habit is to decide before you hand anything over whether this is a loan or a gift, and to say which out loud. If it is a loan, name an amount and a rough date. If you would not be willing to chase it, make it a gift and expect nothing.

And a rule many people keep, having learned it the hard way: only lend an amount you could lose without it changing how you feel about the person.

When it is bigger than this

If the amount is large enough to be affecting your own finances, it is worth taking seriously rather than politely. If a family member keeps borrowing and not repaying, or if there is pressure, guilt, or anger when you raise it, that is a pattern rather than an incident, and a therapist can help you work out what to do about it. Money in relationships is one of the most common things people bring to therapy, precisely because it is never only about money. And if you are the one who owes, please know that saying I cannot pay this yet, here is what I can do is almost always received better than silence.', array['Money', 'Boundaries']::text[], 0, '2026-09-26T14:00:00+00:00'::timestamptz),
  ('the-first-weeks-back-at-work-after-something-hard', 'The First Weeks Back at Work After Something Hard', 'Someone died, or you were ill, or your life came apart. Now you are back at your desk and everyone is being normal. How to get through the return without pretending you are fine.', 'You buried your mother eleven days ago. Or you came out of hospital, or your marriage ended, or something happened that split your life in two. And this morning you put on work clothes and went back, and by ten o''clock someone was asking you about a spreadsheet.

The return to work after something serious is strange in a way nobody prepares you for. The world carried on. Your inbox filled up with things that do not matter. And you are expected, more or less, to be the person you were before.

Expect to be much less capable than usual

Grief, illness, and shock all take a large amount of the machinery you use for work. Concentration, short-term memory, decision-making, and patience are all reduced, often dramatically, and often without you noticing until you have read the same email four times.

This is temporary and it is not a character failure. Plan for it rather than being surprised by it: write everything down, do not trust your memory, check your own work, and do the hardest thing early in the day if you can.

Go back gradually if there is any way to

Half days, three days a week, two weeks of reduced responsibility. If your workplace allows it, take it, even if you feel able to go back fully. Almost everyone who returns at full speed hits a wall in week two or three.

If it cannot be gradual, at least keep the first weeks narrow: fewer meetings, no new projects, nothing you volunteer for.

Decide in advance what you will say

The hardest part for many people is the thirty conversations. Someone catches you at the coffee machine and says how are you, and you have to decide in that second how much to give.

Have two answers ready. A short one for people you barely know: thank you for asking, it has been a hard few weeks, I am glad to be back. And a fuller one for the two or three people you actually want to tell. Practice the short one until it comes out without effort, because it is the one you will use most.

You are allowed to say I would rather not talk about it here, and to say it pleasantly and repeatedly.

Let someone go first for you

If you can, ask one person, your manager or a colleague you trust, to tell people what happened and what you want. That saves you from delivering the news thirty times. Many people find this the single most helpful thing anyone did.

Tell them what you need too, specifically: please do not ask me how I am every morning. Please do put things in writing. Please do carry on talking about normal things around me.

Expect it to hit at unpredictable times

You will be fine through a difficult meeting and then be undone by a song in the elevator, or by a colleague mentioning their own mother. The wave arrives without warning and often at the most inconvenient moment.

Have a plan for it: where you can go for ten minutes, how you leave a room without explaining, what you say if someone sees. Something as simple as I need a minute, back shortly is enough. Nobody needs a reason.

Let work be a relief when it is

Many people feel guilty when work turns out to help, when a few hours of ordinary problem-solving gives them a break from the thing. That is not disloyalty or denial. Being absorbed in something is genuinely restorative, and the grief will be there when you finish.

Protect the rest of the day

The return uses more energy than the work itself. Do less in the evenings than you normally would, and expect to be exhausted in a way the hours do not explain. This is the part people underestimate: they manage the working day and then have nothing left for the people at home.

Know your rights, roughly

Bereavement leave, sick leave, and flexible arrangements vary a great deal, and many people take much less than they are entitled to because they never asked. It is worth one conversation with your manager or human resources about what is actually available, including a phased return, which is more common than most people think.

Watch the three-month mark

The support tends to fade around the time it gets harder. In the first weeks people are kind and ask after you. By month three they have moved on, and you may be at your lowest, because the shock has worn off and the permanence has arrived. Expect that shape rather than reading it as evidence that you are failing at recovery.

When to get more help

Please talk to your doctor or a therapist if, after a couple of months, you cannot function at work, if you are not sleeping, if you are drinking more to get through, if you feel nothing at all, or if the thought of going in produces dread every single day. Many workplaces have a confidential employee assistance program that you can use without telling anyone, and a bereavement or trauma counselor can help you carry this while you work. And if you ever find yourself hopeless or thinking of harming yourself, please reach out that day. In the US you can call or text 988 at any time. You are doing something difficult with far less than your usual capacity. That deserves patience, most of all from you.', array['Work', 'Grief']::text[], 0, '2026-09-26T14:00:00+00:00'::timestamptz),
  ('when-your-adult-child-stops-speaking-to-you', 'When Your Adult Child Stops Speaking to You', 'The calls stopped. You do not fully understand why, and every attempt to fix it seems to make it worse. What tends to help, what makes it harder, and how to survive the waiting.', 'They stopped answering. Maybe there was a message explaining it, maybe a conversation that went badly, maybe nothing at all. You have written, apologized, sent things on their birthday. Some of it went unanswered and some of it made things worse. You do not know whether this is a season or the rest of your life.

Estrangement from an adult child is one of the loneliest things a person can go through, partly because of the loss itself and partly because there is nowhere to talk about it. Other people''s children call them.

Start with the hardest part

Whatever you believe about the fairness of it, the practical situation is this: they have the say. An adult gets to decide who is in their life, and no amount of being right will change that. Any path back runs through respecting that, even when you think they have it wrong.

That is not the same as accepting a version of events you do not agree with. It is accepting who controls the door.

Try to hear what they actually said

If they gave you a reason, read it again, slowly, as information rather than as an accusation. Most estranged children say afterward that they explained clearly and were not heard: the parent argued with the facts, or apologized for the wrong thing, or made the conversation about their own pain.

Try to separate what you did from what you meant. Most parents in this situation did not intend harm. Intention and effect are different things, and they are asking about the effect.

If you genuinely do not know the reason, you can ask once, plainly, and then wait.

Apologize for the thing, not for the estrangement

The apology that helps names specifics and takes responsibility without conditions. I am sorry I dismissed you when you told me about that. I have thought about it and I can see now that it hurt you.

The apology that makes things worse is the one that is really a complaint: I am sorry for whatever I did, but I do not think I deserve this. I am sorry you feel that way. I did my best and you have no idea what I sacrificed.

Send one good one and then stop. Repeated apologizing becomes pressure.

Do not flood them

The instinct is to keep reaching: messages, gifts, showing up, calling other relatives, sending long letters. Every one of those is love and most of them push a person further away, because they signal that their decision is not being respected.

A better pattern is small, low-pressure, and infrequent. Something once in a while that requires no reply: thinking of you on your birthday, I love you, no need to write back. Then leave it.

Do not go through other people

Enlisting siblings, your ex, or their partner as messengers or advocates almost always backfires and tends to damage those relationships too. If there are grandchildren involved, that becomes agonizing, and pressure still does not work. Keep the line simple and direct.

Take the blame you actually own, and only that

Some estrangements follow something serious. Some follow years of small things: contempt, control, taking sides, not protecting them, an inability to hear criticism. Some follow nothing that a reasonable person would call harm, and involve a partner, a new belief, or an illness.

Work out honestly which parts are yours, and let go of defending the rest. A parent who can say I got that wrong without also needing to win is the parent an adult child can eventually come back to.

Get help for yourself, separately

This is the practical advice most often skipped. Estranged parents frequently carry this alone for years, because it feels shameful and because people assume the worst about them.

A therapist of your own gives you somewhere to put the grief, and helps with the harder question of what to look at in yourself, which is much easier to do with support than alone. There are also support groups specifically for estranged parents; being with people who do not need the situation explained is a considerable relief.

Build a life that is not waiting

The hardest and most necessary thing: do not put your life on hold. People can wait years. Keep your friendships, your work, your interests, your health. Not as a way of moving on, which you may never do, but because a parent whose entire existence is suspended around one absence is both very unhappy and harder to reconnect with.

Grieve it, even though they are alive

This is a real loss and it deserves to be grieved rather than only fought. Let yourself be sad about it, mark the birthdays, cry when it comes. Grief for a living person is disorienting because there is no ending, and it still works better felt than held down.

Leave the door visibly open

If there is one thing to keep doing, it is making sure they know the door is not locked. A message once a year that says it, without pressure, without a list of grievances, without conditions. Many reconciliations happen years later, and almost all of them happen because the child knew they could come back without having to fight their way in.

When you need more support

Please talk to a therapist if this is affecting your sleep, your health, or your ability to function, if you have withdrawn from the people still in your life, or if the grief has become despair. And if you ever find yourself feeling hopeless or having thoughts of harming yourself, please reach out that day. In the US you can call or text 988 at any time. This is one of the heaviest things a parent can carry, and you should not be carrying it without help.', array['Family', 'Loss']::text[], 0, '2026-09-26T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
