-- =============================================================================
-- License lookup URLs for the other 49 states.
-- -----------------------------------------------------------------------------
-- The admin license queue (site/admin.html) links each pending therapist to
-- the `behavioral_health` row for their first license state, and falls back to
-- a web search when there is none. Until now only California had a row.
--
-- Each verify_url is the board's own public lookup, opened and checked on
-- 2026-09-10. Where a state splits counselors, social workers and marriage and
-- family therapists across separate boards, verify_url is the counselor board
-- and `notes` names the others. Psychologists usually sit with a separate
-- board of psychology, which these rows do not cover.
--
-- None of these boards publishes a machine-readable endpoint, so api_url stays
-- null and automatable false: an administrator confirms by hand against the
-- lookup, exactly as for California.
--
-- Re-running is harmless: the upsert refreshes the name, URL and notes of a
-- state that already has a row and keeps its id. California is left alone.
-- =============================================================================

insert into public.state_boards (state, profession, board_name, verify_url, notes)
values
  ('AL', 'behavioral_health', 'Alabama Board of Examiners in Counseling',
   'https://abec.alabama.gov/',
   'LPC and ALC. Social workers: Alabama State Board of Social Work Examiners, https://socialwork.alabama.gov/'),
  ('AK', 'behavioral_health', 'Alaska Division of Corporations, Business and Professional Licensing',
   'https://www.commerce.alaska.gov/cbp/main/search/professional',
   'One statewide search covering the counselor, social work and marital and family therapy boards.'),
  ('AZ', 'behavioral_health', 'Arizona Board of Behavioral Health Examiners',
   'https://azbbhe.portalus.thentiacloud.net/webs/portal/register/',
   'One board for LPC, LCSW, LMFT and LISAC. Board site: https://bbhe.az.gov/directory-and-verifications-search'),
  ('AR', 'behavioral_health', 'Arkansas Board of Examiners in Counseling and Marriage and Family Therapy',
   'https://portal.arkansas.gov/service/ar-counselor-mariage-fam-therapist-lic-search/',
   'LPC, LAC, LMFT. Social workers: Arkansas Social Work Licensing Board (Department of Health).'),
  ('CO', 'behavioral_health', 'Colorado Department of Regulatory Agencies, Division of Professions and Occupations',
   'https://apps2.colorado.gov/dora/licensing/lookup/licenselookup.aspx',
   'One statewide lookup for LPC, LCSW, LMFT, LAC and psychologists.'),
  ('CT', 'behavioral_health', 'Connecticut Department of Public Health',
   'https://www.elicense.ct.gov/Lookup/LicenseLookup.aspx',
   'One statewide eLicense lookup for LPC, LCSW, LMFT and psychologists.'),
  ('DE', 'behavioral_health', 'Delaware Division of Professional Regulation',
   'https://delpros.delaware.gov/OH_VerifyLicense',
   'DELPROS lookup covers the Board of Mental Health and Chemical Dependency Professionals and the Board of Social Work Examiners.'),
  ('FL', 'behavioral_health', 'Florida Department of Health, Division of Medical Quality Assurance',
   'https://mqa-internet.doh.state.fl.us/MQASearchServices/HealthCareProviders',
   'Board of Clinical Social Work, Marriage and Family Therapy and Mental Health Counseling. Same lookup covers psychologists.'),
  ('GA', 'behavioral_health', 'Georgia Composite Board of Professional Counselors, Social Workers and Marriage and Family Therapists',
   'https://verify.sos.ga.gov/verification/',
   'Secretary of State verification. One board for LPC, LCSW and LMFT.'),
  ('HI', 'behavioral_health', 'Hawaii Department of Commerce and Consumer Affairs, Professional and Vocational Licensing',
   'https://mypvl.dcca.hawaii.gov/public-license-search/',
   'One statewide search for mental health counselors, social workers and MFTs.'),
  ('ID', 'behavioral_health', 'Idaho Division of Occupational and Professional Licenses',
   'https://dopl.idaho.gov/license-search/',
   'One statewide search. Counselors and MFTs sit with the Licensing Board of Professional Counselors and Marriage and Family Therapists; social workers with the Board of Social Work Examiners.'),
  ('IL', 'behavioral_health', 'Illinois Department of Financial and Professional Regulation',
   'https://online-dfpr.micropact.com/lookup/licenselookup.aspx',
   'One statewide lookup for LPC, LCPC, LCSW, LMFT and psychologists.'),
  ('IN', 'behavioral_health', 'Indiana Professional Licensing Agency, Behavioral Health and Human Services Licensing Board',
   'https://mylicense.in.gov/everification/',
   'One board for LMHC, LCSW, LMFT and LCAC.'),
  ('IA', 'behavioral_health', 'Iowa Board of Behavioral Health Professionals',
   'https://amanda-portal.idph.state.ia.us/ibpl/portal/',
   'Merged board (July 2024) for LMHC, LMFT, social workers and psychologists, under the Department of Inspections, Appeals and Licensing.'),
  ('KS', 'behavioral_health', 'Kansas Behavioral Sciences Regulatory Board',
   'https://licensing.ks.gov/Verification_BSRB/Search.aspx',
   'One board for LPC, LCPC, LCSW, LMFT, LCMFT and psychologists.'),
  ('KY', 'behavioral_health', 'Kentucky Board of Licensed Professional Counselors',
   'https://lpc.ky.gov/',
   'Use the Verify a License link. Social workers: Kentucky Board of Social Work, https://bsw.ky.gov/ . MFTs: Kentucky Board of Licensure for Marriage and Family Therapists.'),
  ('LA', 'behavioral_health', 'Louisiana Licensed Professional Counselors Board of Examiners',
   'https://www.lpcboard.org/',
   'LPC and LMFT. Social workers: Louisiana State Board of Social Work Examiners, https://www.labswe.org/'),
  ('ME', 'behavioral_health', 'Maine Office of Professional and Occupational Regulation',
   'https://www.pfr.maine.gov/ALMSOnline/ALMSQuery/SearchIndividual.aspx',
   'One statewide search covering the Board of Counseling Professionals Licensure and the Board of Social Worker Licensure.'),
  ('MD', 'behavioral_health', 'Maryland Board of Professional Counselors and Therapists',
   'https://mdbnc.health.maryland.gov/PCTPortal/verify',
   'LCPC, LGPC, LCMFT. Social workers: Maryland Board of Social Work Examiners, https://health.maryland.gov/bswe/'),
  ('MA', 'behavioral_health', 'Massachusetts Board of Registration of Allied Mental Health and Human Services Professions',
   'https://www.mass.gov/how-to/check-a-professional-license',
   'LMHC and LMFT. Social workers: Board of Registration of Social Workers, same check-a-license page.'),
  ('MI', 'behavioral_health', 'Michigan Department of Licensing and Regulatory Affairs, Bureau of Professional Licensing',
   'https://val.apps.lara.state.mi.us/',
   'One statewide Verify a License search for LPC, LMSW, LMFT and psychologists.'),
  ('MN', 'behavioral_health', 'Minnesota Board of Behavioral Health and Therapy',
   'https://bht.hlb.state.mn.us/',
   'LPC, LPCC, LADC. Social workers: Board of Social Work, https://mn.gov/boards/social-work/ . MFTs: Board of Marriage and Family Therapy.'),
  ('MS', 'behavioral_health', 'Mississippi State Board of Examiners for Licensed Professional Counselors',
   'https://www.lpc.ms.gov/secure/licensesearch.asp',
   'LPC. Social workers and MFTs: Mississippi Board of Examiners for Social Workers and Marriage and Family Therapists, https://www.swmft.ms.gov/'),
  ('MO', 'behavioral_health', 'Missouri Division of Professional Registration',
   'https://mopro.mo.gov/license/s/license-search',
   'MOPRO search covers the Committee for Professional Counselors, the State Committee for Social Workers and the State Committee of Marital and Family Therapists.'),
  ('MT', 'behavioral_health', 'Montana Board of Behavioral Health',
   'https://ebiz.mt.gov/pol/',
   'One board for LCPC, LCSW, LMFT and LAC.'),
  ('NE', 'behavioral_health', 'Nebraska Department of Health and Human Services, Licensure Unit',
   'https://www.nebraska.gov/LISSearch/search.cgi',
   'One statewide search for LIMHP, LMHP, LCSW, LMFT and psychologists.'),
  ('NV', 'behavioral_health', 'Nevada Board of Examiners for Marriage and Family Therapists and Clinical Professional Counselors',
   'https://www.marriage.nv.gov/',
   'LMFT and CPC. Social workers: Nevada Board of Examiners for Social Workers, https://socwork.nv.gov/'),
  ('NH', 'behavioral_health', 'New Hampshire Office of Professional Licensure and Certification',
   'https://forms.nh.gov/licenseverification/',
   'One statewide lookup covering the Board of Mental Health Practice (LCMHC, LICSW, LMFT).'),
  ('NJ', 'behavioral_health', 'New Jersey Division of Consumer Affairs',
   'https://newjersey.mylicense.com/verification/',
   'One statewide lookup covering the Professional Counselor Examiners Committee, the Board of Social Work Examiners and the Board of Marriage and Family Therapy Examiners.'),
  ('NM', 'behavioral_health', 'New Mexico Regulation and Licensing Department, Counseling and Therapy Practice Board',
   'https://nmrldlpi.my.site.com/bcd/s/',
   'One statewide lookup. Social workers sit with the Board of Social Work Examiners on the same lookup.'),
  ('NY', 'behavioral_health', 'New York State Education Department, Office of the Professions',
   'https://www.op.nysed.gov/verification-search',
   'One statewide verification for LMHC, LCSW, LMSW, LMFT and psychologists.'),
  ('NC', 'behavioral_health', 'North Carolina Board of Licensed Clinical Mental Health Counselors',
   'https://ncblpc.org/',
   'LCMHC. Social workers: North Carolina Social Work Certification and Licensure Board, https://www.ncswboard.org/ . MFTs: North Carolina Marriage and Family Therapy Licensure Board.'),
  ('ND', 'behavioral_health', 'North Dakota Board of Counselor Examiners',
   'https://www.ndbce.org/',
   'LPC, LPCC, LAPC. Social workers: North Dakota Board of Social Work Examiners, https://www.ndbswe.com/'),
  ('OH', 'behavioral_health', 'Ohio Counselor, Social Worker and Marriage and Family Therapist Board',
   'https://elicense.ohio.gov/oh_verifylicense',
   'One board for LPC, LPCC, LSW, LISW and LMFT, on the statewide eLicense lookup.'),
  ('OK', 'behavioral_health', 'Oklahoma State Board of Behavioral Health Licensure',
   'https://oklahoma.gov/behavioralhealth.html',
   'LPC, LMFT, LBP, LADC. Social workers: Oklahoma State Board of Licensed Social Workers.'),
  ('OR', 'behavioral_health', 'Oregon Board of Licensed Professional Counselors and Therapists',
   'https://www.oregon.gov/mhra/pages/verify.aspx',
   'LPC and LMFT, verified through the Mental Health Regulatory Agency. Social workers: Oregon Board of Licensed Social Workers.'),
  ('PA', 'behavioral_health', 'Pennsylvania State Board of Social Workers, Marriage and Family Therapists and Professional Counselors',
   'https://www.pals.pa.gov/',
   'One board for LPC, LCSW and LMFT, on the statewide PALS lookup.'),
  ('RI', 'behavioral_health', 'Rhode Island Department of Health',
   'https://healthri.mylicense.com/verification/',
   'One statewide lookup covering the Board of Mental Health Counselors and Marriage and Family Therapists and the Board of Social Work Examiners.'),
  ('SC', 'behavioral_health', 'South Carolina Board of Examiners for Licensure of Professional Counselors, Marriage and Family Therapists, Addiction Counselors and Psycho-Educational Specialists',
   'https://verify.llronline.com/LicLookup/',
   'LLR lookup. Social workers: South Carolina Board of Social Work Examiners, same lookup.'),
  ('SD', 'behavioral_health', 'South Dakota Board of Examiners for Counselors and Marriage and Family Therapists',
   'https://dss.sd.gov/licensingboards/counselors/',
   'LPC, LPC-MH, LMFT. Social workers: South Dakota Board of Social Work Examiners, https://dss.sd.gov/licensingboards/socialwork/'),
  ('TN', 'behavioral_health', 'Tennessee Department of Health',
   'https://apps.health.tn.gov/Licensure/',
   'One statewide lookup covering the Board for Professional Counselors, Marital and Family Therapists and Clinical Pastoral Therapists and the Board of Social Worker Licensure.'),
  ('TX', 'behavioral_health', 'Texas Behavioral Health Executive Council',
   'https://bhec.texas.gov/tbhec/verify-a-license/',
   'One council for LPC, LCSW, LMFT and psychologists. The council states its online search counts as primary source verification.'),
  ('UT', 'behavioral_health', 'Utah Division of Professional Licensing',
   'https://secure.utah.gov/llv/search/index.html',
   'One statewide lookup for CMHC, LCSW, LMFT and psychologists.'),
  ('VT', 'behavioral_health', 'Vermont Office of Professional Regulation',
   'https://sos.vermont.gov/opr/find-a-professional/',
   'One statewide lookup for LCMHC, LICSW, LMFT and psychologists.'),
  ('VA', 'behavioral_health', 'Virginia Department of Health Professions, Board of Counseling',
   'https://dhp.virginiainteractive.org/lookup/index',
   'One statewide lookup. Social workers sit with the Board of Social Work on the same lookup.'),
  ('WA', 'behavioral_health', 'Washington State Department of Health',
   'https://fortress.wa.gov/doh/providercredentialsearch/',
   'One statewide credential search for LMHC, LICSW, LMFT and psychologists.'),
  ('WV', 'behavioral_health', 'West Virginia Board of Examiners in Counseling',
   'https://wvbec.certemy.com/public-registry/789a3bf9-db9c-4cb7-9a88-2dbb2745460c',
   'LPC and LMFT. Social workers: West Virginia Board of Social Work, https://www.wvsocialworkboard.org/'),
  ('WI', 'behavioral_health', 'Wisconsin Department of Safety and Professional Services',
   'https://license.wi.gov/s/license-lookup',
   'One statewide lookup covering the Marriage and Family Therapy, Professional Counseling and Social Work Examining Board.'),
  ('WY', 'behavioral_health', 'Wyoming Mental Health Professions Licensing Board',
   'https://mentalhealth.wyo.gov/public/license-verification',
   'One board for LPC, LCSW, LMFT and LAT.')
on conflict (state, profession) do update
  set board_name = excluded.board_name,
      verify_url = excluded.verify_url,
      notes      = excluded.notes;
