-- The two checklists published on 2026-10-06: the week after losing a job
-- (Work) and eating with no appetite (Food).
-- Generated by `python3 tools/checklists_sql.py --since 2026-10-06`; the repo
-- copy in data/checklists.json is the source. Re-applying is harmless.
insert into public.checklists
  (slug, title, description, category, items, cadence, tags, min_level, published_at)
values
  ('the-week-after-losing-your-job', 'The Week After Losing Your Job', 'For the first days after a layoff or a firing, before the job search begins in earnest. It helps you file the paperwork that matters, keep some shape to the day, and tell people in words that do not cost you anything.', 'Work', '["File for unemployment in the first week — in most states the clock starts the day you apply.", "Write down your last day and what you are owed — final pay and unused leave are easy to lose track of.", "Check what happens to your health coverage — the gap is the part that catches people out.", "Set a get-up time and keep it — a day with no edges is harder than a busy one.", "Decide the one sentence you will tell people — having it ready saves you explaining it twelve times.", "Keep one appointment outside the house each day — leaving the house stops the week from blurring.", "Save the contacts and files you are allowed to — access tends to disappear sooner than you expect.", "Give yourself a date to start applying — a planned pause is rest, an unplanned one is dread."]'::jsonb, 'as needed', array['Work', 'Life Transitions']::text[], 1, '2026-10-06T16:00:00+00:00'::timestamptz),
  ('eating-when-you-have-no-appetite', 'Eating When You Have No Appetite', 'For the stretches when food feels like a chore and meals get skipped without you deciding to. It helps you get something in without cooking, make eating less of an event, and notice when it is time to tell a doctor.', 'Food', '["Keep something you can eat cold in the house — a meal that needs no cooking gets eaten.", "Aim for something small every few hours — frequent and small beats waiting for hunger.", "Drink it instead of chewing it — a smoothie or a glass of milk asks less of you.", "Put it on a smaller plate — a full small plate is less daunting than a half-empty one.", "Eat with someone, in person or on a call — company carries a meal that willpower will not.", "Set a quiet alarm at the times you usually eat — appetite is a poor reminder right now.", "Keep one food you always like within reach — familiar beats nutritious on the hard days.", "Tell a doctor if this has run on for weeks — a long stretch is worth someone looking at."]'::jsonb, 'daily', array['Food', 'Self-Care']::text[], 1, '2026-10-06T16:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  description  = excluded.description,
  category     = excluded.category,
  items        = excluded.items,
  cadence      = excluded.cadence,
  tags         = excluded.tags,
  min_level    = excluded.min_level,
  published_at = excluded.published_at;
