-- The first twenty themed challenges, 2026-09-24. Generated from
-- data/challenges.json by tools/challenges_sql.py --since 2026-09-24;
-- an upsert on slug, so applying it twice is harmless.

-- The templates: an upsert on slug, so a re-run keeps every id.
insert into public.challenge_templates
  (slug, title, description, category, total_days, tags, min_level, published_at)
values
  ('slowing-down-the-mental-chatter', 'Slowing Down the Mental Chatter', 'For the days when your mind will not stop talking. Each day gives you one small way to notice the noise, let it pass, and come back to what is in front of you.', 'Mindfulness', 30, array['Mindfulness', 'Stress']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('fostering-gratitude', 'Fostering Gratitude', 'A daily habit of noticing what is already good, even on hard days. Each day points you at one small thing to appreciate, say thank you for, or savor a little longer.', 'Gratitude', 30, array['Resilience', 'Mindfulness']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('redirecting-unhelpful-thoughts', 'Redirecting Unhelpful Thoughts', 'For thoughts that run in circles, jump to the worst case, or talk you down. Each day offers one practical way to catch an unhelpful thought and steer it somewhere more useful.', 'Thinking', 30, array['Thinking Traps', 'CBT']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('winding-down-for-better-sleep', 'Winding Down for Better Sleep', 'Small evening changes that make it easier to drift off. Each day asks for one adjustment to the last hour of your day, so sleep has a clearer path to find you.', 'Sleep', 30, array['Sleep', 'Habits']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('softening-the-inner-critic', 'Softening the Inner Critic', 'For anyone who talks to themselves more harshly than they would ever talk to a friend. Each day gives you one way to notice the critical voice and answer it with something kinder and more honest.', 'Self-Compassion', 30, array['Self-Compassion', 'Self-Esteem']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('moving-a-little-every-day', 'Moving a Little Every Day', 'Gentle daily movement for people who do not want a workout plan, just a body that feels a little looser and a mood that feels a little lighter. Every day is one small, doable way to move.', 'Body', 30, array['Movement', 'Body']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('reaching-out-to-people', 'Reaching Out to People', 'For when your circle has gone quiet or you have been keeping to yourself. Each day is one small, low-pressure way to reconnect with someone, so contact becomes easier again.', 'Connection', 30, array['Relationships', 'Loneliness']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('loosening-the-grip-of-worry', 'Loosening the Grip of Worry', 'For a mind that spends its days rehearsing what could go wrong. Each day gives you one way to set worry down for a while, so it takes up less of your day.', 'Worry', 30, array['Worry', 'Anxiety']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('holding-your-boundaries', 'Holding Your Boundaries', 'For people who say yes when they mean no, or feel used up by everyone else''s needs. Each day is one small practice in noticing your limits and stating them plainly and kindly.', 'Boundaries', 30, array['Boundaries', 'Assertiveness']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('building-a-calmer-morning', 'Building a Calmer Morning', 'For mornings that start with a scramble and set the tone for the whole day. Each day is one small change to the first hour, so you begin from somewhere steadier.', 'Mornings', 30, array['Habits', 'Stress']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('making-room-for-rest', 'Making Room for Rest', 'For people who are running on empty and cannot remember the last real break. Each day gives you one small permission to stop, so rest becomes part of the day instead of something you earn.', 'Rest', 30, array['Burnout', 'Self-Care']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('living-by-your-values', 'Living by Your Values', 'For when your days are full but do not feel like yours. Each day asks you to notice what matters to you and take one small action in that direction, so your life lines up a little more with what you care about.', 'Values', 30, array['Values', 'Motivation']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('small-acts-of-kindness', 'Small Acts of Kindness', 'A daily practice of doing something small for someone else, which has a way of lifting the giver too. Each day is one easy, specific act of kindness, most of them taking less than five minutes.', 'Kindness', 30, array['Relationships', 'Values']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('making-peace-with-time-alone', 'Making Peace with Time Alone', 'For when being on your own feels more like emptiness than freedom. Each day offers one small way to make time alone feel chosen, full, and kind, while keeping the door open to other people.', 'Loneliness', 30, array['Loneliness', 'Self-Care']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('loosening-the-phone-habit', 'Loosening the Phone Habit', 'For anyone who picks up their phone without deciding to and puts it down feeling worse. Each day is one small experiment in using the phone on purpose, so your attention comes back to you.', 'Focus', 30, array['Habits', 'Mindfulness']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('tidying-one-corner-at-a-time', 'Tidying One Corner at a Time', 'For a home that has gotten on top of you and a mind that feels the same. Each day is one small corner, drawer, or surface, ten minutes at most, so order comes back a little at a time.', 'Home', 30, array['Habits', 'Stress']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('meeting-anger-early', 'Meeting Anger Early', 'For anger that arrives fast and leaves a mess behind. Each day gives you one way to notice it sooner, cool it a little, and say what you mean without the heat, one practice at a time.', 'Anger', 30, array['Anger', 'Emotion Regulation']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('rebuilding-confidence-in-small-steps', 'Rebuilding Confidence in Small Steps', 'For when your confidence has taken a knock and everything feels like a risk. Each day is one small, doable act of showing up, so evidence that you can builds one day at a time.', 'Confidence', 30, array['Self-Esteem', 'Social Anxiety']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('feeling-your-feet-on-the-ground', 'Feeling Your Feet on the Ground', 'For the moments when everything speeds up and you feel far away from yourself. Each day teaches one simple grounding practice, so you have a toolkit ready when you need to come back to the present.', 'Grounding', 30, array['Grounding', 'Anxiety']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz),
  ('getting-unstuck-one-tiny-step-at-a-time', 'Getting Unstuck, One Tiny Step at a Time', 'For the task you keep putting off and the guilt that grows around it. Each day asks for one tiny, specific step on something you have been avoiding, so momentum comes back without needing a burst of willpower.', 'Motivation', 30, array['Motivation', 'Perfectionism']::text[], 1, '2026-09-24T17:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  description  = excluded.description,
  category     = excluded.category,
  total_days   = excluded.total_days,
  tags         = excluded.tags,
  min_level    = excluded.min_level,
  published_at = excluded.published_at;

-- The bank of to-dos for each of those templates, replaced wholesale.
delete from public.challenge_days d
  using public.challenge_templates t
  where d.template_id = t.id and t.slug in ('slowing-down-the-mental-chatter', 'fostering-gratitude', 'redirecting-unhelpful-thoughts', 'winding-down-for-better-sleep', 'softening-the-inner-critic', 'moving-a-little-every-day', 'reaching-out-to-people', 'loosening-the-grip-of-worry', 'holding-your-boundaries', 'building-a-calmer-morning', 'making-room-for-rest', 'living-by-your-values', 'small-acts-of-kindness', 'making-peace-with-time-alone', 'loosening-the-phone-habit', 'tidying-one-corner-at-a-time', 'meeting-anger-early', 'rebuilding-confidence-in-small-steps', 'feeling-your-feet-on-the-ground', 'getting-unstuck-one-tiny-step-at-a-time');

insert into public.challenge_days (template_id, day, title, task)
select t.id, v.day, null, v.task
from (values
  ('slowing-down-the-mental-chatter', 1, 'Sit for two minutes and count your breaths from one to ten. When you lose count, start again at one.'),
  ('slowing-down-the-mental-chatter', 2, 'Pick one ordinary sound near you, a fan, traffic, birds, and listen to it alone for one full minute.'),
  ('slowing-down-the-mental-chatter', 3, 'Each time a thought pulls you away today, silently label it "thinking" and return to what you were doing.'),
  ('slowing-down-the-mental-chatter', 4, 'Eat one meal or snack with nothing else going on. Notice the taste of the first three bites.'),
  ('slowing-down-the-mental-chatter', 5, 'Set a timer for three minutes and watch your thoughts go by as if they were cars on a road. You are on the sidewalk.'),
  ('slowing-down-the-mental-chatter', 6, 'Walk for five minutes and name what you see, in your head, as you pass it: tree, mailbox, door.'),
  ('slowing-down-the-mental-chatter', 7, 'Before you reply to any message today, take one slow breath first.'),
  ('slowing-down-the-mental-chatter', 8, 'Write down the thought that keeps circling. Seeing it on paper often shrinks it.'),
  ('slowing-down-the-mental-chatter', 9, 'Do one chore, dishes, folding, sweeping, at half your usual speed and stay with the movements.'),
  ('slowing-down-the-mental-chatter', 10, 'Notice the pause at the end of each out-breath. Rest there for a second before the next breath comes.'),
  ('slowing-down-the-mental-chatter', 11, 'Choose a word like "steady" or "here." Say it silently on each out-breath for two minutes.'),
  ('slowing-down-the-mental-chatter', 12, 'Stand at a window for three minutes and simply look. No phone, no plan, just looking.'),
  ('slowing-down-the-mental-chatter', 13, 'When your mind races today, feel your feet on the floor and press them down gently for ten seconds.'),
  ('slowing-down-the-mental-chatter', 14, 'Put your hand on your chest and feel it rise and fall for ten breaths.'),
  ('slowing-down-the-mental-chatter', 15, 'Give your mind one job for five minutes: count backward from 100 by threes.'),
  ('slowing-down-the-mental-chatter', 16, 'Drink a glass of water slowly, noticing the temperature and the swallow.'),
  ('slowing-down-the-mental-chatter', 17, 'Spend three minutes noticing five things you can see, four you can hear, and three you can touch.'),
  ('slowing-down-the-mental-chatter', 18, 'When a worry loop starts, ask it: "Is there anything to do about this right now?" If not, let it wait until tomorrow.'),
  ('slowing-down-the-mental-chatter', 19, 'Do a two-minute body scan from head to feet, just noticing, not fixing.'),
  ('slowing-down-the-mental-chatter', 20, 'Take a shower or wash your hands and put all your attention on the water.'),
  ('slowing-down-the-mental-chatter', 21, 'Sit with a cup of something warm and do nothing else until it is finished.'),
  ('slowing-down-the-mental-chatter', 22, 'Repeat one line of a song, a poem, or a prayer slowly, three times, and notice how your mind settles.'),
  ('slowing-down-the-mental-chatter', 23, 'Set an hourly reminder and take three conscious breaths each time it goes off.'),
  ('slowing-down-the-mental-chatter', 24, 'Look at one small object, a leaf, a coin, a pen, for two full minutes as if you had never seen one.'),
  ('slowing-down-the-mental-chatter', 25, 'Notice when you are rehearsing a conversation in your head and gently drop the script.'),
  ('slowing-down-the-mental-chatter', 26, 'Lie on the floor for five minutes and feel the ground holding you up.'),
  ('slowing-down-the-mental-chatter', 27, 'Stretch your arms overhead and breathe out with a long, audible sigh. Do it three times.'),
  ('slowing-down-the-mental-chatter', 28, 'Spend five minutes coloring, doodling, or tracing shapes without trying to make anything.'),
  ('slowing-down-the-mental-chatter', 29, 'Before bed, write down three things your mind is holding for tomorrow so it can put them down tonight.'),
  ('slowing-down-the-mental-chatter', 30, 'Sit quietly for five minutes and, whenever a thought appears, say to yourself "not now" and return to your breath.'),
  ('fostering-gratitude', 1, 'Write down three things that went right today, however small. A warm cup counts.'),
  ('fostering-gratitude', 2, 'Thank someone in person or by text for something specific they did, and say why it mattered.'),
  ('fostering-gratitude', 3, 'Notice one thing your body did for you today and thank it, out loud or on paper.'),
  ('fostering-gratitude', 4, 'Look around the room you are in and find five things you are glad to have.'),
  ('fostering-gratitude', 5, 'Recall one person who helped you this year. Write two sentences about what they did.'),
  ('fostering-gratitude', 6, 'Savor one pleasant moment today for a full thirty seconds instead of moving straight on.'),
  ('fostering-gratitude', 7, 'Write a short thank-you note to someone from your past. You do not have to send it.'),
  ('fostering-gratitude', 8, 'Name one hard thing that taught you something you are glad to know now.'),
  ('fostering-gratitude', 9, 'Take a photo of something ordinary that you appreciate and keep it where you will see it.'),
  ('fostering-gratitude', 10, 'At a meal, pause and think of everyone whose work brought the food to your table.'),
  ('fostering-gratitude', 11, 'Tell a family member or friend one thing you value about them.'),
  ('fostering-gratitude', 12, 'Write down one thing about where you live that you would miss if it were gone.'),
  ('fostering-gratitude', 13, 'Notice one comfort you usually take for granted, warm water, a soft bed, and enjoy it on purpose.'),
  ('fostering-gratitude', 14, 'Think of a skill you have and remember who helped you learn it.'),
  ('fostering-gratitude', 15, 'List three things you are looking forward to, near or far.'),
  ('fostering-gratitude', 16, 'Say thank you to yourself for one thing you did today, even if it was just getting through it.'),
  ('fostering-gratitude', 17, 'Notice one act of kindness you see between other people today and let it land.'),
  ('fostering-gratitude', 18, 'Write down a small win from this week and how it felt.'),
  ('fostering-gratitude', 19, 'Find one thing outside, the sky, a tree, the air, and spend a minute appreciating it.'),
  ('fostering-gratitude', 20, 'Thank a coworker, classmate, or neighbor for something you have never mentioned before.'),
  ('fostering-gratitude', 21, 'Write down one thing that is easier for you now than it used to be.'),
  ('fostering-gratitude', 22, 'Before bed, replay the best minute of your day in detail.'),
  ('fostering-gratitude', 23, 'Pick one object you own that carries a good memory and hold it for a moment.'),
  ('fostering-gratitude', 24, 'Write three sentences starting with "I get to" instead of "I have to."'),
  ('fostering-gratitude', 25, 'Leave a kind review or thank-you message for a small business or a helper you rely on.'),
  ('fostering-gratitude', 26, 'Notice one thing a stranger did today that made your day slightly easier.'),
  ('fostering-gratitude', 27, 'Think of a mistake that turned out fine in the end and feel the relief of it.'),
  ('fostering-gratitude', 28, 'Write down one thing you appreciate about your mind, the way it learns, jokes, or notices.'),
  ('fostering-gratitude', 29, 'Share one thing you are grateful for with someone and ask them for one of theirs.'),
  ('fostering-gratitude', 30, 'Read back through what you have written during this challenge and add one line about how it feels to see it all in one place.'),
  ('redirecting-unhelpful-thoughts', 1, 'Catch one unhelpful thought today and write it down word for word.'),
  ('redirecting-unhelpful-thoughts', 2, 'Take a thought that upset you and ask: what is the evidence for it, and what is the evidence against it?'),
  ('redirecting-unhelpful-thoughts', 3, 'Notice one "always" or "never" in your thinking today and swap it for "sometimes."'),
  ('redirecting-unhelpful-thoughts', 4, 'When a thought says the worst will happen, write down the most likely outcome next to it.'),
  ('redirecting-unhelpful-thoughts', 5, 'Ask yourself what you would say to a friend who had the thought you just had. Say that to yourself.'),
  ('redirecting-unhelpful-thoughts', 6, 'Notice one time today you assumed you knew what someone else was thinking. Write down two other possibilities.'),
  ('redirecting-unhelpful-thoughts', 7, 'Turn one "I should" into "I could" or "I would like to" and see how it changes the pressure.'),
  ('redirecting-unhelpful-thoughts', 8, 'Rate a thought''s power from zero to ten now, then again in an hour. Notice whether it moved.'),
  ('redirecting-unhelpful-thoughts', 9, 'Catch a thought that blames you for everything and list two other factors that played a part.'),
  ('redirecting-unhelpful-thoughts', 10, 'Write an unhelpful thought on a sticky note, then write a fairer version underneath it.'),
  ('redirecting-unhelpful-thoughts', 11, 'When you notice a harsh label like "lazy" or "stupid," replace it with a description of what actually happened.'),
  ('redirecting-unhelpful-thoughts', 12, 'Ask one thought: "Is this a fact or a feeling?" Sort it into the right pile.'),
  ('redirecting-unhelpful-thoughts', 13, 'Take a thought that feels certain and add the words "I am having the thought that" in front of it.'),
  ('redirecting-unhelpful-thoughts', 14, 'Spot one prediction you made today and check later whether it came true.'),
  ('redirecting-unhelpful-thoughts', 15, 'Write down a thought that ignores the good parts, then add the parts it left out.'),
  ('redirecting-unhelpful-thoughts', 16, 'Notice a thought that starts with "what if" and answer it with "then I would."'),
  ('redirecting-unhelpful-thoughts', 17, 'Give a repeating thought a silly voice in your head and hear how it sounds.'),
  ('redirecting-unhelpful-thoughts', 18, 'Pick one thought that is not helping and ask: "Will this matter in a month?"'),
  ('redirecting-unhelpful-thoughts', 19, 'Write down the thought you have most often about yourself and one piece of evidence that does not fit it.'),
  ('redirecting-unhelpful-thoughts', 20, 'When you catch yourself mind-reading, ask the person directly instead, if you can.'),
  ('redirecting-unhelpful-thoughts', 21, 'Take a thought about the future and list one thing that is within your control today.'),
  ('redirecting-unhelpful-thoughts', 22, 'Notice a thought that compares you to someone else and write down what you are comparing against, their highlight reel or their whole life.'),
  ('redirecting-unhelpful-thoughts', 23, 'Write down one thought that you have been treating as an order, then ask whether you agree with it.'),
  ('redirecting-unhelpful-thoughts', 24, 'Spend two minutes listing three explanations for something that went wrong today, not just the one that blames you.'),
  ('redirecting-unhelpful-thoughts', 25, 'Rewrite one all-or-nothing thought on a scale from zero to one hundred.'),
  ('redirecting-unhelpful-thoughts', 26, 'Notice a thought that predicts embarrassment and write down what would actually happen if it came true.'),
  ('redirecting-unhelpful-thoughts', 27, 'Catch a "here we go again" thought and write down one way today is different from last time.'),
  ('redirecting-unhelpful-thoughts', 28, 'Ask a recurring thought: "What would I need to know to let this go?" and go find it, if you can.'),
  ('redirecting-unhelpful-thoughts', 29, 'Write a thought that says you cannot cope, then list three hard things you have already gotten through.'),
  ('redirecting-unhelpful-thoughts', 30, 'Review your notes from this challenge and circle the thinking pattern that showed up most. Name it so you can spot it faster.'),
  ('winding-down-for-better-sleep', 1, 'Pick a bedtime for tonight and set an alarm thirty minutes before it as your cue to start winding down.'),
  ('winding-down-for-better-sleep', 2, 'Put your phone somewhere out of reach from bed tonight and use a plain alarm clock if you need one.'),
  ('winding-down-for-better-sleep', 3, 'Dim the lights in the room you spend the evening in an hour before bed.'),
  ('winding-down-for-better-sleep', 4, 'Write tomorrow''s to-do list before you get into bed so your mind can stop holding it.'),
  ('winding-down-for-better-sleep', 5, 'Do five minutes of gentle stretching before bed, slow and easy.'),
  ('winding-down-for-better-sleep', 6, 'Skip caffeine after noon today and notice how the evening feels.'),
  ('winding-down-for-better-sleep', 7, 'Take a warm shower or bath in the hour before bed.'),
  ('winding-down-for-better-sleep', 8, 'Keep your bedroom a little cooler tonight, open a window or lower the heat.'),
  ('winding-down-for-better-sleep', 9, 'Read a few pages of a paper book or magazine in bed instead of a screen.'),
  ('winding-down-for-better-sleep', 10, 'Do a slow breath count in bed: in for four, out for six, for ten rounds.'),
  ('winding-down-for-better-sleep', 11, 'Get outside in daylight for ten minutes this morning. It helps your body know when night is.'),
  ('winding-down-for-better-sleep', 12, 'Finish eating at least two hours before bed tonight.'),
  ('winding-down-for-better-sleep', 13, 'If you are awake for more than twenty minutes in bed, get up, sit somewhere dim, and return when sleepy.'),
  ('winding-down-for-better-sleep', 14, 'Write down one worry that tends to visit at night and one thing you will do about it tomorrow.'),
  ('winding-down-for-better-sleep', 15, 'Make your bed this morning so it is ready for you tonight.'),
  ('winding-down-for-better-sleep', 16, 'Tidy the surfaces in your bedroom for five minutes so the room feels calmer.'),
  ('winding-down-for-better-sleep', 17, 'Try a body scan in bed: relax your feet, then your legs, and keep moving up until you reach your head.'),
  ('winding-down-for-better-sleep', 18, 'Listen to something quiet and slow, music, rain sounds, a calm audiobook, as you settle.'),
  ('winding-down-for-better-sleep', 19, 'Get up at the same time tomorrow as you did today, even if last night was rough.'),
  ('winding-down-for-better-sleep', 20, 'Keep the last hour of your evening free of work email and news.'),
  ('winding-down-for-better-sleep', 21, 'Do a two-minute gratitude review in bed: three good moments from the day.'),
  ('winding-down-for-better-sleep', 22, 'If your mind is busy, imagine a place you love in detail, the light, the sounds, the temperature.'),
  ('winding-down-for-better-sleep', 23, 'Swap your usual evening drink for a caffeine-free herbal tea or warm milk.'),
  ('winding-down-for-better-sleep', 24, 'Take a short walk after dinner tonight to give your body a gentle signal that the day is ending.'),
  ('winding-down-for-better-sleep', 25, 'Change into sleep clothes at the same time each evening this week, starting tonight.'),
  ('winding-down-for-better-sleep', 26, 'Write a single sentence in a notebook about how you slept last night. Patterns show up over time.'),
  ('winding-down-for-better-sleep', 27, 'Keep naps to twenty minutes and before mid-afternoon today, or skip them if you can.'),
  ('winding-down-for-better-sleep', 28, 'Say a short, kind sentence to yourself as you lie down, something like "The day is done. I can rest now."'),
  ('winding-down-for-better-sleep', 29, 'Spend five minutes in the evening doing something with your hands, knitting, a puzzle, folding laundry.'),
  ('winding-down-for-better-sleep', 30, 'Look back at your sleep notes from this challenge and pick the one change that helped most. Keep it.'),
  ('softening-the-inner-critic', 1, 'Write down the exact words your inner critic used today. Notice its tone.'),
  ('softening-the-inner-critic', 2, 'Put your hand on your heart for thirty seconds and say silently, "This is hard right now."'),
  ('softening-the-inner-critic', 3, 'Think of something you did imperfectly today and say, "That is what learning looks like."'),
  ('softening-the-inner-critic', 4, 'Write one sentence to yourself that you would write to a friend who made the same mistake.'),
  ('softening-the-inner-critic', 5, 'Notice when you call yourself a name today and replace it with your actual first name.'),
  ('softening-the-inner-critic', 6, 'List three things you did today that were good enough. Not perfect. Good enough.'),
  ('softening-the-inner-critic', 7, 'When the critic speaks, ask it: "Whose voice is this really?" Sometimes it is someone from long ago.'),
  ('softening-the-inner-critic', 8, 'Give yourself permission to do one thing at eighty percent today.'),
  ('softening-the-inner-critic', 9, 'Write down one thing you like about how you treat other people.'),
  ('softening-the-inner-critic', 10, 'Say "thank you" when someone compliments you today, with nothing added.'),
  ('softening-the-inner-critic', 11, 'Catch a "should have" and rewrite it as "next time I could."'),
  ('softening-the-inner-critic', 12, 'Take a photo of yourself and find one thing to say kindly about the person in it.'),
  ('softening-the-inner-critic', 13, 'Notice one small kindness you showed yourself today, a break, a meal, a rest, and name it.'),
  ('softening-the-inner-critic', 14, 'Write a short note from your future self, ten years on, to the you of today.'),
  ('softening-the-inner-critic', 15, 'Remember a time you were hard on yourself and it did not help. Give the critic the day off.'),
  ('softening-the-inner-critic', 16, 'Do one thing today purely because you enjoy it, with no productivity attached.'),
  ('softening-the-inner-critic', 17, 'When you make a mistake today, say out loud, "Everyone does this sometimes."'),
  ('softening-the-inner-critic', 18, 'Write down a strength you have that you rarely give yourself credit for.'),
  ('softening-the-inner-critic', 19, 'Notice a moment of self-criticism and place both feet on the floor and breathe out slowly before responding.'),
  ('softening-the-inner-critic', 20, 'Ask someone you trust to tell you one thing they appreciate about you, and let it in.'),
  ('softening-the-inner-critic', 21, 'Forgive yourself for one specific thing tonight, in writing.'),
  ('softening-the-inner-critic', 22, 'Treat your body with one gesture of care today, a stretch, a slower meal, an earlier night.'),
  ('softening-the-inner-critic', 23, 'Write down the critic''s harshest line and then answer it in the voice of someone who loves you.'),
  ('softening-the-inner-critic', 24, 'Say no to one thing today that you would only be doing to prove yourself.'),
  ('softening-the-inner-critic', 25, 'Spend two minutes listing what you have handled in the past year. Read it twice.'),
  ('softening-the-inner-critic', 26, 'Notice the difference today between "I did something wrong" and "I am wrong." Only the first is ever true.'),
  ('softening-the-inner-critic', 27, 'Choose a small reward for finishing something today and actually take it.'),
  ('softening-the-inner-critic', 28, 'Write "I am doing my best with what I have today" and put it where you will see it.'),
  ('softening-the-inner-critic', 29, 'When you compare yourself to someone today, name one thing you are not seeing about their life.'),
  ('softening-the-inner-critic', 30, 'Read back over your notes from this challenge and write one line about how the critic''s voice has changed.'),
  ('moving-a-little-every-day', 1, 'Walk for ten minutes today, anywhere, at any pace.'),
  ('moving-a-little-every-day', 2, 'Stand up and stretch your arms overhead for thirty seconds every hour you are sitting.'),
  ('moving-a-little-every-day', 3, 'Do ten slow shoulder rolls backward, then ten forward.'),
  ('moving-a-little-every-day', 4, 'Take the stairs once today when you normally would not.'),
  ('moving-a-little-every-day', 5, 'Put on one song you love and move to it, however you like, until it ends.'),
  ('moving-a-little-every-day', 6, 'Do five slow squats, holding onto a counter if it helps.'),
  ('moving-a-little-every-day', 7, 'Stretch your calves against a wall for thirty seconds each side.'),
  ('moving-a-little-every-day', 8, 'Walk to the end of your street and back, noticing the air.'),
  ('moving-a-little-every-day', 9, 'Do a two-minute march in place while the kettle boils or a page loads.'),
  ('moving-a-little-every-day', 10, 'Lie on your back and hug your knees to your chest for one minute.'),
  ('moving-a-little-every-day', 11, 'Take a walk with someone, in person or on the phone, for fifteen minutes.'),
  ('moving-a-little-every-day', 12, 'Do ten wall push-ups, standing at arm''s length from a wall.'),
  ('moving-a-little-every-day', 13, 'Spend five minutes stretching your neck: ear to shoulder, chin to chest, slow and gentle.'),
  ('moving-a-little-every-day', 14, 'Balance on one foot for thirty seconds, then the other. Hold the wall if you need to.'),
  ('moving-a-little-every-day', 15, 'Walk somewhere you would normally drive, if it is under a mile.'),
  ('moving-a-little-every-day', 16, 'Do a slow "cat and cow" stretch on hands and knees for one minute.'),
  ('moving-a-little-every-day', 17, 'Carry your groceries or a bag a little farther than usual today.'),
  ('moving-a-little-every-day', 18, 'Dance while you cook or clean tonight for at least one song.'),
  ('moving-a-little-every-day', 19, 'Rise onto your toes and lower back down, twenty times, while brushing your teeth.'),
  ('moving-a-little-every-day', 20, 'Take a fifteen-minute walk after a meal today.'),
  ('moving-a-little-every-day', 21, 'Do five minutes of any gentle movement first thing after getting out of bed.'),
  ('moving-a-little-every-day', 22, 'Stretch your hips: sit with one ankle on the opposite knee and lean forward gently, thirty seconds each side.'),
  ('moving-a-little-every-day', 23, 'Spend ten minutes on yard work, a garden, or a plant, bending, reaching, tending.'),
  ('moving-a-little-every-day', 24, 'Do twenty seconds of jumping jacks or fast marching, rest, and repeat three times.'),
  ('moving-a-little-every-day', 25, 'Take a walk with no destination for twenty minutes and turn wherever you feel like turning.'),
  ('moving-a-little-every-day', 26, 'Sit on the floor to do something you would usually do on the couch, then get up without using your hands, if you can.'),
  ('moving-a-little-every-day', 27, 'Do a full-body stretch in bed before you get up: reach your toes down and your fingers up.'),
  ('moving-a-little-every-day', 28, 'Try a five-minute beginner video of yoga, tai chi, or stretching.'),
  ('moving-a-little-every-day', 29, 'Walk a little faster than usual for five minutes and notice your breathing change.'),
  ('moving-a-little-every-day', 30, 'Look back at which kinds of movement you enjoyed most in this challenge and plan one for tomorrow.'),
  ('reaching-out-to-people', 1, 'Send a two-line message to someone you have not spoken to in a month, just to say hello.'),
  ('reaching-out-to-people', 2, 'Ask one person today a question about their life and listen to the whole answer.'),
  ('reaching-out-to-people', 3, 'Say good morning to a neighbor, a barista, or a coworker and use their name if you know it.'),
  ('reaching-out-to-people', 4, 'Reply to a message you have been putting off, even with just a few words.'),
  ('reaching-out-to-people', 5, 'Call a family member for five minutes with no agenda.'),
  ('reaching-out-to-people', 6, 'Tell someone about one small thing that happened to you today.'),
  ('reaching-out-to-people', 7, 'Invite someone for a walk, a coffee, or a video call sometime this week.'),
  ('reaching-out-to-people', 8, 'Comment kindly on something a friend shared, instead of just scrolling past.'),
  ('reaching-out-to-people', 9, 'Thank someone for a way they have been there for you, in a text or in person.'),
  ('reaching-out-to-people', 10, 'Sit somewhere public today, a café, a park, a library, for twenty minutes and notice the people around you.'),
  ('reaching-out-to-people', 11, 'Ask a coworker or classmate how their weekend was and share one thing about yours.'),
  ('reaching-out-to-people', 12, 'Send a photo to a friend that reminded you of them.'),
  ('reaching-out-to-people', 13, 'Say yes to the next small invitation you get, or make one yourself.'),
  ('reaching-out-to-people', 14, 'Ask someone for a small favor or a recommendation. People like being asked.'),
  ('reaching-out-to-people', 15, 'Write down the names of five people you could call if you needed to. Keep the list.'),
  ('reaching-out-to-people', 16, 'Join one group conversation today, online or in person, with a single sentence.'),
  ('reaching-out-to-people', 17, 'Tell a friend one thing you appreciate about them, out of the blue.'),
  ('reaching-out-to-people', 18, 'Look up one local club, class, or volunteer group you might try, and save the details.'),
  ('reaching-out-to-people', 19, 'Share something you are struggling with, in one honest sentence, with someone you trust.'),
  ('reaching-out-to-people', 20, 'Plan a regular call, weekly or monthly, with one person and put the first one on the calendar.'),
  ('reaching-out-to-people', 21, 'Ask an older relative or friend to tell you a story from their life.'),
  ('reaching-out-to-people', 22, 'Sit with someone at lunch or on a break instead of alone.'),
  ('reaching-out-to-people', 23, 'Send a voice note instead of a text to someone today so they can hear your voice.'),
  ('reaching-out-to-people', 24, 'Offer to help someone with something small: a ride, a task, a listening ear.'),
  ('reaching-out-to-people', 25, 'Reconnect with a friend from an old chapter of your life with a message that says you were thinking of them.'),
  ('reaching-out-to-people', 26, 'Compliment a stranger on something specific, their dog, their jacket, their patience.'),
  ('reaching-out-to-people', 27, 'Ask a friend what they are looking forward to this month.'),
  ('reaching-out-to-people', 28, 'Attend something with other people this week, a class, a service, a game, a meetup, and stay ten minutes longer than you want to.'),
  ('reaching-out-to-people', 29, 'Tell someone you love them, in whatever words feel natural.'),
  ('reaching-out-to-people', 30, 'Look at the list of people you contacted during this challenge and pick one to keep in closer touch with.'),
  ('loosening-the-grip-of-worry', 1, 'Set a fifteen-minute "worry window" this evening. When worries appear earlier, write them down and save them for then.'),
  ('loosening-the-grip-of-worry', 2, 'Write down one worry and sort it: something you can act on, or something you cannot. Act on the first kind, breathe through the second.'),
  ('loosening-the-grip-of-worry', 3, 'Notice one "what if" today and answer it with "even if that happened, I would..."'),
  ('loosening-the-grip-of-worry', 4, 'Take a worry and write down the most likely outcome, not the worst one.'),
  ('loosening-the-grip-of-worry', 5, 'Ask yourself: "Is this worry solving anything right now?" If not, put it down for an hour.'),
  ('loosening-the-grip-of-worry', 6, 'Do something with your hands for ten minutes, cooking, gardening, drawing, and let your mind follow.'),
  ('loosening-the-grip-of-worry', 7, 'Write down a worry from last month. Did it come true? What actually happened?'),
  ('loosening-the-grip-of-worry', 8, 'When you catch yourself worrying, name what you can see, hear, and feel right now.'),
  ('loosening-the-grip-of-worry', 9, 'Pick one small step on the thing you are worried about and do it today.'),
  ('loosening-the-grip-of-worry', 10, 'Limit checking the news to two set times today.'),
  ('loosening-the-grip-of-worry', 11, 'Tell someone one worry out loud. Notice how it changes when it is said.'),
  ('loosening-the-grip-of-worry', 12, 'Breathe out for longer than you breathe in, ten times, when a worry spikes.'),
  ('loosening-the-grip-of-worry', 13, 'Write a worry on paper, fold it, and put it in a drawer until tomorrow.'),
  ('loosening-the-grip-of-worry', 14, 'Notice a worry about someone else and ask whether there is something kind you could do for them instead.'),
  ('loosening-the-grip-of-worry', 15, 'Spend ten minutes on something that fully absorbs you, a puzzle, a game, a craft.'),
  ('loosening-the-grip-of-worry', 16, 'Ask: "What would I tell a friend who was worrying about this?" and take your own advice.'),
  ('loosening-the-grip-of-worry', 17, 'Rate a worry from zero to ten in the morning and again at night. Notice the difference.'),
  ('loosening-the-grip-of-worry', 18, 'Replace one "I can''t stop thinking about it" with "I am choosing to think about something else for now."'),
  ('loosening-the-grip-of-worry', 19, 'Make a short list of what is going fine today. Worry tends to leave those off.'),
  ('loosening-the-grip-of-worry', 20, 'Delay checking for a reply or result by thirty minutes today and see what happens in the gap.'),
  ('loosening-the-grip-of-worry', 21, 'Write down the thing you are worried about and next to it the date you will actually know the answer.'),
  ('loosening-the-grip-of-worry', 22, 'Do a quick body check: unclench your jaw, drop your shoulders, loosen your hands.'),
  ('loosening-the-grip-of-worry', 23, 'Write down what you would do if the worst case happened, in three steps. Having a plan shrinks it.'),
  ('loosening-the-grip-of-worry', 24, 'Spend fifteen minutes outside and leave the worry indoors.'),
  ('loosening-the-grip-of-worry', 25, 'Notice a worry that is really about wanting certainty. Say, "I can handle not knowing for now."'),
  ('loosening-the-grip-of-worry', 26, 'Choose one worry to stop researching online today.'),
  ('loosening-the-grip-of-worry', 27, 'Say to a worry: "Thanks for trying to protect me. I have got this."'),
  ('loosening-the-grip-of-worry', 28, 'Make a small decision you have been putting off, in under two minutes.'),
  ('loosening-the-grip-of-worry', 29, 'Look at your worry notes from this challenge and count how many worries came true. Let the number speak.'),
  ('loosening-the-grip-of-worry', 30, 'Write down one thing you want to do this week that worry has been talking you out of, and do the first step.'),
  ('holding-your-boundaries', 1, 'Write down one thing you agreed to recently that you did not want to do.'),
  ('holding-your-boundaries', 2, 'Say "Let me check and get back to you" to one request today instead of answering right away.'),
  ('holding-your-boundaries', 3, 'Notice one moment today when your body tightened. That is often a boundary being crossed.'),
  ('holding-your-boundaries', 4, 'Practice saying "No, I can''t do that" out loud, alone, five times.'),
  ('holding-your-boundaries', 5, 'Turn down one small thing today, an extra task, a call, a favor, with one sentence and no apology.'),
  ('holding-your-boundaries', 6, 'Decide on a time to stop working today and stop at that time.'),
  ('holding-your-boundaries', 7, 'Write down three things you need more of: time, quiet, help, rest, and one way to get one of them.'),
  ('holding-your-boundaries', 8, 'Tell someone what you would prefer, instead of going along with their plan.'),
  ('holding-your-boundaries', 9, 'Leave one message unanswered until tomorrow. Nothing will break.'),
  ('holding-your-boundaries', 10, 'Say "I am not available then, but I could do Thursday" to one request.'),
  ('holding-your-boundaries', 11, 'Notice one time you over-explained yourself today and practice a shorter version.'),
  ('holding-your-boundaries', 12, 'Set your phone to do not disturb for one hour and tell the people who might need to know.'),
  ('holding-your-boundaries', 13, 'Write down one boundary you wish you had held recently and how you would say it next time.'),
  ('holding-your-boundaries', 14, 'Ask for what you need today in one clear sentence: "I need some quiet for an hour."'),
  ('holding-your-boundaries', 15, 'Let someone else handle something you would normally take over.'),
  ('holding-your-boundaries', 16, 'Say "That does not work for me" once today and leave it there.'),
  ('holding-your-boundaries', 17, 'Take your full break at work or school today, away from your desk if you can.'),
  ('holding-your-boundaries', 18, 'Notice a guilty feeling after saying no and remind yourself: guilt is not proof you did something wrong.'),
  ('holding-your-boundaries', 19, 'Decide on one topic you will not discuss with a particular person, and change the subject if it comes up.'),
  ('holding-your-boundaries', 20, 'Write down the difference between what someone wants from you and what you owe them.'),
  ('holding-your-boundaries', 21, 'Give yourself an hour today that no one else gets to schedule.'),
  ('holding-your-boundaries', 22, 'Practice a gentle exit line: "I need to go now, let''s talk soon."'),
  ('holding-your-boundaries', 23, 'Notice one person who respects your boundaries easily and thank them for it.'),
  ('holding-your-boundaries', 24, 'Say "I will think about it" to something you are tempted to agree to on the spot.'),
  ('holding-your-boundaries', 25, 'Stop doing one thing today that you only do to avoid someone''s disappointment.'),
  ('holding-your-boundaries', 26, 'Tell someone how you would like to be spoken to, calmly, in one sentence.'),
  ('holding-your-boundaries', 27, 'Set a limit on one thing that drains you, screen time, a group chat, and hold it today.'),
  ('holding-your-boundaries', 28, 'Write down what you are afraid will happen if you hold a boundary. Then write what usually actually happens.'),
  ('holding-your-boundaries', 29, 'Hold one boundary today and afterward write down how your body felt.'),
  ('holding-your-boundaries', 30, 'Reread your notes from this challenge and pick the one boundary that matters most. Write it as a sentence you can say.'),
  ('building-a-calmer-morning', 1, 'Lay out tomorrow''s clothes tonight.'),
  ('building-a-calmer-morning', 2, 'Keep your phone off for the first ten minutes after you wake up.'),
  ('building-a-calmer-morning', 3, 'Drink a full glass of water before anything else this morning.'),
  ('building-a-calmer-morning', 4, 'Open a window or step outside for two minutes of fresh air when you get up.'),
  ('building-a-calmer-morning', 5, 'Set your alarm ten minutes earlier and use the time for nothing in particular.'),
  ('building-a-calmer-morning', 6, 'Eat something for breakfast today, sitting down, without a screen.'),
  ('building-a-calmer-morning', 7, 'Make your bed as the first small thing you finish today.'),
  ('building-a-calmer-morning', 8, 'Write down the three most important things for today before you check any messages.'),
  ('building-a-calmer-morning', 9, 'Stretch for three minutes before you get dressed.'),
  ('building-a-calmer-morning', 10, 'Prepare your bag, keys, and anything you need by the door tonight.'),
  ('building-a-calmer-morning', 11, 'Pick one song to play while you get ready and let it set the pace.'),
  ('building-a-calmer-morning', 12, 'Say one kind sentence to yourself in the mirror, even if it feels silly.'),
  ('building-a-calmer-morning', 13, 'Do the hardest small task of the morning first, and notice how the rest feels.'),
  ('building-a-calmer-morning', 14, 'Take five slow breaths before you leave the house or start work.'),
  ('building-a-calmer-morning', 15, 'Prepare breakfast, or part of it, the night before.'),
  ('building-a-calmer-morning', 16, 'Look outside and notice the weather and the light before you look at any news.'),
  ('building-a-calmer-morning', 17, 'Give yourself an extra five minutes for the commute or the walk to your desk, and do not rush it.'),
  ('building-a-calmer-morning', 18, 'Write one line in a notebook about how you want today to feel.'),
  ('building-a-calmer-morning', 19, 'Sit with your morning drink for five minutes before doing anything else.'),
  ('building-a-calmer-morning', 20, 'Turn off notifications overnight so the morning is quiet until you choose otherwise.'),
  ('building-a-calmer-morning', 21, 'Decide tonight what tomorrow''s first task will be so you do not have to decide in the morning.'),
  ('building-a-calmer-morning', 22, 'Move gently for ten minutes before work, a walk, a stretch, a few stairs.'),
  ('building-a-calmer-morning', 23, 'Notice one thing you like about your home as you move through it this morning.'),
  ('building-a-calmer-morning', 24, 'Set a clear "leaving" or "starting" time and count backward to plan the morning.'),
  ('building-a-calmer-morning', 25, 'Keep the first conversation of the day gentle, with yourself or with anyone you live with.'),
  ('building-a-calmer-morning', 26, 'Skip one thing from your morning routine that you do out of habit but do not need.'),
  ('building-a-calmer-morning', 27, 'Put a note by your bed with one word for the morning: "slow," "steady," "easy."'),
  ('building-a-calmer-morning', 28, 'Do a two-minute tidy of the kitchen tonight so the morning starts clear.'),
  ('building-a-calmer-morning', 29, 'Wake up at the same time as yesterday, even if it is the weekend.'),
  ('building-a-calmer-morning', 30, 'Look back at this challenge and write down the two morning changes that helped most. Keep those.'),
  ('making-room-for-rest', 1, 'Take a ten-minute break today with nothing to do, no phone, no task.'),
  ('making-room-for-rest', 2, 'Write down what "rest" actually means to you. It might not be sleep.'),
  ('making-room-for-rest', 3, 'Sit down for your lunch today and eat it away from your work.'),
  ('making-room-for-rest', 4, 'Say no to one optional thing this week and leave that time empty.'),
  ('making-room-for-rest', 5, 'Lie down for fifteen minutes this afternoon or evening, eyes closed, no goal.'),
  ('making-room-for-rest', 6, 'Go to bed thirty minutes earlier tonight.'),
  ('making-room-for-rest', 7, 'Do one thing slowly today that you usually rush through.'),
  ('making-room-for-rest', 8, 'Notice what you do when you are tired: push harder, scroll, snack? Write it down without judging it.'),
  ('making-room-for-rest', 9, 'Let one thing stay undone today and see that the world goes on.'),
  ('making-room-for-rest', 10, 'Spend twenty minutes on a hobby or interest that has nothing to do with work.'),
  ('making-room-for-rest', 11, 'Turn off work notifications at a set time this evening.'),
  ('making-room-for-rest', 12, 'Ask someone to take one thing off your plate today.'),
  ('making-room-for-rest', 13, 'Take a short walk with no phone and nowhere to be.'),
  ('making-room-for-rest', 14, 'Sit outside or by a window for ten minutes and let your eyes rest on something far away.'),
  ('making-room-for-rest', 15, 'Cancel or shorten one meeting, plan, or errand that is not essential.'),
  ('making-room-for-rest', 16, 'Take a bath or a long shower with no time limit.'),
  ('making-room-for-rest', 17, 'Spend five minutes doing nothing but breathing before you switch from work to home.'),
  ('making-room-for-rest', 18, 'Write down the last time you felt truly rested and what was different about that day.'),
  ('making-room-for-rest', 19, 'Let yourself be bored for ten minutes without reaching for anything.'),
  ('making-room-for-rest', 20, 'Do a restful activity with someone else: a slow meal, a quiet walk, a movie.'),
  ('making-room-for-rest', 21, 'Say "I am tired" out loud to someone today, and let that be a full sentence.'),
  ('making-room-for-rest', 22, 'Block out one hour on your calendar this week labeled "rest" and protect it.'),
  ('making-room-for-rest', 23, 'Put your feet up, literally, for ten minutes.'),
  ('making-room-for-rest', 24, 'Skip the most draining item on today''s list if it can wait until tomorrow.'),
  ('making-room-for-rest', 25, 'Take your breaks at work today, all of them, even the short ones.'),
  ('making-room-for-rest', 26, 'Listen to an album or a playlist from start to finish while doing nothing else.'),
  ('making-room-for-rest', 27, 'Give yourself a slower start tomorrow morning by preparing tonight.'),
  ('making-room-for-rest', 28, 'Notice one sign your body gives you when it needs rest, and answer it today instead of overriding it.'),
  ('making-room-for-rest', 29, 'Spend an evening without any screens and notice how you feel by bedtime.'),
  ('making-room-for-rest', 30, 'Look back at this challenge and write down the kind of rest that restored you most. Plan it for next week.'),
  ('living-by-your-values', 1, 'Write down five words that describe the person you want to be.'),
  ('living-by-your-values', 2, 'Pick one of your values and do one small thing today that expresses it.'),
  ('living-by-your-values', 3, 'Think of a person you admire and write down which of their qualities you want more of.'),
  ('living-by-your-values', 4, 'Notice one moment today when you acted in line with what you care about. Name the value.'),
  ('living-by-your-values', 5, 'Write down one thing you spend time on that does not match your values, and one small change.'),
  ('living-by-your-values', 6, 'Ask yourself: "If today were a chapter, what would I want it to be about?" Then live one page of it.'),
  ('living-by-your-values', 7, 'Do something today for a cause, a person, or a place you care about.'),
  ('living-by-your-values', 8, 'Choose one value and put it somewhere you will see it all day.'),
  ('living-by-your-values', 9, 'Write down what you would want a friend to say about you at your eightieth birthday.'),
  ('living-by-your-values', 10, 'Make one decision today based on what matters, not on what is easiest.'),
  ('living-by-your-values', 11, 'Spend fifteen minutes on something that feels meaningful rather than urgent.'),
  ('living-by-your-values', 12, 'List three moments in your life when you felt most yourself. What did they have in common?'),
  ('living-by-your-values', 13, 'Say what you think today in one conversation where you would normally keep quiet.'),
  ('living-by-your-values', 14, 'Notice one value you have been neglecting and give it ten minutes today.'),
  ('living-by-your-values', 15, 'Write a sentence that starts with "I want to be the kind of person who..."'),
  ('living-by-your-values', 16, 'Pick one relationship and do one thing that reflects how much it matters to you.'),
  ('living-by-your-values', 17, 'Spend money, even a little, on something that matches your values instead of a habit.'),
  ('living-by-your-values', 18, 'Notice when you feel proud today and write down what value you were honoring.'),
  ('living-by-your-values', 19, 'Do one thing today that your younger self would be glad to see you doing.'),
  ('living-by-your-values', 20, 'Write down one value you hold that you rarely talk about, and tell someone about it.'),
  ('living-by-your-values', 21, 'Turn one value into a tiny daily action: "kindness" becomes "one warm message a day."'),
  ('living-by-your-values', 22, 'Choose how you want to show up in one meeting or gathering today, and do it on purpose.'),
  ('living-by-your-values', 23, 'Notice one thing you do out of habit, and ask whether it reflects who you want to be.'),
  ('living-by-your-values', 24, 'Write down one value you got from your family and whether you want to keep it.'),
  ('living-by-your-values', 25, 'Do a small act of courage today in the direction of something you care about.'),
  ('living-by-your-values', 26, 'Spend ten minutes learning about something you value, a skill, a place, a cause.'),
  ('living-by-your-values', 27, 'Write down what "a good day" looks like for you, in three lines.'),
  ('living-by-your-values', 28, 'Let one value guide how you treat yourself today, not just others.'),
  ('living-by-your-values', 29, 'Notice a moment today when you were pulled away from your values, and gently return.'),
  ('living-by-your-values', 30, 'Look back over this challenge and write down the two or three values that came up most. Those are yours.'),
  ('small-acts-of-kindness', 1, 'Hold the door and make eye contact with a smile for someone today.'),
  ('small-acts-of-kindness', 2, 'Send a message to someone telling them one thing they do well.'),
  ('small-acts-of-kindness', 3, 'Let someone go ahead of you in a line or in traffic.'),
  ('small-acts-of-kindness', 4, 'Leave a generous tip or a kind word for someone who serves you today.'),
  ('small-acts-of-kindness', 5, 'Pick up one piece of litter you would normally walk past.'),
  ('small-acts-of-kindness', 6, 'Ask someone who looks busy or stressed if there is anything you can do to help.'),
  ('small-acts-of-kindness', 7, 'Write a thank-you note to a teacher, mentor, or coach from your past.'),
  ('small-acts-of-kindness', 8, 'Bring a coworker, classmate, or neighbor a coffee, a snack, or a small treat.'),
  ('small-acts-of-kindness', 9, 'Give a real compliment to a stranger.'),
  ('small-acts-of-kindness', 10, 'Check in on someone who has been quiet lately.'),
  ('small-acts-of-kindness', 11, 'Share something useful, a tip, an article, a contact, with someone who needs it.'),
  ('small-acts-of-kindness', 12, 'Do a chore that someone in your home usually does, without mentioning it.'),
  ('small-acts-of-kindness', 13, 'Leave a positive review for a small business you like.'),
  ('small-acts-of-kindness', 14, 'Call or visit someone who might be lonely.'),
  ('small-acts-of-kindness', 15, 'Offer your seat, your place, or your turn to someone today.'),
  ('small-acts-of-kindness', 16, 'Make a small donation of money, food, clothes, or time to something local.'),
  ('small-acts-of-kindness', 17, 'Tell a parent, teacher, or caregiver you see that they are doing a good job.'),
  ('small-acts-of-kindness', 18, 'Forgive someone for a small thing today and let it go completely.'),
  ('small-acts-of-kindness', 19, 'Cook or share a meal with someone.'),
  ('small-acts-of-kindness', 20, 'Write down three kind things you could do for yourself and do one.'),
  ('small-acts-of-kindness', 21, 'Say thank you to someone whose work is usually invisible: a cleaner, a driver, a security guard.'),
  ('small-acts-of-kindness', 22, 'Listen to someone for five minutes without giving advice or checking your phone.'),
  ('small-acts-of-kindness', 23, 'Return a cart, hold an elevator, or carry something for someone.'),
  ('small-acts-of-kindness', 24, 'Send a short message to someone celebrating something, or someone grieving.'),
  ('small-acts-of-kindness', 25, 'Give away one thing you do not need to someone who could use it.'),
  ('small-acts-of-kindness', 26, 'Leave a kind note somewhere someone will find it.'),
  ('small-acts-of-kindness', 27, 'Be patient with someone who is slow, new, or struggling today, and say something reassuring.'),
  ('small-acts-of-kindness', 28, 'Tell someone a specific way they made a difference to you.'),
  ('small-acts-of-kindness', 29, 'Do a favor for someone who could never repay it.'),
  ('small-acts-of-kindness', 30, 'Look back at this challenge and notice which acts of kindness felt best. Plan to keep doing those.'),
  ('making-peace-with-time-alone', 1, 'Spend fifteen minutes alone doing something you enjoy, on purpose, and notice how it feels.'),
  ('making-peace-with-time-alone', 2, 'Write down the difference between being alone and being lonely, in your own words.'),
  ('making-peace-with-time-alone', 3, 'Take yourself somewhere nice today, a café, a park, a bookstore, and stay for a while.'),
  ('making-peace-with-time-alone', 4, 'Cook one meal for yourself as carefully as you would for a guest.'),
  ('making-peace-with-time-alone', 5, 'Write down three things you like about your own company.'),
  ('making-peace-with-time-alone', 6, 'Talk to yourself kindly out loud for a minute, the way you would to a friend who was visiting.'),
  ('making-peace-with-time-alone', 7, 'Do one thing today that you have been waiting to do "with someone." Do it alone and enjoy it.'),
  ('making-peace-with-time-alone', 8, 'Notice a lonely moment today and put a hand on your arm or chest. You are here with you.'),
  ('making-peace-with-time-alone', 9, 'Spend an evening with a book, a film, or music that you chose just for you.'),
  ('making-peace-with-time-alone', 10, 'Write down one thing you would tell a friend who was feeling lonely tonight. Then tell yourself.'),
  ('making-peace-with-time-alone', 11, 'Set up your space for one small comfort tonight: a candle, a blanket, a favorite mug.'),
  ('making-peace-with-time-alone', 12, 'Reach out to one person today, then spend the rest of the evening happily on your own.'),
  ('making-peace-with-time-alone', 13, 'Take a walk alone and notice everything that is pleasant about not having to talk.'),
  ('making-peace-with-time-alone', 14, 'Learn something new for twenty minutes, a recipe, a song, a few words of a language.'),
  ('making-peace-with-time-alone', 15, 'Write a letter to yourself about what you are hoping for this year.'),
  ('making-peace-with-time-alone', 16, 'Join a group activity this week where you can be around people without needing to perform.'),
  ('making-peace-with-time-alone', 17, 'Sit in a public place with a drink and simply watch the world for twenty minutes.'),
  ('making-peace-with-time-alone', 18, 'Do something creative alone: draw, write, sing, build, plant.'),
  ('making-peace-with-time-alone', 19, 'Notice when loneliness turns into scrolling and swap ten minutes of it for a walk or a call.'),
  ('making-peace-with-time-alone', 20, 'Say hello to three people today, even briefly.'),
  ('making-peace-with-time-alone', 21, 'Take yourself on a small outing this weekend: a museum, a trail, a market.'),
  ('making-peace-with-time-alone', 22, 'Write down the people who care about you, even if they are far away. Keep the list where you can see it.'),
  ('making-peace-with-time-alone', 23, 'Try a solo meal out and bring a book or a notebook.'),
  ('making-peace-with-time-alone', 24, 'Make plans with a friend for sometime this month so there is something on the calendar.'),
  ('making-peace-with-time-alone', 25, 'Spend ten minutes tidying one space so being home alone feels like a choice, not a lack.'),
  ('making-peace-with-time-alone', 26, 'Write down what you would do with a whole free day if no one else''s needs were involved. Do one part of it.'),
  ('making-peace-with-time-alone', 27, 'Do something kind for a stranger or a neighbor today; it connects you without needing anything back.'),
  ('making-peace-with-time-alone', 28, 'Notice a quiet moment today that feels peaceful rather than empty, and stay in it a minute longer.'),
  ('making-peace-with-time-alone', 29, 'Ask yourself what you actually want from other people right now: company, comfort, fun? Then take one step to get some.'),
  ('making-peace-with-time-alone', 30, 'Look back over this challenge and write down what you learned about your own company.'),
  ('loosening-the-phone-habit', 1, 'Count how many times you pick up your phone today, without changing anything yet.'),
  ('loosening-the-phone-habit', 2, 'Move your most-used app off your home screen.'),
  ('loosening-the-phone-habit', 3, 'Turn off every notification that is not from a person.'),
  ('loosening-the-phone-habit', 4, 'Charge your phone outside the bedroom tonight.'),
  ('loosening-the-phone-habit', 5, 'Leave your phone in another room during one meal today.'),
  ('loosening-the-phone-habit', 6, 'Delete one app that never leaves you feeling better.'),
  ('loosening-the-phone-habit', 7, 'Turn your screen to grayscale for the day and notice what changes.'),
  ('loosening-the-phone-habit', 8, 'Wait ten minutes after waking before you touch your phone.'),
  ('loosening-the-phone-habit', 9, 'Set a thirty-minute limit on one app and stop when it goes off.'),
  ('loosening-the-phone-habit', 10, 'Go for a walk without your phone, or with it on airplane mode.'),
  ('loosening-the-phone-habit', 11, 'Notice one urge to check your phone and let it pass without acting on it. Count to twenty.'),
  ('loosening-the-phone-habit', 12, 'Sit through one wait, a line, a bus, a lobby, with your phone in your pocket.'),
  ('loosening-the-phone-habit', 13, 'Put your phone face down and out of reach while you work on one task.'),
  ('loosening-the-phone-habit', 14, 'Unfollow or mute five accounts that make you feel worse.'),
  ('loosening-the-phone-habit', 15, 'Do one thing you usually do on your phone on paper today: a list, a note, a calculation.'),
  ('loosening-the-phone-habit', 16, 'Choose one hour this evening to leave your phone on silent in a drawer.'),
  ('loosening-the-phone-habit', 17, 'Ask yourself "What am I looking for?" before you open a social app today.'),
  ('loosening-the-phone-habit', 18, 'Read something printed for fifteen minutes instead of scrolling.'),
  ('loosening-the-phone-habit', 19, 'Turn off autoplay on one video app.'),
  ('loosening-the-phone-habit', 20, 'Have one conversation today with your phone completely out of sight.'),
  ('loosening-the-phone-habit', 21, 'Set a "last check" time tonight and keep to it.'),
  ('loosening-the-phone-habit', 22, 'Replace one scroll session with a two-minute stretch or a glass of water.'),
  ('loosening-the-phone-habit', 23, 'Leave your phone behind on bathroom trips for a day.'),
  ('loosening-the-phone-habit', 24, 'Log out of one app so opening it takes effort.'),
  ('loosening-the-phone-habit', 25, 'Notice how you feel after twenty minutes of scrolling, and write one word for it.'),
  ('loosening-the-phone-habit', 26, 'Spend the first ten minutes of a break without a screen.'),
  ('loosening-the-phone-habit', 27, 'Set a single time to check the news today, and stick to it.'),
  ('loosening-the-phone-habit', 28, 'Put your phone in a bag or drawer during a show, a game, or a meal with others.'),
  ('loosening-the-phone-habit', 29, 'Try a full morning, until noon, with no social apps.'),
  ('loosening-the-phone-habit', 30, 'Look back at your phone habits during this challenge and choose the two changes you want to keep.'),
  ('tidying-one-corner-at-a-time', 1, 'Clear one surface completely, a table, a counter, a nightstand, and wipe it down.'),
  ('tidying-one-corner-at-a-time', 2, 'Empty one drawer, keep what you use, and put the rest in a bag.'),
  ('tidying-one-corner-at-a-time', 3, 'Make your bed and open the curtains.'),
  ('tidying-one-corner-at-a-time', 4, 'Take out the trash and recycling from every room.'),
  ('tidying-one-corner-at-a-time', 5, 'Wash whatever is in the sink and leave it empty tonight.'),
  ('tidying-one-corner-at-a-time', 6, 'Pick up everything on the floor of one room and put it where it belongs.'),
  ('tidying-one-corner-at-a-time', 7, 'Sort one pile of mail or paper. Recycle, file, or act.'),
  ('tidying-one-corner-at-a-time', 8, 'Put five things back in their proper place.'),
  ('tidying-one-corner-at-a-time', 9, 'Clean one mirror or window.'),
  ('tidying-one-corner-at-a-time', 10, 'Clear the top of your fridge or one shelf inside it.'),
  ('tidying-one-corner-at-a-time', 11, 'Gather everything that does not belong in the room you are in and return it.'),
  ('tidying-one-corner-at-a-time', 12, 'Fold and put away one load of laundry.'),
  ('tidying-one-corner-at-a-time', 13, 'Wipe down the bathroom sink and mirror.'),
  ('tidying-one-corner-at-a-time', 14, 'Choose five items of clothing you have not worn in a year and set them aside to donate.'),
  ('tidying-one-corner-at-a-time', 15, 'Tidy the area by your front door: shoes, coats, keys.'),
  ('tidying-one-corner-at-a-time', 16, 'Clear your desk or the spot where you work so only what you need is on it.'),
  ('tidying-one-corner-at-a-time', 17, 'Throw away expired food from one shelf or drawer.'),
  ('tidying-one-corner-at-a-time', 18, 'Sweep or vacuum one room.'),
  ('tidying-one-corner-at-a-time', 19, 'Organize one small container: a cutlery tray, a makeup bag, a toolbox.'),
  ('tidying-one-corner-at-a-time', 20, 'Put away the dishes and clear the drying rack.'),
  ('tidying-one-corner-at-a-time', 21, 'Clear off one chair that has become a clothes pile.'),
  ('tidying-one-corner-at-a-time', 22, 'Empty your bag or backpack and put everything back in its place.'),
  ('tidying-one-corner-at-a-time', 23, 'Wipe down the light switches and door handles you use most.'),
  ('tidying-one-corner-at-a-time', 24, 'Clear the nightstand so only what helps you sleep is on it.'),
  ('tidying-one-corner-at-a-time', 25, 'Take five things you no longer need and put them in the car or by the door to donate.'),
  ('tidying-one-corner-at-a-time', 26, 'Water your plants, or throw out the ones that have not made it.'),
  ('tidying-one-corner-at-a-time', 27, 'Tidy one shelf of books, games, or papers.'),
  ('tidying-one-corner-at-a-time', 28, 'Clean out the car, or one bag, or one pocket of a coat.'),
  ('tidying-one-corner-at-a-time', 29, 'Reset the kitchen before bed: surfaces clear, sink empty, floor swept.'),
  ('tidying-one-corner-at-a-time', 30, 'Walk through your home and notice every corner you have cleared during this challenge. Choose one to keep clear every day.'),
  ('meeting-anger-early', 1, 'Write down the last three things that made you angry. Look for what they have in common.'),
  ('meeting-anger-early', 2, 'Notice where anger shows up in your body first today: jaw, chest, hands, stomach.'),
  ('meeting-anger-early', 3, 'When you feel a flash of anger, breathe out slowly for a count of six before you say anything.'),
  ('meeting-anger-early', 4, 'Practice the phrase "I need a minute" and use it once today if you need it.'),
  ('meeting-anger-early', 5, 'Write down what you were really feeling underneath your last angry moment. Hurt? Scared? Tired?'),
  ('meeting-anger-early', 6, 'Unclench your hands and jaw on purpose five times today.'),
  ('meeting-anger-early', 7, 'Take a ten-minute walk when something irritates you, before responding.'),
  ('meeting-anger-early', 8, 'Say "I feel frustrated when..." instead of "You always..." once today.'),
  ('meeting-anger-early', 9, 'Rate your anger from zero to ten when you notice it. Respond only when it is under five.'),
  ('meeting-anger-early', 10, 'Splash cold water on your face or hold something cold when your temper rises.'),
  ('meeting-anger-early', 11, 'Write down what you would want to say in the heat of the moment. Then wait an hour and reread it.'),
  ('meeting-anger-early', 12, 'Notice one small annoyance today and let it go without commenting.'),
  ('meeting-anger-early', 13, 'Ask yourself, "What do I need right now?" when you feel angry, and try to give it to yourself.'),
  ('meeting-anger-early', 14, 'Move your body hard for two minutes, stairs, a fast walk, when anger builds.'),
  ('meeting-anger-early', 15, 'Get enough to eat and drink today. Hunger and thirst make everything sharper.'),
  ('meeting-anger-early', 16, 'Write a list of your early warning signs of anger and keep it on your phone.'),
  ('meeting-anger-early', 17, 'Delay one reaction by ten minutes today and see if the same response still feels right.'),
  ('meeting-anger-early', 18, 'Say sorry for something small today, cleanly, without explaining why you did it.'),
  ('meeting-anger-early', 19, 'Notice one thought that fuels your anger, like "they did that on purpose," and write down another possibility.'),
  ('meeting-anger-early', 20, 'Tell someone calmly what you would like them to do differently, in one sentence.'),
  ('meeting-anger-early', 21, 'Take three slow breaths before you open a message or email that might annoy you.'),
  ('meeting-anger-early', 22, 'Spend ten minutes doing something physical and productive, cleaning, chopping, digging, when tension builds.'),
  ('meeting-anger-early', 23, 'Write down what anger has cost you recently and what it has protected.'),
  ('meeting-anger-early', 24, 'Practice lowering your voice on purpose in one tense moment today.'),
  ('meeting-anger-early', 25, 'Ask a question instead of making an accusation once today.'),
  ('meeting-anger-early', 26, 'Leave a conversation that is getting heated and come back to it later, saying that you will.'),
  ('meeting-anger-early', 27, 'Notice what you are tired of today and say it in plain words to someone who can help.'),
  ('meeting-anger-early', 28, 'Do something soothing for your body tonight: a stretch, a warm shower, an early night.'),
  ('meeting-anger-early', 29, 'Write down one thing you handled well today when you could have gotten angry.'),
  ('meeting-anger-early', 30, 'Review your notes from this challenge and pick the one early sign of anger you can now spot. Watch for it.'),
  ('rebuilding-confidence-in-small-steps', 1, 'Write down three things you have done in your life that were hard at the time and that you managed.'),
  ('rebuilding-confidence-in-small-steps', 2, 'Speak first in one conversation today.'),
  ('rebuilding-confidence-in-small-steps', 3, 'Stand up straight, shoulders back, for one minute and notice how it changes your mood.'),
  ('rebuilding-confidence-in-small-steps', 4, 'Ask a question in a meeting, a class, or a shop today.'),
  ('rebuilding-confidence-in-small-steps', 5, 'Write down one skill you are good at and one piece of evidence for it.'),
  ('rebuilding-confidence-in-small-steps', 6, 'Wear something today that makes you feel like yourself.'),
  ('rebuilding-confidence-in-small-steps', 7, 'Say your opinion once today without adding "but I might be wrong."'),
  ('rebuilding-confidence-in-small-steps', 8, 'Make one small decision quickly today and do not revisit it.'),
  ('rebuilding-confidence-in-small-steps', 9, 'Introduce yourself to someone new.'),
  ('rebuilding-confidence-in-small-steps', 10, 'Set a tiny goal for today and finish it. Write "done" next to it.'),
  ('rebuilding-confidence-in-small-steps', 11, 'Accept a compliment with only "thank you."'),
  ('rebuilding-confidence-in-small-steps', 12, 'Try something you are not good at yet for ten minutes, just to practice being a beginner.'),
  ('rebuilding-confidence-in-small-steps', 13, 'Write down what a confident version of you would do today. Do one part of it.'),
  ('rebuilding-confidence-in-small-steps', 14, 'Make a phone call you have been avoiding.'),
  ('rebuilding-confidence-in-small-steps', 15, 'Look someone in the eye when you say hello today.'),
  ('rebuilding-confidence-in-small-steps', 16, 'Write down one thing you did well this week that nobody noticed.'),
  ('rebuilding-confidence-in-small-steps', 17, 'Volunteer for one small thing, a task, an errand, a turn, before you have time to talk yourself out of it.'),
  ('rebuilding-confidence-in-small-steps', 18, 'Practice saying "I don''t know, but I can find out."'),
  ('rebuilding-confidence-in-small-steps', 19, 'Do one thing today that scares you a little, on a scale of one to ten a three or a four.'),
  ('rebuilding-confidence-in-small-steps', 20, 'Write down the worst-case outcome of something you are avoiding, then how you would handle it.'),
  ('rebuilding-confidence-in-small-steps', 21, 'Notice one time today you compared yourself to someone and turn your attention back to your own next step.'),
  ('rebuilding-confidence-in-small-steps', 22, 'Ask for help with something today. Confident people do.'),
  ('rebuilding-confidence-in-small-steps', 23, 'Teach someone something small that you know.'),
  ('rebuilding-confidence-in-small-steps', 24, 'Sit at the front, or in the middle, instead of the back.'),
  ('rebuilding-confidence-in-small-steps', 25, 'Write down one thing you believe about yourself that is out of date.'),
  ('rebuilding-confidence-in-small-steps', 26, 'Speak a little slower and a little louder than usual in one conversation today.'),
  ('rebuilding-confidence-in-small-steps', 27, 'Say no to something you do not want to do, once, and let it stand.'),
  ('rebuilding-confidence-in-small-steps', 28, 'List three people who believe in you and one thing each of them would say to you today.'),
  ('rebuilding-confidence-in-small-steps', 29, 'Do something you are already good at and let yourself enjoy being good at it.'),
  ('rebuilding-confidence-in-small-steps', 30, 'Read your list of small steps from this challenge and write down what you now know you can do.'),
  ('feeling-your-feet-on-the-ground', 1, 'Press your feet into the floor and feel the ground push back, for thirty seconds.'),
  ('feeling-your-feet-on-the-ground', 2, 'Name five things you can see, four you can hear, three you can touch, two you can smell, and one you can taste.'),
  ('feeling-your-feet-on-the-ground', 3, 'Hold a piece of ice or run cold water over your wrists for one minute.'),
  ('feeling-your-feet-on-the-ground', 4, 'Breathe in for four, hold for four, out for four, hold for four. Repeat four times.'),
  ('feeling-your-feet-on-the-ground', 5, 'Describe the room you are in out loud, in detail, as if to someone who cannot see it.'),
  ('feeling-your-feet-on-the-ground', 6, 'Walk barefoot on grass, sand, or your floor for two minutes and notice every step.'),
  ('feeling-your-feet-on-the-ground', 7, 'Squeeze each muscle group for five seconds, then release, from your feet to your face.'),
  ('feeling-your-feet-on-the-ground', 8, 'Carry a small object in your pocket today, a stone, a coin, a shell, and touch it when you need to.'),
  ('feeling-your-feet-on-the-ground', 9, 'Name every color you can see from where you are sitting.'),
  ('feeling-your-feet-on-the-ground', 10, 'Sit with your back against a wall and feel the support behind you for one minute.'),
  ('feeling-your-feet-on-the-ground', 11, 'Count backward from fifty by threes.'),
  ('feeling-your-feet-on-the-ground', 12, 'Drink something cold or warm slowly, noticing the temperature travel down.'),
  ('feeling-your-feet-on-the-ground', 13, 'Name three things that are true right now: the date, where you are, what you are doing.'),
  ('feeling-your-feet-on-the-ground', 14, 'Hum a steady note for thirty seconds and feel the vibration in your chest.'),
  ('feeling-your-feet-on-the-ground', 15, 'Wrap yourself in a blanket or put on a heavy coat for five minutes and feel the weight.'),
  ('feeling-your-feet-on-the-ground', 16, 'Trace the outline of your hand with a finger, breathing in up each finger and out down the other side.'),
  ('feeling-your-feet-on-the-ground', 17, 'Smell something strong and pleasant: coffee, citrus, mint, soap.'),
  ('feeling-your-feet-on-the-ground', 18, 'Stamp your feet or clap your hands for twenty seconds.'),
  ('feeling-your-feet-on-the-ground', 19, 'Look at something far away, then something close, and switch five times.'),
  ('feeling-your-feet-on-the-ground', 20, 'Say your full name, your age, and today''s date out loud.'),
  ('feeling-your-feet-on-the-ground', 21, 'Push against a wall with both hands as hard as you can for ten seconds. Then rest.'),
  ('feeling-your-feet-on-the-ground', 22, 'List five things in the room that are the same color, then five that are round.'),
  ('feeling-your-feet-on-the-ground', 23, 'Rub your palms together until they are warm and place them over your eyes.'),
  ('feeling-your-feet-on-the-ground', 24, 'Notice the weight of your body on the chair, the bed, or the ground, for one minute.'),
  ('feeling-your-feet-on-the-ground', 25, 'Eat something with a strong taste slowly: a mint, a lemon slice, a pickle.'),
  ('feeling-your-feet-on-the-ground', 26, 'Walk up and down a flight of stairs, counting each step out loud.'),
  ('feeling-your-feet-on-the-ground', 27, 'Hold a warm mug with both hands and feel the heat spread into your fingers.'),
  ('feeling-your-feet-on-the-ground', 28, 'Draw or write your name with your non-dominant hand.'),
  ('feeling-your-feet-on-the-ground', 29, 'Pick a category, animals, cities, foods, and name one for each letter of the alphabet.'),
  ('feeling-your-feet-on-the-ground', 30, 'Write down the three grounding practices from this challenge that worked best for you. Keep the list somewhere you can find it fast.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 1, 'Write down the one thing you have been avoiding most. Just the name of it.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 2, 'Spend two minutes on that thing, then stop. Two minutes counts.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 3, 'Break the thing you are avoiding into five steps, each small enough to do in ten minutes.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 4, 'Do the first of those steps today.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 5, 'Set a timer for ten minutes and work on the avoided task until it rings.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 6, 'Tell someone what you are going to do today, and then do it.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 7, 'Do the easiest version of the task: a rough draft, a quick call, an ugly first attempt.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 8, 'Clear the space you need to do the task, and lay out what you need for tomorrow.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 9, 'Write down what you are afraid will happen if you start. Then start anyway for five minutes.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 10, 'Do one thing today at "good enough" and leave it there.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 11, 'Pair the task with something you like: a coffee, a playlist, a comfortable spot.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 12, 'Make one decision that has been holding the task up, in under a minute.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 13, 'Do the next step before you check your phone this morning.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 14, 'Ask someone for help with the part you are stuck on.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 15, 'Write down what you will do first tomorrow, specifically, and where.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 16, 'Work on the task for fifteen minutes and then reward yourself with something small.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 17, 'Finish one tiny, unrelated thing today, a dish, an email, a bill, to feel the click of "done."'),
  ('getting-unstuck-one-tiny-step-at-a-time', 18, 'Do a step you have been calling boring and notice it was not as bad as the dread.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 19, 'Lower the bar: what is the smallest possible version of the next step? Do that.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 20, 'Sit with the task open for five minutes, even if you do nothing else. Just be near it.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 21, 'Say out loud, "I don''t have to feel like it to do it," and do five minutes.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 22, 'Cross off anything on your list that no longer matters. Fewer things means less stuck.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 23, 'Do the step you are dreading at the time of day when you have the most energy.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 24, 'Show someone a piece of the unfinished work, whatever state it is in.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 25, 'Write down what finishing the task would let you do or feel.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 26, 'Work on the task next to someone else who is working, in person or on a call.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 27, 'Do the next step even if the last one was imperfect. Forward beats perfect.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 28, 'Spend ten minutes on the task standing up.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 29, 'Write down one thing you learned about how you get stuck, and one thing that got you moving.'),
  ('getting-unstuck-one-tiny-step-at-a-time', 30, 'Look at everything you have done during this challenge and decide the next single step. Write it on a card for tomorrow.')
) as v(slug, day, task)
join public.challenge_templates t on t.slug = v.slug;
