-- Five articles published 2026-10-08. Generated by:
--   python3 tools/articles_sql.py --since 2026-10-08
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('when-a-goal-stops-mattering', 'When a Goal Stops Mattering', 'You are halfway to something you no longer want. How to tell the difference between a bad week and a goal that has genuinely expired, and how to put one down well.', 'You set it eighteen months ago and it made complete sense then. Now you look at it and feel nothing, or something worse than nothing, and you carry on anyway because stopping would mean having been wrong.

Goals are treated as fixed objects you either reach or fail. They are actually statements about what mattered to you on the day you wrote them, and people change.

First, rule out the ordinary slump

Most moments of a goal stopping mattering are not that. They are the middle.

Almost everything worth doing has a long, unglamorous stretch where the novelty has gone and the end is not in sight. That stretch feels exactly like having lost interest, and pushing through it is usually right.

So check the simple explanations first. Are you tired. Is it the hardest part. Did something else take all your attention this month. Did you just have a setback.

If the answer to any of those is yes, do not decide now. A goal reviewed on a bad Tuesday is reviewed by the worst available judge.

Then ask the questions that tell you something

Give it a week, and then ask these properly, ideally on paper.

Why did I want this originally, and is that reason still true? A great many goals belong to a situation that has changed: a job you left, a relationship that ended, a version of your body, a worry you no longer have.

Who is this for? If the honest answer is that you want to be seen to have done it, that is worth knowing. It does not automatically make the goal worthless, but it predicts how it will feel when you arrive.

Would I choose this today, from scratch? Not would I regret dropping it, but would I pick it up.

And: what would I do with the time and attention instead? If there is no answer, you may not be bored of the goal; you may just be tired.

Be careful with what you have already put in

The strongest argument for continuing is usually the hours already spent, and it is the weakest one logically.

Those hours are gone either way. They cannot be recovered by spending more. What they can do is make you finish something you no longer want, which is a second cost rather than a recovery of the first.

A cleaner way to think about it: the only question is whether the remaining effort is worth the remaining reward, to you, now. Where you started does not come into it.

The same applies to having told people. Having announced something is a real social cost and a poor reason to spend another year.

Four things you can do, not two

The usual framing is finish or fail, which is why so many goals die by neglect instead of by decision. There are more options.

Finish it, as planned, because the reason still holds.

Shrink it. Many goals are the right direction and the wrong size: the half rather than the marathon, conversational rather than fluent, one room rather than the house. A shrunken goal you complete is worth far more than a grand one you abandon.

Change its shape. Keep what you actually valued and drop the form. If the point was being outdoors, the specific race may be optional. If the point was writing, the novel may not be the only container.

Or end it, deliberately. Which brings us to the part people skip.

How to put one down properly

A goal abandoned quietly leaves residue: a flicker of failure every time you see the equipment, and a slow erosion of trust in your own plans.

So end it on purpose. Say it out loud or write it down: I am not doing this, and here is why. Tell anyone who was involved, in one sentence. Deal with the physical traces — cancel the subscription, sell or store the kit, delete the file or archive it with a date.

And name what you are keeping, if anything. I am stopping the course and I am keeping the half hour of reading. That turns a dropped goal into a changed one, which is what it usually is.

Then give it a decent epitaph: that was the right idea for who I was then. Most expired goals deserve that rather than an apology.

Expect it to feel like loss

Even a goal you are relieved to drop takes something with it: a version of yourself you were going to become.

That is a real small grief, and it usually arrives a few days after the decision rather than at the moment. People misread it as evidence they decided wrongly.

Sit with it for a week before you reopen the question. If after a month you are genuinely pulled back, that is information, and you are allowed to restart. Picking something up again is not an admission of anything.

Make the next one easier to review

Two habits prevent most of this.

Put a review date on a goal when you set it: three months, six months, a year. A date makes stopping a scheduled decision rather than a failure, and people honor goals they are allowed to re-examine.

And write down why, not just what. In a year, the reason is what tells you whether the goal still belongs to you, and it is the thing nobody records.

When losing interest is not about the goal

If everything has stopped mattering, not just this, that is a different question. Goals going flat across the board, alongside low energy, poor sleep, or a general sense that nothing is worth beginning, is a pattern rather than a preference.

Long-running low mood and burnout both look exactly like having lost your ambitions, and both are treatable. That is worth a conversation with a doctor or a therapist rather than another round of choosing better goals.', array['Goals', 'Values']::text[], 0, '2026-10-08T14:00:00+00:00'::timestamptz),
  ('naming-what-you-feel', 'Naming What You Feel', 'Bad, stressed and fine cover a lot of ground. Why putting a more exact word to a feeling changes it, and how to do that when you have no idea what you feel.', 'Someone asks how you are and you say stressed. Later you say you had a bad day. Both are true and neither tells you anything you can use.

A feeling you cannot name tends to run the evening. A feeling you can name, specifically, becomes something you are having rather than something you are.

What naming actually does

Putting a precise word to an emotion does a few things at once.

It separates you from it. There is a difference between I am furious and I notice I am resentful about the way that was decided. The second one has you in it, looking.

It points at the cause. Vague bad has no direction. Resentful, disappointed, embarrassed, lonely and overwhelmed each point somewhere specific, which is the first step toward doing anything about it.

And it tends to lower the volume. Describing a feeling precisely is a different mental activity from being carried by it, and people usually report that the intensity drops a little as soon as the word lands.

The words most of us are missing

Most people run on about five: fine, tired, stressed, annoyed, sad. The useful vocabulary is bigger and not very complicated.

Under stressed, there is often: overwhelmed, rushed, pressured, dreading something, resentful, or simply exhausted. Those need completely different responses.

Under annoyed: irritated, offended, disrespected, impatient, or hurt. The last one is the most commonly mislabeled emotion there is; a great deal of anger is hurt wearing something sturdier.

Under sad: disappointed, lonely, grieving, flat, homesick, regretful, defeated.

And under fine: numb, braced, relieved, quietly furious, or genuinely all right, which is also allowed.

Start with the body, not the word

If someone asks what you feel and your mind returns nothing, that is normal and the way in is through sensation.

Where is it, and what is it like. Chest tight. Stomach hollow. Jaw clenched. Shoulders up. Hands restless. Heavy, like being pressed down. Fizzing.

Then guess, loosely. Heaviness and slowness often go with sadness or exhaustion. Tight chest and fast breathing with fear. Hot face and clenched jaw with anger. Hollow stomach with dread or shame.

A guess you can correct is far more useful than nothing. You will usually know within a few seconds whether the word fits.

Ask what it wants you to do

Every feeling comes with an impulse attached, and the impulse is often the clearest clue to the name.

If you want to hide, that is usually shame or embarrassment. If you want to argue, anger. If you want to leave, fear. If you want to stop moving, sadness or exhaustion. If you want to check something repeatedly, anxiety.

So the question what do I want to do right now often answers what am I feeling faster than introspection does.

Expect more than one at once

The most common reason people cannot name a feeling is that there are two, and they conflict.

Relieved and guilty. Grieving and free. Proud and resentful. Loving someone and wanting them to leave the room.

Mixed feelings are not confusion; they are the normal state for anything that matters, and insisting on one answer is what makes them hard to identify. Name both. And is usually the right conjunction.

Say it out loud or write it down

Thinking it is weaker than saying it, which is weaker than writing it.

A sentence is enough: I am disappointed about the meeting and embarrassed that I pushed for it. Three lines in a notebook does more than an hour of turning it over, because turning it over in your head tends to be rumination rather than naming.

If you are telling someone else, the format that lands best is simple: I am feeling X about Y. It is also enormously more useful to the other person than being told you are fine.

What not to do with the name

Do not use it as a verdict on yourself. Noticing jealousy is not a confession of being a jealous person, and the people who name feelings most accurately are usually the ones who treat them as weather rather than character.

Do not stop at the name either. Naming is a first move. The second is deciding whether the feeling is telling you something to act on, something to say, or something to sit with until it passes.

And do not expect it to work during a peak. At the top of a wave, nothing verbal loads. Name it afterward, and use something physical in the moment.

Build the habit cheaply

Once a day, at a fixed time, ask: what am I feeling, in one or two specific words, and about what. Thirty seconds.

People who do this for a couple of weeks tend to report the same thing: fewer evenings hijacked by something they could not identify, and conversations that go better because they can say what is wrong before it comes out sideways.

When you genuinely cannot find anything

Some people reach for a feeling and find a blank, consistently. That has several ordinary explanations: exhaustion, long-running low mood, a childhood where naming feelings was not safe, or the numbness that can follow something frightening.

None of those is a character flaw and all of them respond to help. If you are flat most of the time, if you only notice feelings as physical symptoms, or if looking inward brings distress rather than information, that is worth taking to a doctor or a therapist, who can help you get the vocabulary back rather than leaving you to guess.', array['Emotion Regulation', 'Mindfulness']::text[], 0, '2026-10-08T14:00:00+00:00'::timestamptz),
  ('asking-for-something-clearly', 'Asking for Something Clearly', 'Hinting, over-explaining and hoping they offer all fail. A plain structure for asking someone for what you want, and what to do with the answer.', 'You have wanted to ask for three weeks. You have mentioned it twice, sideways, in a way you hoped they would pick up. They did not, and now you are annoyed with them for not noticing something you never actually said.

Most people are not bad at asking because they lack nerve. They are bad at it because nobody ever showed them the shape of a clear request, so they improvise, and the improvised version has four common faults.

The four ways a request goes wrong

Hinting. It would be nice if someone did the bins. Said to a room, this is not a request, and being ignored is the expected outcome.

Over-explaining. Five minutes of context before the ask, which buries it and signals that you expect to be refused. People stop listening before the sentence that matters.

Apologizing through it. So sorry, I know you are busy, this is probably stupid, but. That invites them to agree it is an imposition.

And bundling. Asking for one thing while actually wanting another, usually acknowledgment: I would like help with the kitchen, when the real request is I would like you to notice what I do.

A plain structure that works

Four short parts, in this order. It comes from practical skills work in therapy and it is almost boringly effective.

The situation, in one neutral sentence. The bins have not gone out the last three weeks.

How you feel, briefly and without accusation. I am fed up with being the one who notices.

The request, specific and single. Would you take them out on Tuesday nights from now on.

And what makes it easy to say yes to. I will stop reminding you about it.

That is it. Four sentences, maybe thirty words. Most unsuccessful requests are five times longer and say less.

Be specific enough to be answerable

The most common fault that survives everything else is vagueness.

Help more is not answerable. Take Tuesday evenings is. Be more supportive is not answerable. Ask me how the appointment went is.

A test: could someone do what you asked tomorrow, and would you both agree afterward whether they had? If not, the request is still a wish.

And one ask at a time. A list of three is a negotiation, and negotiations default to no.

Say it at a time that is not loaded

Not in the middle of an argument, not at eleven at night, not while one of you is about to leave.

It is also worth flagging it, briefly, which gives people a moment to arrive: there is something I want to ask you about, is now all right.

For anything significant, in writing is often better than in person, especially at work. It is clearer, they can think, and there is a record of what was actually asked.

Then stop talking

After the request, the strongest thing you can do is be quiet.

People fill the silence with more explanation, additional reasons, and often a preemptive retreat: but honestly, if it is difficult, do not worry. That last sentence undoes everything before it.

So ask, and then wait. The pause is uncomfortable for about four seconds and it is where the answer comes from.

What to do with the answer

If they say yes, say thank you and leave it. Do not add conditions or go back over why you asked.

If they say no, you have options and none of them require a fight. Ask what would be possible instead. Ask whether a smaller version works. Ask them to tell you what they can commit to.

And if it is a no you can live with, accept it cleanly. People who accept a no gracefully get far more yeses over time, because asking them for things is not dangerous.

If it matters too much to accept, say that plainly rather than sulking: this one is important to me, can we find a version that works. Repeating the same request later, calmly, is also allowed; persistence done pleasantly is remarkably effective.

Where the difficulty usually comes from

If asking feels disproportionately hard, it is often not about this particular request.

Some people learned that asking produced anger or disappointment, so they became people who anticipate rather than ask. Others learned they were only welcome when they needed nothing.

That history is worth knowing, because it explains why a four-sentence request can feel like an imposition. It also means the fix is practice rather than insight: small asks, often, with low stakes, until the sentence stops feeling expensive.

Start with the easy ones

Ask for the window seat. Ask someone to pass the salt rather than reaching. Ask a colleague for the file instead of hunting for it. Ask your partner for ten minutes.

Those sound trivial and they are the training. By the time you need to ask for something that matters, the shape of the sentence is already familiar.

When asking is not safe or not working

If asking for ordinary things reliably produces anger, punishment or a long sulk from someone, the problem is not your technique. That is worth taking seriously, and if it is frightening, please talk to a professional or a domestic abuse helpline rather than refining your phrasing.

And if the fear of asking is strong enough that you go without things you need, or you cannot ask for help even when you are struggling, that is very workable with a therapist, often in a short course of practical sessions. A doctor is a reasonable first step if you do not know where to begin.', array['Assertiveness', 'DBT']::text[], 0, '2026-10-08T14:00:00+00:00'::timestamptz),
  ('what-if-it-really-is-as-bad-as-you-think', 'What If It Really Is as Bad as You Think', 'Reassurance does not touch some worries. The alternative is to follow the fear to the end on purpose and ask what you would actually do.', 'You are worrying about the thing again. Someone has told you it will probably be fine, and the reassurance lasted about ninety seconds, because your worry was never asking for odds. It was asking whether you could survive the outcome.

For that kind of worry, there is a move that sounds backward and works much better than reassurance: instead of arguing that it will not happen, you follow it all the way to the end and ask what you would do.

Why reassurance bounces off

Most worry is not a mistake about probability. It is a belief about your capacity.

So telling someone the scan is probably clear, or that nobody will notice, addresses a question they were not really asking. The real question is: and if it is not, what then? Unanswered, that question keeps the worry running regardless of the odds.

Reassurance also has a short half-life, and seeking it repeatedly teaches you that you cannot settle your own mind without someone else. That is why the fourth reassurance works less well than the first.

Follow it down, one step at a time

Take the worry and keep asking the same question: and then what would happen?

Say the fear is a bad review at work. And then what? My manager thinks I am not good enough. And then what? I might be managed out. And then what? I would have to find another job. And then what? It would take a few months, money would be tight, I would have to tell people.

Keep going until you reach the bottom, which is usually not an event but a feeling: I would be humiliated. I would be alone. I would not cope.

That bottom is the actual fear, and it is almost never the thing you thought you were worrying about.

Then ask the useful question

Not how likely is it, but: if that happened, what would I do?

Specifically. Who would I call. What would the first week look like. What money would I have. What help exists. What have I survived before that was comparable.

Most people find two things here. The plan is shorter and more obvious than they expected. And the bottom of the fear turns out to be something they have already lived through a version of.

Write it down. A worry answered in your head returns tomorrow; a worry answered on paper can be reread.

Where it goes wrong, and how to do it well

This can turn into rumination if you are not careful, so two rules.

Do it once, on paper, with an end. Not in bed, not in circles. Fifteen minutes, written, finished.

And keep moving down rather than sideways. The trap is branching into every possible version: but what if it is this instead, or that. Pick the version that frightens you most, follow that one to the bottom, and ignore the branches. The bottom is usually the same whichever branch you take, which is itself useful to discover.

If you find yourself feeling worse rather than steadier, stop and come back to it with someone else.

What to do about the part that is real

Sometimes following it down reveals something you can actually act on, which is good news badly disguised.

If the bottom is money, the action is knowing your numbers and what help exists. If it is a medical fear, the action is the appointment. If it is losing the job, the action might be updating your resume and keeping one contact warm.

A small amount of real preparation does more for a worry than hours of argument. And notice the difference between preparing, which has a finish, and checking, which does not.

Also: some worries deserve to be taken to someone. If the honest answer is I genuinely could not manage that alone, then the next step is working out who would be there, and asking them now rather than in the emergency.

The part you have to leave uncertain

Some of it cannot be settled, and pretending otherwise is what keeps people searching for a better reassurance.

The version that holds is not it will be fine. It is: I do not know how this goes, and here is what I would do if it went badly. That sentence is boring, accurate, and liveable, which is more than certainty ever manages.

You can also say the uncertain part out loud rather than resolving it: I might not get the result I want. People often find that saying the feared sentence plainly takes more charge out of it than any amount of being told it will not happen.

For the things that cannot be prepared for

Some fears have no plan available: a child''s safety, a diagnosis, something far outside your control.

For those, the honest answer is that preparation does not apply, and the work is different: putting the worry in one time slot a day rather than all of them, keeping your life populated with other things, and letting the uncertainty be uncertain.

That is harder and it is still a skill rather than a mood.

When to get help with it

If worry has taken over most of your day, if you cannot stop asking people for reassurance, if the physical knot never fully goes, or if following a fear to the end leaves you panicky rather than calmer, that is worth treating rather than managing.

This kind of worry responds well to cognitive behavioral therapy, often in a fairly small number of sessions, and a doctor or a therapist is the right place to start. Take your written list; it is more useful than trying to describe it from memory.', array['CBT', 'Worry']::text[], 0, '2026-10-08T14:00:00+00:00'::timestamptz),
  ('burnout-in-a-job-you-cannot-leave', 'Burnout in a Job You Cannot Leave', 'Every piece of advice ends with changing jobs, and you cannot. What actually helps when leaving is not an option this year, and what to stop doing.', 'You have read the articles. They all arrive at the same place: this job is harming you, so leave. And you cannot, because of the money, the visa, the pension, the years left on the mortgage, the fact that there is nothing else within sixty miles.

So here is the other version. What helps when the exit is closed for now, and what quietly makes it worse.

Name the constraint, properly

Before anything else, be precise about what is actually fixed, because people often treat the whole situation as immovable when only one part is.

Is it money, and if so how much and for how long. Is it a date, like a qualification or a vesting period. Is it a place. Is it a season of life that will change in two years.

That matters because an indefinite trap and a two-year stretch feel completely different to live in, and the second one is often the truth. Writing down when the constraint lifts, even approximately, changes the shape of the problem.

Then find the smallest real changes

Most jobs have more adjustable parts than they look like they do, and the question is which ones you have not tried asking about.

Hours and shape: a different start time, one day working elsewhere, no meetings before ten, a compressed week.

Content: which part of the work is actually draining you. It is often one specific task, one client, one recurring meeting. Swapping or shedding one item is far more achievable than changing the job, and it can account for most of the damage.

People: being moved off a particular team or away from one person sometimes fixes what looked like whole-job burnout.

And ask properly rather than hinting: here is what I am struggling with, here is one specific change that would help, is that possible. Managers refuse vague complaints and quite often say yes to specific requests.

Lower the standard where nobody is watching

This is the part people resist most and it is the heart of surviving a job you cannot leave.

If the work asks for more than can be done, something will give, and your choices are your health or the output. Most people in burnout have been quietly choosing their health for years without admitting it.

So choose deliberately instead. Which parts actually matter, and which have you been doing to an exceptional standard that nobody has ever noticed? Do those adequately. Stop volunteering. Stop fixing other people''s work. Leave the email at five.

That is not laziness; it is rationing. And rationed effort is what allows you to stay.

Protect the edges

Burnout spreads by eating the time around the job: the commute spent working, the evening spent dreading, the Sunday spent braced.

So build hard edges. A route home that is a walk rather than more screen. Notifications off after a set time, properly off. One evening a week with a fixed thing in it so it cannot be absorbed. The first ten minutes at home belonging to nobody.

Those edges do more for recovery than any amount of weekend sleeping, because the problem is usually continuousness rather than volume.

Get your identity out of the building

The longer a job is intolerable and inescapable, the more important it is that it is not the main thing you are.

That means having something in the week that you are visibly competent and useful at, somewhere else. A class, a team, volunteering, a craft, a role in a community.

This sounds like an addition to an already full week, and it is the thing that most reliably keeps people functioning in bad jobs. A life with one load-bearing wall is fragile; a life with two or three can take a lot more weather.

Stop doing these three things

Waiting for it to get better on its own. Jobs rarely improve by themselves, and waiting is what turns two bad years into eight.

Using the evenings to recover with alcohol. It works for an hour, costs the second half of the night, and makes the next day measurably harder.

And keeping it secret. Burnout thrives in isolation, and most people in it have told nobody specific. One person who knows the real version changes how heavy the week is.

Keep a door open, even a small one

You cannot leave now. That is not the same as doing nothing about later.

Half an hour a week: a resume kept current, one contact spoken to, one qualification started, one saved amount set aside. Small, regular, and unglamorous.

The practical value is real and the psychological value is larger. The difference between a trap and a long stretch is whether you can see yourself doing anything about the end of it.

Know the lines that change the calculation

Some situations stop being endurable in a way that rationing can fix: when the work is making you physically ill, when you are being bullied or harassed, when the job is unsafe, or when you are making errors that could hurt someone.

At those points the sums change, and so do your options: occupational health, HR, a union, your doctor, a regulator, or a formal grievance. Those routes are slow and they exist.

When to get help

If you are not sleeping, dreading Monday from Saturday, numb at work, drinking more, or finding that a week off makes no difference at all, please take it to a doctor or a therapist rather than waiting for the constraint to lift.

Burnout is treatable while you are still in the job, and a doctor can also check what has happened to your sleep, your blood pressure and your mood. If things have reached a point where you cannot see any way through, tell someone the same day; this is exactly the kind of pressure that distorts how the future looks, and it responds to help.', array['Burnout', 'Resilience']::text[], 0, '2026-10-08T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
