-- The checklist library for 2026-09-21: a description for every checklist (the
-- line a member reads on the library tile and at the top of the page), tags for
-- the four imported at launch, and the day's two new ones — Steadying Yourself
-- When Nerves Hit, and Winding Down for the Evening.
--
-- Generated with: python3 tools/checklists_sql.py
-- Source of truth: data/checklists.json. An upsert on slug, so applying it
-- twice is harmless and every member's ticked items survive.

insert into public.checklists
  (slug, title, description, category, items, cadence, tags, min_level, published_at)
values
  ('daily-mental-health-checklist', 'Daily Mental Health Checklist', 'A once-a-day pass over the basics that hold a mood steady: food, water, movement, people, rest. Use it to see what you have already covered today and what is still missing.', 'Wellbeing', '["Check-in with your emotions — How am I feeling today?", "Stay hydrated and nourished — Have I eaten and drunk enough water?", "Move my body — Did I engage in any physical activity (stretching, walking, etc.)?", "Connect with others — Did I interact with someone in a meaningful way?", "Practice mindfulness — Did I pause and take deep breaths or meditate?", "Limit social media/news exposure — Did I avoid excessive negative content?", "Engage in an enjoyable activity — Did I do something I love?", "Get adequate rest — Am I prioritizing sleep and relaxation?"]'::jsonb, 'daily', array['Self-Care', 'Habits']::text[], 1, null),
  ('recognizing-warning-signs', 'Recognizing Warning Signs', 'Helps you notice the shifts that tend to arrive before a harder stretch, like broken sleep, pulling away from people, or a mood that will not lift. It is for catching a pattern early, never for putting a label on yourself.', 'Wellbeing', '["Persistent sadness or mood shifts — Have I felt low for two weeks or more?", "Loss of motivation — Am I struggling with tasks that used to feel easy?", "Changes in appetite or sleep — Am I sleeping too much or too little?", "Increased stress or anxiety — Am I constantly overwhelmed?", "Avoidance behavior — Am I withdrawing from friends, work, or activities?", "Self-critical or negative thoughts — Do I frequently feel hopeless?", "Physical symptoms — Have I noticed headaches, tension, or fatigue linked to stress?"]'::jsonb, 'daily', array['Resilience', 'Stress']::text[], 1, null),
  ('coping-self-care-strategies', 'Coping & Self-Care Strategies', 'A menu of things that help when a day turns heavy, from breathing and grounding to telling someone. Pick one or two that fit the moment rather than working down the whole list.', 'Wellbeing', '["Journaling — Write down thoughts to process emotions.", "Therapeutic exercises — Use structured worksheets or grounding techniques.", "Breathing practices — Try box breathing or the 4-7-8 method.", "Sensory grounding — Engage with sights, sounds, and textures to stay present.", "Social support — Talk to a friend, therapist, or support group.", "Routine setting — Create stability with morning and evening rituals.", "Affirmations — Challenge negative thoughts with empowering statements.", "Professional help — Seek guidance if symptoms persist or worsen."]'::jsonb, 'daily', array['Self-Care', 'Grounding', 'Stress']::text[], 1, null),
  ('long-term-mental-wellness-practices', 'Long-Term Mental Wellness Practices', 'The slower habits that keep you well over months rather than hours: boundaries, hobbies, reflection and community. Come back to it whenever you want to see where the balance has drifted.', 'Wellbeing', '["Develop healthy boundaries — Say no when needed.", "Nurture hobbies — Engage in activities that bring joy.", "Schedule time for reflection — Regular check-ins on progress.", "Educate yourself — Learn about mental health to reduce stigma.", "Volunteer or engage with community — Giving back can boost well-being.", "Prioritize balance — Avoid burnout by adjusting workload and self-care."]'::jsonb, 'daily', array['Habits', 'Boundaries', 'Values']::text[], 1, null),
  ('steadying-yourself-when-nerves-hit', 'Steadying Yourself When Nerves Hit', 'For the twenty minutes before something that matters — an interview, a scan, a hard conversation. It walks you through settling your body first, then your head, so the nerves have somewhere to go besides your chest.', 'Anxiety', '["Name it plainly — Say “I am nervous” rather than “something is wrong with me.”", "Slow the out-breath — In for four, out for six, six rounds; the long exhale is the part that settles you.", "Put both feet flat on the floor — Press down and let the ground take your weight for a moment.", "Find five things you can see — Naming them moves your attention out of your head and into the room.", "Drop your shoulders, unclench your jaw — Nerves gather there first, and letting go tells your body the danger is not here.", "Drink some water — A dry mouth and a racing heart both ease a little with a few slow sips.", "Ask what you are preparing for — Nerves usually mean something matters to you, not that it will go badly.", "Plan the first thirty seconds — Know your opening line or first step so you are not deciding it while shaking."]'::jsonb, 'as needed', array['Anxiety', 'Grounding']::text[], 1, '2026-09-21T16:00:00+00:00'::timestamptz),
  ('winding-down-for-the-evening', 'Winding Down for the Evening', 'A short evening routine for closing the day instead of letting it trail off into midnight. Each line is one small signal to your body and mind that nothing more is being asked of them tonight.', 'Sleep', '["Set a stop time for work — Pick the hour the day ends and let the unfinished things stay unfinished.", "Write down tomorrow’s first three things — On paper, so your mind can stop holding the list for you.", "Lower the lights an hour before bed — Dim light is the oldest signal there is that the day is closing.", "Put the phone in another room — Distance works where willpower does not.", "Do one slow thing — A shower, a stretch, a few pages, a cup of tea; something with no goal attached.", "Let the room get cool and dark — A cooler, darker room makes falling asleep easier than trying harder does.", "Park the worries on paper — When your head starts up, write the thought down and tell it you will look tomorrow.", "Go to bed at about the same time — A steady hour does more for your sleep than one perfect night."]'::jsonb, 'daily', array['Sleep', 'Self-Care']::text[], 1, '2026-09-21T16:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  description  = excluded.description,
  category     = excluded.category,
  items        = excluded.items,
  cadence      = excluded.cadence,
  tags         = excluded.tags,
  min_level    = excluded.min_level,
  published_at = excluded.published_at;
