-- Five articles published 2026-09-21. Generated by:
--   python3 tools/articles_sql.py --since 2026-09-21
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('why-you-stay-up-late-when-you-are-tired', 'Why You Stay Up Late When You Are Tired', 'You are exhausted and you still will not go to bed. Scrolling, one more episode, anything but sleeping. What that late hour is really giving you, and how to get it back another way.', 'It is past midnight. You have been tired since eight. You are not doing anything you would call important, just scrolling, or watching something you are barely following, or wandering the kitchen. And every twenty minutes you tell yourself you will go to bed after this, and you do not.

You know you will feel terrible tomorrow. You do it anyway. Then you tell yourself you have no discipline, which is not what is happening at all.

What the late hour is for

Ask people why they stay up and the honest answer is usually some version of this: it is the only time that belongs to me.

If your whole day is spoken for, by work, by children, by other people''s needs, then the hours after everyone sleeps are the first hours nobody is asking you for anything. Going to bed ends that. So you stay, not because you want the scrolling, but because you want the ownership, and this is the only place you have found it.

Once you see it that way, the problem changes shape. You are not failing at bedtime. You are taking, in the only place available, something you need and are not getting anywhere else.

The other reasons it happens

A few more, often layered on top.

Going to bed means facing your own mind. For many people, lights-out is when the worrying starts. Staying awake with a screen is a way of avoiding the quiet, and it works, which is why it is so hard to stop.

The day had no ending. Without a clear point where work stops and rest begins, the evening drifts. Nothing tells you it is over, so it never is.

You are too wound up to feel sleepy. Tired and wired are different states. A body still carrying the day''s stress does not produce the drowsy feeling you are waiting for, so you wait, and the waiting happens on a screen.

Tomorrow is unappealing. If the next day looks like a grind, midnight is the last moment before it starts, and part of you wants to hold it.

Give yourself the time earlier

The most useful change is not a stricter bedtime. It is moving the hour that belongs to you to somewhere earlier in the day, so the night does not have to carry it.

Thirty minutes after the kids are down, or before anyone is up, or on a break at work, that is genuinely yours and not spent on chores. Not productive time. Time you would describe as yours. People who find this often discover the late-night pull gets weaker on its own, because the need it was meeting is already met.

Give the evening an ending

Decide when the day stops and mark it with something small and physical. Shut the laptop and put it in a drawer. Wash the last dish. Change into different clothes. Turn off the main lights and use lamps. It sounds trivial and it works, because the drift happens when nothing signals the transition.

Make the hour before bed one you actually want

If bedtime is only the end of something, there is nothing to move toward. Try making the last hour genuinely nice: a book you are enjoying, a hot shower, music, a stretch on the floor, tea. Something you look forward to. Going to bed is much easier when it is the entrance to something pleasant rather than the exit from your only free time.

Deal with the screen practically

Willpower against a phone in bed rarely works. Charge it in another room and use a real alarm clock. If you read on a device, take the interesting apps off it. Decide in advance what the last thing of the evening will be, so the ending is chosen rather than negotiated at midnight with a tired brain.

If the quiet is what you are avoiding

For some people the late hour is mostly avoidance of the thoughts that arrive when there is nothing else. If that is you, the answer is not more discipline; it is giving those thoughts somewhere to go earlier. Ten minutes with a notebook before the evening ends, writing out what is on your mind and anything you plan to do about it, empties a surprising amount of what would otherwise arrive at lights-out.

Change one thing, not everything

Do not overhaul your nights. Pick the one that matches your version of this: the earlier free time, the clear ending, the pleasant last hour, the phone in another room. Give it two weeks. A single change kept beats a full plan abandoned by Thursday.

Be honest about the cost

It helps to look plainly at what the late hours actually cost you: the flat mood, the short fuse with people you love, the day spent half-present. Not as a reason for guilt, but as a reason to want something different. And notice, when you do get a decent night, how different the following day feels. That memory is what makes the change stick.

When it is more than a habit

If you cannot sleep even when you go to bed on time, if you lie awake for hours, if you are exhausted every day regardless, or if the thoughts that arrive in the dark are frightening or hopeless, please talk to your doctor or a therapist. Ongoing sleep trouble is very treatable, and it is often tangled up with anxiety or low mood in ways that are much easier to untangle with help. Your evenings are allowed to be yours. They just do not have to cost you the next day.', array['Sleep', 'Habits']::text[], 0, '2026-09-21T14:00:00+00:00'::timestamptz),
  ('the-thing-you-have-never-told-anyone', 'The Thing You Have Never Told Anyone', 'Most people carry something they have never said out loud. Why the keeping is often heavier than the thing itself, and how to begin setting it down without telling the whole world.', 'There is probably something. A thing you did, or something that was done to you, or a thought you have had. You have carried it for years, maybe most of your life. Nobody knows. And some part of you is certain that if anyone found out, they would see you differently forever.

Almost everyone has one of these. That is worth sitting with for a moment, because the thing shame insists on most strongly is that you are the only one.

What secrecy does

The secret itself may be small or serious. What makes it heavy is the keeping.

Every relationship you have is slightly filtered through it: there is a part of you nobody is allowed near, so closeness always stops at a certain depth. You are watchful, in case a conversation gets close. And you cannot get any perspective on it, because it has never been outside your own head, where it has been growing unchallenged for years.

Guilt says I did something bad. Shame says I am something bad. Secrets almost always feed the second one, and the second one is what wears a person down.

The story has been unchecked for a long time

Whatever this is, you have been the only one interpreting it. And you have been interpreting it with the least generous reading available, probably from the perspective of whoever you were when it happened, often a child or a much younger person.

If it happened when you were young, consider that a child cannot be responsible for an adult''s behavior, whatever they were told and however they behaved afterward. If it was something you did, consider whether the judgment you pass on yourself is one you would pass on anyone else who did the same thing at the same age in the same situation. You are almost certainly applying a standard you apply to no one else.

Say it to yourself first

Before anyone else hears it, let it exist outside your head. Write it down in plain words, exactly what happened, with no softening and no self-attack. Read it back. Then, if you can, write what you would say to a friend who handed you that same page.

This is not a substitute for telling someone. But it is often the first time the thing has had edges, rather than being a fog of dread, and edges make it smaller.

Then tell one person

One. Not everyone, not publicly, not on the internet. One person, chosen carefully: someone who has shown over time that they can be trusted with something, who is not entangled in the situation, and whose reaction you can survive.

For many people the safest first person is a therapist, precisely because they have no stake in your life, have heard a great deal, and are bound to keep it. If that feels impossible, a helpline, a support group, or a religious counselor can serve the same purpose. What matters is that it leaves your head and lands somewhere without the world ending.

What usually happens when you tell

People who finally say the thing out loud tend to report a few things. The other person was far less shocked than expected. The actual telling took about ninety seconds after years of dread. And the relief afterward was physical, as if something had been put down.

That is not a guarantee. Sometimes people react badly, which is why the choosing matters. But the near-universal experience is that the anticipated catastrophe does not come.

You do not owe it to everyone

Setting something down is not the same as broadcasting it. You get to decide who knows, and it is fine for the answer to be one or two people forever. Telling is for your sake, not as a penance or a debt to the world.

If it involves harm you did

If what you are carrying is something you did that hurt someone, the relief is real but so is the repair. Once it is out of the dark and you can think about it clearly, you can consider whether there is an amends to make, and what an actual amends would look like. That is worth thinking through with someone rather than acting on impulse, because a confession made to relieve your own guilt can sometimes land as another injury on the person you hurt.

If it involves harm done to you

Then the shame you have been carrying was never yours. It belonged to whoever did it and got transferred to you, which is what abuse tends to do. This is among the most common and most painful versions of a kept secret, and it is the one most worth taking to someone trained to help. If any of this brings up thoughts of harming yourself, please tell someone today. In the US you can call or text 988 at any time.

Where to take it

A therapist''s room is built for exactly this. You do not have to lead with it; you can take weeks to get there. But it is the one place where saying the thing has no social cost, and where someone can help you look at it without flinching and without judgment. You have carried this alone for long enough. It was never proof of what you are.', array['Shame', 'Self-Compassion']::text[], 0, '2026-09-21T14:00:00+00:00'::timestamptz),
  ('how-to-get-through-a-party-you-are-dreading', 'How to Get Through a Party You Are Dreading', 'The invitation has been sitting there and the day has arrived. A practical plan for before, during, and after, so the evening costs you less than the dread suggests it will.', 'The party is tonight. You said yes weeks ago when it was abstract, and now it is real, and you have spent the afternoon constructing reasons not to go. You picture standing alone holding a drink. You picture running out of things to say. You picture everyone else finding this easy.

Here is a plan. Not for becoming a person who loves parties, but for getting through this one with less cost than the dread promises.

Before you go

Decide how long you will stay. An hour is a real amount of time and a complete appearance. Knowing there is an end makes the whole thing possible, and you can always stay longer if it turns out fine.

Eat something first. A lot of social anxiety is worse on an empty stomach, and it keeps you from relying on a drink to take the edge off, which tends to cost more later.

Ask the host one useful question: who else is coming, and is there anything you can help with. Knowing one name changes the room. Having a job, taking coats, refilling something, manning the grill, is the single most effective trick there is, because it gives you a reason to move and a reason to talk to everyone.

Arrive early rather than late. This feels wrong and it is right. Walking into a room of six people is far easier than walking into a room of forty, and if you are early you become one of the people already there.

Getting in the door

The hardest moment is the first three minutes. Have a plan for them. Find the host and say hello. Then find the kitchen, or the drinks, or anything with a task attached.

If you feel the physical spike, fast heart, hot face, the urge to leave, give it a minute. That spike almost always peaks and falls within a few minutes of arriving. Try putting your feet flat on the floor and naming five things you can see. It sounds too simple. It pulls your attention out of your own body and into the room, which is exactly what is needed.

Once you are in

Ask questions. This is the whole of it, really. People enjoy talking about themselves and will remember you as good company if you let them. How do you know the host. What are you working on. Where were you before this. Have you seen anything good lately.

Then listen to the answer and ask one more thing about it. Most conversations fail because nobody follows up, not because nobody was clever.

If you run dry, you can say so cheerfully: I am terrible at parties, tell me something interesting. Most people find this a relief.

Approach pairs and small groups rather than the big loud one, and look for the other person standing alone. They are not judging you. They are hoping someone comes over.

Give yourself exits

You are allowed to leave a conversation. I am going to get a drink, it was good to meet you. Nobody is offended; people do this constantly.

You are also allowed to take a break. The bathroom, the porch, a walk to the car. Two minutes of quiet resets a lot. This is not failing at the party. It is how many people get through any long social event.

When your mind starts narrating

At some point you will catch yourself running commentary: that was a stupid thing to say, they are bored, everyone can tell. Notice that this is the anxiety talking and not a report from the room. Nobody at a party is analyzing you; they are busy being self-conscious themselves.

If you can, put your attention back on the other person. Curiosity and self-consciousness cannot occupy the same space, and the easiest way out of your own head is genuine interest in someone else''s.

Leaving

Go when you said you would, or when you have had enough. Say goodbye to the host and go. You do not need a reason, and you do not need to apologize for leaving a party.

Afterward

This is the part that catches people. The replaying, sometimes for days: what you said, how it landed, the moment you misheard someone. Know it is coming and treat it as the last stretch rather than a verdict.

When it starts, try naming it: this is the post-party replay, it always happens, and it is never accurate. Then do something absorbing. It fades faster when it is not fed.

And notice the part that went fine, because your memory will not offer it unprompted. You went. You talked to people. The catastrophe you rehearsed did not occur.

When it is bigger than nerves

If dread of social events is shaping your life, if you turn down most invitations, if the aftermath eats days, or if you can only face people with a drink in hand, that is worth taking seriously. Social anxiety is common and it responds very well to treatment, usually in a matter of months rather than years. A therapist can help you work through it in steps that are actually manageable. You should not have to spend the afternoon before every gathering talking yourself into it.', array['Social Anxiety', 'Grounding']::text[], 0, '2026-09-21T14:00:00+00:00'::timestamptz),
  ('when-your-child-is-being-left-out', 'When Your Child Is Being Left Out', 'They were not invited, again. Watching your child be excluded hurts in a way few things do. How to help without making it worse, and what to do when it crosses into bullying.', 'Your child mentions it in passing, or you see the photos, or they come home quiet and you have to pry it out. Everyone was invited except them. They were left out of the game again. The friend they talk about constantly has a different best friend now.

Few things hurt a parent like this. And most parents'' first instinct, fix it immediately, makes it harder. Here is what tends to help.

Feel your own reaction first, elsewhere

You will feel fury, grief, and a strong urge to call someone''s parents. That is love, and it is also exactly what your child does not need in the first five minutes.

Children read a parent''s face before they hear the words. If your reaction is enormous, they learn that this is a catastrophe, and that telling you costs them a scene. Many kids stop mentioning it entirely for that reason. Have your reaction later, with another adult.

Listen without rescuing

Start with almost nothing. That sounds hard. Tell me what happened. Then stop talking.

Resist the pull to explain it away, to say the other kids are jealous, to promise it will not happen again, or to jump to solutions. What your child needs first is the experience of being heard by someone who did not panic. Their feeling is the thing to attend to, not the situation.

A useful phrase: that makes sense, I would feel terrible too. It sounds like doing nothing. It is the foundation for everything that comes after.

Do not rush to reassure

It is hard to hear your child say nobody likes me and not immediately argue. But arguing, of course they do, what about so-and-so, tells them they are wrong about their own experience, and the conversation closes.

Try staying with it instead. It feels like nobody wants you around right now. That sounds really lonely. Being understood does more for a child''s sense of worth than being contradicted.

Then, later, help them get accurate

Once the feeling has been heard, and usually not the same evening, you can gently widen the picture. Who did you sit with at lunch this week? Who did you play with on Tuesday? Children in pain generalize hard, and one exclusion becomes nobody ever. Helping them notice the people who are there is different from telling them they are wrong to be sad.

Help with skills, carefully

Sometimes exclusion is partly about something learnable: joining a game rather than waiting to be asked, reading when a friend needs space, not always directing the play. If you can see something like that, coach it gently and later, never in the moment of pain, and never in a way that sounds like this is your fault.

Practice can help: what could you say to get into the game, let us try it. Role-play feels silly and works well with younger kids.

Build friendship outside that group

The most useful thing many parents do is widen the field. One-on-one time, which is where friendships actually form, works far better than group settings. Invite one child over. Help arrange the meet-up. And look for a context outside school entirely, a club, a team, a class, where your child can be a different version of themselves with people who do not already have a script for them.

One steady friend is protective in a way that popularity is not. That is the goal, not a full invitation list.

Be careful about calling other parents

Sometimes it helps, especially with younger children and a parent you know well, and especially if it is a genuine oversight. Often it backfires, because the child finds out, and it confirms both that they cannot handle their own life and that their parent thinks the situation is dire.

With older kids, ask first: do you want me to say something? Respect the answer. Not being invited to a party is, painful as it is, within a child''s ordinary social world, and children are allowed to choose their own friends.

Know when it is not ordinary exclusion

There is a line between not being included and being targeted. If it is repeated, deliberate, involves cruelty, spreading things about them, or online harassment, that is bullying and it is not your child''s to manage alone. That is when you go to the school, in writing, with specifics and dates, and keep going until something changes. Be clear with your child that this is not them failing to cope; it is adults doing their job.

Watch for the signs that it is going deeper

Pay attention if your child stops wanting to go to school, loses interest in things they loved, has stomachaches or headaches most mornings, is sleeping badly, or starts saying things about themselves that are very harsh. If they ever say anything about not wanting to be here, take it seriously immediately and ask them directly; asking does not put the idea in their head. In the US you can call or text 988 at any time.

When to get help

If the loneliness has lasted months, if your child''s sense of themselves is taking real damage, or if you can see anxiety or low mood settling in, talk to their doctor or to a child therapist, and loop in the school counselor, who often knows the social landscape better than anyone. Being left out is one of childhood''s ordinary heartbreaks, and it is also something a child should not have to carry without help. Neither should you.', array['Parenting', 'Loneliness']::text[], 0, '2026-09-21T14:00:00+00:00'::timestamptz),
  ('coming-back-when-you-feel-far-away', 'Coming Back When You Feel Far Away', 'The room goes flat, sounds come from a distance, and you feel like you are watching yourself from outside. What that spacing-out is, why it happens, and how to come back.', 'It comes on without warning. The room seems slightly unreal, like a set. Your own voice sounds like it is coming from somewhere else. Your hands look like they belong to someone else. You are still functioning, answering questions, driving, sitting in the meeting, but you are not quite in it, and part of you is watching from a few feet behind.

Afterward you may not be able to explain it, and you may not have told anyone, because it sounds alarming to describe. It is a great deal more common than most people realize, and there are practical things that help.

What it is

This is usually some form of dissociation, which is the mind''s way of turning down the volume when something is too much. It exists on a wide range, from the everyday version, driving home with no memory of the drive, to the more disorienting version described above.

It tends to show up when a system is overwhelmed: under high stress, after something frightening, during conflict, when exhausted, or when something in the present quietly resembles something difficult from the past. For people who have been through frightening or unsafe experiences, it may have been an essential protection once, a way of not being fully present for something unbearable. The mechanism can stay available long after it is needed.

It can also happen with panic, with very poor sleep, with some medical conditions, and with some substances. That is worth mentioning to a doctor at some point, to rule things out.

It is frightening and it is not dangerous

The most common fear people have during these episodes is that they are losing their mind or that this will not stop. Neither is what is happening. It is a temporary state, it passes, and being frightened of it tends to make it last longer. Knowing what it is takes away a surprising amount of its power.

Coming back through the senses

Thinking your way out does not work well, because thinking is the part that has gone hazy. Sensation works better. The aim is strong, specific physical input.

Cold is the most reliable. Cold water on your face or wrists, a cold drink, an ice cube in your hand, stepping outside.

Pressure helps. Press your feet hard into the floor. Press your palms together. Push against a wall. Wrap yourself in something heavy.

Texture helps. Something rough or ridged in your pocket that you can rub between your fingers, keys, a stone, a piece of fabric.

Strong taste or smell helps. Something sour or minty, a strong scent you keep for this.

Orient yourself to the room

Say, out loud if you can, where you are and when. I am in my kitchen. It is Monday afternoon. I am thirty-four years old and it is 2026. This sounds strange and it directly counters the part of the state that has lost its anchor in the present.

Then name what is around you. Five things you can see. Four you can hear. Three you can touch. Move your eyes deliberately around the room and let them land on ordinary objects.

Move

Stand up. Walk. Stamp your feet. Shake out your hands. Stretch. Movement reconnects you to a body that has gone distant, and it does it faster than sitting still and waiting.

Find your pattern

After it passes, when you can think again, note down what was happening beforehand. Over time most people find a pattern: certain conversations, certain places, being very tired, a particular kind of pressure, a specific person. Knowing the triggers gives you warning, and warning means you can use the tools early, when they work best.

Make a card

Because the state itself makes it hard to remember what to do, write your three most effective things on a card or a note in your phone. Cold water. Feet on the floor. Say the date out loud. Then you do not have to think, you just follow the list.

Take care of the ground conditions

These episodes get more frequent when you are exhausted, undernourished, or under sustained stress. Sleep, regular food, and something that discharges tension are not a cure, but they meaningfully change how often this happens.

If it gets very dark

Feeling detached from yourself for long stretches can be deeply distressing, and for some people it comes with a sense that nothing is real or that it does not matter what happens to them. If you have thoughts of harming yourself, please reach out today. In the US you can call or text 988 at any time.

When to get help

Please talk to a doctor or a therapist if this happens often, if you lose time or find yourself somewhere without knowing how you got there, if it started after something frightening, or if it is interfering with work, driving, or caring for people who depend on you. A doctor can rule out physical causes. A therapist who works with trauma can help with the reason it is happening, not just the moments, and that is what makes it fade rather than just become manageable. This is a known, understood thing, and you do not have to keep handling it privately.', array['Grounding', 'Trauma']::text[], 0, '2026-09-21T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
