-- Five articles published 2026-09-29. Generated by:
--   python3 tools/articles_sql.py --since 2026-09-29
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('when-you-stop-enjoying-things-you-used-to-love', 'When You Stop Enjoying Things You Used to Love', 'The music sounds flat, the hobby feels like a chore, and seeing friends is one more task. What it means when enjoyment goes missing, and how it usually comes back.', 'You put on the album that used to do something to you. It plays. You hear it. Nothing happens.

It is not that you are sad about the music. It is that the part of you that responded to it seems to have gone quiet. The same thing has happened to the hobby, the show you were looking forward to, the food you used to love, and the friend whose messages now feel like admin.

This is one of the most disorienting experiences there is, partly because it is so hard to describe. You are not in pain. You are just not getting anything back.

What is actually missing

It helps to separate two things that usually travel together: wanting and liking.

Wanting is the pull that gets you to start something. Liking is the reward when you do. When enjoyment goes flat, often both are affected, but not equally. Many people find the wanting goes first: they still enjoy something once they are ten minutes into it, but nothing makes them begin.

That distinction matters more than it sounds, because it tells you not to trust the forecast. If you wait until you want to do something, you may wait a very long time. The wanting tends to return after the doing, not before it.

Why the usual advice backfires

The obvious response is to do more of what you love. Then you do it, feel nothing, and now you have evidence that even the good things are ruined.

So aim lower and aim wider. Rather than trying to recreate a strong pleasure, look for the faintest signal: a cup of something warm, ten minutes of sun, a shower, a song you used to like on in the background while you do something else. You are not trying to feel joy. You are checking whether anything registers at all, even slightly.

And pay attention on a scale of small numbers. Not "did I enjoy that" but "was that a two or a three out of ten". People who are flat often dismiss a two, and a two is the thing that grows.

Do it first, judge it later

A practical rule for a flat stretch: decide by the schedule, not the feeling.

Pick a small number of ordinary things and put them in the day whether or not you feel like them. Walk before lunch. Message one person on Tuesdays. Cook one thing on Sunday. The point is not to enjoy them on cue. The point is that activity, done regularly, is one of the few things that reliably brings the responsiveness back over weeks.

It helps to notice what you actually did rather than how it felt. A short note at the end of the day, just the facts: walked, called my sister, sat outside. On a flat week that list is the evidence that you are doing something, which your own memory will not give you credit for.

Beware the shrinking circle

There is a loop here that is worth knowing about because it is so easy to fall into.

Nothing feels rewarding, so you stop doing things. Doing fewer things means fewer chances for anything to land. Fewer chances means more flatness, which makes stopping more things feel reasonable. Within a few weeks the week has emptied out and there is very little left that could possibly lift anything.

Cancelling plans is the most common first step. So is dropping the thing you did with other people: the class, the team, the standing coffee. Those are worth protecting even when they feel pointless, because they are much harder to restart than to keep.

Being honest with people about it

This is hard to explain to people who care about you, and the explanation that lands is usually plain: I am not upset with you, things just are not landing for me at the moment, and I would still like to come.

That sentence does two useful things. It stops people reading your flatness as coldness. And it leaves the door open for you to show up without pretending to be enthusiastic, which is often the price that keeps people home.

The other thing worth telling one person: I am finding it hard to want anything. Said out loud once, it is much less frightening than it is at three in the morning.

What else can flatten you out

Losing enjoyment is not always what it looks like. Long stretches of exhaustion do it. So do burnout, grief, chronic pain, a thyroid problem, some medications, heavy drinking, and weeks of broken sleep.

That is worth knowing because some of these are quickly checkable. If this arrived alongside being tired all the time, or after a medication change, it is worth a conversation with a doctor rather than months of trying harder.

When to get help with it

If flatness has lasted more than a couple of weeks, if it is shrinking your life, or if it comes with low mood, guilt, or a sense that there is no point, that is worth taking to someone. This is one of the most treatable experiences in mental health care, and it usually improves with the right support rather than with more effort on your own.

Please talk to a doctor or a therapist, especially if you have found yourself thinking that things would be easier if you were not here. In the US you can call or text 988 at any time.', array['Depression', 'Self-Care']::text[], 0, '2026-09-29T14:00:00+00:00'::timestamptz),
  ('being-strong-enough-for-your-own-life', 'Being Strong Enough for Your Own Life', 'Not strong for a gym, strong for groceries, stairs and getting off the floor. Why everyday strength matters more than fitness goals, and how to build it in small amounts.', 'There is a kind of strength that has nothing to do with how you look or what you can lift in a gym. It is the strength that decides whether the stairs to your apartment are nothing or something, whether you can carry both bags in one trip, and whether getting up off the floor is easy or a small project.

Most fitness advice skips straight past this. It talks about programs and goals and getting back in shape, and a lot of people hear all of it as an invitation to something they are not going to do.

So here is a smaller, more useful question: what does your actual life ask your body to do, and can it do those things comfortably?

The short list of things worth being able to do

Look at an ordinary week and you will find the same handful of movements over and over.

Standing up from a low chair without using your hands. Carrying something heavy for a hundred yards. Going up two flights without stopping. Reaching something on a high shelf. Getting down to the floor and back up. Holding a child, a bag of groceries, or a suitcase on one side without your back complaining.

That is most of it. Nothing on that list requires a gym, a plan, or a change of identity. But each one gets noticeably harder if it is never asked for, and noticeably easier within weeks of being practiced a little.

Strength is the one that fades quietly

Most people notice when their stamina drops, because being out of breath is obvious. Strength goes without announcing itself: you just start avoiding things.

You take the elevator. You make two trips. You ask someone else to reach it. You sit on chairs with arms. None of these feel like a decision, and each one removes one of the few times in the week your body would have been asked to do something.

Which means the first and best intervention is often not exercise at all. It is to stop outsourcing the small efforts. Carry the thing. Take the stairs. Stand up without pushing off. That is real training, and it costs no extra time.

The amounts are smaller than you think

If you want to add something deliberate, the useful doses are almost comically short.

Ten slow stands out of a chair. A minute of holding a heavy bag in each hand and walking the hallway. Five push-ups against a counter. Standing on one leg while the kettle boils. Two or three of those, a few days a week, is enough to move the needle for most people who are currently doing none of it.

Two things make it work. Do it often enough that your body treats it as normal, and make it a bit hard by the last couple of repetitions. Easy movement is good for you in other ways, but strength specifically needs a little effort near the end.

Balance belongs in the same conversation

Balance is the quiet twin of strength, and it responds fast to almost no work.

Stand on one foot while you brush your teeth, one leg per side. Walk heel to toe along a line in the kitchen. Get up and down off the floor a couple of times a week just to keep the pattern familiar.

None of this looks like anything. All of it is the difference between a stumble that you correct and a stumble that becomes a fall, and that difference matters more with every decade.

If you are starting from very little

Start with the version you can do today rather than the version you think should count.

Stand up from a higher chair before a lower one. Push against a wall before a counter. Carry one bag before two. Two repetitions is a start, and the second week will not feel like the first.

Soreness a day or two later is normal and usually a sign you asked for something new. Sharp pain during a movement is not; that is a signal to stop and to ask someone about it rather than push through.

What tends to change first

People expect to notice their body looking different. What they usually notice first is smaller and better: the stairs stop registering, the groceries stop being a decision, they sleep a bit more heavily, and their back complains less at the end of a day of sitting.

That is the whole point. Not a fitter version of you in six months, but a week that asks less of you because your body has more room in it.

When to check with someone first

If you have heart or lung trouble, a recent injury or surgery, a problem with dizziness, a joint that is already painful, or you are pregnant, it is worth a short conversation with a doctor or a physical therapist before adding anything new. They can tell you which movements to start with, which to modify, and what pain to take seriously.

And if you are avoiding movement because your body has felt unsafe or unpredictable to you, or because exercise has been tied up with shame or with a hard history around food and weight, that is worth taking to a therapist alongside anything physical. Getting stronger goes much better when it is not a punishment.', array['Movement', 'Body']::text[], 0, '2026-09-29T14:00:00+00:00'::timestamptz),
  ('living-through-a-long-wait', 'Living Through a Long Wait', 'Test results, a hiring decision, a court date, a visa: waiting for news you cannot influence has its own kind of difficulty. How to hold a life together while the answer is pending.', 'The test was on Monday. The results come next Thursday. Between those two points you have nine days, and no amount of thinking will move the answer by a single hour.

Waiting like this is its own experience, different from the thing you are waiting for. A diagnosis, a hiring decision, a court date, a visa, a loan, a call about someone in hospital. What makes it hard is not only the stakes but the combination: it matters enormously, and there is nothing to do.

Why an empty wait is so tiring

Most stress comes with an action attached. This one does not, and your mind does not handle that well.

So it substitutes activity for action. It rehearses both outcomes. It searches for information that does not exist yet. It reruns the appointment looking for clues in someone''s tone of voice. It plans for a version of the future it cannot yet see.

All of that feels like preparing, which is why it is so hard to stop. But rehearsing an outcome does not prepare you for it; it just makes you live it repeatedly at full volume before you know whether it is real.

Decide what you are going to do with the not-knowing

The task in a wait is not to stop feeling uncertain. It is to stop spending your days as though the answer is already in.

One question helps more than any other: is there anything I can actually do about this today? Usually the honest answer is no, or it is one small thing: chase the appointment, send the document, ask when to expect the call.

Do that one thing early, and then treat the rest of the day as yours. Not because the wait does not matter, but because the alternative is handing over nine days to something that will take the same nine days either way.

Give the worry a time and a place

Trying not to think about it fails, and you have probably already discovered that. Deliberately corralling it works better.

Pick a time, fifteen minutes, same slot each day. That is when you are allowed to think about it properly: what you fear, what you would do, what you need to find out. When it arrives outside that window, note it and tell yourself it will get its turn at six.

This is not a trick to make the thoughts go away. It is a way to stop them being in charge of every hour, and most people find the worry loses some of its urgency when it has an appointment.

Do the obvious, unglamorous things

Waiting is physically taxing, and the basics matter more than usual.

Keep the shape of your days: get up at the normal time, eat at normal times, go outside once. Keep the plans you had, even at half strength; cancelling everything makes the wait the only thing in the room. Move your body, because unspent stress goes somewhere and movement is the cheapest place to put it. Protect sleep, and if your mind spins at night, get up for ten minutes rather than lying there arguing with it.

Be careful with searching. Looking up the thing you are waiting on gives a moment of relief and then more to fear, and it never delivers the one piece of information you want, which is your answer.

Plan one step, not two futures

There is a useful middle between refusing to think about it and living in the bad outcome.

Make one short, specific plan: if the news is bad, who I will call, what I will ask, and what I will not decide that day. Write it down. Then close it.

That plan is usually enough to satisfy the part of you that insists on being ready, and it takes far less out of you than imagining the whole of a life you may never have to live.

What to tell people

Decide in advance who you are telling and what you want from them, because being asked about it repeatedly is its own strain.

Some people want company and no questions. Some want to be distracted entirely. Both are fine, and both are easier to get if you say which one you are: I do not want to talk about it, I would like to go for a walk, is a complete and reasonable request.

If it is a wait other people are also inside, say your version out loud rather than assuming you are handling it the same way.

When the wait gets longer

Sometimes the date moves, or there is no date at all. That is harder, and it needs a different setting.

Set your own checkpoints instead: a day each week when you chase for news and update your plan, and the rest of the week left alone. Open-ended waits swallow people who keep checking hourly, and the weekly version is survivable for months.

When to get help with it

If the waiting has stopped you eating or sleeping, if you cannot work or be with people, if panic is arriving regularly, or if the wait is about something that would change your life completely, there is no reason to do it alone. A therapist can help with the spinning, and a doctor can help if sleep or panic has become the bigger problem. Many hospitals and clinics also have counselors attached to the service you are waiting on, and asking whether one is available is a perfectly ordinary request.', array['Resilience', 'Stress']::text[], 0, '2026-09-29T14:00:00+00:00'::timestamptz),
  ('the-apology-you-never-gave', 'The Apology You Never Gave', 'Something you did years ago still makes you wince. Whether to reach out, what to say if you do, and what to do with the regret when contact is not possible or wise.', 'There is something you did. It might be years old. You do not think about it often, but it arrives sometimes, unannounced, usually at night, and for a few seconds you feel it in your chest as though it happened this week.

You never said anything at the time. Now the moment feels long gone, and reaching out seems either self-indulgent or likely to make things worse. So it sits there.

Old regret behaves differently from fresh guilt. It is quieter, more sunken, and it tends to have become part of how you see yourself rather than something you did.

Guilt is about the act, shame is about you

Worth separating, because they need different things.

Guilt says: that was a bad thing to do. It is uncomfortable and useful, and it points at an action, which means it can be addressed.

Shame says: I am the kind of person who does that. It points at you, and it is much less useful, because there is no repair for being a person. Shame also makes contact harder, since it turns an apology into an admission about your whole character rather than a sentence about one afternoon.

If the thing you carry has become a verdict on you rather than a memory of something you did, that is the first thing to unpick, and it is often easier with help than alone.

Who the apology is for

This question decides most of what follows: are you reaching out to repair something for them, or to relieve something in you?

Both are human. But they lead to very different messages. An apology aimed at your own relief tends to be long, to explain itself, to ask for reassurance, and to put the other person in charge of making you feel better. An apology aimed at repair is short, specific, takes responsibility, and asks for nothing.

So before you write anything, sit with the possibility that they may not reply, or may reply coolly, and that the apology would still have been worth giving. If that idea is unbearable, you are probably not ready to send it yet.

When reaching out is not the right move

Sometimes the kindest thing is not to make contact.

If the person has asked for no contact, respect that; an apology that overrides someone''s stated boundary is not an apology. If getting in touch would reopen something they have put down, or expose them to something they have moved past, think hard. If there is any question of your contact being frightening or unsafe for them, do not, and talk to a professional about how to handle what you are carrying instead.

Not reaching out does not mean doing nothing. Regret can be answered by how you behave now: repairing the same pattern where it currently lives, being the person you wish you had been to somebody in front of you today, or making something right in a way that does not involve the person you hurt.

What a good apology actually contains

If you do reach out, keep it plain and keep it short. Three parts do almost all the work.

Name the thing specifically, without softening it. Not "I know things were difficult between us" but "I told people something you told me in confidence."

Say the effect, if you can see it. "I imagine that made it hard to trust me, and I am sorry."

Then stop. No explanation of what you were going through, no request to be told it is fine, no mention of how long you have felt bad about it. If they want the context they will ask, and offering it unasked turns an apology into a defense.

One more line is often welcome: tell them they do not need to reply.

What to expect back

Prepare for a range. Warmth, sometimes. Silence, often. Occasionally anger, which is not a sign you should not have written; it may be the first chance they have had to say so.

Do not press. One message, and then leave it with them. An apology followed by follow-up messages asking whether they got it becomes something you are doing to them.

And if they do reply with what it was like for them, the job is to listen without repairing yourself. Hearing it without arguing is most of the amends.

If the person is gone

Sometimes there is no one to write to. They have died, or vanished, or you never knew their name.

The regret still deserves somewhere to go. Write the letter you would have sent and keep it or burn it. Tell one person the whole thing out loud. Do something in their direction that costs you a little. These are not substitutes for an apology; they are how people live with the ones they cannot give.

When it will not put itself down

Some old regret sits heavier than this. If it visits most weeks, if it shapes what you think you deserve, if you are still paying for it in how you treat yourself, or if the thing itself was serious enough that you have never said it out loud to anyone, that is worth taking to a therapist. It is very common ground in therapy, and saying it to one person who does not flinch often does more than a decade of carrying it quietly.', array['Shame', 'Relationships']::text[], 0, '2026-09-29T14:00:00+00:00'::timestamptz),
  ('giving-your-worries-an-appointment', 'Giving Your Worries an Appointment', 'Trying not to worry does not work. Setting aside fifteen minutes a day to worry on purpose does, surprisingly well. How to run a worry window and what to do inside it.', 'Worry does not respond to being told to stop. You have probably tested this thoroughly: the harder you push a worry away, the more often it comes back, and now you have two problems, the worry and the effort of suppressing it.

There is an approach that works better, and it sounds odd the first time you hear it. Instead of trying to worry less, you give worry a fixed appointment and keep the rest of the day out of its reach.

The idea in one paragraph

Pick a time and a length: fifteen minutes, mid-evening, same slot each day. During that window you worry deliberately and thoroughly. Outside it, when a worry arrives, you note it down and tell yourself it will be dealt with at the appointment.

That is the whole method. It comes from cognitive behavioral therapy, and it is one of the more reliable things you can do about a mind that runs all day.

Why it works when suppression does not

Pushing a thought away has a cost: some part of your attention has to keep watch for the thought in order to block it, which keeps it live.

Postponing is different. You are not arguing with the worry or denying it. You are agreeing to take it seriously, later. That turns out to be enough for most worries to loosen their hold in the moment, because the thing they are demanding is attention, and you have promised it rather than refused it.

There is a second effect that people notice within a week or two. By the time the appointment arrives, a good number of the worries have expired. They looked urgent at eleven in the morning and are uninteresting at eight at night, which is useful information about what worry actually is.

How to set it up

Choose a time that is not just before bed, because you do not want to hand your worries the hour when you are trying to sleep. Early evening works well for most people.

Choose a place that is not your bed or the sofa where you relax. A kitchen table is ideal. You want the worrying attached to a spot you can get up and leave.

Set a timer for fifteen minutes. When it goes, you stop, even mid-thought. Stopping on time is part of what makes the method credible to yourself.

Keep a short list during the day, on paper or your phone: three or four words per worry, just enough to recognize it later. Writing it down is what makes postponing possible; trying to remember it keeps it in the room.

What to do inside the window

Do not use the fifteen minutes to spin. Use them to sort.

Take each worry on your list and ask one question: is this a problem or a what-if? A problem has a next action, even a small one. A what-if does not; it is about a future you cannot influence today.

For a problem, write the next action and when you will do it. That is all. You are not solving the whole thing, just naming the next step and giving it a slot.

For a what-if, the job is different and less satisfying. You let it be there without solving it. Say the feared thing plainly to yourself, including the part you usually avoid, and notice that you are still sitting at a table. Repeated deliberately, a feared thought loses some of its charge; chased and pushed away, it keeps it.

When the timer goes, stand up, leave the table, and do something with your hands for a few minutes. The transition matters.

What usually goes wrong

Three things, all fixable.

You skip the window when you feel fine, and then the postponing stops working, because your promise has been broken. Keep the appointment even on quiet days, and finish early if there is nothing in the list.

You let the worry negotiate. It says this one is different, this one is urgent. Unless there is an action you can take in the next hour, it is not urgent; it is loud. Write it down and let it wait.

You use the window to reassure yourself, checking and rechecking until you feel better. That is the rechecking loop wearing a different hat, and it will keep you exactly where you are. The aim is sorting and sitting with, not settling.

Give it two weeks before you judge it

The first few days feel clumsy and you will forget often. That is normal, and the method survives being done imperfectly.

What tends to change first is not the amount of worry but its timing. The day gets quieter before the total goes down, and a quieter day is worth a great deal on its own.

When it is not enough

Worry that has taken over most of your day, that comes with a knot you never lose, that has you avoiding things, or that keeps you awake most nights is worth treating properly rather than managing alone. This kind of worry responds well to therapy, often in a fairly small number of sessions, and a doctor or a therapist is the right place to start. Bring the list you have been keeping; it is more useful than trying to describe it from memory.', array['CBT', 'Worry']::text[], 0, '2026-09-29T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
