-- Five articles published 2026-09-09. Generated by:
--   python3 tools/articles_sql.py --since 2026-09-09
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('why-your-brain-keeps-replaying-that-conversation', 'Why Your Brain Keeps Replaying That Conversation', 'Rumination feels like problem-solving but works like a loop. Here is what keeps the replay going, and four small moves that help it wind down.', 'You said something slightly off at lunch. Nobody seemed to notice. It is now eleven at night and you have replayed the moment forty times, each time with a better line you did not say. If this sounds familiar, you are not broken and you are not unusually self-absorbed. You are ruminating, and rumination is one of the most common habits a mind can fall into.

What rumination actually is

Rumination is repetitive thinking about something upsetting that does not move you anywhere new. It borrows the costume of problem-solving. It feels like you are working on the issue. But real problem-solving ends with a plan or a decision, and rumination ends only when you are too tired to keep going. The tell is simple: after twenty minutes of replay, do you know anything you did not know before? Usually not.

The mind replays the conversation because it is trying to protect you. Somewhere in there is a question it wants answered: did I damage the relationship, did I look foolish, will there be consequences? Because the question has no clean answer, the mind keeps circling it, the way you might keep tapping a phone that will not turn on.

Why it feels so convincing

Three things make the loop sticky. The first is that replaying an event brings back the feeling of the event, and a feeling in the body reads as evidence. If you feel embarrassed while remembering, the mind concludes the moment must have been embarrassing. The second is that the replay is never accurate. Memory edits. Each pass adds a little drama, drops a little context, and centers you a little more, until you are the only person at the table and everyone else is an audience. The third is that the loop is rewarded. Every so often, ruminating produces a plan, such as sending a follow-up text, and that occasional payoff keeps the habit alive, the same way a slot machine keeps people pulling the lever.

The loop is not the same as reflection

Reflection is useful. It asks, what happened, what did I do, what would I do next time, and then it stops. Rumination asks, why am I like this, why does this always happen, what is wrong with me, and never stops because those questions cannot be answered from inside the loop. If your thinking is producing verbs, things you could actually do, it is reflection. If it is producing adjectives about you, it is rumination.

Four moves that help

Name it. The moment you notice the replay, say to yourself, in words, I am ruminating. This sounds too small to matter. It is not. Naming the process pulls you one step back from it, so you are watching the loop instead of living inside it.

Give it a time and a place. Tell yourself you will think about the conversation for ten minutes at four o''clock, then set a timer. The mind loops partly because it is afraid that if it stops, the thing will be forgotten and go unhandled. A scheduled slot answers that fear. Most people find that when four o''clock arrives, the urgency has already drained out of it.

Change the channel with your body. Rumination is a mental activity, and it is hard to out-think it. It is easier to interrupt it physically. Stand up, walk to another room, run cold water over your wrists, or do something that needs both hands and a little attention, like cooking or folding laundry. You are not distracting yourself from a real problem. You are stepping out of a loop that was never going to solve one.

Ask the other-person question. Picture a friend telling you the story as if it happened to them. What would you say to them? Almost everyone, asked this, lands somewhere near: it was a small thing, nobody is thinking about it, and if it did matter you could just say something tomorrow. That answer is available to you too. The loop makes it hard to hear.

When to expect more of it

Rumination gets louder when you are tired, hungry, lonely, or already anxious about something else. Late evening is its favorite hour, because there is nothing left to compete with it. If the replays cluster at night, the fix may be less about the thoughts and more about getting to bed before the mind has an empty stage.

If the replaying is constant, spreads to most things, or comes with a low mood that will not lift, it is worth talking with a therapist. Rumination is a habit, and habits respond well to practice, but they respond faster with someone in your corner.', array['Worry', 'Thinking Traps']::text[], 0, '2026-09-09T14:00:00+00:00'::timestamptz),
  ('when-sleep-hygiene-is-not-enough', 'When Sleep Hygiene Is Not Enough', 'You have cut the caffeine and dimmed the screens and you are still awake at 2 am. Here is what the sleep advice usually leaves out, and what to try instead.', 'Everyone who has struggled to sleep has heard the list. No caffeine after noon. No screens in bed. Keep the room cool and dark. Go to bed at the same time every night. It is good advice, and for many people it is enough. If you are reading this, it probably was not enough for you. Here is why, and what tends to help when the basics are already in place.

Sleep hygiene fixes the room, not the relationship

The list treats sleep as a matter of conditions: get the environment right and sleep will follow. That works when the problem is the environment. It does not work when the problem is that bed has become a place where you lie awake feeling frustrated. After enough nights like that, the bed itself becomes a cue for wakefulness, the way the smell of a dentist''s office can make your jaw tighten. No amount of blackout curtain fixes a learned association.

The first thing to change, then, is what you do when you are not sleeping. If you have been awake for what feels like twenty minutes and you are alert and annoyed, get up. Go to another room, keep the lights low, and do something quiet and slightly boring until you feel drowsy. Then go back. It feels counterintuitive to leave the bed when the whole point is to be in it, but you are teaching your body that bed is for sleeping, not for lying awake.

Trying harder makes it worse

Sleep is one of the few things that retreats when you chase it. The effort of trying to fall asleep is itself a form of arousal, and arousal is the opposite of sleep. People who sleep well are not doing anything. They are simply not preventing it.

If you notice yourself straining, try the reverse. Lie comfortably, keep your eyes gently open in the dark, and quietly try to stay awake a little longer. This is an old trick and a surprisingly reliable one. It takes the pressure off, and without pressure, sleep tends to show up on its own.

The 2 am mind is not a fair witness

Waking in the night is normal. Most adults surface briefly several times and do not remember it. What turns a brief surfacing into an hour of wakefulness is what the mind does with it. At 2 am, small worries look enormous, and the arithmetic starts: if I fall asleep now I will get four hours, if I do not I will be useless tomorrow. That calculation is itself a stimulant.

Two things help here. The first is to have decided, in daylight, that a bad night is survivable. It is. You have had them before, and you got through the next day. The second is to give the worries somewhere to go. A notepad by the bed, and a rule that anything written down is handled until morning, saves a lot of people a lot of hours.

The daytime half of the problem

Sleep is regulated by two systems: a clock, which is set mostly by light, and a pressure, which builds the longer you are awake. Sleep hygiene mostly addresses the clock. The pressure gets ignored, and it is often the real issue.

Pressure builds with wakefulness and activity and drains with rest, including the rest you take without meaning to. A long lie-in after a bad night, a nap on the couch, an evening spent half-asleep in front of the television: each of these lets pressure out before bedtime, so there is less of it to carry you under. The fix is unglamorous. Get up at the same time every day, including after a bad night, and stay properly awake through the day. Morning light outdoors, even ten minutes, sets the clock more firmly than anything you do at night.

If you are spending nine hours in bed to get six hours of sleep, it can also help to shorten the window. Go to bed later, keep the wake time fixed, and let the pressure build until sleep is fast and solid. Then widen the window slowly. This is the core of the therapy that works best for long-term insomnia, and it is worth doing with a therapist trained in it rather than alone, because the first week is hard.

What to stop doing

Stop checking the clock at night; turn it to face the wall. Stop reading about sleep in bed. Stop treating one bad night as a sign that something has gone wrong. And stop trying. Sleep will come when you get out of its way.

If poor sleep has lasted more than a few months, comes with loud snoring or gasping, or leaves you fighting to stay awake during the day, talk with a doctor. Some sleep problems are medical, and they are very treatable once they are named.', array['Sleep', 'Anxiety']::text[], 0, '2026-09-09T14:00:00+00:00'::timestamptz),
  ('how-to-set-a-boundary-without-starting-a-fight', 'How to Set a Boundary Without Starting a Fight', 'A boundary is a statement about what you will do, not a demand about what someone else must do. That one shift makes most of them easier to say and easier to hear.', 'The word boundary gets used so much that it has started to lose its shape. People say they are setting a boundary when they are issuing an ultimatum, and people say they cannot set boundaries when what they mean is they cannot control other adults. It helps to get precise, because a well-shaped boundary is one of the least confrontational things you can say.

A boundary is about you

Here is the distinction that matters most. A rule tells someone else what to do: stop calling me after nine. A boundary tells someone what you will do: I do not answer calls after nine, so I will call you back in the morning. The first invites an argument, because it is a claim on the other person''s behavior. The second does not need their agreement. It describes your own conduct, which is the one thing you fully control.

This is why boundaries feel less like fights when they are built correctly. You are not asking for permission. You are not negotiating. You are giving information about yourself, calmly, in advance.

Say it before you are angry

Most boundary conversations go wrong because they happen too late. The line has been crossed six times, resentment has built, and the seventh time it comes out as an accusation. By then it sounds like a punishment, and the other person hears the anger rather than the request.

If you can, say it early and in a neutral moment. Not while the thing is happening, and not right after. Something like: I have been thinking about how we handle weekend plans, and I want to tell you something about what works for me. That opening does a lot. It signals that this is about you, that it is considered, and that nobody is in trouble.

Keep it short and leave out the case

There is a strong pull, when saying something uncomfortable, to justify it at length. We explain, we cite history, we make sure the other person understands why. The longer the explanation, the more it sounds like a debate, and debates invite counterarguments. A boundary is not a proposal to be voted on.

One sentence for the boundary, one sentence for what you will do about it, is usually enough. I am not able to lend money anymore. If you are in a tight spot, I am happy to help you look at other options. Then stop talking. The silence that follows is not a gap you need to fill.

Expect pushback and do not take the bait

When a boundary is new, the people around you will often test it. Not always out of malice. Often out of habit. They are used to the old arrangement, and the new one is inconvenient. The test might be guilt, or a joke, or simply doing the thing again to see what happens.

The answer to a test is not a bigger explanation. It is a calm repeat. I hear that this is frustrating. I am still not able to lend money. Then, and this is the part that makes a boundary real, do what you said you would do. A boundary you do not follow through on is just a preference you mentioned once.

Some people will be upset

This is the part that stops most of us. We would like to set the boundary and also have everyone feel fine about it, and that is not always on offer. Someone''s disappointment is not proof that you did something wrong. It is proof that they wanted something and did not get it, which is a normal thing for adults to survive.

You are allowed to feel bad about their feeling bad and hold the boundary anyway. Both can be true. In fact, that combination, warmth plus firmness, is exactly what makes a boundary land as care rather than rejection.

A few shapes that work

I am going to step away from this conversation when voices get raised, and we can pick it up later.

I will not be available on my phone during dinner, so I will get back to you after.

I do not discuss my weight or my body, so let us talk about something else.

I can stay until eight, and then I need to head home.

Notice that every one of these describes your own action. None of them requires the other person to change. That is what makes them boundaries, and that is what makes them hard to argue with.

If setting even a small boundary brings on strong fear, or the people in your life respond to boundaries with threats or punishment, that is worth talking through with a therapist. Boundaries are a skill, and like any skill they are easier to learn with someone alongside you.', array['Boundaries', 'Communication']::text[], 0, '2026-09-09T14:00:00+00:00'::timestamptz),
  ('stress-or-burnout-how-to-tell-the-difference', 'Stress or Burnout: How to Tell the Difference', 'Stress is too much. Burnout is not enough left. They call for different responses, and treating one like the other is why so many people rest and still feel empty.', 'People use stressed and burned out almost interchangeably, and it is an easy mistake, because both feel bad and both usually involve work. But they are different states, and they call for different responses. Getting the label right is the first step to getting the response right.

Stress is too much

Stress is what happens when demands outrun resources, and it is fundamentally a state of over-engagement. You are working hard, caring a lot, and feeling the strain of it. The signs are mostly physical and mostly about urgency: a tight chest, a racing mind, trouble switching off, snapping at people, waking early with the day already running. Stressed people tend to feel they cannot do enough. They still care about the outcome. If anything, they care too much.

The thing about stress is that it usually gets better when the load lifts. A deadline passes, a weekend arrives, a project ships, and the body settles. It is uncomfortable, but it responds to rest and to reducing what is on the plate.

Burnout is not enough left

Burnout is what can grow out of long, unrelieved stress, and it looks almost like the opposite. Where stress is over-engagement, burnout is disengagement. The three classic markers are exhaustion that a weekend does not touch, a growing cynicism or detachment about the work and the people in it, and a sense that nothing you do makes any difference. Burned-out people do not feel they cannot do enough. They feel there is no point.

The emotional texture is different too. Stress is often anxious and sharp. Burnout is flat, numb, and quietly resentful. Stressed people say I am drowning. Burned-out people say I do not care anymore, and are often unsettled by how true it feels.

Why the distinction matters

If you are stressed and you take a week off, you usually come back better. If you are burned out and you take a week off, you often come back exactly the same, and now you have the added despair of having tried the thing that was supposed to work. That experience, resting and staying empty, is one of the clearest signs that what you have is burnout, not stress.

The reason is that burnout is rarely about the amount of work. It is about the relationship with the work. The usual ingredients are some mix of these: effort that is not recognized, very little control over how the work gets done, values that clash with what you are asked to do, unfairness that goes unaddressed, and isolation from the people you work alongside. None of those is fixed by sleeping in.

What helps with stress

For stress, the classic advice holds. Reduce what you can, delegate what you can, and put real recovery back into the week. Recovery means things that are the opposite of the strain: if the work is mental, move your body; if the work is social, take some solitude; if the work is sitting still, get outside. Protect sleep. Cut the thing that is only there because it always has been. Say no to one thing this week.

What helps with burnout

For burnout, rest still matters, but it is not the treatment. The treatment is changing one of the ingredients. That usually means one or more of these:

Get some control back. Even small choices, such as when you do a task, in what order, or how, restore a sense of agency. Ask for them explicitly.

Find recognition somewhere. If the job will not give it, find a colleague, a mentor, or a friend who sees your work and says so. Being seen is not a luxury; its absence is part of what drains people.

Reconnect with the why. Burnout often begins when the work loses its meaning. Look for the smallest piece of the job that still connects to something you value, and do more of that piece, even if it is a fraction of the day.

Reduce the isolation. Burnout thrives in silence. Talking with someone else in the same situation does more than most people expect, partly because it turns a private failure into a shared circumstance.

Consider whether the ingredient is the job itself. Sometimes the honest answer is that the values clash cannot be resolved from the inside, and the right response is to plan a way out. That is not giving up. It is reading the situation correctly.

If you are not sure which one you have

Ask yourself two questions. Do I still care about this, even if I am overwhelmed by it? And when I rest, do I recover? Two yeses point to stress. Two noes point to burnout. Mixed answers usually mean you are somewhere on the road between them, which is the best time to change direction.

If the exhaustion has spread beyond work, if you have stopped enjoying things you used to enjoy, or if you are having thoughts of not wanting to be here, please talk with a doctor or a therapist. Burnout and depression overlap, and the difference matters for what will help. In the US you can call or text 988 at any time.', array['Stress', 'Burnout', 'Work']::text[], 0, '2026-09-09T14:00:00+00:00'::timestamptz),
  ('five-ways-to-come-back-to-the-present-when-anxiety-spikes', 'Five Ways to Come Back to the Present When Anxiety Spikes', 'Grounding is not about calming down. It is about getting your attention out of the future and back into the room. Five techniques, and why each one works.', 'Anxiety lives in the future. Whatever the specific worry, the shape is always the same: something bad might happen, and the mind runs ahead to meet it. The body follows, bracing for a threat that is not in the room. Grounding is the set of skills for bringing attention back to what is actually here, right now, where things are usually fine.

Grounding is not the same as relaxing. You may not feel calm afterward. The goal is narrower and more reliable: to shift your attention from imagined danger to present reality, so that the body gets a chance to notice that the danger is not here. Calm often follows, but it is a side effect, not the aim.

Here are five techniques. Try each of them once when you are not anxious, so they are familiar when you need them.

1. Name five things

This is the one most people have heard of, and it works. Look around and name, silently or out loud, five things you can see. Then four things you can hear. Then three things you can feel against your skin: your feet in your shoes, the chair, the air. Then two things you can smell, and one you can taste.

Why it works: anxiety pulls attention inward, to the racing heart and the racing thoughts. Naming things in the room forces attention outward, and the mind cannot fully do both at once. The counting down gives it a structure to follow, so you do not have to decide what to notice.

2. Feel your feet

Sit or stand, and put your full attention on your feet. Notice where they touch the floor. Press them down a little. Notice the weight of your body moving through them. Spend a full minute there, and when attention drifts to the worry, bring it back to the feet without scolding yourself.

Why it works: the feet are as far from the head as you can get. Anxiety is a head-and-chest experience, and moving attention to the ground literally lowers it. There is also something steadying about noticing that the floor is holding you up and has been the whole time.

3. Cold water or a cold object

Run cold water over your wrists and the insides of your forearms, hold an ice cube, or press a cold can against your cheeks and the sides of your neck. Stay with the sensation for thirty seconds or so.

Why it works: cold on the face and neck triggers a reflex that slows the heart rate. It is one of the few grounding tools that works directly on the body rather than through attention, which makes it useful when the mind is too loud to steer. It is also a strong, simple sensation, and strong simple sensations crowd out everything else.

4. Long exhale

Breathe in through your nose for a count of four, and out through your mouth for a count of six or eight. The numbers matter less than the shape: the out-breath should be longer than the in-breath. Do it six times.

Why it works: the exhale is the part of the breath that tells the nervous system to stand down. Fast, shallow breathing, which anxiety produces on its own, does the opposite. You cannot always change how you feel, but you can nearly always change how you breathe, and the feeling tends to follow with a short delay.

5. Describe the room like a detective

Pick one object nearby and describe it in detail, as if you had to report on it. The mug is white, it has a chip on the rim, there is a ring of coffee at the bottom, the handle is slightly too small for my fingers. Keep going until you run out of detail, then pick another object.

Why it works: this is the outward-attention move from the first technique, but with more precision, which makes it harder for anxious thoughts to run alongside it. It also uses the part of the mind that observes and labels, and that part is quieter and slower than the part that panics.

Making them stick

Grounding works best when it is practiced, not just remembered. Pick one or two of these and do them at low-stakes moments, waiting for the kettle or sitting in the car, until they are automatic. Then, when anxiety spikes, you are not learning a new skill under pressure. You are reaching for a familiar one.

None of these will stop anxiety from ever showing up. That is not the job. The job is to give you somewhere to stand while it passes, which it does, every time.

If anxiety is spiking often, arriving without an obvious trigger, or coming with a pounding heart and a feeling that something terrible is about to happen, it is worth talking with a therapist or a doctor. Those episodes are common and very treatable. In the US you can call or text 988 at any time.', array['Anxiety', 'Grounding']::text[], 0, '2026-09-09T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
