-- The challenges for 2026-09-27: Celebrating Small Wins and Easing
-- Perfectionism. Generated from data/challenges.json by tools/challenges_sql.py
-- --since 2026-09-27; an upsert on slug.

-- The templates: an upsert on slug, so a re-run keeps every id.
insert into public.challenge_templates
  (slug, title, description, category, total_days, tags, min_level, published_at)
values
  ('celebrating-small-wins', 'Celebrating Small Wins', 'For anyone who finishes something and moves straight to the next thing without a pause. Each day is one small way to notice what went right and let it count, so progress feels real instead of invisible.', 'Motivation', 365, array['Motivation', 'Self-Esteem']::text[], 1, '2026-09-27T17:00:00+00:00'::timestamptz),
  ('easing-perfectionism', 'Easing Perfectionism', 'For people who redo, over-prepare and put things off until they can be flawless. Each day is one small experiment in letting good enough be enough, so you finish more, rest more, and enjoy the work again.', 'Self-Compassion', 365, array['Perfectionism', 'Self-Compassion']::text[], 1, '2026-09-27T17:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  description  = excluded.description,
  category     = excluded.category,
  total_days   = excluded.total_days,
  tags         = excluded.tags,
  min_level    = excluded.min_level,
  published_at = excluded.published_at;

-- The bank of to-dos for each of those templates, replaced wholesale.
delete from public.challenge_days d
  using public.challenge_templates t
  where d.template_id = t.id and t.slug in ('celebrating-small-wins', 'easing-perfectionism');

insert into public.challenge_days (template_id, day, title, task)
select t.id, v.day, null, v.task
from (values
  ('celebrating-small-wins', 1, 'Before you move on to the next thing tonight, name one thing you finished today and say "that counts" out loud.'),
  ('celebrating-small-wins', 2, 'Start a note on your phone called "Wins" and add the first entry now, however small it seems.'),
  ('celebrating-small-wins', 3, 'Write down one thing that went right at work today, and leave the mistakes off the list for once.'),
  ('celebrating-small-wins', 4, 'Take a photo of something you completed today, a cleared sink, a sent report, a made bed, and keep it.'),
  ('celebrating-small-wins', 5, 'Tell one person about something small you pulled off this week, and stop talking before you add "but."'),
  ('celebrating-small-wins', 6, 'Put a check mark next to one task you finished today and look at it for five full seconds.'),
  ('celebrating-small-wins', 7, 'Getting out of bed on a heavy morning is a win. If you did it today, write it down.'),
  ('celebrating-small-wins', 8, 'Buy or make yourself a small treat tonight and say what it is for before you enjoy it.'),
  ('celebrating-small-wins', 9, 'Find an empty jar and drop in a coin or a folded note for one win you had today.'),
  ('celebrating-small-wins', 10, 'Pause for three slow breaths after finishing your next task, before you open anything new.'),
  ('celebrating-small-wins', 11, 'Write a two-line message to your future self about something you managed today, and set it to arrive next month.'),
  ('celebrating-small-wins', 12, 'Notice one thing your body did well today, carrying groceries, walking farther, sleeping longer, and thank it.'),
  ('celebrating-small-wins', 13, 'Pick a bill you paid, a purchase you skipped, or a dollar you saved this week, and count it as progress.'),
  ('celebrating-small-wins', 14, 'Look back at a habit you have kept up for even a few days and write down how many times you showed up.'),
  ('celebrating-small-wins', 15, 'Name one thing you understand today that you did not understand a month ago.'),
  ('celebrating-small-wins', 16, 'Ask someone close to you what they think you did well lately, and write their answer down.'),
  ('celebrating-small-wins', 17, 'Saying no to something this week was a win. Write down what you said no to and what it protected.'),
  ('celebrating-small-wins', 18, 'Keep a running tally on a sticky note today: one mark for every small task you finish.'),
  ('celebrating-small-wins', 19, 'Tonight, replay one moment from today that went better than you expected, in detail.'),
  ('celebrating-small-wins', 20, 'Send a message congratulating someone else on a small win, and notice how it feels to be the one cheering.'),
  ('celebrating-small-wins', 21, 'Write down one thing you did today that nobody saw and that still mattered.'),
  ('celebrating-small-wins', 22, 'Set an alarm for the middle of the afternoon that says "What has gone right so far?" and answer it.'),
  ('celebrating-small-wins', 23, 'Choose a physical object, a stone, a bead, a button, to move from one pocket to another each time you finish something today.'),
  ('celebrating-small-wins', 24, 'Start your to-do list today with two things you have already done, and check them off right away.'),
  ('celebrating-small-wins', 25, 'At dinner, tell whoever you are with one thing that went well for you, and ask them the same.'),
  ('celebrating-small-wins', 26, 'Write down a win from a hard week in your past, and how you got through it.'),
  ('celebrating-small-wins', 27, 'Resting when you were tired today counts. If you did it, add it to your list.'),
  ('celebrating-small-wins', 28, 'Notice one small thing at home that is better than it was a week ago, and say so to yourself.'),
  ('celebrating-small-wins', 29, 'Draw a small star on today''s date on a calendar for one thing you completed.'),
  ('celebrating-small-wins', 30, 'Write the sentence "Today I made progress on..." and finish it before you close your laptop.'),
  ('celebrating-small-wins', 31, 'Tell a coworker about something they did well this week, in a sentence that names the specific thing.'),
  ('celebrating-small-wins', 32, 'Look at your bank balance or a budget line and find one number that moved in the right direction, even by a dollar.'),
  ('celebrating-small-wins', 33, 'Stand up, stretch, and say "done" out loud the next time you finish a task.'),
  ('celebrating-small-wins', 34, 'Before sleep, count three things you finished today on your fingers, in the dark.'),
  ('celebrating-small-wins', 35, 'Write down one conversation you handled better today than you would have a year ago.'),
  ('celebrating-small-wins', 36, 'Not sending the angry message is a win. If you held back today, give yourself credit in writing.'),
  ('celebrating-small-wins', 37, 'Make a short voice memo for yourself about something you got done, and listen to it tomorrow.'),
  ('celebrating-small-wins', 38, 'Pick one recurring chore you did today and notice that it does not do itself. You did it.'),
  ('celebrating-small-wins', 39, 'Write down a skill you have practiced this month and one sign that it is improving.'),
  ('celebrating-small-wins', 40, 'Share a small win in a group chat and let people respond before you change the subject.'),
  ('celebrating-small-wins', 41, 'Give yourself a real lunch break today as a reward for the morning, away from your desk.'),
  ('celebrating-small-wins', 42, 'Keep a "done" list next to your to-do list today and see which one is longer by evening.'),
  ('celebrating-small-wins', 43, 'Notice one time today you asked for help instead of struggling alone, and count it.'),
  ('celebrating-small-wins', 44, 'Write a thank-you note to yourself for one thing you did this week, and sign it.'),
  ('celebrating-small-wins', 45, 'Look at the weather today and name one thing you did anyway, went out, stayed in and worked, took a walk in the rain.'),
  ('celebrating-small-wins', 46, 'Tell your partner, roommate, or a friend about one thing you finished today, in the first minute you see them.'),
  ('celebrating-small-wins', 47, 'Set a timer for two minutes and do nothing but sit with the feeling of having finished something.'),
  ('celebrating-small-wins', 48, 'Write down the smallest win you can find in the last hour, then a smaller one.'),
  ('celebrating-small-wins', 49, 'Circle one item on an old to-do list that you did eventually finish, however late.'),
  ('celebrating-small-wins', 50, 'Put on a favorite song tonight and let it play all the way through as a small celebration of the day.'),
  ('celebrating-small-wins', 51, 'Notice one moment today when you were patient when you could have snapped, and mark it.'),
  ('celebrating-small-wins', 52, 'Write down one thing you learned from a mistake this week, and count the learning as the win.'),
  ('celebrating-small-wins', 53, 'Tell a family member about a win they had that you noticed, and be specific about what you saw.'),
  ('celebrating-small-wins', 54, 'Move one dollar into savings today and text yourself "that counts."'),
  ('celebrating-small-wins', 55, 'Notice that you fed yourself today. On a hard day, that is a win worth naming.'),
  ('celebrating-small-wins', 56, 'Jot down something you did at work today that made someone else''s day easier.'),
  ('celebrating-small-wins', 57, 'Pick one item you have owned for years and kept in good shape, and count taking care of it as a quiet win.'),
  ('celebrating-small-wins', 58, 'End your workday by writing down one thing you finished, then close everything before you read email again.'),
  ('celebrating-small-wins', 59, 'Say "I did that" out loud, alone, after finishing something today. Notice how odd and how good it feels.'),
  ('celebrating-small-wins', 60, 'Choose one habit you skipped today and one you kept, and give the kept one the last word.'),
  ('celebrating-small-wins', 61, 'Ask a friend what small win they had this week, and celebrate it with them before mentioning your own.'),
  ('celebrating-small-wins', 62, 'Write a list of five things you can do now that you could not do at twenty, or at ten.'),
  ('celebrating-small-wins', 63, 'Put a check mark on your hand or a bracelet on your wrist for a win today, and let it remind you all day.'),
  ('celebrating-small-wins', 64, 'Cook or order something you love tonight to mark getting through this week, and say so as you sit down.'),
  ('celebrating-small-wins', 65, 'Write down a time this month you spoke up when it would have been easier to stay quiet.'),
  ('celebrating-small-wins', 66, 'Notice one step you took toward a long goal today, even a single email or a single page.'),
  ('celebrating-small-wins', 67, 'Text someone a photo of something you made, fixed, or finished today, with no explanation.'),
  ('celebrating-small-wins', 68, 'Note one money win from this month, a bill paid on time, a price compared, a purchase delayed.'),
  ('celebrating-small-wins', 69, 'Before you start tomorrow''s list tonight, read back through today''s and count the finished items.'),
  ('celebrating-small-wins', 70, 'Take a slow walk around the block after finishing something, as a way of saying it is done.'),
  ('celebrating-small-wins', 71, 'Notice one time today you took a break before you were exhausted, and name it as progress.'),
  ('celebrating-small-wins', 72, 'Write down a win you had this week that nobody praised, and praise it yourself in two sentences.'),
  ('celebrating-small-wins', 73, 'Tell your kids, or a young person in your life, about a small thing you finished today and why it mattered to you.'),
  ('celebrating-small-wins', 74, 'Leave a note on the fridge tonight naming one good thing you did today, for whoever reads it first.'),
  ('celebrating-small-wins', 75, 'Look at one thing you have been learning, a language, a recipe, a piece of software, and name the last thing you got right.'),
  ('celebrating-small-wins', 76, 'On a gray day, notice one thing you kept going with anyway, and write it at the top of a fresh page.'),
  ('celebrating-small-wins', 77, 'Make a "wins" folder in your photos and move three pictures into it from the past year.'),
  ('celebrating-small-wins', 78, 'Tell the story of a small win to yourself in the third person tonight, as if you were describing a friend.'),
  ('celebrating-small-wins', 79, 'Notice one thing you did today that your younger self would have found impossible.'),
  ('celebrating-small-wins', 80, 'Write down a win from your body this week: a stretch, a walk, a night of good sleep, a glass of water instead of another coffee.'),
  ('celebrating-small-wins', 81, 'Give yourself ten quiet minutes tonight with tea and no screen, as a marker for something you completed.'),
  ('celebrating-small-wins', 82, 'Count how many days this month you did one thing you meant to do, and let the number be enough.'),
  ('celebrating-small-wins', 83, 'Write down one problem at work you solved today, even a small one, and how you solved it.'),
  ('celebrating-small-wins', 84, 'Draw a tiny trophy in the margin of your notebook next to one finished thing today.'),
  ('celebrating-small-wins', 85, 'Ask a coworker or classmate to name one thing that went well in a shared project, then add your own.'),
  ('celebrating-small-wins', 86, 'Notice one habit you have quietly kept up, brushing, locking the door, watering a plant, and count the reliability as a win.'),
  ('celebrating-small-wins', 87, 'Tell someone on the phone today about one thing you finished, and let the call be about that for a minute.'),
  ('celebrating-small-wins', 88, 'Write down the last hard conversation you had, and one thing you did well in it.'),
  ('celebrating-small-wins', 89, 'Look around your home for one repair or improvement you made and stand in front of it for a moment.'),
  ('celebrating-small-wins', 90, 'Put one dollar, or one coin, in a jar for every task you finish today, and count it at bedtime.'),
  ('celebrating-small-wins', 91, 'Notice if you got outside at all today, and count that as a win on a day when you did not feel like it.'),
  ('celebrating-small-wins', 92, 'Write down one thing you decided today instead of postponing, and the relief it brought.'),
  ('celebrating-small-wins', 93, 'Choose a small reward for finishing your hardest task this week and write it on the same line as the task.'),
  ('celebrating-small-wins', 94, 'Post one small win somewhere, a group chat, a forum, a family thread, and let the replies land.'),
  ('celebrating-small-wins', 95, 'Jot down one purchase you skipped this week and what you did with the money or the space.'),
  ('celebrating-small-wins', 96, 'Notice that you showed up to something today, work, a class, an appointment, and count showing up as the win.'),
  ('celebrating-small-wins', 97, 'Keep a tally today of every time you finished a sentence, a task, or an errand you started, and read it tonight.'),
  ('celebrating-small-wins', 98, 'Write a note that says "You handled that" and tape it somewhere you will see it tomorrow morning.'),
  ('celebrating-small-wins', 99, 'Recall one thing you fixed this year, a leak, a schedule, a misunderstanding, and give yourself credit for it now.'),
  ('celebrating-small-wins', 100, 'Celebrate a friend''s small win today with a gift under five dollars: a coffee, a card, a snack.'),
  ('celebrating-small-wins', 101, 'Spot a moment today when you stayed calm while someone else was not, and count it.'),
  ('celebrating-small-wins', 102, 'List one thing you did for your future self today: a prepared lunch, a set alarm, a saved file.'),
  ('celebrating-small-wins', 103, 'Pause at the top of the stairs, or at your front door, and name one good thing you did before you go in.'),
  ('celebrating-small-wins', 104, 'Tell your manager or a teammate about one thing you completed this week that they may not have seen.'),
  ('celebrating-small-wins', 105, 'Name something you did today that took courage, however ordinary it looked from outside.'),
  ('celebrating-small-wins', 106, 'Make tonight''s dinner a small celebration of one thing you did this week, and say what it is before the first bite.'),
  ('celebrating-small-wins', 107, 'Look at a project you are in the middle of and list what is already done, before you look at what is left.'),
  ('celebrating-small-wins', 108, 'Notice one meal you cooked at home this week instead of ordering, and count the effort.'),
  ('celebrating-small-wins', 109, 'Write down one way you were kind to yourself today and treat it as a win, not a slip.'),
  ('celebrating-small-wins', 110, 'Send a voice message to a friend telling them about one small thing that went well today.'),
  ('celebrating-small-wins', 111, 'Look at your calendar for the week and circle every appointment you actually kept.'),
  ('celebrating-small-wins', 112, 'Write down one habit that has gotten easier, and how it felt when it was still hard.'),
  ('celebrating-small-wins', 113, 'Notice one time today you finished a thought before picking up your phone, and count that as focus.'),
  ('celebrating-small-wins', 114, 'Give your day a small win before noon: finish one tiny task and mark it with a check mark before lunch.'),
  ('celebrating-small-wins', 115, 'Write down a sentence about one thing you did today that you would praise in a coworker.'),
  ('celebrating-small-wins', 116, 'Learn one new fact, word, or shortcut today and write it down as evidence that you are still learning.'),
  ('celebrating-small-wins', 117, 'Notice if you drank water, took your medication, or ate a vegetable today, and count each one as a win.'),
  ('celebrating-small-wins', 118, 'Tell a neighbor or an acquaintance about one small thing that went well this week, just to practice saying it.'),
  ('celebrating-small-wins', 119, 'Write a short list called "Things I finished this month" and add three items from memory.'),
  ('celebrating-small-wins', 120, 'Take a photo of your workspace at the end of the day, and notice what got done there.'),
  ('celebrating-small-wins', 121, 'On a hard week, lower the bar on purpose: write down one thing you did today that kept life running.'),
  ('celebrating-small-wins', 122, 'Record something you did today that a year ago you would have avoided.'),
  ('celebrating-small-wins', 123, 'Sit down for one minute after a chore is done, and let the finished thing be finished before the next one starts.'),
  ('celebrating-small-wins', 124, 'Ask an older relative about a small win from their life, and share one of yours.'),
  ('celebrating-small-wins', 125, 'Notice one email or message you answered today that you had been dreading, and mark it finished.'),
  ('celebrating-small-wins', 126, 'Note one step you took this week toward a savings goal, a debt, or a budget, and how it felt.'),
  ('celebrating-small-wins', 127, 'Notice one thing you did well as a parent, partner, friend, or child today, and write it in a sentence.'),
  ('celebrating-small-wins', 128, 'Say a quiet thank-you to yourself the next time you finish something today, and mean it.'),
  ('celebrating-small-wins', 129, 'Write a "done" list for the whole week on a Friday or Sunday evening and read it slowly.'),
  ('celebrating-small-wins', 130, 'Keep one finished thing from today visible tomorrow, a folded blanket, a cleared desk, a printed page.'),
  ('celebrating-small-wins', 131, 'Write down one thing you were nervous about that turned out fine this week, and what you did to help it go well.'),
  ('celebrating-small-wins', 132, 'Catch a moment today when you chose a walk, a stretch, or a stair over sitting, and count it.'),
  ('celebrating-small-wins', 133, 'Text a friend a photo of one thing you crossed off your list today, with the words "small win."'),
  ('celebrating-small-wins', 134, 'Let yourself say "I''m proud of that" once today, about something small, without a joke after it.'),
  ('celebrating-small-wins', 135, 'Write down what you did today to make tomorrow a little easier.'),
  ('celebrating-small-wins', 136, 'Notice the first thing you finished today, and give it a check mark even if it was making coffee.'),
  ('celebrating-small-wins', 137, 'Choose one skill you are learning and write down the very first step you ever took toward it.'),
  ('celebrating-small-wins', 138, 'Tell someone you love about a win of theirs that you noticed this month, and say why it impressed you.'),
  ('celebrating-small-wins', 139, 'Write down one habit you broke this week, even for a day, and count the day.'),
  ('celebrating-small-wins', 140, 'End the day by saying one finished thing aloud to an empty room, as if reporting to a kind supervisor.'),
  ('celebrating-small-wins', 141, 'Notice one time today when you asked a question instead of pretending to know, and count it.'),
  ('celebrating-small-wins', 142, 'Write the words "That was enough" at the bottom of today''s to-do list, whatever got done.'),
  ('celebrating-small-wins', 143, 'Buy fresh flowers, or pick a stem from outside, to mark something you finished this week.'),
  ('celebrating-small-wins', 144, 'Notice one boundary you kept today, a stop time, a no, a closed door, and write it down.'),
  ('celebrating-small-wins', 145, 'Write down one thing you made today: a meal, a spreadsheet, a plan, a joke that landed.'),
  ('celebrating-small-wins', 146, 'Give someone at work public credit for a small win of theirs, in a meeting or a message.'),
  ('celebrating-small-wins', 147, 'Find something you did today that you did not have to do, and count the extra as a win.'),
  ('celebrating-small-wins', 148, 'Open a fresh page and title it "Went right," then fill three lines before you write anything else today.'),
  ('celebrating-small-wins', 149, 'Hang a small piece of paper by your door and add one word for each win as you come home this week.'),
  ('celebrating-small-wins', 150, 'Rate your day out of ten, then write one thing that pushed the number up.'),
  ('celebrating-small-wins', 151, 'Tell a colleague at the end of a meeting one thing that went well in it, before anyone moves to the next item.'),
  ('celebrating-small-wins', 152, 'Finish a book, an episode, a chapter, or an article today and let the finishing itself count.'),
  ('celebrating-small-wins', 153, 'When you close a tab, a file, or a door today, say "done" quietly, and mean each one.'),
  ('celebrating-small-wins', 154, 'Collect your wins from the week into one message and send it to a friend who will be glad.'),
  ('celebrating-small-wins', 155, 'Read an old text, email, or note where you were worried about something that later worked out.'),
  ('celebrating-small-wins', 156, 'Pick a small physical reward that costs nothing, a hot shower, a nap, ten minutes in the sun, and take it after finishing a task.'),
  ('celebrating-small-wins', 157, 'Recall one time this year you kept a promise to yourself, and write down which one.'),
  ('celebrating-small-wins', 158, 'Ask your household to each name one thing that went well today, before anyone talks about what went wrong.'),
  ('celebrating-small-wins', 159, 'Set your phone wallpaper to a photo of something you finished or built.'),
  ('celebrating-small-wins', 160, 'Notice one thing in your kitchen that is clean because you cleaned it, and let it count.'),
  ('celebrating-small-wins', 161, 'Write "I showed up" on a calendar square for today, and nothing else.'),
  ('celebrating-small-wins', 162, 'Give yourself the last slice, the good seat, or the first shower tonight, and call it a prize for the week.'),
  ('celebrating-small-wins', 163, 'Name a skill you use so easily now that you forget you once had to learn it.'),
  ('celebrating-small-wins', 164, 'Look at a number that tracks something you care about, steps, savings, pages, minutes, and note the direction, not the size.'),
  ('celebrating-small-wins', 165, 'In the shower or on your commute, list three things you have handled since you woke up.'),
  ('celebrating-small-wins', 166, 'Tell your doctor, trainer, teacher, or coach one small thing you have kept up since you last spoke.'),
  ('celebrating-small-wins', 167, 'Reread the last thing you wrote, a report, an email, a caption, and find one sentence you did well.'),
  ('celebrating-small-wins', 168, 'Mark today on your calendar with a color for "good enough," and use it again whenever a day earns it.'),
  ('celebrating-small-wins', 169, 'Make a paper chain, one link for each finished task this week, and hang it somewhere visible.'),
  ('celebrating-small-wins', 170, 'When someone thanks you today, let it land fully before you say "it was nothing."'),
  ('celebrating-small-wins', 171, 'Find one thing you did today that made a small mess smaller, and count it.'),
  ('celebrating-small-wins', 172, 'Take yourself out for a coffee or a walk at lunchtime and tell yourself, in words, what it is celebrating.'),
  ('celebrating-small-wins', 173, 'Remember one thing you were afraid to try this year and did anyway, whatever the result.'),
  ('celebrating-small-wins', 174, 'Change one item on your to-do list from "do" to "done" tonight, and rewrite it in the past tense.'),
  ('celebrating-small-wins', 175, 'Take a photo of the sky when you finish something today, and let the two be linked in your memory.'),
  ('celebrating-small-wins', 176, 'Whisper "one more thing done" every time you finish a small task this afternoon.'),
  ('celebrating-small-wins', 177, 'Write down what your morning would have looked like if you had not done the one thing you did.'),
  ('celebrating-small-wins', 178, 'Praise yourself for a win in the exact words you would use for a friend, and notice the difference.'),
  ('celebrating-small-wins', 179, 'Save a screenshot of a kind message, a good grade, or a finished list in a folder called "Proof."'),
  ('celebrating-small-wins', 180, 'Arriving on time today is a win. If you managed it, note it before you walk in.'),
  ('celebrating-small-wins', 181, 'Bring a small treat to share at work or at home, and say that it is to mark something ordinary that went well.'),
  ('celebrating-small-wins', 182, 'Write down one hard thing you did not make worse today, and count that as skillful.'),
  ('celebrating-small-wins', 183, 'Carry a small notebook today and write a single word for each win as it happens.'),
  ('celebrating-small-wins', 184, 'Watch someone else finish something today, a cashier, a kid, a coworker, and tell them "nice work."'),
  ('celebrating-small-wins', 185, 'Compare yourself only to yourself from a year ago today, and write down one difference.'),
  ('celebrating-small-wins', 186, 'Gather three small wins from this week and read them aloud to yourself in the mirror.'),
  ('celebrating-small-wins', 187, 'Rewrite one item you failed at this week as the part of it you did manage.'),
  ('celebrating-small-wins', 188, 'Toast something small at dinner tonight, with water, juice, or whatever is in your glass.'),
  ('celebrating-small-wins', 189, 'Notice one habit you have kept through a busy stretch, and let its survival be the win.'),
  ('celebrating-small-wins', 190, 'If you cried today and kept going, write that down as strength, not as failure.'),
  ('celebrating-small-wins', 191, 'Spend one minute at the end of your workday listing what you handled, before you list what is left.'),
  ('celebrating-small-wins', 192, 'Applaud yourself, actually clap, alone, after finishing a task you did not want to do.'),
  ('celebrating-small-wins', 193, 'Sort your finished tasks this week into work, home, and people, and see which column surprises you.'),
  ('celebrating-small-wins', 194, 'Spend the money you saved skipping something this week on one small treat, and name the win it marks.'),
  ('celebrating-small-wins', 195, 'Tell the person who taught you a skill about a recent time you used it well.'),
  ('celebrating-small-wins', 196, 'Look at your hands and name one useful thing they did today.'),
  ('celebrating-small-wins', 197, 'Put a gold star, a sticker, or a doodle on your planner for one thing you finished, like a kid would.'),
  ('celebrating-small-wins', 198, 'Find the win inside a canceled plan: the rest, the time, the money not spent, and write it down.'),
  ('celebrating-small-wins', 199, 'Message a coworker at the end of the week naming one thing the team got done together.'),
  ('celebrating-small-wins', 200, 'Think of a habit you started this year that stuck, and write down what day of the week you usually do it.'),
  ('celebrating-small-wins', 201, 'Count the steps you took toward one goal this month, however small, and write the number, not the distance left.'),
  ('celebrating-small-wins', 202, 'Let a compliment about your work sit for a full ten seconds before you reply today.'),
  ('celebrating-small-wins', 203, 'Spend the last five minutes of your workday writing tomorrow''s list, and count that as today''s final win.'),
  ('celebrating-small-wins', 204, 'Write down a small win from your childhood you still remember, and what it felt like then.'),
  ('celebrating-small-wins', 205, 'Choose one room, and stand in the doorway naming everything in it that is done, put away, or working.'),
  ('celebrating-small-wins', 206, 'Tell a friend about a habit you have kept up, and ask them to check in on it next week.'),
  ('celebrating-small-wins', 207, 'Pick one thing you did today that was hard for you but easy for others, and count it at your size, not theirs.'),
  ('celebrating-small-wins', 208, 'Highlight one line in your journal or notes from this month that shows progress.'),
  ('celebrating-small-wins', 209, 'Before you criticize a piece of your own work today, find two things in it that are right.'),
  ('celebrating-small-wins', 210, 'Notice that you kept a plant, a pet, or a person fed and watered this week, and count it.'),
  ('celebrating-small-wins', 211, 'Pause after sending an email you had been putting off, and feel the difference in your shoulders.'),
  ('celebrating-small-wins', 212, 'Give yourself a title for the day, "Bill Payer," "Dish Doer," "Email Finisher," and say it with a straight face.'),
  ('celebrating-small-wins', 213, 'Text yourself one thing that went right today, so it is waiting in your messages tomorrow morning.'),
  ('celebrating-small-wins', 214, 'Ask a friend to tell you about their win of the week, and celebrate it before you talk about anything else.'),
  ('celebrating-small-wins', 215, 'Keep the wrapper, the receipt, the ticket stub from something you finished or attended, and tuck it in a jar.'),
  ('celebrating-small-wins', 216, 'Hold up one finger for each thing you finished today, and stop when you run out of fingers or things.'),
  ('celebrating-small-wins', 217, 'Recall one thing you did for your health this week and write it down without a "but I also."'),
  ('celebrating-small-wins', 218, 'Say "we did that" to your partner, roommate, or teammate about one shared thing that went well today.'),
  ('celebrating-small-wins', 219, 'Take a break of at least five minutes after finishing your next task, and do not start another during it.'),
  ('celebrating-small-wins', 220, 'Find one place in your home where you can see progress, a shelf, a drawer, a corner, and look at it on purpose.'),
  ('celebrating-small-wins', 221, 'Make a list of things you can do in the kitchen now that you could not do five years ago.'),
  ('celebrating-small-wins', 222, 'On the first cold morning of the year, count getting out from under the blankets as the day''s first win.'),
  ('celebrating-small-wins', 223, 'Mark the turn of a season by writing down three things you finished since the last one.'),
  ('celebrating-small-wins', 224, 'In the week before a holiday, notice one thing you got done that nobody will see, and write it on the shopping list.'),
  ('celebrating-small-wins', 225, 'On New Year''s Day, list five small wins from last year instead of making a single big resolution.'),
  ('celebrating-small-wins', 226, 'Write down one thing you handled well during a family gathering, and let it outweigh the awkward moments.'),
  ('celebrating-small-wins', 227, 'If you kept a holiday simpler than usual this year, count the simplicity as a win, not a shortfall.'),
  ('celebrating-small-wins', 228, 'On a summer evening, sit outside and name one thing you did today that you are glad you did.'),
  ('celebrating-small-wins', 229, 'Send a card, not a text, to someone celebrating something small this month.'),
  ('celebrating-small-wins', 230, 'When the clocks change, notice one routine you kept anyway, and count it.'),
  ('celebrating-small-wins', 231, 'On your birthday, or on the day after, write down one thing you learned to do this year.'),
  ('celebrating-small-wins', 232, 'After a long holiday weekend, notice that you rested and count the rest as done, not as lost time.'),
  ('celebrating-small-wins', 233, 'Pick a small tradition for marking wins, a specific mug, a particular walk, a song, and use it once this week.'),
  ('celebrating-small-wins', 234, 'Watch the leaves, the snow, or the first buds today and name one thing that has changed in you as well.'),
  ('celebrating-small-wins', 235, 'In a hard week, count getting dressed as a win, and write it on the same line as anything bigger.'),
  ('celebrating-small-wins', 236, 'When a week has gone badly, find the one thing that went less badly than it could have, and name it.'),
  ('celebrating-small-wins', 237, 'If today felt like nothing got done, write down five tiny things that did: a text answered, a dish washed, a decision made.'),
  ('celebrating-small-wins', 238, 'On a day you feel behind, write down what you would tell a friend who did exactly what you did today.'),
  ('celebrating-small-wins', 239, 'When you are sick, count each glass of water, each nap, each small meal as a win on the list.'),
  ('celebrating-small-wins', 240, 'On a day of bad news, notice one way you took care of yourself, and let it count.'),
  ('celebrating-small-wins', 241, 'If you canceled something to protect your energy this week, write down what it protected.'),
  ('celebrating-small-wins', 242, 'When a project fails, list three things you did right along the way before you list what went wrong.'),
  ('celebrating-small-wins', 243, 'On a lonely day, count reaching out to one person, even by a single emoji, as the win.'),
  ('celebrating-small-wins', 244, 'When you feel stuck, write down the last three things you finished, however long ago, to remember that you do finish things.'),
  ('celebrating-small-wins', 245, 'Congratulate a stranger today, a barista who nailed the order, a driver who parked well, a kid who stuck a landing.'),
  ('celebrating-small-wins', 246, 'Celebrate a coworker''s small win by remembering it a week later and asking how it turned out.'),
  ('celebrating-small-wins', 247, 'Ask a parent, sibling, or old friend what they are quietly proud of lately, and let them talk.'),
  ('celebrating-small-wins', 248, 'When a friend downplays their own win, hand it back to them: "No, that was a real thing you did."'),
  ('celebrating-small-wins', 249, 'Cheer for someone''s progress on a habit, not their result, today.'),
  ('celebrating-small-wins', 250, 'Write a short note to someone who helped make one of your wins possible, and tell them their part.'),
  ('celebrating-small-wins', 251, 'Notice a small win a child, a student, or a beginner had today, and name it to them specifically.'),
  ('celebrating-small-wins', 252, 'Share a coworker''s good work with someone who did not see it, with their name attached.'),
  ('celebrating-small-wins', 253, 'Ask your partner or a close friend what they finished this week, and say "that counts" about the smallest one.'),
  ('celebrating-small-wins', 254, 'Look at a group you belong to, a team, a class, a family, and name one thing it managed together this month.'),
  ('celebrating-small-wins', 255, 'Leave a kind comment on something a friend made, finished, or shared, naming what you liked about it.'),
  ('celebrating-small-wins', 256, 'Write down one time you kept your temper this week, and count it as a win, not a minimum.'),
  ('celebrating-small-wins', 257, 'Remember one thing you fixed at work this quarter without anyone asking, and record it somewhere you will find it at review time.'),
  ('celebrating-small-wins', 258, 'Add a "wins" line to your weekly planning and fill it in before you fill in the tasks.'),
  ('celebrating-small-wins', 259, 'Tell a mentor or a former teacher about a recent small success, and thank them for their part in it.'),
  ('celebrating-small-wins', 260, 'Let one finished chore stay visible tonight instead of moving straight to the next, and admire it.'),
  ('celebrating-small-wins', 261, 'Wear something today that you bought, made, or mended, and count it as a small win you can see.'),
  ('celebrating-small-wins', 262, 'Mark one saved-for purchase, however small, with a note about how long you saved for it.'),
  ('celebrating-small-wins', 263, 'Pull up your loan, card, or savings balance and write down how far it has moved since you started paying attention.'),
  ('celebrating-small-wins', 264, 'Count one grocery trip where you stuck to the list, and note what it saved.'),
  ('celebrating-small-wins', 265, 'Write down a bill you set up on autopay, a subscription you canceled, or a fee you avoided, and let it count as a money win.'),
  ('celebrating-small-wins', 266, 'Notice one thing you learned about yourself this week, and count learning as progress.'),
  ('celebrating-small-wins', 267, 'Play one song or one exercise you have practiced, and note what is easier than last month.'),
  ('celebrating-small-wins', 268, 'Answer one question today that you would have needed to look up a year ago, and notice that you knew it.'),
  ('celebrating-small-wins', 269, 'Finish one lesson, one page, or one video of something you are learning and write the date next to it.'),
  ('celebrating-small-wins', 270, 'Take a photo of your progress on a craft, a garden, a repair, or a skill, and compare it with an earlier one.'),
  ('celebrating-small-wins', 271, 'Notice how far you walked, lifted, stretched, or slept this week compared with a rough week, and write the difference down.'),
  ('celebrating-small-wins', 272, 'Recall a time your body carried you through a hard day this month, and thank it in writing.'),
  ('celebrating-small-wins', 273, 'Count one healthy meal, one early night, or one walk this week as a full win, not a fraction of a plan.'),
  ('celebrating-small-wins', 274, 'Book, attend, or complete one health appointment this month and let the tick count for the whole process.'),
  ('celebrating-small-wins', 275, 'Choose one habit you want to celebrate, and decide tonight what small ritual will mark it each time.'),
  ('celebrating-small-wins', 276, 'Pick a habit you have kept up for a month and treat yourself to something in its honor.'),
  ('celebrating-small-wins', 277, 'Notice one time this week you did a habit even though you were tired, and count doing it tired as double.'),
  ('celebrating-small-wins', 278, 'Note something from work this week that you would put on a résumé, however small it looked.'),
  ('celebrating-small-wins', 279, 'Notice one meeting you ran, joined, or sat through today with patience, and count it.'),
  ('celebrating-small-wins', 280, 'Write down one time you delegated or shared a task instead of doing it all yourself, and count that as skill.'),
  ('celebrating-small-wins', 281, 'Recall one deadline you met this month, and give yourself a check mark for it even if it is old news.'),
  ('celebrating-small-wins', 282, 'Notice one thing at home that runs smoothly because you set it up, a shelf, a routine, a system, and give it a nod.'),
  ('celebrating-small-wins', 283, 'Count a load of laundry, from washer to drawer, as a whole win today.'),
  ('celebrating-small-wins', 284, 'Write down one thing about your home you improved this season, however small.'),
  ('celebrating-small-wins', 285, 'Notice one household task you did before it became urgent, and count the foresight.'),
  ('celebrating-small-wins', 286, 'Tell someone who lives with you about one thing you did today that made the home nicer, without hinting for thanks.'),
  ('celebrating-small-wins', 287, 'Say "I''m glad I did that" about one small thing today, and stop there.'),
  ('celebrating-small-wins', 288, 'Set a reminder for a year from today that says "Look how far you came," and write two current wins in the note.'),
  ('celebrating-small-wins', 289, 'Write a message to yourself to open at the end of the year, listing three things you have already done this year.'),
  ('celebrating-small-wins', 290, 'Record a ten-second video of yourself saying one thing you finished today, and keep it.'),
  ('celebrating-small-wins', 291, 'Place one object on your desk or nightstand tonight that stands for a win, and leave it there through tomorrow.'),
  ('celebrating-small-wins', 292, 'Buy or find one small token, a pin, a stone, a card, to mark a milestone you reached this year.'),
  ('celebrating-small-wins', 293, 'Take a sip of something warm and say "to getting through today," before you go to bed.'),
  ('celebrating-small-wins', 294, 'Start a "wins" page at the back of your notebook and add one line tonight.'),
  ('celebrating-small-wins', 295, 'Sketch a rough line graph of a habit, a skill, or a savings amount from the start to today, and look at the slope.'),
  ('celebrating-small-wins', 296, 'Draw a small box on your hand or a sticky note and color it in when today''s one task is done.'),
  ('celebrating-small-wins', 297, 'Reply to one message today with "thank you, that took some work" when someone praises you, instead of shrugging it off.'),
  ('celebrating-small-wins', 298, 'When you catch yourself saying "it was nothing," stop and name the one thing it actually was.'),
  ('celebrating-small-wins', 299, 'Give a finished task a nickname, "the beast," "the dragon," "the Tuesday email," and tell someone you slayed it.'),
  ('celebrating-small-wins', 300, 'Read your wins note from the beginning tonight, however short it is, and notice the pattern.'),
  ('celebrating-small-wins', 301, 'Before you check the news this morning, name one thing that already went right since you woke up.'),
  ('celebrating-small-wins', 302, 'Sit in the car for one extra minute after arriving somewhere and name one thing you managed today.'),
  ('celebrating-small-wins', 303, 'Notice one thing you finished today that you had started weeks ago, and count the whole stretch.'),
  ('celebrating-small-wins', 304, 'Choose one small win and tell it to three different people today, without shrinking it each time.'),
  ('celebrating-small-wins', 305, 'Leave one thing off your to-do list tonight because you already did it, and notice how that feels.'),
  ('celebrating-small-wins', 306, 'Find a win in a mistake you caught before it mattered, and write down what you caught.'),
  ('celebrating-small-wins', 307, 'Rename a folder, a file, or a list from "to do" to "done" when it is finished, and read the new name.'),
  ('celebrating-small-wins', 308, 'Point to one item in your home you assembled, installed, or hung yourself, and say "I did that" out loud.'),
  ('celebrating-small-wins', 309, 'Give yourself one win before breakfast: a made bed, a glass of water, a stretch, and call it the first of the day.'),
  ('celebrating-small-wins', 310, 'Count how many times you kept your word this week, to yourself or to someone else, and let the number sit.'),
  ('celebrating-small-wins', 311, 'Take one thing off your plate this week and count the removal as an accomplishment, not a retreat.'),
  ('celebrating-small-wins', 312, 'Say "that''s progress" to yourself once today in a moment where you would normally say "not enough."'),
  ('celebrating-small-wins', 313, 'Tell a shopkeeper, server, or receptionist one thing they did well today, on your way out.'),
  ('celebrating-small-wins', 314, 'Pick a coworker''s win from this week and mention it to your manager before you mention your own.'),
  ('celebrating-small-wins', 315, 'Bake, buy, or share a small sweet thing to mark a friend''s news, however minor it seems to them.'),
  ('celebrating-small-wins', 316, 'Notice what your team, family, or household finished this week that no single person could have done alone.'),
  ('celebrating-small-wins', 317, 'Let someone tell you about their good day today without turning the conversation to yours.'),
  ('celebrating-small-wins', 318, 'Write down a win that came out of a hard week: a call you made, a meal you ate, a morning you got through.'),
  ('celebrating-small-wins', 319, 'On a day when you did not do the big thing, list the small things that kept you afloat.'),
  ('celebrating-small-wins', 320, 'If you got through today without something you usually lean on, write down that you did.'),
  ('celebrating-small-wins', 321, 'Notice one moment this week when you stopped, rested, and started again, and count the stopping.'),
  ('celebrating-small-wins', 322, 'Recall one week this year when things fell apart and you kept one habit going anyway. Name the habit.'),
  ('celebrating-small-wins', 323, 'Turn the last line of today''s journal entry into a win, however you have to reword it.'),
  ('celebrating-small-wins', 324, 'Notice one skill you used at work today that you learned outside work, and give the outside credit.'),
  ('celebrating-small-wins', 325, 'Mark a work win in your calendar as an event, "Finished the proposal," so it shows up when you look back.'),
  ('celebrating-small-wins', 326, 'Send yourself an email with the subject line "Done" and one line about what you completed today.'),
  ('celebrating-small-wins', 327, 'Notice one bit of feedback you took well this week, and count the taking as growth.'),
  ('celebrating-small-wins', 328, 'Choose one recurring task at work and count today''s version as a real win, not just maintenance.'),
  ('celebrating-small-wins', 329, 'Give a room in your home a "done" moment today: stand in it and name what is finished there.'),
  ('celebrating-small-wins', 330, 'Name one part of your morning routine that works now and did not a year ago.'),
  ('celebrating-small-wins', 331, 'Notice one purchase this month that you thought through instead of grabbing, and count the thinking.'),
  ('celebrating-small-wins', 332, 'Add one line to your budget or money note today that records a small win, not a slip.'),
  ('celebrating-small-wins', 333, 'Recall one conversation about money this year that went better than you feared, and write down why.'),
  ('celebrating-small-wins', 334, 'Write down one small skill you picked up from a video, a friend, or a mistake this month.'),
  ('celebrating-small-wins', 335, 'Notice one word, phrase, or concept you can now explain to someone else, and explain it to someone tonight.'),
  ('celebrating-small-wins', 336, 'Count one page read, one lesson finished, or one tricky thing understood as today''s learning win.'),
  ('celebrating-small-wins', 337, 'Stretch for two minutes and thank your body for one specific thing it did well this week.'),
  ('celebrating-small-wins', 338, 'Count one flight of stairs, one walk, or one dance in the kitchen as the day''s win for your body.'),
  ('celebrating-small-wins', 339, 'Notice one night this week you went to bed when you meant to, and count it.'),
  ('celebrating-small-wins', 340, 'Let one healthy choice today, water, a vegetable, a walk, stand as a complete win with no follow-up required.'),
  ('celebrating-small-wins', 341, 'Pick one habit you kept this week and give it a small ceremony tonight: a candle, a song, a line in your notebook.'),
  ('celebrating-small-wins', 342, 'Notice one day this week when you did the habit at the wrong time or in a rushed way, and count it anyway.'),
  ('celebrating-small-wins', 343, 'Tell a friend about one habit that finally feels automatic, and how long it took.'),
  ('celebrating-small-wins', 344, 'Find one holiday task you finished early, a gift, a card, a plan, and let it count now, not in December.'),
  ('celebrating-small-wins', 345, 'On a hot day, count one thing you did anyway, and give yourself the cool drink you earned.'),
  ('celebrating-small-wins', 346, 'At the end of a school year, a work quarter, or a season, write down three wins that would otherwise be forgotten.'),
  ('celebrating-small-wins', 347, 'On a snow day, a sick day, or a slow day, count the day itself as a win if you let it be slow.'),
  ('celebrating-small-wins', 348, 'Mark the first day of a new month by reading last month''s wins list before writing anything new.'),
  ('celebrating-small-wins', 349, 'Notice one thing you kept going during a busy holiday stretch, sleep, a walk, a phone call, and count its survival.'),
  ('celebrating-small-wins', 350, 'Write down one win that only you could have known was a win today.'),
  ('celebrating-small-wins', 351, 'Notice the feeling of a task ending today, the click, the exhale, the empty inbox, and stay with it for a breath.'),
  ('celebrating-small-wins', 352, 'Give yourself one small treat this week that you choose in advance and connect to a specific finished thing.'),
  ('celebrating-small-wins', 353, 'Fold a small piece of paper with one win on it into your wallet, and find it later.'),
  ('celebrating-small-wins', 354, 'Stack three coins, three books, or three pens, one for each thing you finished today, and leave the stack out.'),
  ('celebrating-small-wins', 355, 'Tell the next person you see about one thing that went right today, before they ask how you are.'),
  ('celebrating-small-wins', 356, 'Name one thing you finished today that felt impossible at nine this morning.'),
  ('celebrating-small-wins', 357, 'Before you criticize your week, list the promises you kept in it.'),
  ('celebrating-small-wins', 358, 'Keep a "win of the week" spot on the fridge and fill it in every Sunday, starting today.'),
  ('celebrating-small-wins', 359, 'Record one thing you did today that your future self will thank you for, and let that be the day''s win.'),
  ('celebrating-small-wins', 360, 'Notice one thing you handled by yourself this week that you used to need help with, and give yourself credit.'),
  ('celebrating-small-wins', 361, 'Choose the smallest possible finished thing from today and give it the biggest possible check mark.'),
  ('celebrating-small-wins', 362, 'Recall a win from earlier this year that you have already forgotten about, and write it back down.'),
  ('celebrating-small-wins', 363, 'Take a photo of the last page of a notebook, a book, or a workbook you finished, and keep it.'),
  ('celebrating-small-wins', 364, 'Tonight, ask yourself what went right, and refuse to answer "nothing." Find one thing.'),
  ('celebrating-small-wins', 365, 'Close today by writing a single sentence that begins "I am glad I" and ends with something small.'),
  ('easing-perfectionism', 1, 'Write down one task you have been polishing for too long, and decide what "done" looks like for it in a single sentence.'),
  ('easing-perfectionism', 2, 'Send one email today without rereading it a second time.'),
  ('easing-perfectionism', 3, 'Notice the standard you are holding yourself to on one task, and ask whether anyone else expects that from you.'),
  ('easing-perfectionism', 4, 'Pick a small chore, set a timer for ten minutes, and stop when it rings even if it is not finished.'),
  ('easing-perfectionism', 5, 'Leave one typo in a text message to a friend and send it anyway.'),
  ('easing-perfectionism', 6, 'Choose a task you tend to over-prepare for and cut your preparation time in half today.'),
  ('easing-perfectionism', 7, 'Cook dinner tonight without measuring anything exactly, and eat it without commenting on what went wrong.'),
  ('easing-perfectionism', 8, 'Hand a task to someone else at home or at work today and let them do it their way, start to finish.'),
  ('easing-perfectionism', 9, 'Before starting one piece of work, write the lowest bar it needs to clear, then aim for that bar and no higher.'),
  ('easing-perfectionism', 10, 'Make your bed a little sloppily on purpose and leave it that way all day.'),
  ('easing-perfectionism', 11, 'Rate a piece of your work from one to ten, then ask what a seven would have looked like and whether it would have done the job.'),
  ('easing-perfectionism', 12, 'Post a photo on social media without editing it or checking how the light looks.'),
  ('easing-perfectionism', 13, 'Ask a coworker what they think a finished version of a shared task looks like, and notice if their bar is lower than yours.'),
  ('easing-perfectionism', 14, 'Notice one thing you avoided starting today because you could not do it well, and spend five minutes doing it badly.'),
  ('easing-perfectionism', 15, 'Wear the outfit you put together first this morning, without changing any part of it.'),
  ('easing-perfectionism', 16, 'Say "that is good enough" out loud at the end of one task today, and mean it.'),
  ('easing-perfectionism', 17, 'Send a draft to someone before you think it is ready and ask for their reaction.'),
  ('easing-perfectionism', 18, 'Hang a picture or shelf in your home without measuring, then decide whether anyone would ever notice.'),
  ('easing-perfectionism', 19, 'Make a list of everything you did today, then circle the items where extra effort would have changed nothing.'),
  ('easing-perfectionism', 20, 'Let your child, partner, or roommate load the dishwasher their way and do not rearrange it afterward.'),
  ('easing-perfectionism', 21, 'Write a rough first draft of something in fifteen minutes with your spell-checker turned off.'),
  ('easing-perfectionism', 22, 'Pick one recurring task and decide, in writing, how much time it deserves from now on.'),
  ('easing-perfectionism', 23, 'Serve guests or family a meal on mismatched plates and notice whether anyone cares.'),
  ('easing-perfectionism', 24, 'Give yourself permission to hand in one thing today at the level of "fine."'),
  ('easing-perfectionism', 25, 'Leave the last five percent of a project undone for a day and notice how uncomfortable it feels, then notice that nothing bad happens.'),
  ('easing-perfectionism', 26, 'Make one decision today in under a minute that you would normally research for an hour.'),
  ('easing-perfectionism', 27, 'Wrap a gift quickly, without perfect corners, and give it as it is.'),
  ('easing-perfectionism', 28, 'Notice a moment today when you thought "it is either perfect or a failure" and write down a third option.'),
  ('easing-perfectionism', 29, 'Spend a workout going through the motions at an easy pace instead of trying to hit your best numbers.'),
  ('easing-perfectionism', 30, 'Practice a hobby for twenty minutes with the goal of enjoying it rather than improving at it.'),
  ('easing-perfectionism', 31, 'Ask someone you trust to tell you honestly whether they noticed the flaw you are worried about in something you made.'),
  ('easing-perfectionism', 32, 'Set a deadline for a task that is one day earlier than feels comfortable, and finish a rougher version by then.'),
  ('easing-perfectionism', 33, 'Read back an old piece of work you agonized over and notice whether the details you fretted about still matter.'),
  ('easing-perfectionism', 34, 'Delegate one errand today and resist checking whether it was done correctly.'),
  ('easing-perfectionism', 35, 'Leave a voicemail without rehearsing it first.'),
  ('easing-perfectionism', 36, 'Choose one area of your home where you will lower the standard this week, and write the new standard down.'),
  ('easing-perfectionism', 37, 'Fill out a form or application in one sitting and submit it without a second review.'),
  ('easing-perfectionism', 38, 'Bake or cook something new and let it look homemade, then take a photo of it exactly as it turned out.'),
  ('easing-perfectionism', 39, 'Ask yourself before finishing a task today: "Who is this extra effort actually for?"'),
  ('easing-perfectionism', 40, 'Let a meeting or conversation end without saying the one extra thing that would have made your point complete.'),
  ('easing-perfectionism', 41, 'Write down three things that happened when you last made a mistake at work, and notice how few of them were lasting.'),
  ('easing-perfectionism', 42, 'Pick a small project you have restarted more than once and finish the current version without starting over again.'),
  ('easing-perfectionism', 43, 'Go out with your hair or beard exactly as it dried this morning.'),
  ('easing-perfectionism', 44, 'Answer one question at work with "I am not sure, let me find out" instead of stalling until you have a perfect answer.'),
  ('easing-perfectionism', 45, 'Play a board game or a sport tonight without keeping close track of whether you are winning.'),
  ('easing-perfectionism', 46, 'Set a fifteen-minute limit for choosing what to buy, cook, or watch, and go with your first reasonable pick.'),
  ('easing-perfectionism', 47, 'Let someone else plan the weekend, and go along with the plan without improving it.'),
  ('easing-perfectionism', 48, 'Notice when you say "I should have" today, and finish the sentence with "and it was still fine."'),
  ('easing-perfectionism', 49, 'Send a birthday card or message a day late instead of skipping it because the moment passed.'),
  ('easing-perfectionism', 50, 'Sketch, doodle, or write something for ten minutes and throw it away without judging whether it was any good.'),
  ('easing-perfectionism', 51, 'Look at a mistake you made this week and write down one thing it taught you that a flawless run would not have.'),
  ('easing-perfectionism', 52, 'Leave one small task on your list unchecked at the end of the day and go to bed anyway.'),
  ('easing-perfectionism', 53, 'Decide how many times you will proofread one document today, and stick to that number.'),
  ('easing-perfectionism', 54, 'Water the plants, vacuum, or wipe a counter without going back for the spots you missed.'),
  ('easing-perfectionism', 55, 'Give a presentation, update, or toast from a few notes rather than a full script.'),
  ('easing-perfectionism', 56, 'Buy the first suitable gift you find rather than the perfect one.'),
  ('easing-perfectionism', 57, 'Try a new recipe and substitute one ingredient you do not have instead of going to the store for it.'),
  ('easing-perfectionism', 58, 'Write down the worst realistic thing that would happen if a piece of your work went out with a small error.'),
  ('easing-perfectionism', 59, 'Notice how a friend you admire handles their own mistakes, and borrow one of their habits today.'),
  ('easing-perfectionism', 60, 'Let a child or beginner do a task slowly and imperfectly while you keep your hands in your pockets.'),
  ('easing-perfectionism', 61, 'Declare one project finished today by saying its name and the word "done" out loud.'),
  ('easing-perfectionism', 62, 'Choose one photo to send from a set of similar ones without comparing them all first.'),
  ('easing-perfectionism', 63, 'Learn a new skill for fifteen minutes and expect to be bad at it the whole time.'),
  ('easing-perfectionism', 64, 'Let a cake, a wall, or a garden bed have a visible flaw and leave it there for a week.'),
  ('easing-perfectionism', 65, 'Set a timer for how long you will spend on an email longer than three lines, and hit send when it rings.'),
  ('easing-perfectionism', 66, 'Ask a coworker to review your work for errors that matter, not for style, and accept the rest as is.'),
  ('easing-perfectionism', 67, 'Notice the difference today between "this needs fixing" and "this could be better," and only act on the first.'),
  ('easing-perfectionism', 68, 'Wear something with a small stain or wrinkle to a low-stakes errand.'),
  ('easing-perfectionism', 69, 'Write three bullet points instead of the full report, and see whether they cover what people need.'),
  ('easing-perfectionism', 70, 'Hold a party, dinner, or game night and let one part of it be visibly unprepared.'),
  ('easing-perfectionism', 71, 'Skip the last round of edits on a creative piece and share it with one person tonight.'),
  ('easing-perfectionism', 72, 'Run, walk, or stretch without tracking the distance or the time.'),
  ('easing-perfectionism', 73, 'Give yourself one "good enough" pass today on a chore you usually redo until it is right.'),
  ('easing-perfectionism', 74, 'Notice the moment you reach for the redo, and pause for a full breath before deciding whether the redo is worth it.'),
  ('easing-perfectionism', 75, 'Ask a mentor, coach, or older relative how many mistakes they made in their first year of doing something, and listen to their answer.'),
  ('easing-perfectionism', 76, 'Pick the messiest drawer in your kitchen and organize it for five minutes, then close it while it is still imperfect.'),
  ('easing-perfectionism', 77, 'Reply to a group chat with your first thought instead of the wittiest version you could craft.'),
  ('easing-perfectionism', 78, 'Plan a meal for guests with one store-bought dish and do not apologize for it.'),
  ('easing-perfectionism', 79, 'Set your standard for today''s workout as "showed up," and count it as complete the moment you begin.'),
  ('easing-perfectionism', 80, 'Write a to-do list with only three items, and call the day a success if you finish two.'),
  ('easing-perfectionism', 81, 'Notice when you are re-explaining something to make it airtight, and stop after the first clear version.'),
  ('easing-perfectionism', 82, 'Trust the first draft of a text to your boss or client, read it once, and send it.'),
  ('easing-perfectionism', 83, 'Ask your partner or a friend to name one thing you fuss over that they have never once noticed.'),
  ('easing-perfectionism', 84, 'Post a comment or reply online without rewriting it more than once.'),
  ('easing-perfectionism', 85, 'Let the laundry stay folded imperfectly in the drawer instead of refolding it.'),
  ('easing-perfectionism', 86, 'Skip a step in a recipe that you suspect makes no difference, and see whether the dish suffers.'),
  ('easing-perfectionism', 87, 'Notice an all-or-nothing thought like "if I cannot do the full hour, there is no point" and do ten minutes instead.'),
  ('easing-perfectionism', 88, 'Sign up for a class, race, or event before you feel ready for it.'),
  ('easing-perfectionism', 89, 'Estimate how long a task should take, do it in that time, and stop regardless of how it looks.'),
  ('easing-perfectionism', 90, 'Let your handwriting be messy in a card or note, and mail it without rewriting.'),
  ('easing-perfectionism', 91, 'Begin a piece of work in the middle instead of agonizing over the opening line.'),
  ('easing-perfectionism', 92, 'Say yes to a plan tonight even though you have not looked up every option.'),
  ('easing-perfectionism', 93, 'Notice where you hold others to a lower standard than you hold yourself, and borrow that standard for one task today.'),
  ('easing-perfectionism', 94, 'Buy produce that is slightly bruised or oddly shaped, and cook with it.'),
  ('easing-perfectionism', 95, 'Leave a cooking mess for later once, and enjoy the meal while it is hot.'),
  ('easing-perfectionism', 96, 'Turn in a piece of work at the deadline instead of asking for an extension to make it better.'),
  ('easing-perfectionism', 97, 'Try drawing, singing, or dancing for five minutes with no intention of being good at it.'),
  ('easing-perfectionism', 98, 'Give a compliment to someone whose work was imperfect but finished, and notice what you admire about that.'),
  ('easing-perfectionism', 99, 'Make a decision about a purchase under a hundred dollars without reading a single review.'),
  ('easing-perfectionism', 100, 'Notice the sentence "I will do it when I have time to do it right," and do a small piece of it right now.'),
  ('easing-perfectionism', 101, 'Stop rehearsing a phone call you need to make and dial within the next five minutes.'),
  ('easing-perfectionism', 102, 'Let a report or spreadsheet go out with plain formatting and no color-coding.'),
  ('easing-perfectionism', 103, 'Write a thank-you note in two sentences instead of waiting until you can write a heartfelt page.'),
  ('easing-perfectionism', 104, 'Hand a child a task that matters, such as setting the table, and let the result stand.'),
  ('easing-perfectionism', 105, 'Decide on a paint color, plant, or throw pillow within one visit to the store.'),
  ('easing-perfectionism', 106, 'Notice a moment you are rearranging something already tidy, and walk away from it.'),
  ('easing-perfectionism', 107, 'Give an honest, unpolished answer when someone asks how your project is going.'),
  ('easing-perfectionism', 108, 'Set a two-edit limit on a photo before you post or send it.'),
  ('easing-perfectionism', 109, 'Mow, rake, or sweep the yard in a rough pass and call it finished for the week.'),
  ('easing-perfectionism', 110, 'Leave a book, show, or podcast unfinished if you are not enjoying it, without feeling you must complete it.'),
  ('easing-perfectionism', 111, 'Notice one place today where "not yet perfect" is stopping you from sharing something useful, and share it.'),
  ('easing-perfectionism', 112, 'Cook a familiar recipe from memory without checking the exact amounts.'),
  ('easing-perfectionism', 113, 'Ask for feedback on a rough outline instead of waiting until you have a full draft.'),
  ('easing-perfectionism', 114, 'Allow yourself to be a beginner in a conversation about a topic you know little about, and ask an obvious question.'),
  ('easing-perfectionism', 115, 'Set a standard for cleaning before guests arrive that takes one hour, not an afternoon, and stop at the hour.'),
  ('easing-perfectionism', 116, 'Send the invitation for a gathering before you have every detail planned.'),
  ('easing-perfectionism', 117, 'Notice when you are checking a finished task a third time, and put it away instead.'),
  ('easing-perfectionism', 118, 'Wear an outfit that is comfortable rather than the one you think looks most put together.'),
  ('easing-perfectionism', 119, 'Write "B minus work is fine here" at the top of one task, and work to that grade.'),
  ('easing-perfectionism', 120, 'Let a small typo you notice in something you already sent stay uncorrected.'),
  ('easing-perfectionism', 121, 'Pick a project that has been waiting for the perfect conditions and start it in imperfect ones today.'),
  ('easing-perfectionism', 122, 'Hang holiday lights or decorations unevenly, then step back and let them be festive anyway.'),
  ('easing-perfectionism', 123, 'Notice a rule you follow that nobody set for you, such as "every email needs a greeting," and break it once.'),
  ('easing-perfectionism', 124, 'Let the kids decorate cookies, a room, or a card entirely their way, with no touch-ups from you.'),
  ('easing-perfectionism', 125, 'Give a rough estimate at work instead of a precise one, and say plainly that it is rough.'),
  ('easing-perfectionism', 126, 'Make a phone call to a business without writing down what you will say.'),
  ('easing-perfectionism', 127, 'Notice when your standard for a task is "everyone must be impressed," and lower it to "this helps someone."'),
  ('easing-perfectionism', 128, 'Order at a restaurant in under thirty seconds and enjoy whatever arrives.'),
  ('easing-perfectionism', 129, 'Share a hobby project in progress with one person, seams and all.'),
  ('easing-perfectionism', 130, 'Finish a task today at the point where extra effort would only be visible to you.'),
  ('easing-perfectionism', 131, 'Choose the plainer of two options for a gift, a card, or a dish, and see whether it lands just as well.'),
  ('easing-perfectionism', 132, 'Spend fifteen minutes on a task you have been saving for a "perfect block of time."'),
  ('easing-perfectionism', 133, 'Wash the car, windows, or floor once, without a second pass for streaks.'),
  ('easing-perfectionism', 134, 'Let someone else give directions, choose the route, or drive, and stay quiet about how you would do it.'),
  ('easing-perfectionism', 135, 'Write the ugliest first version of an important message, then edit it once and send.'),
  ('easing-perfectionism', 136, 'Notice a moment you compared your beginner efforts to someone''s tenth year of practice, and drop the comparison.'),
  ('easing-perfectionism', 137, 'Tell a coworker or friend about a mistake you made this week, plainly and without excuses or self-blame.'),
  ('easing-perfectionism', 138, 'Take the photo, frame it, and hang it today instead of waiting for the ideal shot.'),
  ('easing-perfectionism', 139, 'Set a rule that meals on weeknights need one pot or pan, and follow it tonight.'),
  ('easing-perfectionism', 140, 'Let the presentation slides have plain text and no images, and give the talk anyway.'),
  ('easing-perfectionism', 141, 'Pick a weekend chore and do only the visible part, leaving the hidden part for another week.'),
  ('easing-perfectionism', 142, 'Try a new exercise class and stand at the back, expecting to get half the moves wrong.'),
  ('easing-perfectionism', 143, 'Give yourself a set number of tries at something today, three at most, and accept the best of them.'),
  ('easing-perfectionism', 144, 'Notice when you are apologizing for something that was merely imperfect, and replace the apology with "here it is."'),
  ('easing-perfectionism', 145, 'Let a gift arrive late rather than searching endlessly for the ideal one.'),
  ('easing-perfectionism', 146, 'Trust a recipe, a guide, or a colleague''s instructions without double-checking them against a second source.'),
  ('easing-perfectionism', 147, 'Look at a task you keep putting off until you can do it properly, and ask what a scrappy version would look like.'),
  ('easing-perfectionism', 148, 'Let the garden have weeds this week and spend the time you saved sitting in it.'),
  ('easing-perfectionism', 149, 'Notice one moment today when the fear of doing something wrong is louder than the task itself, and do the task anyway.'),
  ('easing-perfectionism', 150, 'Bring store-bought cookies to the potluck and put them on your own plate.'),
  ('easing-perfectionism', 151, 'Write your grocery list on the back of an envelope instead of in a neat app.'),
  ('easing-perfectionism', 152, 'Post a work update that says what you did without dressing it up.'),
  ('easing-perfectionism', 153, 'Let the frosting be lopsided and serve the cake.'),
  ('easing-perfectionism', 154, 'Ask a friend to describe a time they saw you do something well but not perfectly, and listen without arguing.'),
  ('easing-perfectionism', 155, 'Cap your research for a purchase at ten minutes and buy the first option that meets your needs.'),
  ('easing-perfectionism', 156, 'Leave a slightly crooked picture on the wall until the weekend.'),
  ('easing-perfectionism', 157, 'Skip your usual final read of a document and let your teammate catch what matters.'),
  ('easing-perfectionism', 158, 'Fold a fitted sheet badly and put it in the closet.'),
  ('easing-perfectionism', 159, 'Do a puzzle, crossword, or game and leave it unfinished when you lose interest.'),
  ('easing-perfectionism', 160, 'Practice saying "that will do" in the kitchen tonight, out loud, about at least one dish.'),
  ('easing-perfectionism', 161, 'Notice the belief that a small mistake will be remembered forever, and recall one mistake someone else made that you have already forgotten.'),
  ('easing-perfectionism', 162, 'Give a half-formed idea in a meeting and let others build on it.'),
  ('easing-perfectionism', 163, 'Decide tonight''s dinner in the time it takes to open the fridge.'),
  ('easing-perfectionism', 164, 'Take on a small home repair with a video tutorial and accept the result even if it is a little rough.'),
  ('easing-perfectionism', 165, 'Write a review, note, or caption in one pass with no edits.'),
  ('easing-perfectionism', 166, 'Notice a moment when you hold back from trying because you might look like a beginner, and try for two minutes.'),
  ('easing-perfectionism', 167, 'Let a child tie their own shoes or zip their own coat, even if it takes twice as long and ends up uneven.'),
  ('easing-perfectionism', 168, 'Say to yourself before a task, "Done is the goal today, not perfect," and watch how your pace changes.'),
  ('easing-perfectionism', 169, 'Pick a recurring meeting and stop preparing more than five minutes for it.'),
  ('easing-perfectionism', 170, 'Send your holiday cards with just a signature this year, no personal note.'),
  ('easing-perfectionism', 171, 'Play a song on an instrument all the way through, mistakes included, without stopping to fix them.'),
  ('easing-perfectionism', 172, 'Notice a moment you delay a reply because you want to word it perfectly, and reply in one plain sentence.'),
  ('easing-perfectionism', 173, 'Let a houseguest see one room you did not clean.'),
  ('easing-perfectionism', 174, 'Give the same effort to a task you would give if nobody were ever going to check it.'),
  ('easing-perfectionism', 175, 'Notice when you are about to say "let me just fix one more thing" and stop at the current version.'),
  ('easing-perfectionism', 176, 'Wear your glasses, hat, or shoes that are slightly worn rather than hunting for a better pair.'),
  ('easing-perfectionism', 177, 'Complete a workout at half the intensity you planned and log it as a full session.'),
  ('easing-perfectionism', 178, 'Let a coworker take over part of a project and thank them for their version without editing it.'),
  ('easing-perfectionism', 179, 'Sketch a floor plan, a garden, or a schedule with a pen instead of erasing your way to a perfect one in pencil.'),
  ('easing-perfectionism', 180, 'Notice when "I have to do it all today" shows up, and pick one third of it.'),
  ('easing-perfectionism', 181, 'Accept a compliment on your work today without pointing out what you would have changed.'),
  ('easing-perfectionism', 182, 'Cook a dish for someone else while narrating out loud the things you are letting slide.'),
  ('easing-perfectionism', 183, 'Publish, post, or hand in a piece with one sentence you are not sure about.'),
  ('easing-perfectionism', 184, 'Set a fifteen-minute timer for getting ready this morning and leave when it rings.'),
  ('easing-perfectionism', 185, 'Ask someone to teach you something small and let yourself be corrected without embarrassment.'),
  ('easing-perfectionism', 186, 'Notice a project you have wanted to restart from scratch, and instead fix the worst single flaw in the current version.'),
  ('easing-perfectionism', 187, 'Buy a plant you might kill and enjoy it while it lasts.'),
  ('easing-perfectionism', 188, 'Give an answer in a meeting before you have checked it twice.'),
  ('easing-perfectionism', 189, 'Leave the towels folded however they were folded by someone else.'),
  ('easing-perfectionism', 190, 'Notice a moment when doing a task adequately feels like failing, and name what "adequate" would actually accomplish.'),
  ('easing-perfectionism', 191, 'Learn three words of a new language today and use one out loud even if the pronunciation is off.'),
  ('easing-perfectionism', 192, 'Let your kids see you make a mistake in the kitchen and shrug it off.'),
  ('easing-perfectionism', 193, 'Set a monthly budget of time, not just money, for a hobby, and stop when the time is spent.'),
  ('easing-perfectionism', 194, 'Send a two-line reply to a long message.'),
  ('easing-perfectionism', 195, 'Order the same simple meal you always do without scanning the whole menu for a better choice.'),
  ('easing-perfectionism', 196, 'Notice the urge to re-record a voice message, and send the first take.'),
  ('easing-perfectionism', 197, 'Plant seeds in uneven rows and see what grows.'),
  ('easing-perfectionism', 198, 'Let a small chip, scratch, or dent in something you own remain unfixed.'),
  ('easing-perfectionism', 199, 'Make a rough sketch of a solution at work and share it before it is neat.'),
  ('easing-perfectionism', 200, 'Notice when you tell yourself you cannot start until you have the right supplies, and start with what you have.'),
  ('easing-perfectionism', 201, 'Choose a book to read in under a minute at the library or store.'),
  ('easing-perfectionism', 202, 'Bring a friend a meal in a container with no lid that matches.'),
  ('easing-perfectionism', 203, 'Set one appearance rule for the week, such as "hair goes up in a minute," and follow it.'),
  ('easing-perfectionism', 204, 'Take the small, obvious next step on a project instead of mapping every step to the end.'),
  ('easing-perfectionism', 205, 'Notice when you compare your first attempt to a professional''s finished piece, and compare it to your own last attempt instead.'),
  ('easing-perfectionism', 206, 'Serve a dinner that includes one dish that did not turn out, and eat it without an explanation.'),
  ('easing-perfectionism', 207, 'Give a coworker credit for finishing something quickly, and notice what "quick and fine" made possible.'),
  ('easing-perfectionism', 208, 'Write a paragraph of fiction, memoir, or a journal entry without pausing to find the right word.'),
  ('easing-perfectionism', 209, 'Leave a job application shorter than the maximum allowed length.'),
  ('easing-perfectionism', 210, 'Notice when you are managing how others will judge your effort, and do the task for its own sake instead.'),
  ('easing-perfectionism', 211, 'Ask a friend how long they spend getting ready, replying to emails, or cleaning, and compare it with your own time honestly.'),
  ('easing-perfectionism', 212, 'Decorate for a holiday with what you already own, without buying one new thing.'),
  ('easing-perfectionism', 213, 'Accept the first available appointment, seat, or table instead of waiting for a better one.'),
  ('easing-perfectionism', 214, 'Hand in a piece of work that has a known small gap, and note the gap in one line instead of filling it.'),
  ('easing-perfectionism', 215, 'Let a teenager or partner cook dinner and eat what they make without suggestions.'),
  ('easing-perfectionism', 216, 'Catch yourself doing something well enough on the first try today, and let that be the whole story.'),
  ('easing-perfectionism', 217, 'Run the meeting from a three-item agenda written on a sticky note.'),
  ('easing-perfectionism', 218, 'Stop matching the colors of the socks, towels, or containers you fold and store today.'),
  ('easing-perfectionism', 219, 'Practice saying "I made a mistake, here is the fix" once today, even about something tiny.'),
  ('easing-perfectionism', 220, 'Give yourself a shorter time to choose an outfit for a special event than you usually take.'),
  ('easing-perfectionism', 221, 'Let a hobby stay a hobby: finish a session without a plan to get better, faster, or more serious.'),
  ('easing-perfectionism', 222, 'Spend five minutes writing down what "finished" means for the biggest thing on your plate, then stop working on it the moment it meets that definition.'),
  ('easing-perfectionism', 223, 'Pack a lunch, a bag, or a suitcase in ten minutes and accept that you may forget one small thing.'),
  ('easing-perfectionism', 224, 'Open a spreadsheet, document, or plan you keep refining and mark it final today.'),
  ('easing-perfectionism', 225, 'Tell someone at work, "This is a first pass, tear it apart," and let them.'),
  ('easing-perfectionism', 226, 'When a recipe says to let the dough rest for an hour, give it forty minutes and see what happens.'),
  ('easing-perfectionism', 227, 'Spend the first ten minutes of your morning without checking how you look in a mirror.'),
  ('easing-perfectionism', 228, 'Reply to a difficult email with the honest, imperfect version instead of the one you have drafted four times.'),
  ('easing-perfectionism', 229, 'Take a class, workshop, or lesson as the least experienced person in the room, on purpose.'),
  ('easing-perfectionism', 230, 'Put a rough handmade thing on display in your home where guests can see it.'),
  ('easing-perfectionism', 231, 'Read one page of something you wrote long ago and count how many "mistakes" you can no longer even find.'),
  ('easing-perfectionism', 232, 'Wrap up a work session by writing "good enough for today" at the bottom of your notes.'),
  ('easing-perfectionism', 233, 'Cut your gift list down to what you can buy in one afternoon, and buy it in one afternoon.'),
  ('easing-perfectionism', 234, 'Leave the comments section, the reviews, or the replies unread after you post something.'),
  ('easing-perfectionism', 235, 'Print a photo without color-correcting it and put it in a frame.'),
  ('easing-perfectionism', 236, 'Split a big cleaning job into "must" and "nice," and do only the "must" column today.'),
  ('easing-perfectionism', 237, 'Tell your kids or your partner that the house will be "lived-in clean" this week, and keep to that standard.'),
  ('easing-perfectionism', 238, 'Volunteer to draft the first version of a group document, knowing it will be rewritten.'),
  ('easing-perfectionism', 239, 'Wear the same reliable outfit two days in a row.'),
  ('easing-perfectionism', 240, 'Finish a knitting, woodworking, or craft piece with a visible flaw and use it anyway.'),
  ('easing-perfectionism', 241, 'Book the trip, the table, or the tickets tonight without comparing every alternative.'),
  ('easing-perfectionism', 242, 'Sit down to a task with a deliberately low goal, such as one paragraph or one drawer, and stop when it is met.'),
  ('easing-perfectionism', 243, 'Ask your manager which parts of a project truly need to be exact, and give the rest a lighter touch.'),
  ('easing-perfectionism', 244, 'Bring a homemade dish to a gathering even though the last time you made it did not go well.'),
  ('easing-perfectionism', 245, 'Put away the ironing board and wear the shirt slightly creased.'),
  ('easing-perfectionism', 246, 'Take a run or a bike ride on a route you have not planned, and turn back whenever you feel like it.'),
  ('easing-perfectionism', 247, 'Change one word in a saved template so it is no longer perfect, and use it that way.'),
  ('easing-perfectionism', 248, 'Speak up early in a discussion with a half-finished thought rather than waiting for the polished version.'),
  ('easing-perfectionism', 249, 'Let a friend see the messy inside of your car, bag, or closet without a joke about it.'),
  ('easing-perfectionism', 250, 'Set a rule for your inbox this week: one reply per message, no follow-up to correct wording.'),
  ('easing-perfectionism', 251, 'Try a haircut, nail color, or style that might not suit you, and give it a week before judging.'),
  ('easing-perfectionism', 252, 'Notice the words "I just want it to be right" today, and ask what "right" is costing you in time.'),
  ('easing-perfectionism', 253, 'Cook breakfast for the household and let the eggs, pancakes, or toast be uneven.'),
  ('easing-perfectionism', 254, 'Hand your phone to someone else to take the group photo, and keep whatever they take.'),
  ('easing-perfectionism', 255, 'Schedule a hard stop for a project you tend to stretch, and honor it tonight.'),
  ('easing-perfectionism', 256, 'Pick a home project to leave at ninety percent, and start enjoying the room now.'),
  ('easing-perfectionism', 257, 'Forgive one small error in someone else''s work today without pointing it out.'),
  ('easing-perfectionism', 258, 'Type an important message with your thumbs, on the go, and send it from wherever you are.'),
  ('easing-perfectionism', 259, 'Approach your workout with the question "did I move?" instead of "did I improve?"'),
  ('easing-perfectionism', 260, 'Draft your bio, resume line, or profile in ten minutes and let it stand for now.'),
  ('easing-perfectionism', 261, 'Decide the level of clean the bathroom needs for you, not for an inspector, and clean to that level.'),
  ('easing-perfectionism', 262, 'Let the kids'' art on the fridge be crooked and overlapping.'),
  ('easing-perfectionism', 263, 'Choose "done today" over "better tomorrow" on one deadline and turn the work in.'),
  ('easing-perfectionism', 264, 'Spend a whole conversation without correcting yourself or clarifying what you meant.'),
  ('easing-perfectionism', 265, 'Turn off the grammar checker for one document and rely on your own reading.'),
  ('easing-perfectionism', 266, 'Take one imperfect step toward learning an instrument, language, or craft you have been waiting to start "properly."'),
  ('easing-perfectionism', 267, 'Serve a salad without arranging it, straight from the bowl you tossed it in.'),
  ('easing-perfectionism', 268, 'Watch how a coworker you respect handles being wrong in a meeting, and try their approach next time you are.'),
  ('easing-perfectionism', 269, 'Buy a card with a printed message and simply sign your name.'),
  ('easing-perfectionism', 270, 'Set the table for guests in five minutes, and spend the saved time with them.'),
  ('easing-perfectionism', 271, 'Notice your urge to explain why something is not your best work, and hand it over without the explanation.'),
  ('easing-perfectionism', 272, 'Paint a wall, a fence, or a piece of furniture and let the brush strokes show.'),
  ('easing-perfectionism', 273, 'Deliver the news, the update, or the ask in a meeting in three sentences, then stop talking.'),
  ('easing-perfectionism', 274, 'Take a photo of your workspace exactly as it is and keep it as a reminder that work happens in mess.'),
  ('easing-perfectionism', 275, 'Leave the tags, labels, or files in your system slightly inconsistent instead of spending an hour standardizing them.'),
  ('easing-perfectionism', 276, 'Ask for a rough version of something from a colleague, and treat it as useful the moment it arrives.'),
  ('easing-perfectionism', 277, 'Practice the phrase "close enough" while measuring, cutting, or pouring something at home tonight.'),
  ('easing-perfectionism', 278, 'Tackle a task by asking "what is the smallest version that would still count?" and doing only that.'),
  ('easing-perfectionism', 279, 'Show a friend a hobby project you consider a failure, and ask what they see in it.'),
  ('easing-perfectionism', 280, 'Adjust an appointment, a plan, or a route on the fly instead of starting over from a clean plan.'),
  ('easing-perfectionism', 281, 'Take a walk without a destination, a step goal, or a podcast.'),
  ('easing-perfectionism', 282, 'Keep a running list this week of mistakes that turned out not to matter, and add one today.'),
  ('easing-perfectionism', 283, 'Trust a store clerk, a mechanic, or a neighbor''s recommendation instead of researching it yourself.'),
  ('easing-perfectionism', 284, 'Turn the sound off on the parts of a task you cannot control, such as how it will be received, and finish the part you can.'),
  ('easing-perfectionism', 285, 'Give a rough answer to "how long will this take?" and let the estimate be wrong.'),
  ('easing-perfectionism', 286, 'Move a project from your "someday, when I am ready" list to "start with what I have," and spend twenty minutes on it.'),
  ('easing-perfectionism', 287, 'Spend a rainy afternoon making something with no plan for how it should turn out.'),
  ('easing-perfectionism', 288, 'Release a small piece of work to a wider audience than you normally would.'),
  ('easing-perfectionism', 289, 'Refuse to redo one thing today that already works.'),
  ('easing-perfectionism', 290, 'Set a "no restarting" rule for the next creative session and keep going even when the beginning is weak.'),
  ('easing-perfectionism', 291, 'Cut the number of items in a presentation, plan, or email in half and send the shorter one.'),
  ('easing-perfectionism', 292, 'Sit through a meal you cooked without listing what you would do differently next time.'),
  ('easing-perfectionism', 293, 'Deal with an error you find in old work by asking whether anyone was harmed, and if not, leave it.'),
  ('easing-perfectionism', 294, 'Start the day by naming one thing you will let be imperfect, and check in at bedtime to see whether it mattered.'),
  ('easing-perfectionism', 295, 'Introduce yourself to someone new without steering the conversation to show your best side.'),
  ('easing-perfectionism', 296, 'Trim a hedge, a beard, or a fringe of hair in one careful pass, then step back rather than evening it out endlessly.'),
  ('easing-perfectionism', 297, 'Look at an inbox with ten replies waiting and answer all ten in twenty minutes, plainly.'),
  ('easing-perfectionism', 298, 'Bring a friend into a task you usually do alone because only you do it right, and share the work.'),
  ('easing-perfectionism', 299, 'Complete an online course lesson without taking notes on every detail.'),
  ('easing-perfectionism', 300, 'Allow one visible imperfection in your holiday table, such as a paper napkin or a store-bought pie.'),
  ('easing-perfectionism', 301, 'Speak a few sentences in a language you are learning to someone who speaks it, expecting to get some of it wrong.'),
  ('easing-perfectionism', 302, 'Give your best guess on a quiz, form, or trivia question instead of looking it up.'),
  ('easing-perfectionism', 303, 'Photograph your meal, your project, or your view once and put the camera down.'),
  ('easing-perfectionism', 304, 'Pass your notes to a colleague in their raw state, without tidying them first.'),
  ('easing-perfectionism', 305, 'Trust yourself to remember a short list instead of writing it down and checking it twice.'),
  ('easing-perfectionism', 306, 'Leave a comment on a friend''s post with a single emoji or a single word.'),
  ('easing-perfectionism', 307, 'Write your holiday or vacation plans on one page and stop planning there.'),
  ('easing-perfectionism', 308, 'Skip the practice run for a small recipe, speech, or route and do the real thing first.'),
  ('easing-perfectionism', 309, 'Allow a sibling, parent, or partner to wrap the gifts their way.'),
  ('easing-perfectionism', 310, 'Dress for comfort at a family event and notice how much attention your clothes actually receive.'),
  ('easing-perfectionism', 311, 'Redefine a "bad" workout as one you did not do, and count everything else as good.'),
  ('easing-perfectionism', 312, 'Say "I do not know yet" to a question at work and let the sentence sit without filling the silence.'),
  ('easing-perfectionism', 313, 'Leave the last dish in the sink overnight.'),
  ('easing-perfectionism', 314, 'Tell a story at dinner without worrying about getting every detail right.'),
  ('easing-perfectionism', 315, 'Frame a piece of your own art or your child''s, flaws included, and hang it in a room you use every day.'),
  ('easing-perfectionism', 316, 'Aim to be on time rather than early for one appointment, and see whether anything changes.'),
  ('easing-perfectionism', 317, 'Pick the first name that comes to mind for a document, folder, project, or pet, and keep it.'),
  ('easing-perfectionism', 318, 'Sew, glue, or tape a repair that holds rather than one that is invisible.'),
  ('easing-perfectionism', 319, 'Book a haircut or appointment with someone new without reading their reviews.'),
  ('easing-perfectionism', 320, 'Bring an unpolished idea to a brainstorm and let it be picked apart without defending it.'),
  ('easing-perfectionism', 321, 'Finish a crossword, a level, or a chapter with a couple of guesses rather than getting every answer right.'),
  ('easing-perfectionism', 322, 'Rewrite one rule you hold, such as "my house must be spotless for guests," into a gentler one you can actually live by.'),
  ('easing-perfectionism', 323, 'Let a group project have a section that is not up to your standard, and let it belong to the person who wrote it.'),
  ('easing-perfectionism', 324, 'Ask an experienced friend to tell you about their first, terrible attempt at something they are now good at.'),
  ('easing-perfectionism', 325, 'Choose a running, cycling, or swimming pace that is easy enough to keep talking, and hold it the whole way.'),
  ('easing-perfectionism', 326, 'Spend fifteen minutes on a craft or hobby you gave up because you were not good enough at it.'),
  ('easing-perfectionism', 327, 'Hand in a form, essay, or report with an answer you are only fairly sure about.'),
  ('easing-perfectionism', 328, 'Go to bed with a small mess in the kitchen and see how you feel about it in the morning.'),
  ('easing-perfectionism', 329, 'Say something in a meeting that is useful but not brilliant.'),
  ('easing-perfectionism', 330, 'Cook without tasting and adjusting the seasoning more than once.'),
  ('easing-perfectionism', 331, 'Ask a colleague to take a task off your plate that only you have ever done, and walk them through it once, not three times.'),
  ('easing-perfectionism', 332, 'Write a limerick, a joke, or a caption that is only mildly funny, and share it anyway.'),
  ('easing-perfectionism', 333, 'Pull one thing from your "redo" pile and decide to leave it exactly as it is, permanently.'),
  ('easing-perfectionism', 334, 'Skip color-coding, labeling, or sorting for a project this week, and notice whether the work still gets done.'),
  ('easing-perfectionism', 335, 'Send a rough sketch or wireframe to a client or teammate instead of a finished mockup.'),
  ('easing-perfectionism', 336, 'Buy the paint, the plant, or the frame that is in stock rather than ordering the exact one you pictured.'),
  ('easing-perfectionism', 337, 'Practice handing something over with the words "here is a start" instead of "sorry, it is not finished."'),
  ('easing-perfectionism', 338, 'Delegate the family''s dinner plans to the person least likely to plan them your way.'),
  ('easing-perfectionism', 339, 'Walk out the door with a coat that does not match your shoes.'),
  ('easing-perfectionism', 340, 'Name the standard you set for a task this morning, then set it one notch lower before you begin.'),
  ('easing-perfectionism', 341, 'Give a toast, a thank-you, or a welcome from the heart without notes or a rehearsal.'),
  ('easing-perfectionism', 342, 'Take a beginner''s swimming, dance, or pottery class and enjoy being the worst in the room for an hour.'),
  ('easing-perfectionism', 343, 'Leave a piece of furniture assembled with one small part done imperfectly, as long as it is safe and stable.'),
  ('easing-perfectionism', 344, 'Answer a survey, a quiz, or a form quickly instead of weighing each option.'),
  ('easing-perfectionism', 345, 'Stop editing a photo or a video after the second change.'),
  ('easing-perfectionism', 346, 'Bake bread or cookies and let them be a little misshapen, then share them the same day.'),
  ('easing-perfectionism', 347, 'Ask a teammate to send you their "rough enough" version of something, and thank them for not polishing it.'),
  ('easing-perfectionism', 348, 'Let one of your children or a younger relative teach you something, and let yourself do it wrong the first few times.'),
  ('easing-perfectionism', 349, 'Spend twenty minutes on a task you would normally give two hours, and see how much of the result you keep.'),
  ('easing-perfectionism', 350, 'Look for one place in your day where perfect and good would look identical to everyone else, and choose good.'),
  ('easing-perfectionism', 351, 'Turn off the "one more pass" instinct on a chore tonight by setting a timer for five minutes and quitting at the bell.'),
  ('easing-perfectionism', 352, 'Deliver a piece of work early and rough rather than late and polished.'),
  ('easing-perfectionism', 353, 'Wash your hair, skip the styling, and go about your day.'),
  ('easing-perfectionism', 354, 'Set a limit of three drafts for anything you write this week, and hit send on the third.'),
  ('easing-perfectionism', 355, 'Give a piece of feedback to someone without softening it into perfection or over-explaining.'),
  ('easing-perfectionism', 356, 'Assemble a meal from leftovers without a recipe and serve it with a name you make up on the spot.'),
  ('easing-perfectionism', 357, 'Choose a workout on the spot from whatever equipment or space is in front of you rather than the ideal plan.'),
  ('easing-perfectionism', 358, 'Take a family photo where someone is blinking, and keep it as the official one.'),
  ('easing-perfectionism', 359, 'Read an instruction manual once and then try the device, expecting to figure out the rest by using it.'),
  ('easing-perfectionism', 360, 'Let the guest room have a few of your things in it when someone stays over.'),
  ('easing-perfectionism', 361, 'Trust your first ranking of options today, whether jobs, restaurants, or paint chips, and act on it.'),
  ('easing-perfectionism', 362, 'Notice how much you enjoy a task once you stop grading it, and stay in that mode for the rest of the hour.'),
  ('easing-perfectionism', 363, 'Finish today''s version of a long project, save it, and close the file without opening it again tonight.'),
  ('easing-perfectionism', 364, 'Practice letting a small error stand in a conversation: do not correct the date, name, or detail you got slightly wrong.'),
  ('easing-perfectionism', 365, 'End the day by naming one imperfect thing you finished, and let that be what you remember about today.')
) as v(slug, day, task)
join public.challenge_templates t on t.slug = v.slug;
