-- Five articles published 2026-09-30. Generated by:
--   python3 tools/articles_sql.py --since 2026-09-30
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('the-loneliness-of-working-alone-all-day', 'The Loneliness of Working Alone All Day', 'You are in meetings all day and still have not had a conversation. Why working alone drains people quietly, and what small amounts of contact actually fix it.', 'You logged on at half past eight. You have been in four calls. You have typed several hundred messages. It is now six in the evening and you realize you have not had a single conversation all day.

This is one of the odd shapes loneliness takes now. Not an empty diary, not a lack of people, but a whole day of contact that somehow does not count.

If you work from home, work remotely, drive for a living, or run something on your own, you probably recognize it. And because you were technically surrounded by people all day, it is easy to conclude the problem must be you.

Contact is not the same as company

The contact that leaves you feeling connected has a few features, and work contact often has none of them.

It is unstructured: nobody has an agenda. It is unnecessary: it is not there to produce anything. It involves being seen as a person rather than as a role. And it usually has a body in it, or at least a voice, rather than text.

A day of meetings can be full of contact and contain none of that. You were a function all day. Useful, engaged, and never actually met.

What working alone quietly removes

Offices have a lot of accidental contact, and its value is invisible until you lose it.

The two minutes at the kettle. Overhearing a joke. Someone noticing you look tired. Walking out at the same time as a colleague. Complaining about something small to a person who understands the context without explanation.

None of it is friendship, and all of it is company. Working alone removes the entire category at once, and nothing replaces it by default. So the week can be busy, sociable on paper, and still short of the thing that makes a person feel among others.

Notice which kind of empty it is

Two things get mixed up here, and they need different repairs.

One is being alone too much: a genuine shortage of contact. That one responds to more people, in almost any form.

The other is being with people all day without being known. That one does not respond to more contact; it responds to different contact. Adding another call will make it worse. One honest ten-minute conversation will help more than five meetings.

Ask yourself which of the two today was, and you will usually know immediately.

The repairs are smaller than you expect

People imagine fixing this requires a new social life. In practice it usually takes a few small, repeatable things.

Put one voice in your day on purpose. A phone call rather than a message, ten minutes, no agenda. Voice carries far more than text does, and hearing someone''s tone is most of what makes contact land.

Work near other people once or twice a week, even without talking to them. A library, a cafe, a shared desk somewhere. Being among people has some of the effect of talking to them, and it costs nothing socially.

Have one appointment in the week that is not about work and involves the same people each time: a class, a team, a volunteer shift, a walk with a neighbor. Repetition is what turns contact into familiarity, and familiarity is what stops a week feeling anonymous.

And build in one leaving-the-house trip a day, however trivial. The errand is not the point; the point is being a person in the world for twenty minutes.

Change the shape of work contact where you can

Some small changes make work itself less isolating.

Start one call a week with two minutes that are not about the task, and let it be genuine rather than performed. Turn a long thread into a short call when the subject is at all delicate. Ask one colleague how they actually are and stay for the answer.

If you manage people who work alone, know that a check-in about deliverables is not contact. A five-minute call about nothing in particular does more for someone''s week than another status update.

The trap worth naming

Loneliness makes people less likely to reach out, not more. It lowers your energy, makes contact feel effortful, and quietly suggests that other people are busy and would rather not hear from you.

That means the days you most need company are the days you are least likely to arrange it. The way around it is to decide in advance, not in the moment: a standing call on Wednesdays, a class already paid for, a walk that happens whether or not you feel like it.

Lower the bar for what counts, too. Sending one message is contact. Ten minutes is contact. You are not looking for a great evening; you are looking to not go a whole week unmet.

What about the parts that are not fixable

Some of this is the job. If you drive alone, work nights, or live somewhere remote, no amount of scheduling turns your week into an office.

In that case, aim for depth rather than frequency: two or three people you speak to properly and regularly, rather than trying to manufacture a crowd. A small number of real connections carries a person much further than a busy calendar.

When it is more than a quiet week

If loneliness has become constant, if it has started to feel like a fact about you rather than about your circumstances, or if it comes with low mood, hopelessness or a pull to withdraw further, it is worth talking to someone. Loneliness is one of the most common things people bring to therapy and one of the least embarrassing, and a therapist can help with both the practical side and the part that has started telling you that you are not worth anyone''s time. A doctor is also a reasonable place to start if your mood or sleep has gone with it.', array['Loneliness', 'Work']::text[], 0, '2026-09-30T14:00:00+00:00'::timestamptz),
  ('saying-you-cannot-afford-it', 'Saying You Cannot Afford It', 'The group trip, the dinner, the gift, the wedding. How to say no to something you cannot pay for without over-explaining, apologizing, or quietly putting it on a card.', 'The group chat is deciding on a weekend away. The number goes past what you can spend, and everyone else says yes. You type something, delete it, and then type: sounds great.

Most people have done some version of this. It is rarely about being bad with money. It is about a particular kind of exposure: saying you cannot afford something tells people something about you that you did not choose to share.

The cost of the quiet yes

Saying yes when you cannot pay has three bills attached.

There is the money itself, sometimes on a card, sometimes taken out of something that mattered more. There is the dread in the weeks beforehand, which usually spoils whatever you agreed to. And there is the precedent: once you have said yes at this level, next time is assumed.

None of that is visible to the people you said yes to. From the outside it looked easy, which is exactly why it keeps happening.

You do not have to open the books

The most common mistake is over-explaining. People are afraid a plain no will sound rude, so they add context: a long account of the boiler, the vet bill, the hours that got cut.

That tends to backfire. Detailed explanations invite negotiation, because now people can try to solve your problem or argue with your figures. A short answer with no accounting behind it is much harder to argue with, and it leaves your privacy intact.

The useful version is one sentence: that is more than I can spend right now. No apology tour, no figures, no story.

What to say, depending on the ask

For a group plan you want to be part of: that is out of my range this year, but I would love to see you. Then propose a version you can afford, if you want one.

For a dinner you can attend but not at that level: I am going to come and just have something small, and I would rather we split by what each of us ordered.

For a gift: I am keeping gifts small this year. That is all. It stands on its own.

For a wedding or a milestone that involves travel: I cannot make the trip work this time, and I am sorry to miss it. Weddings are where people most often spend money they do not have, out of a fear of being seen as not caring, and the fear is almost always larger than the actual reaction.

For a recurring cost, like a group subscription or a regular night out: I am going to drop out of this one. Said once, plainly, rather than by slowly becoming unavailable.

Expect the two-second wobble, then nothing

The moment after you say it is the uncomfortable part. Sit through it rather than filling it.

Most people respond with something entirely unremarkable: fine, no problem, next time. Some are quietly relieved, because they were in the same position and nobody had said it first. That happens far more than people expect, and one person naming a limit often changes the whole plan.

If someone pushes, repeat the same sentence rather than producing a new argument. It is more than I can spend right now works as many times as it needs to. Adding reasons gives them something new to push against; repeating gives them nothing.

The one response worth preparing for

Occasionally someone offers to cover you. That is kind and it can be awkward, and you are allowed either answer.

If you want to accept, accept cleanly: thank you, that is generous, I will take you up on it. If you do not want to be carried, that is also fine: I appreciate it, but I would rather not, let us do something cheaper instead.

What is worth avoiding is accepting while feeling in debt, because that turns a nice evening into something you are paying off socially for months.

Get ahead of it where you can

Most of the strain comes from deciding in the moment, under pressure, in front of everyone.

So decide beforehand. Know roughly what you can spend on social things this month, and know your line before the group chat starts. Say your number early in a group plan rather than late, because early is when it shapes the plan and late is when it looks like an objection.

And notice who you are protecting. Often the person you most fear disappointing has no idea there is a limit, because you have always absorbed it.

When money is the bigger problem

If you are regularly saying yes with money you do not have, if debt is growing, or if you cannot look at your accounts at all, the conversation is bigger than one weekend away. Free, nonprofit credit counseling exists in most places and is more practical than people expect, and a doctor or a therapist is the right place to take the part that is not arithmetic: the shame, the sleeplessness, or the sense that being honest about money would cost you the people around you.', array['Money', 'Assertiveness']::text[], 0, '2026-09-30T14:00:00+00:00'::timestamptz),
  ('a-body-scan-you-can-do-in-bed', 'A Body Scan You Can Do in Bed', 'A slow tour of your own body, from feet to head, done lying down. What it is for, how to run one, and why it is fine to fall asleep partway through.', 'You are lying down, tired, and your mind is still going. Telling yourself to relax is not working, and neither is telling yourself to stop thinking.

A body scan is a different move. Instead of managing your thoughts, you give your attention a slow, undemanding job somewhere else: the body, one part at a time, from the feet up.

It is the most forgiving practice in this whole area, because it has almost no way to go wrong and it works even when you are doing it badly.

What it actually is

You lie on your back, or on your side if that is more comfortable, and move your attention through your body in order: feet, lower legs, knees, thighs, hips, belly, back, chest, hands, arms, shoulders, neck, jaw, face, head.

At each place you spend a few breaths noticing what is there. Not changing it, not fixing it. Warmth, coolness, weight, tingling, tightness, nothing at all. Nothing at all is a completely acceptable answer, and beginners get it constantly.

That is the whole practice. Fifteen minutes if you have them, five if you do not.

Why noticing rather than relaxing

Most people arrive expecting to relax on command, and instructing yourself to relax usually adds pressure rather than removing it.

Noticing works better for two reasons. It is something you can actually do, whereas relaxing is a result you cannot force. And attention has a way of loosening whatever it settles on, without being asked to.

So the instruction is: go there, notice, move on. If the shoulder softens, good. If it does not, you still did the practice correctly.

How to run one

Lie down somewhere you are warm enough. Let your arms rest at your sides, palms wherever they fall.

Take three slower breaths, with the out-breath longer than the in-breath, just to arrive.

Put your attention on your left foot. Notice the sole, the toes, the top of the foot, whatever is there for two or three breaths. Then move to the lower leg, the knee, the thigh. Do the right leg the same way.

Move up through the hips and the belly, and notice the belly rising as you breathe. Then the lower back and the upper back against the mattress. Then the chest.

Do the hands, one at a time, then the arms and shoulders. Shoulders often hold a lot; give them a few extra breaths but do not go to work on them.

Then the neck, the jaw, the space around the eyes, the forehead, the scalp. Jaws are often clenched without their owner knowing.

At the end, hold the whole body at once for a few breaths: one thing, lying down, breathing.

When your mind wanders, which it will

It will wander constantly. That is not a failure, it is the practice; the whole exercise is noticing you have gone and coming back.

So when you find yourself planning tomorrow, note where you had got to, and return to that part of the body. If you cannot remember, start again from the feet. Nobody is counting.

You may need to come back thirty times in ten minutes. That is thirty repetitions of the skill, which is more than the person who drifted off for the whole ten got.

Falling asleep is allowed

Many people use this at bedtime and never finish it. That is a fine outcome, not a wasted attempt.

If sleep is what you are after, do it lying in bed, in the dark, and let the practice be the last thing you do rather than something you complete. If you want to be awake for it, do it earlier in the evening, or lie on the floor, which is markedly harder to fall asleep on.

And if you wake at three in the morning, a body scan is a reasonable thing to do rather than lying there arguing with your thoughts. Start at the feet. You may or may not reach your head.

When it does not feel good

Turning attention to the body is not neutral for everyone.

If you live with chronic pain, going to a painful area can amplify it. It is fine to go around it: notice the parts that are quiet and touch the painful part briefly or not at all.

If attention to your body brings anxiety, panicky feelings, or a sense of being unsafe, that is worth respecting rather than pushing through. Try keeping your eyes open, sitting up instead of lying down, doing only the hands and feet, or doing it with a light on. Shorter is better than braver.

For some people, especially after trauma, this kind of inward attention can open more than they expected. If that happens, stop, get up, do something ordinary with your hands, and take it up with a therapist who works with trauma before trying again on your own.

When to bring in help

If you cannot sleep most nights, if a painful part of your body is getting worse, or if attention inward reliably brings distress, a body scan is not the tool for that on its own. A doctor can look at sleep and pain properly, and a therapist can help with the rest. This practice sits alongside that kind of help rather than replacing it.', array['Mindfulness', 'Sleep']::text[], 0, '2026-09-30T14:00:00+00:00'::timestamptz),
  ('accepting-something-you-cannot-change', 'Accepting Something You Cannot Change', 'Acceptance is not approval, and it is not giving up. What it means to stop fighting a fact you cannot alter, and why refusing usually costs more than the fact itself.', 'There is a fact in your life that should not be true. The diagnosis, the layoff, the person who is not coming back, the years you cannot have again, the thing that was done to you.

You have argued with it. Not out loud, but in the part of your mind that keeps returning to how unfair it is and how it was not supposed to go this way. That argument can run for years, and it never once changes the fact.

Acceptance is what people call the alternative, and it is one of the most misunderstood words in this whole area.

What acceptance is not

It is not saying the thing is acceptable. Terrible things are not made acceptable by being accepted.

It is not approval, forgiveness, or letting anyone off. It is not being fine with it, and it is not liking it.

And it is not giving up. You can accept that something has happened and still work hard to change what comes next. In fact you usually work better, because arguing with what already happened uses the energy you would need.

Acceptance is just this: acknowledging that reality is what it is, including the parts you hate, and stopping the fight against the fact itself.

The bill for refusing

Refusal feels like loyalty to yourself, which is why it is so hard to put down. But it has costs.

You keep re-running the moment, hunting for the version where it goes differently. You put your life on hold until it is fixed, or until someone admits what they did. You spend your days somewhere that no longer exists, and the present passes with nobody in it.

There is a phrase worth remembering: pain is what happened, and suffering is what you add by insisting it should not have. The first one is unavoidable. The second one is where almost all of the extra weight lives.

It is a decision you make many times

People expect acceptance to be a single moment, like a door closing. It almost never is.

It is more like a turn you make repeatedly. You notice you are back in the argument, you turn toward what is true, and ten minutes later you are back in the argument again. That is normal, and it is not evidence that you are doing it wrong.

Over weeks, the turning gets faster and the arguing gets shorter. That is what progress looks like here; it does not look like never minding.

What it involves, practically

Say the fact plainly, in the simplest words you have. This happened. He is not coming back. My body does not work the way it did. Vague language keeps the fight alive; plain language is what you are trying to be able to hold.

Notice where you feel the refusal in your body, and let your body stop fighting too. Unclench your hands, drop your shoulders, breathe out longer than you breathe in. Acceptance is at least half physical, and a rigid body keeps a rigid position.

Allow the grief that follows. Accepting something is usually followed by sadness rather than relief, and people often read the sadness as a sign it went wrong. It is the opposite: the sadness is what was underneath the arguing.

Then ask the only forward-facing question: given that this is true, what do I want to do now? Not what should have been, but what is available.

Be careful with the word acceptance around other people

If someone is in the middle of something terrible, telling them to accept it usually lands as being told to shut up. It is a thing a person does for themselves, in their own time, and it cannot be handed over.

The same goes for yourself. If a fact is very fresh, you do not have to be anywhere near acceptance yet. Early on, the job is getting through the week, not making peace with it.

Where acceptance is the wrong tool

Not everything unchangeable is actually unchangeable, and this is worth checking honestly.

If the situation can be changed, even partly, change it. Acceptance is for facts, not for problems with available solutions, and it makes a poor excuse for tolerating something that could be different.

And it is never a reason to accept being harmed. If someone is hurting you, the fact to accept might be that they are unlikely to change, which usually points toward action rather than endurance.

The line that helps most people

One sentence does a surprising amount of the work, and it is worth having ready: this is how it is right now, and I do not have to like it.

Both halves matter. The first stops the argument with reality. The second means you are not required to pretend, which is what makes the first one possible.

When you cannot get there alone

Some facts are too heavy to accept by yourself, and trying harder is not the answer. A loss that has not moved in a long time, something that was done to you, or a diagnosis that changed everything are all worth working through with a therapist, and this kind of acceptance is standard ground in several practical therapies. If you find yourself stuck in the argument for most of your waking hours, or if it has begun to feel like there is no point in anything, please talk to a doctor or a therapist about it rather than carrying it quietly.', array['DBT', 'Resilience']::text[], 0, '2026-09-30T14:00:00+00:00'::timestamptz),
  ('taking-a-real-day-off', 'Taking a Real Day Off', 'A day with no work in it can still leave you flat. What separates a day off that restores you from one that disappears, and how to build the first kind on purpose.', 'You had the whole day. You did not work. By nine in the evening you could not say where it went, and you do not feel any better than you did yesterday.

This is a common and demoralizing experience, especially for people who are running low. The day was technically free, and it gave nothing back.

The problem is usually not that you rested wrong. It is that nothing in the day was different enough from your working life for your system to register that it had stopped.

Absence of work is not the same as rest

A day off is defined by what it lacks. Recovery is defined by what it contains.

So you can remove work entirely and still spend the day in the same posture, in the same rooms, on the same screen, in the same low-grade state of half-alertness. Nothing has changed except the task, and your body cannot tell the difference between working and waiting to work.

That is why a day of scrolling leaves people flat. It is not lazy; it is just not different from anything.

The things that make a day feel like it happened

Look back at days off that did leave you better, and you will usually find some of these.

Something outdoors, even briefly. Some movement, at any pace. Something with your hands. Something with a person you like. Something absorbing enough that you lost track of time. Something with a clear beginning and end, so the day has a shape you can remember.

You do not need all of them. Two is usually enough to turn an empty day into one that registers.

Pick one anchor and let the rest be loose

Planning a day off in detail is its own kind of work, and people rightly resist it.

The version that works is one anchor: a single thing, with a time, that is not admin. A swim at eleven. A walk with someone at two. Baking something in the afternoon. Then let the rest of the day be shapeless.

The anchor does the important job of dividing the day. Before it and after it, the hours are yours and it does not matter much what happens in them, because the day now has something in it besides its own passing.

The admin question

Days off get eaten by errands, and pretending otherwise is unrealistic.

The useful compromise is to give admin a slot rather than the day. Ninety minutes in the morning, list written the night before, and then closed. What is left waits.

Beware the two-hour job that expands to fill everything: the one where you decide to reorganize the whole cupboard while you are in there. Set a timer if that is a thing you do.

Rest is not one thing

People default to the same kind of rest and then wonder why they are still tired.

If your week is mentally demanding, lying still may not help as much as doing something physical. If your week is physically hard, stillness is the thing. If your week is full of people, you may need solitude; if you have been alone all week, more solitude will not help at all, however much you feel like it.

So ask what your week actually took from you, and aim the day at that. The answer is often the opposite of what you feel like doing at the time.

Screens, honestly

You do not have to give up your phone to have a good day off. But a whole day inside it is the most reliable way to have one that vanishes.

A practical middle: keep the first hour and the last hour of the day off it, and put it in another room during your anchor. That is usually enough to leave the day with edges you can remember.

If your day off is not your own

Plenty of people have days off that contain small children, a relative who needs care, or a second job. Anchors and loose hours are not really available.

In that case, aim much smaller and more specific: twenty minutes that are yours, at a time somebody else has agreed to cover, doing something you actually chose. That is not a consolation prize. For people carrying a lot, a defended twenty minutes does more than a theoretical free day that never arrives.

And ask for it in those terms. Saying I need Saturday morning for two hours is far easier for someone to agree to than saying you need a break.

When one day off is not enough

If you get to the end of a proper day off and feel nothing, and that has been true for a while, the problem is probably not the day. Exhaustion that survives a weekend, dread on the night before work, and a general flatness tend to mean the load itself is too heavy for the recovery available, and no amount of clever weekends fixes that.

That is worth saying to someone who can change something: a manager, a partner, the people who assume you will absorb it. And if the tiredness comes with low mood, poor sleep, or a sense that nothing is worth doing, please talk to a doctor or a therapist, who can help work out how much of it is exhaustion and how much is something that needs treating.', array['Burnout', 'Self-Care']::text[], 0, '2026-09-30T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
