-- Five articles published 2026-09-19. Generated by:
--   python3 tools/articles_sql.py --since 2026-09-19
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('living-in-fear-of-the-next-panic-attack', 'Living in Fear of the Next Panic Attack', 'The attack itself lasted minutes. The fear of the next one has lasted months. Why the dread between attacks can shrink your life more than the attacks do, and how to take it back.', 'The panic attack was terrible, and it ended. What has not ended is the watching. You scan your body for the first flutter. You avoid the grocery store where it happened, then the highway, then anywhere you could not leave quickly. You carry water and a plan and a quiet dread, and you organize your days around the possibility of something that may never come.

If this is you, you have discovered the part of panic that nobody warns you about. The attacks are frightening, but they are short. The fear of the next one is what moves in and stays.

How the fear takes over

After an attack, the mind does what minds do after a scare: it tries to make sure it never happens again. It starts monitoring. Every heartbeat, every breath, every slight dizziness gets checked against the question, is this the start of one?

The trouble is that a body under this kind of surveillance produces plenty to notice. Hearts skip. Breathing changes. Standing up quickly makes anyone lightheaded. Each ordinary sensation becomes a possible alarm, the alarm creates real fear, and the fear produces exactly the sensations you were watching for. The watching becomes the trigger.

Then the avoidance starts. You skip the place where it happened. Relief. You skip a similar place. More relief. Each avoided place teaches your mind that the place was dangerous, and the list grows. Eventually the fear of panic has taken more from you than any single attack did.

What an attack is, and is not

It helps to hold onto the facts. A panic attack is your body''s emergency system firing without an emergency. It floods you with adrenaline, speeds your heart, quickens your breath, and tells you to run or fight. It is intensely uncomfortable, and it is not dangerous. It does not cause heart attacks, fainting, or losing your mind. It peaks within minutes and then subsides, because the body cannot hold that state for long.

You have survived every attack you have had. That is not luck. It is how they work.

Stop scanning

The first thing to change is the monitoring. When you catch yourself checking your body, name it: I am scanning. Then deliberately put your attention somewhere outside yourself. What can you see in the room? What is someone saying? What does the task in front of you need? You will drift back to scanning; that is fine. Redirect again. You are teaching your attention that it does not have to stand guard.

Let the sensations be there

When you notice a flutter or a skipped breath, try a different response than alarm. Oh, there is a fast heartbeat. That is a sensation. It can be here. The goal is not to make it stop, because trying to make it stop is what turns it into panic. The goal is to let it pass through without a fight. It will, usually faster than you expect.

Some people find it useful to practice this on purpose: run up the stairs to get the heart going, spin in a chair to feel dizzy, breathe through a straw for a minute. Feeling the sensations in a safe setting, and learning that they fade on their own, takes away a lot of their power. If you try this, go slowly, and consider doing it with a therapist''s guidance first.

Take back the places one at a time

Avoidance keeps the fear alive, so the way out is to go back, gradually and on purpose. Make a list of the places and situations you have been avoiding, from easiest to hardest. Start with the easiest. Go, stay until the discomfort drops even a little, and leave when you decide to, not when panic decides for you. Then do it again. Then move up the list.

You are not trying to prove you will not panic. You are proving that if you do, you can handle it. That is the belief that ends the fear.

Drop the safety props

The water bottle, the pills you never take, the friend who has to be there, the seat by the exit. These feel protective and they keep the fear going, because every time you get through a situation with the prop, your mind credits the prop rather than you. Try leaving one behind at a time. Notice that nothing changes except the story.

Let the attack come if it comes

The deepest shift is a strange one: stop fighting to prevent the next attack. Say to yourself, if it comes, it comes; I know what it is, and I know it ends. This is not giving up. It is refusing to make an enemy of your own body. People often find that the attacks come less once they stop being braced for them.

If you have thoughts of not wanting to be here

Living in this kind of fear can wear a person down until it feels hopeless. If you ever have thoughts of harming yourself, please tell someone right away. In the US you can call or text 988 at any time.

When to get help

If the fear of panic is shaping where you go, what you do, or who you can be with, please talk to a therapist, ideally one who works with panic and anxiety. This is one of the most treatable problems there is, and the treatment is essentially a guided version of what is described here. A doctor can also check that nothing physical is going on, which is worth doing once so you can stop wondering. You do not have to live braced. That is a life you can get back.', array['Panic', 'Worry']::text[], 0, '2026-09-19T14:00:00+00:00'::timestamptz),
  ('how-to-stop-overexplaining-yourself', 'How to Stop Overexplaining Yourself', 'You say no, then add three reasons, an apology, and an offer to make it up to them. Why some of us cannot let a simple answer stand, and how to say what you mean and stop there.', 'Someone asks if you can help them move on Saturday. You cannot. What comes out is: Oh, I am so sorry, I would really love to, but I have this thing with my sister, well, it is not definite, but she has been going through a lot and I promised, and I feel terrible, maybe I could come by Sunday instead, or I could send a gift card for pizza?

All you needed to say was no. But the no felt naked, so you dressed it in reasons, apologies, and offers until it was buried. If this is how you talk, you already know how exhausting it is. Here is why it happens and how to stop.

Where overexplaining comes from

Most people who overexplain learned early that a plain answer was not safe. Maybe a parent needed a justification for everything and got angry without one. Maybe you were the peacemaker in a tense house and learned to head off conflict before it started. Maybe you were told, in words or in silence, that your needs were an imposition and required an excuse.

So you built a habit: pad every no, every request, every opinion with enough reasons that nobody could be upset. It worked, once. Now it runs on its own, and it costs you.

What it costs

Overexplaining sounds polite, but it does a few unhelpful things. It signals that your answer is up for debate: every reason you give is a thing the other person can argue with. It hands them your worry, so they end up reassuring you instead of just hearing you. It makes you look less certain than you are. And it is tiring, for you and for them.

Most of all, it keeps you from ever finding out whether a simple answer would have been fine. It almost always would.

A reason is not a permission slip

Here is the belief under the habit: I am only allowed to say no if I have a good enough reason. That is not true. You are allowed to say no because you do not want to. That is a complete reason. You do not owe anyone an account of your Saturday.

Try saying it to yourself a few times: I can decline without justifying it. It will feel wrong. That is just the old rule protesting.

Practice the short version

Start with low-stakes moments. When a coworker asks if you want to grab lunch and you would rather not: No thanks, not today. Full stop. When someone asks a favor you cannot do: I cannot this time. When you disagree in a meeting: I see it differently; I think we should wait.

Then the hard part. Stop talking. Let the silence sit. The urge to fill it with reasons will be strong. Count to three in your head. Most of the time the other person simply says okay and moves on, and you will be a little stunned by how easy it was.

One reason at most

If it feels too abrupt, you can give one reason, and only one. I cannot Saturday; I have family plans. That is plenty. The second and third reasons are where it turns into pleading. And notice that a reason is different from an excuse: you are informing them, not asking them to agree that your reason is good enough.

Drop the apology when you have done nothing wrong

I am sorry belongs after a mistake. Declining an invitation is not a mistake. Try swapping sorry for something true: Thanks for asking. I appreciate you thinking of me. That will not work for me. You can be warm without being apologetic.

Stop offering to make it up

The compensating offer, the Sunday visit or the pizza money, is another way of saying, please do not be upset with me. If you genuinely want to do something else, offer it later, on its own, as a real offer. Do not attach it to the no as a bribe.

Let people have their reaction

Some of overexplaining is an attempt to control how the other person feels. If I explain enough, they will not be disappointed. But their disappointment is not yours to prevent. People are allowed to be a little let down when you say no, and they will survive it, and so will your relationship. Grown relationships can hold a no.

Watch for who requires the explaining

Sometimes overexplaining is not a habit but a response to a specific person, one who really does punish a plain no with sulking, guilt, or anger. If you only overexplain with your mother, or your boss, or your partner, that is information about the relationship, not about you. A plain answer is still the right move, and their reaction is theirs to manage.

When the habit runs deep

If you cannot stop explaining even after trying, if every plain no leaves you sick with guilt, or if the fear of someone being upset with you shapes most of what you say, there is likely an older story underneath, and it is worth looking at with a therapist. Learning to let a simple answer stand is not a small thing. It is learning that you are allowed to take up space without permission, and that lesson tends to change more than your Saturdays.', array['Boundaries', 'Assertiveness']::text[], 0, '2026-09-19T14:00:00+00:00'::timestamptz),
  ('making-peace-with-the-mirror', 'Making Peace With the Mirror', 'You catch your reflection and the commentary starts. Most people have some version of it. Why the way you see your body is not the truth about your body, and how to quiet the running judgment.', 'You walk past a mirror or a shop window, and before you have decided to look, the commentary has started. The stomach. The arms. The face. The thing you always check first and always find wanting. You look away, and the day goes on a little heavier.

Almost everyone has some version of this. It cuts across age, size, and gender, and it is rarely talked about honestly, because admitting it feels vain and admitting it feels shameful at the same time. So let us talk about it plainly.

What you see is not a photograph

The way you see your own body is not neutral. It is filtered through years of messages: from family, from other kids, from advertising, from every screen that shows you a narrow range of bodies as the normal ones. By adulthood, most people cannot look at themselves without that filter running.

That means the mirror is not showing you what other people see. It is showing you what you have been trained to look for. Other people look at you and see a whole person, in motion, with a face that changes when you laugh. You look and see the one spot you have been told to hate. Neither view is complete, but yours is the more distorted one.

Notice the commentary as commentary

The first shift is to hear the inner remarks as remarks rather than as facts. There is the voice saying my arms are disgusting. That is a thought. It is not a measurement. Thoughts about your body are not the same as your body.

Try, for a few days, simply naming it when it happens. Body commentary. Then let it pass without agreeing or arguing. You are not trying to replace it with compliments you do not believe. You are trying to stop treating it as the truth.

Ask where you learned it

Whose voice is that, exactly? For many people it is a parent who dieted constantly and talked about their own body with contempt. Or a comment from a classmate at thirteen that never left. Or a partner who made a remark and moved on while it stayed. When you can trace the voice back to its source, it loses some authority. It is not your judgment. It is something you were handed.

Change what you do in front of the mirror

You cannot stop having a reflection, but you can change the ritual. Most people with a harsh body relationship have a checking routine: certain angles, certain pinches, certain clothes tried and rejected. The checking feels like it is about fixing something, but it feeds the problem. Every check confirms the flaw.

Try reducing the checking. Get dressed and leave the mirror. Cover it for a week if you need to. When you do look, try looking at your whole self, briefly, the way you would glance at a friend, rather than zooming in on the part you police.

Treat your body as something you live in, not something you display

Ask a different question of your body. Not, how does it look? Instead, what did it do today? It carried you. It let you hug someone, eat something good, feel the shower, laugh. A body is not a picture. It is the thing that lets you have a life. People who shift their attention from appearance to function often find the mirror gets quieter on its own.

Move for the feeling, not the fixing

Movement helps how people feel about their bodies, but only when it is not another form of punishment. Exercise done to shrink or fix a hated part rarely leads to peace; it usually deepens the checking. Movement done because it feels good, because it is strong or calming or fun, changes the relationship. Choose the kind you would do even if it changed nothing about how you look.

Clean up what you look at

Your feed shapes your eyes. If you scroll through hours of edited, filtered, narrowly selected bodies, the range of normal in your head shrinks, and you fall outside it. Unfollow what makes you feel worse. Follow people whose bodies look like real ones, in a range of shapes and ages, doing real things. It sounds small. It is not.

Speak about your body the way you would want your child to speak about theirs

If you have children, or nieces, or students, they learn how to treat their bodies by watching how you treat yours. Every sigh at the mirror, every I cannot wear this, every comment about needing to earn dessert lands on them. Practicing kindness toward your own body is not just for you. It is one of the most protective things you can do for the young people around you.

When it is more than an ordinary struggle

If thoughts about your body take up most of your day, if you avoid events, relationships, or being photographed because of how you look, if you are restricting food or exercising past exhaustion, or if the distress feels unbearable, please talk to a therapist, and one who works with body image and eating if you can find one. These struggles are common, they are serious, and they get better with the right help. Your body is not a problem to solve. It is where you live, and you deserve to feel at home there.', array['Body', 'Self-Esteem']::text[], 0, '2026-09-19T14:00:00+00:00'::timestamptz),
  ('moving-your-body-when-you-hate-exercise', 'Moving Your Body When You Hate Exercise', 'The gym feels like punishment, the running app is a source of guilt, and every attempt fizzles. You may not hate moving. You may hate what you have been told movement is. A different way in.', 'You know movement is good for your mood. Everyone has told you. You have downloaded the apps, bought the shoes, signed up for the gym, and each time it lasted three weeks before it became one more thing you were failing at. So now the word exercise makes you tired before you start.

Here is a thought that changes things for a lot of people: you may not hate moving. You may hate exercise, which is a very specific idea about moving, involving effort you do not enjoy, measured in ways that make you feel bad, done to fix something about you. That version deserves to be hated. The rest of movement is still available.

Why the usual approach fails

The standard prescription is built for people who already like it. Thirty minutes, most days, at an intensity that leaves you breathless, tracked and logged. If you are starting from a place of dread, that is a mountain, and the first missed day proves you cannot climb it.

It also frames movement as medicine or penance, something to endure for a payoff later. Nobody sustains something they endure. People sustain what they enjoy or what is woven so far into their day that it stops being a decision.

Start from what your body already likes

Forget the gym for a moment. Think back to when your body felt good doing something. Dancing in the kitchen. Swimming as a kid. Walking a dog. Gardening. Throwing a ball around. Climbing something. Wandering a city. Playing with children on the floor. Somewhere in there is a kind of movement you did not have to force.

That is your starting point. Not the thing that burns the most or builds the most, but the thing you would do without being told. It counts. All of it counts.

Make the unit of success absurdly small

If the goal is a workout, most days will fail. If the goal is to move at all, most days will succeed, and success is what builds the habit. Stand up and stretch during a show. Walk to the end of the street and back. Do ten squats while the coffee brews. Park at the far end of the lot. Take the stairs once.

This feels too small to matter. It is not. Small movement done daily changes your mood and your energy more than a big workout done once and abandoned. And small things grow on their own once they are easy, which they never do while they are hard.

Hide it inside something else

Movement that is only movement has to compete with everything else for your motivation. Movement that comes with something you already want does not. Walk while you take the phone call. Listen to the podcast or audiobook you only allow yourself while moving. Meet a friend for a walk instead of coffee. Take the long way to the good bakery. Let the movement be the side effect.

Throw out the tracking if it makes you feel bad

For some people, numbers are motivating. For many, the app becomes one more voice saying not enough. If the step count or the calendar streak makes you feel guilty or defeated, delete it. You are allowed to move without measuring it. The point was never the number. The point was how you feel afterward, and you can notice that without a device.

Pay attention to the after, not the during

Movement often feels unpleasant while it is happening and good in the hour after. If you judge it by the during, you will quit. Try instead to notice, deliberately, how you feel thirty minutes later. Clearer, calmer, a little lighter, sleepier at night. That is the thing to remember when you are deciding whether to go tomorrow. Write it down if it helps: after the walk, I felt less stuck.

Expect to stop and start

You will fall off. Everyone does, especially when life gets heavy. The measure of whether movement is part of your life is not whether you ever stop. It is whether you start again, and how quickly, and how kindly. A week off followed by a walk is not failure. It is exactly how it goes for people who keep moving for decades.

Let it be about feeling, not fixing

If movement is a tool for changing how your body looks, it becomes tied up with shame, and shame is a terrible long-term fuel. Try to keep it about how you feel: steadier, stronger, more awake, less anxious, more like yourself. Those payoffs arrive quickly and keep arriving, and they do not depend on anything about your shape.

When something else is in the way

If you cannot get moving at all, if the tiredness is bone-deep no matter how much you sleep, if pain or a health condition makes even small movement hard, or if the block feels like more than reluctance, talk to your doctor before pushing yourself. Low mood, sleep problems, and physical illness can all make movement feel impossible from the inside, and they deserve attention in their own right. A therapist can also help if the thing stopping you is not your body but the harsh voice that goes with it. You were made to move. It is allowed to feel good.', array['Movement', 'Motivation']::text[], 0, '2026-09-19T14:00:00+00:00'::timestamptz),
  ('getting-through-the-first-weeks-after-a-breakup', 'Getting Through the First Weeks After a Breakup', 'Whether you ended it or they did, the first weeks are a strange kind of grief. What to expect, what helps and what quietly makes it worse, and how to know when you need more support.', 'The relationship is over. Maybe you saw it coming, maybe it blindsided you, maybe you were the one who said the words. Either way, you are now in the first weeks, and they are worse than anyone warned you. You cannot eat or cannot stop. You reach for your phone to tell them something and remember. The apartment is too quiet. A song comes on and you have to leave the store.

This is grief. Not a version of it, not something like it. The person is still alive, which makes it confusing, but what you have lost is real: a daily life, a future you had pictured, the person who knew you best. Treat it as the loss it is.

What the first weeks are like

Expect your mind to do strange things. It will replay the last conversation and rewrite it. It will swing between missing them and being furious with them, sometimes in the same hour. It will make a case for calling them at two in the morning. It will insist the whole thing was your fault, then that it was entirely theirs.

Expect your body to be affected too. Sleep gets broken. Appetite goes one way or the other. You may feel physically ill, heavy in the chest, unable to concentrate. Some people describe the early days as a kind of withdrawal, and that is close to right: your system was built around another person, and it is recalibrating.

None of this means you are handling it badly. It means you are handling it.

Cut the contact, at least for now

The hardest and most useful thing in the early weeks is distance. Mute or unfollow them. Do not check their pages. Do not text to see how they are. Every contact reopens the wound, and every glance at their life feeds the replaying. This is not about punishing them. It is about giving yourself a chance to stop the bleeding.

If you share children, a lease, or a workplace, keep the contact to what is necessary and practical, and keep it short.

Let it hurt

There is a strong pull to skip the pain: stay busy, drink more, jump into someone new, decide you are fine. Some of that is survival and it is okay in doses. But the pain does not go away when you refuse to feel it. It waits. Set aside some time, even ten minutes a day, to let it in. Cry. Write it down. Say it out loud to someone. Feelings that are allowed through tend to pass sooner than feelings that are held off.

Keep the basics going

Eat something at regular times, even if it is small. Get outside every day. Go to bed at roughly the same time. Shower. These sound too basic to mention, but in the first weeks they are the scaffolding that keeps you upright, and they are the first things to slip.

Lean on people, and tell them what you need

Say the words to someone: we broke up and I am not okay. Then be specific about what helps. Some people need to talk it through endlessly. Some need to be distracted. Some need company that does not require conversation. Your friends want to help and mostly do not know how. Tell them.

Do not make big decisions yet

Do not quit the job, move cities, get the tattoo, or send the long message explaining everything. The first weeks are not a time for irreversible choices. Write the message if you must. Then leave it in your drafts for a week. Almost every message left in drafts stays there.

Resist the urge to build a case

Your mind will want to reach a verdict: who was wrong, what it all meant, whether you wasted years. You do not have to decide any of that now. Most people''s understanding of a relationship changes a lot over the months after it ends. Let the story stay unfinished for a while.

When you were the one who ended it

Leaving does not spare you the grief. It adds guilt on top. You can be certain it was right and still miss them, still cry, still doubt yourself at night. Both things are allowed. Ending something is not the same as not having loved it.

If you have thoughts of not wanting to be here

Breakups can bring a pain that feels unsurvivable, especially when they land on top of other losses or a low stretch. If you have thoughts of harming yourself or of not wanting to be alive, please tell someone today. In the US you can call or text 988 at any time.

When to reach out for more help

Most people begin to feel more like themselves within a few months, with good and bad days along the way. But if weeks have passed and you cannot function, if you are not eating or sleeping at all, if you are drinking or using to get through, if the relationship was frightening or controlling and you are struggling with what happened in it, or if the sadness has gone flat and hopeless, please talk to a therapist. A breakup is a real loss, and you are allowed to get help carrying it. You will not always feel like this. That is the one thing every person who has been here can tell you.', array['Loss', 'Relationships']::text[], 0, '2026-09-19T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
