-- Five articles published 2026-09-23. Generated by:
--   python3 tools/articles_sql.py --since 2026-09-23
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('why-one-bad-comment-outweighs-ten-good-ones', 'Why One Bad Comment Outweighs Ten Good Ones', 'Nine people praised the presentation. One made a face. Guess which one you are still thinking about at midnight. Why the mind works this way, and how to stop letting it decide.', 'You gave the talk. Afterward, nine people told you it was good. One person said it was hard to follow. On the drive home you replayed that one sentence twenty times, and by bedtime your honest assessment of the whole day was that it went badly.

Everyone does this. It is not insecurity in the sense of a personal defect; it is how attention is built. But it does mean that your memory of almost everything is systematically skewed, and it is worth knowing how to correct for it.

Why the bad one sticks

Negative information gets processed more thoroughly and remembered more easily than positive information. From a survival point of view this makes sense: missing a threat once was far more costly than missing a compliment, so a mind that weights bad news heavily was the mind that lasted.

That worked well when the threats were physical. It works badly when the input is a coworker''s offhand remark, because the same machinery treats it as important data that must be studied.

There is a second thing, too. Praise is easy to dismiss. They were being polite. They have to say that. They did not really pay attention. Criticism feels like the truth breaking through, because it costs the speaker something to say it. So your mind quietly grants critical opinions more credibility than kind ones, on no evidence at all.

Count the actual numbers

This is the simplest correction. When you catch yourself saying it went badly, stop and count. Nine positive, one negative. Write it down if it helps.

That does not make the one comment go away, and it should not; sometimes it contains something useful. But it puts it in its place: one data point among ten, which is a completely different picture from the one your memory is offering.

Ask what you would conclude about someone else

If a friend told you that nine people praised their work and one did not, what would you say about how it went? You would say it went well. You would not spend the evening analyzing the outlier.

The gap between what you would tell a friend and what you tell yourself is one of the most reliable signs that the thinking has gone off, and asking the question directly is one of the fastest ways to straighten it.

Take the comment apart

Vague criticism is the kind that festers, because there is nothing to do with it. So make it specific. What exactly did they say? What part is factually true? What part is their preference? What, if anything, would you change next time?

Usually one of three things happens. There is a real, useful point, which you can act on and then stop carrying. There is a preference that is not yours to satisfy. Or there is nothing much at all, once it is written down in plain words, which is often startling after hours of replaying.

Consider the source, honestly

Not all feedback is equal. Someone who knows the subject, has your interests at heart, and has seen your work over time is worth listening to closely. A stranger''s drive-by opinion is not. Neither is feedback from someone who criticizes everyone, or who has a reason to want you smaller.

This is not about dismissing what you do not want to hear. It is about weighting input by how much the person actually knows, which is what you would do with any other information.

Write down the good ones

Because positive feedback does not stick on its own, it needs help. Keep a file, a note, a folder of emails. When someone says something specific and kind about your work, put it there. Read it when the one comment is running the evening.

This feels awkward the first time and it is genuinely effective, because it gives your memory something to pull from that it would otherwise have discarded.

Notice the same pattern elsewhere

Once you see it with feedback, you will see it everywhere. One argument outweighs a peaceful week. One awkward moment defines the whole party. One mistake defines the year. Your own review of yourself is being written by the negativity filter, and it is not accurate.

Set the replaying a limit

If the comment is going to circle regardless, contain it. Give it fifteen minutes with a notebook: what was said, what is true, what you will do. Then close the notebook and do something absorbing. Rumination is not analysis; after the first few minutes it stops producing anything and just hurts.

Be careful not to flip too far

The answer is not deciding all criticism is worthless and all critics are wrong. That costs you the useful part. The answer is proportion: take feedback seriously, take it once, weight it by the source, and give the positive its actual share.

When it goes deeper than one comment

If a single piece of criticism can flatten you for days, if fear of it stops you putting work forward at all, or if the voice replaying it starts saying things about your worth as a person rather than about the work, that is worth taking to a therapist. This pattern is very responsive to the kind of practical work therapists do, and living with a mind that is fairer to you changes a great deal more than how you feel after a presentation.', array['CBT', 'Thinking Traps']::text[], 0, '2026-09-23T14:00:00+00:00'::timestamptz),
  ('when-you-cannot-bear-to-look-at-your-bank-account', 'When You Cannot Bear to Look at Your Bank Account', 'The unopened letters, the app you never tap, the card you use with your eyes half closed. Why money avoidance grows, what it costs, and a gentle way back to looking.', 'There is a stack of envelopes you have not opened. You have not checked the balance in weeks. You pay by card and try not to register the number. If someone asks how much you owe, you genuinely do not know, and the not knowing has come to feel safer than knowing.

This is money avoidance, and it is extremely common in people who are otherwise organized and capable. It is also one of those problems that makes itself worse every day it continues, which is why it is worth interrupting even in a small way.

Why avoiding is so appealing

Looking at your finances produces a spike of dread. Not looking makes that spike go away instantly. That is a very effective piece of learning, repeated daily, and it builds a habit fast.

Underneath is usually something heavier than arithmetic: shame. Money is tangled up with beliefs about competence, worth, and being a responsible adult, so the numbers stop being numbers and become a verdict on you. Nobody wants to read a verdict.

And there is the sense that it is too late, that the mess is now so large that looking would be unbearable. That belief grows the longer you avoid, and it is almost always wrong.

What it costs

Interest and late charges on things you could have handled. Subscriptions you no longer use. Missed dates that turn small problems into larger ones. But the largest cost is the low, constant hum of dread, which is present all the time and takes energy you never account for.

The strange thing most people report after finally looking is that the anxiety drops even when the news is bad. Known problems are smaller than unknown ones, because you can do something about them.

Make looking small enough to survive

Do not sit down to sort out your finances. That is far too big and it is why every attempt has failed.

Instead do one thing, once, with a timer. Ten minutes. Today''s task is to open the app and look at the balance. That is all. Then stop, even if you want to keep going.

Tomorrow, another ten minutes: open three envelopes. Do not act on them, just open them and put them in one pile. The next day, list what you owe and to whom on a single sheet of paper.

You are not fixing anything yet. You are only replacing unknown with known, and that alone reduces the dread substantially.

Deal with the body first

If opening the app makes your chest tight, handle that before the numbers. Sit down. Feet on the floor. Breathe out longer than you breathe in for a minute. Have something warm to drink beside you. This sounds fussy and it is the difference between looking for ten minutes and closing the laptop after five seconds.

Some people find it much easier with another person in the room, not helping, just present. That is a legitimate strategy, not a weakness.

Get the whole picture on one page

Once you can look, write it all in one place: what comes in, what goes out regularly, what is owed and to whom, and what the minimum on each is. One page.

This is the hardest step and the most valuable. Vague dread becomes a finite list, and a finite list can be worked through. Most people find the total is somewhat worse than their best guess and much better than their worst fear.

Take one action, then stop

Pick the single most urgent thing and do only that. Call the one creditor. Cancel the one subscription. Set up the one payment plan. Then stop for the day.

Creditors are, in general, far more willing to arrange something than people expect. The call you are dreading is usually a ten-minute conversation with someone who has this conversation all day.

Set up a small, regular look

The way this stays fixed is a standing appointment: fifteen minutes, once a week, same time. Look at the balance, check what is coming, note anything to handle. Put it in the calendar like anything else.

Weekly looking keeps problems small. It is the gap between looks, not the numbers themselves, that grows the dread.

Get the shame out of it

You will want to review your past decisions harshly while you do this. Try to resist, not out of kindness but for practical reasons: shame is what caused the avoidance, and more of it will send you back to not looking. The task is arithmetic and phone calls, not a trial.

Get real help with the numbers

If the situation is genuinely difficult, a nonprofit credit counselor can help you build a plan, often free, and they have seen much worse than yours. That is a different service from anyone selling you a product, and it is worth seeking out the nonprofit kind.

When the avoidance is bigger than money

If you cannot look even with the smallest steps, if money dread is keeping you awake or making you physically unwell, or if the avoidance extends to other things, unopened mail generally, unmade appointments, unanswered messages, that pattern is usually anxiety rather than a money problem, and it responds well to treatment. Please talk to a therapist. Getting the fear down is what makes the practical part possible, and it is much easier with help than alone.', array['Money', 'Worry']::text[], 0, '2026-09-23T14:00:00+00:00'::timestamptz),
  ('when-the-last-child-leaves-home', 'When the Last Child Leaves Home', 'The room is tidy and stays tidy. You did everything right and it still feels like a loss. What the quiet is really about, and how to build the next part without rushing it.', 'The car pulled away. You came back inside and the house was very quiet. You have been waiting eighteen years for them to be able to do this, you are proud, and you sat down on the stairs and cried.

Then, quite possibly, you told yourself off for it. Other people manage. This is what is supposed to happen. You still have a whole life. All true, and none of it makes the quiet any easier.

It is a real loss, even though it is a good thing

You have lost the daily version of one of the central relationships of your life. Not the relationship itself, but its texture: the door at eleven, the noise, the negotiations, the being needed several times a day. That daily contact was most of how you knew them, and it is gone.

You have also lost a job that organized your entire adult life. Most of your days had a shape imposed by someone else''s needs, and now they do not. That sounds like freedom and initially feels more like vertigo.

And it can bring up other losses at once: the small child they were, the years that went faster than you expected, whatever you think you got wrong.

Grief that comes with a good thing is still grief. It does not need justifying.

The first weeks are the worst of it

Expect it to be sharp at first: the empty room, the smaller grocery run, the evenings with nothing to referee. Expect to check your phone too often. Expect it to hit unpredictably, in the cereal aisle.

Most people find the sharpness eases within a few months and settles into something quieter. Knowing that helps in week two, when it feels permanent.

Let yourself miss them out loud

Say it to someone: I miss them, and the house feels wrong. The pressure to perform contentment about this is strong and unhelpful. Other parents you know are feeling the same and mostly not saying it either.

Do not say it constantly to your child, though. A little is fine and it is good for them to know you love having them around. Too much makes their leaving something they have to manage for you, and they need to be free to go.

Work out the new contact, together

The old default, seeing them daily, is gone, and if you do not replace it deliberately it becomes either silence or too much. Agree something: a call on Sundays, a text when they get there, a standing video chat. Then, mostly, let them lead on the rest.

Resist checking in constantly. The urge is love, and the effect is pressure. A parent who is visibly fine tends to hear from their child more, not less.

Expect the relationship to change shape

What you are moving toward is a relationship between adults, and that takes a few years to settle. They will make decisions you would not. Your advice becomes something they can take or leave, which is a real loss of role and also the point of the whole thing. The parents who navigate this best are the ones who move from managing to being available.

Notice what is now possible

Once the sharp part eases, there is a genuine opening: time, quiet, money that is not going on them, the ability to make plans without checking a calendar full of other people''s commitments.

Try not to fill it immediately with more obligations. Sit in it for a bit, then start experimenting: the thing you stopped doing when they were small, the class, the trip, the work you shelved. Some of it will not fit anymore. That is fine; you are finding out.

If there are two of you, this is a transition for the couple

Many couples discover that the children were a good deal of the shared project and the daily conversation. Two people sitting in a quiet house can find each other unexpectedly unfamiliar.

That is worth naming rather than ignoring. Make plans together. Ask each other what you want the next stretch to look like. Some couples find this the best phase they have had; almost all of them had to talk about it first.

Rebuild your own people

Much adult friendship in the parenting years runs through the children: other parents, the sidelines, the school. Some of that thins out now. Rebuilding a social life of your own, not as anyone''s parent, is one of the most protective things to do in this decade.

When it is more than an adjustment

Some sadness and drift is expected. But if months pass and you are still not sleeping, if you have lost interest in everything, if you are drinking more, or if you feel that your usefulness ended when they left, that is worth taking seriously rather than waiting out. Low mood commonly arrives at exactly this transition, and it is very treatable. Please talk to your doctor or a therapist. You did the job you were supposed to do, and they left because you did it well. The next part is allowed to be yours.', array['Life Transitions', 'Family']::text[], 0, '2026-09-23T14:00:00+00:00'::timestamptz),
  ('asking-for-help-without-feeling-like-a-burden', 'Asking for Help Without Feeling Like a Burden', 'You would drop everything for them and you cannot bring yourself to ask for a ride. Where that asymmetry comes from, why people usually want to help, and how to actually ask.', 'You need something. A lift to a procedure, someone to sit with you, help moving a couch, an hour of someone''s expertise. You have a list of people who would say yes.

And you will not ask. You will pay a stranger, or manage badly alone, or quietly not do the thing. If someone offers, you will say you are fine.

Meanwhile, if any of those people needed you, you would be there immediately and would not think twice. That asymmetry is worth looking at, because it is costing you more than you realize.

Where it comes from

For many people it starts early. Maybe you were the capable one in a household where the adults had enough to deal with. Maybe needing things got you an irritated response, or you watched someone be treated as a burden and decided never to be that. Maybe you learned that love had to be earned by being useful, which makes receiving feel like taking something you have not paid for.

Whatever the origin, the belief underneath is usually the same: other people''s needs are legitimate and mine are an imposition.

Look at what you are actually claiming

That belief, said plainly, is that you are a different category of person from everyone else. They deserve support; you deserve to manage. Put like that, most people can see it does not hold. You would never apply it to anyone you love.

What refusing to ask actually does

It denies people the chance to be useful to you, which is one of the main ways humans stay close. Think about the last time someone let you help them with something real. It probably felt good, and it probably made you feel closer to them.

It also keeps relationships one-directional. A friendship where only one person ever needs anything is not equal; it is a service. People often sense this and, over time, feel held at a distance without knowing why.

And it means you carry things alone that you did not have to carry alone, which has a cumulative cost on your health and your mood.

Most people want to be asked

This is the part that is hard to believe until you test it. Being asked is generally experienced as a compliment: it says you are trusted, capable, close enough to be leaned on. People remember being asked at a hard moment for years.

The disaster you are imagining, resentment, an awkward silence, a permanent debt, is almost never what happens.

How to ask

Be specific. Vague requests are much harder to say yes to and are harder to hear. Not, could you help me sometime, but, could you drive me to an appointment on Thursday morning, about two hours in total.

Make it easy to decline. Adding no pressure at all if it does not work is not weakness; it frees them to say yes without feeling cornered, and it means a yes is real.

Do not stack on apologies. I am so sorry, this is such an imposition, I feel terrible asking hands them a second job: reassuring you. Thanks for considering it does the same work without the weight.

Then stop talking. As with any request, let the silence sit and let them answer.

Let a yes be a yes

When they agree, resist the urge to minimize it, to keep offering outs, or to immediately propose repayment. Say thank you and let them do it. Trying to instantly square the ledger is another way of refusing the help.

Receiving well is a skill, and it is a gift to the person helping.

Take the offers people make

Most people who avoid asking also deflect offers. Someone says, can I bring you dinner, and you say, oh no, we are fine. Try saying yes once. Specifically: yes, Thursday would be wonderful.

This is the easiest place to practice, because you did not even have to ask.

Start small

Do not begin with the biggest need you have. Ask someone to recommend something, to look over an email, to pick something up on their way. Small asks, made often, build the muscle and also quietly rebalance a relationship so that a larger ask later is not a shock.

Notice who is worth asking

Some people genuinely do respond badly, keep score, or use it later. That is real information about them and not about asking. Notice who receives your request well, and take those people seriously as the ones to build with.

When it goes deeper

If you cannot ask for anything at all, if needing something makes you feel ashamed of yourself, or if the belief that you are a burden has been with you as long as you can remember, that is usually older than any of your current relationships and it is worth exploring with a therapist. Learning that your needs are ordinary rather than an imposition tends to change far more than logistics. You are not the exception to the human rule that people need each other.', array['Assertiveness', 'Self-Esteem']::text[], 0, '2026-09-23T14:00:00+00:00'::timestamptz),
  ('loving-someone-who-is-depressed', 'Loving Someone Who Is Depressed', 'They have withdrawn, and nothing you try reaches them. What actually helps a partner or friend in a depression, what quietly makes it worse, and how to stay well yourself.', 'The person you love has gone somewhere you cannot follow. They are in the house and not really there. They cancel things, sleep badly or endlessly, and answer in single words. You have suggested a walk, fresh air, seeing friends, and each suggestion has landed like another small failure for both of you.

You feel helpless, and probably also frustrated, and then guilty about the frustration. All of that is normal, and none of it means you are doing this badly.

Understand what you are dealing with

Depression is not sadness and it does not respond to cheering up. It flattens the machinery that produces motivation, interest, and hope. So when they cannot get out of bed, it is not that they will not. When they say nothing will help, that is the illness talking with total conviction.

This matters practically, because most of what does not work comes from treating it as a mood rather than an illness.

What tends not to help

Suggesting solutions. Have you tried exercise, sunlight, gratitude. They have heard it, they may even agree, and hearing it again mostly communicates that you do not understand how heavy things are.

Reasoning them out of it. But you have so much to be grateful for is true and useless. Depression is not a failure of perspective.

Taking the withdrawal personally. They are not pulling away because of you. The illness pulls people away from everyone, including themselves.

Constant reassurance-seeking. Asking repeatedly whether they still love you or whether you are doing enough puts your distress on top of theirs.

Waiting for them to ask. People in a depression usually cannot initiate. Waiting for a request is waiting for the one thing the illness takes away.

What does help

Show up without an agenda. Sit with them. Watch something. Be in the room. Presence with no expectation of improvement is worth more than any suggestion.

Say what you see, kindly. I have noticed you have not been yourself for a while, and I am not going anywhere. Naming it gently is a relief; most people in it are convinced they are hiding it badly and being judged for it.

Do the concrete things. Make food, do a load of laundry, drive them somewhere, sit with them while they make the phone call. Practical help is the most usable kind, because it does not require energy they do not have.

Make invitations easy and keep making them. I am walking to the corner at four, come if you want, no problem if not. Then keep asking even after many nos. The asking itself says they are still wanted, and one day they will say yes.

Help them get treatment, practically. Depression makes finding a therapist or booking a doctor''s appointment nearly impossible. Offer to look up names, make the call, sit in the waiting room, drive. That is often the single most useful thing a person on the outside can do.

Ask about safety, directly

If you are worried, ask plainly: are you having thoughts of hurting yourself, or of not wanting to be here? Asking does not plant the idea. It is a relief to be asked, and it is the only way to know.

If the answer is yes, take it seriously, stay with them, help them contact their doctor or a crisis line, and remove easy means if you can. In the US you can call or text 988 at any time, and you can call it for advice about someone else too.

Keep your own life going

You cannot pour from an empty cup, and loving someone through a depression is a long stretch, not a weekend. Keep seeing your own friends. Keep the things that restore you. Tell at least one person what is happening so you are not carrying it alone.

This is not disloyalty. A person who is well is far more use than one who has gone down with them.

Let yourself have the hard feelings

You will feel frustrated, lonely, resentful, and sometimes you will want to shake them. Those feelings do not make you unkind; they make you a person doing something difficult. Find somewhere to put them that is not the depressed person: a friend, a journal, your own therapist.

Know what is not yours

You cannot cure it. You cannot love someone out of a depression, and if it does not lift, that is not evidence that you failed. What you can do is stay, keep things practical, and help them reach the people whose job this is.

Get support for yourself

Please consider talking to a therapist of your own, or finding a support group for families. And encourage the person you love toward treatment, gently and repeatedly. Depression is one of the most treatable things there is, which is worth saying out loud in a house where it currently feels permanent. It will not always be like this, for them or for you.', array['Depression', 'Relationships']::text[], 0, '2026-09-23T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
