-- Five articles published 2026-10-05. Generated by:
--   python3 tools/articles_sql.py --since 2026-10-05
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('the-bedtime-battle', 'The Bedtime Battle', 'Two hours of stalling, one more drink of water, and everyone ends the day upset. Why bedtime goes wrong and what changes it, without turning it into a fight.', 'It is nine forty. They have been up four times. You have been reasonable, then firm, then sharp, and now you are sitting on the stairs in the dark feeling like a bad parent and wanting your evening back.

Bedtime is the hardest half hour of the day in a lot of houses, and it is hard for an ordinary reason: you are trying to get a tired person to do something they do not want to do, at the exact moment you have the least left in you.

What is actually happening at bedtime

Children stall at bedtime for a short list of reasons, and they are mostly not defiance.

They do not want to miss anything. Bedtime is when the house gets interesting: you are around, the day is ending, and whatever you are doing seems better than the dark.

They are frightened, or at least uneasy, about being alone. Separation is the real content of most bedtime resistance, especially between two and six.

They are overtired, which in children looks like wired rather than sleepy: faster, louder, less able to settle.

Or the day''s leftovers arrive. Bedtime is the first quiet moment, so the worry about school or the thing that happened at lunch surfaces exactly then.

And often, honestly, it works. If one more story has ever been granted after four requests, the stalling has been taught that it pays.

Make the sequence boring and identical

The single most effective change is not a rule, it is a routine so repetitive that nobody has to decide anything.

Same order, same rooms, same length, every night. Bath, teeth, pajamas, two books, one song, light out. Twenty to thirty minutes, and it ends in their bed rather than on the sofa.

The point of a fixed sequence is that it removes negotiation points. Each step is just the next step, not an opportunity. It also tells the body what is coming, which is a real part of settling.

Write it on a card with pictures if they are small, and let them tick the steps. Following a chart is far easier for a child than obeying a person.

Put the stalling inside the routine

You will not out-argue a four-year-old at nine in the evening. So give the usual requests a place in the sequence before they are asked for.

The drink of water is on the nightstand already. The last toilet trip is a step, not an interruption. The extra cuddle has a name and a length: two minutes, then I am going downstairs.

A useful trick for the ones who need one more of everything: a bedtime pass. One card they can spend each night on one extra thing, and when it is used, that is the night done. Many children stop spending it within a week.

Start earlier than feels right

Parents often push bedtime later because the child seems not tired. Overtired looks exactly like that, and a later start usually makes the whole thing worse.

Try moving the start fifteen minutes earlier for a week and watch rather than judging the first night. The same goes for screens: the last hour before bed is much easier without one, mostly because of what screens do to attention and arousal rather than any single mechanism.

And hold the morning time steady, even after a bad night. The wake time is what anchors the whole rhythm.

When they keep coming out

Decide on your approach before the evening rather than during it, because consistency is what works and improvising at nine never is.

The method that has the best track record is dull: walk them back, say one short line, and leave. Same line every time. Back to bed, it is sleep time, I will see you in the morning. No new conversation, no rising volume, no bargaining.

The first few nights get worse before they get better, which is where most people abandon it. If you can hold the same response for a week, the number of exits usually drops sharply.

If they are frightened rather than testing, a different mix helps: a dim light, a door left ajar at an agreed width, something of yours in the bed, and checking in on a schedule you set rather than on demand. I will come back in five minutes, said and then actually done, builds trust faster than staying until they sleep.

Protect the parent in this

Two things make the battle much worse: doing it alone every night, and having nothing left afterward.

Alternate nights with another adult if there is one, and let whoever is on duty run it their way. Children manage two slightly different bedtimes perfectly well.

And set your own end point. Bedtime ends at a time, not when the child is asleep. If they are in bed and safe at eight thirty, your evening has started even if they are still talking to themselves.

On the nights it goes badly, it is worth saying plainly to yourself: this is the hardest half hour in parenting, and it going badly tonight does not mean anything about the rest.

The next morning

Do not relitigate it. A short line is enough: last night was hard, tonight we will do the same steps.

And if something came up at bedtime that was real — a worry about school, a fear, something that happened — have that conversation in daylight rather than at ten at night, when nobody can do anything useful with it.

When to ask for help

Most bedtime trouble responds to a consistent routine in a couple of weeks. Some does not, and that is worth a conversation rather than another year of it.

Talk to your child''s doctor if they snore heavily, stop breathing briefly, wake with headaches, are exhausted all day, or are having frequent night terrors, since there are physical causes worth ruling out. And if bedtime is tangled up with real anxiety, if nobody in the house is sleeping, or if you are frightened by how angry you get in that half hour, a doctor or a therapist can help with both halves of that, and asking early makes it much shorter work.', array['Parenting', 'Sleep']::text[], 0, '2026-10-05T14:00:00+00:00'::timestamptz),
  ('working-fewer-hours-and-the-guilt-that-follows', 'Working Fewer Hours and the Guilt That Follows', 'You finally cut back, and now you feel like a fraud at four in the afternoon. Why reducing your hours brings guilt rather than relief, and how that settles.', 'You did the thing everyone told you to do. You dropped a day, or stopped at five, or handed back the extra responsibility. You expected relief.

What arrived instead was a low hum of guilt. At four in the afternoon, with nothing urgent left, you feel like you are getting away with something.

This surprises almost everyone who cuts back, and it is the main reason the change does not last.

Why less work feels worse at first

Several things arrive at once.

If your sense of being worth something has been attached to output for years, then reducing output removes the main way you reassure yourself. The hours were doing a job beyond the job.

Long hours also keep you ahead of the discomfort of stopping. Slowing down gives space to whatever you were outrunning: a worry, a grief, a question about the shape of your life. Many people find the first quiet weeks are not peaceful at all.

And there is a social layer. If everyone around you is visibly busy, being less busy can feel like a status you are not supposed to want.

Finally there is the practical one: your colleagues can see you leave. Guilt is easier to produce when there is an audience, even an uninterested one.

Decide what the time is for

Unstructured time is where the guilt lives. A Wednesday with no shape invites an afternoon of feeling vaguely idle, and then you quietly fill it with work again.

So give the reclaimed hours a job, at least at first. Not a productive job: a named one. A class, a standing walk with someone, a swim, the garden, picking up a child, a long lunch with the paper.

Something with a time attached is far easier to hold than rest in general, and it gives you a plain answer to the question in your head about what you are doing with the day.

Expect the first month to feel wrong

It usually takes six to eight weeks before fewer hours start to feel normal. Before that, people often report more restlessness, not less, and worse sleep for a while.

Knowing that in advance matters, because the most common ending is quietly going back after three bad weeks and concluding you are simply someone who needs to work like that.

So judge it at two months, not at two weeks, and notice specific things rather than the overall feeling: are you less short-tempered at home, are you sleeping, do you dread Mondays less.

Guard the edges, because they will be tested

Reduced hours erode. A meeting creeps onto your day off; a project needs just this once; the emails continue regardless.

Two things hold the line. Make your non-working time visible and stated: I am not working Fridays, I will pick this up Monday. Say it the same way each time, without apology or explanation.

And do not answer messages on the time you have bought. Replying once teaches everyone, including you, that the day is negotiable. The one exception is something genuinely urgent, and genuinely urgent is rarer than it feels.

If you dropped a day and your workload did not drop with it, that is a conversation to have explicitly rather than absorb: what are we taking off the list, since the hours have changed.

Separate guilt from the actual ledger

If the guilt is about money, look at it properly. The numbers either work or they need adjusting, and either way they are facts rather than a feeling. A plain budget is more settling than reassurance.

If it is about colleagues carrying your share, check whether that is true. Sometimes it is, and the fix is managerial rather than personal. Often it is not, and you have been imagining a resentment nobody has.

And if it is about your own worth, that one is not settled by arithmetic. It helps to notice what else you have brought to people this week: the attention you had left for your children, the patience, the fact that you were there at all. That is not a consolation prize for lost output; it is what the hours were for.

The thing you may have to grieve

Working less often means being less exceptional at work. Fewer of the high-profile pieces, a slower path, someone else being the person who always answers.

That is a real loss, and pretending otherwise is part of why the guilt lingers unnamed. You are allowed to miss being that person while still being glad you stopped.

Saying it out loud to someone tends to shrink it. Carrying it silently tends to turn it into a case for going back.

Watch for the two common relapses

Filling the time with another kind of work: the side project, the renovation, the committee. Full is not the same as sustainable.

And compensating by being extremely intense in the hours you do work, until the four days hurt as much as five used to.

If either is happening, the hours were never the whole problem; the pace was.

When the guilt is not really guilt

If slowing down has brought a flatness you cannot shift, if you feel worse rather than steadier after a couple of months, or if the quiet has surfaced something heavy you cannot put down, that is worth talking to someone about.

Exhaustion that cutting back does not touch, and low mood that arrives in the gap, both respond much better to help than to going back to longer hours. A doctor or a therapist is the right place to take it, and it is a very ordinary thing to bring: I reduced my work and I feel worse, not better.', array['Burnout', 'Work']::text[], 0, '2026-10-05T14:00:00+00:00'::timestamptz),
  ('eating-well-when-money-is-tight', 'Eating Well When Money Is Tight', 'Food advice usually assumes a budget you do not have. A practical, non-judgmental look at eating on very little, and where to get help without shame.', 'Most food advice is written for someone with a full cupboard, a car, and a weekend to cook. If the money is not there, that advice is not just unhelpful, it is an extra weight: one more thing you are apparently failing at.

So this is the other version. What actually holds up when the budget is thin, and where to get help without having to feel ashamed about it.

Start with what is reliable, not what is ideal

When money is tight, the aim is a small number of meals you can make repeatedly with ingredients that keep. Variety is a luxury; reliability is the thing that keeps you fed.

The cheap workhorses are not glamorous and they are genuinely good food: eggs, dried or canned beans and lentils, rice, oats, pasta, potatoes, frozen vegetables, canned fish, canned tomatoes, peanut butter, flour, onions, carrots, cabbage.

Frozen vegetables deserve a particular mention. They are usually cheaper than fresh, they do not rot in the back of the fridge, and nutritionally they hold up perfectly well. Buying frozen is not a compromise.

Four or five meals, on rotation

Pick a handful of things you can make without thinking, and build the shopping around them rather than the other way round.

Beans and rice with onion and whatever spice you have. Lentil soup with carrots. Pasta with canned tomatoes and an egg on top. Baked potatoes with beans and cheese. Oats with peanut butter. Vegetable fried rice from leftovers.

Then buy the same base items each week. A rotation feels dull, and it also means nothing is wasted, nothing needs a decision, and the price is predictable.

Where the money actually goes

A few habits save more than any single clever recipe.

Cook dried beans and lentils rather than buying them canned when you can; the saving is large, and a batch cooked once covers several meals. If you have a freezer, portion and freeze.

Buy the biggest unit you can afford of the things you always use, and nothing in a large size that you do not.

Shop with a list, after eating, and check the unit price on the shelf label rather than the sticker price. Supermarket own brands are nearly always the same food in a different bag.

Look at reduced shelves, and freeze what you buy there the same day. Markets late in the day often sell cheaply too.

And treat waste as money: a wilting vegetable is cash you already spent. Soup, stir-fry and roast trays are the three ways almost anything gets used.

When there is no time, no energy, or no kitchen

Plenty of people on a tight budget are also working long hours or sharing a single hob. Cooking from scratch is not always available.

So keep a shelf of things that need nothing: bread, peanut butter, bananas, canned beans, tinned fish, crackers, long-life milk, cereal. Eating something simple is a result, not a failure.

A kettle and a microwave can do more than people think: oats, instant rice, canned soup, eggs, frozen vegetables. If you have no kitchen at all, prioritize food that needs no cooking rather than feeling defeated by recipes you cannot use.

Feeding children on very little

Children need enough and they need it regularly, which is more important than any specific food.

Free and reduced-price school meals exist in most places and are worth applying for even if you are not sure you qualify. Summer meal programs, food pantries and community kitchens often serve families without means testing at the door.

And try not to let them see food as a crisis. Steady, boring meals say more about safety than a perfect plate does, and children are far more affected by tension at the table than by what is on it.

Getting help is not a last resort

Food pantries, community fridges, free meals, benefits and school programs exist because enough people need them that societies built them. Using them is what they are for.

A few practical notes. Many pantries do not require proof of anything. Benefits programs that help with food are badly underclaimed, often by people who assume they earn too much; checking takes one call or one form. Local charities, churches and community centers often know about help that is not advertised anywhere.

If you are in the US, dialing 211 connects you to someone who can tell you what food help exists where you live, and they will not ask you to justify the call.

The part that is not about food

Money worry and food get tangled together quickly. People skip meals to feed their children, eat the cheapest filling thing and feel guilty about it, or stop having anyone over because feeding a guest is impossible.

That is a real strain, and it is not a character problem. Being poor is expensive and exhausting, and the shame around it does more damage than most of the arithmetic.

So where you can, protect one small thing you actually enjoy eating each week. That is not frivolous. It is what keeps a tight budget survivable rather than punishing.

When to tell someone

If you are regularly skipping meals, if you cannot afford food this week, or if you are losing weight without meaning to, please tell your doctor. They can check the physical side and they are usually the fastest route to a social worker who knows exactly what help exists locally.

And if the stress of money has you unable to sleep, dreading the post, or feeling that there is no way out, that is worth taking to a doctor or a therapist too. There is also free, nonprofit debt and benefits advice in most places, which is practical rather than judgmental, and people who use it generally wish they had gone sooner.', array['Food', 'Money']::text[], 0, '2026-10-05T14:00:00+00:00'::timestamptz),
  ('why-anxiety-makes-your-body-feel-ill', 'Why Anxiety Makes Your Body Feel Ill', 'Chest tightness, dizziness, a stomach that will not settle, tingling hands. What anxiety actually does to the body, and why checking with a doctor is still the right move.', 'Your chest is tight. Your stomach has not been right for weeks. Your hands tingle, your head feels swimmy, and you are tired in a way sleep does not touch.

Somebody has probably told you it is just anxiety, which is one of the least useful sentences in medicine. It sounds like being told you are imagining it, and you are not. The sensations are real, physical, and produced by something your body is actually doing.

Here is what that is, and why it is still worth getting checked.

The alarm system runs the body, not just the mind

Anxiety is a whole-body response, not a mood. When your system reads a threat, it prepares you to fight or run, and that preparation is physical.

Adrenaline and cortisol go out. Your heart beats faster and harder. Breathing gets quicker and shallower. Muscles tense, ready to move. Blood is routed to the big muscles and away from your stomach and skin. Digestion slows down. Your senses sharpen.

That whole package is useful if you have to run. It is deeply unpleasant if you are sitting at a desk, and even more so if it has been running at a low level for months.

What the common symptoms actually are

Tight chest and breathlessness: the muscles across your chest are tense and your breathing has gone shallow and fast. Faster breathing also changes the balance of gases in your blood, which produces much of the rest of this list.

Tingling hands and face, light-headedness, a sense of unreality: these are classic effects of over-breathing, not signs of anything damaged. They can be reproduced in anyone in about a minute of fast breathing.

A stomach that will not behave: digestion is downregulated when you are in alarm mode, and the gut has a dense nerve supply that responds quickly to stress. Nausea, cramping, urgency and appetite changes are extremely common.

Aches, headaches, a sore jaw, a stiff neck: held tension, often all day, often without noticing. Jaw and shoulders are the usual sites.

Exhaustion: running an alarm system continuously is metabolically expensive, and anxiety fragments sleep even when you are in bed for eight hours.

Heart flutters and skipped beats: very common with adrenaline and caffeine, and worth mentioning to a doctor rather than assuming.

Why it keeps going round

Here is the loop that makes this so persistent: the symptom becomes the threat.

You notice your heart. You wonder if something is wrong with it. That wondering raises adrenaline, which raises your heart rate, which gives you more to notice. The same runs with chest tightness, dizziness and swallowing.

Checking feeds it too. Taking your pulse, searching symptoms, pressing on the sore spot, asking for reassurance: each one briefly settles and then sharpens the attention that keeps it running.

That loop is a large part of why physical anxiety symptoms outlast the stressful thing that started them.

Get it checked anyway

This is important and often missed in the rush to call something anxiety.

Several physical conditions produce exactly these sensations: thyroid problems, anemia, heart rhythm disturbances, asthma, diabetes, inner-ear problems, vitamin deficiencies, and the effects of medication, alcohol, nicotine and caffeine.

So see a doctor and describe it plainly. Getting a basic check is not a failure of nerve; it is how you rule things out, and it is also what lets you stop wondering, which is itself part of the treatment.

Treat some symptoms as urgent rather than familiar. Chest pain spreading to the arm or jaw, pain with sweating or vomiting, sudden severe breathlessness, fainting, weakness or drooping on one side, a sudden worst-ever headache, or trouble speaking: those need emergency care, not reassurance from an article.

What helps the body side

Slow the out-breath. Four in, six or seven out, for a few minutes, several times a day rather than only in a crisis. This is the most direct lever on the whole list above.

Unclench on purpose. Several times a day, drop your shoulders, unclench your jaw, let your hands go loose. Held tension is a habit and it responds to being interrupted.

Move most days. Movement spends the chemistry the alarm keeps producing, and it reliably lowers the background level.

Cut caffeine right back for two weeks and see. Caffeine produces a very large share of the heart flutters, jitteriness and stomach trouble people attribute to anxiety.

Protect sleep, and treat alcohol with suspicion: it settles things for an hour and fragments the second half of the night, which makes the next day worse.

And stop the checking where you can. Not pressing on it, not measuring it, not searching it. Leaving a symptom alone is the thing that lets it fade.

When to get proper help

Physical anxiety responds well to treatment, often in a short course of therapy aimed at exactly this loop, and sometimes with medication a doctor can discuss with you.

If this has been going on for weeks, if you are avoiding places or activities because of how your body feels, if panic attacks are arriving regularly, or if the fear that something is seriously wrong will not settle even after tests have come back clear, please take it to a doctor or a therapist rather than managing it alone.

And if things have got dark enough that you are not sure you want to be here, tell a doctor or someone you trust that same day. In the US you can call or text 988 at any time.', array['Panic', 'Body']::text[], 0, '2026-10-05T14:00:00+00:00'::timestamptz),
  ('how-to-decide-what-to-do-first', 'How to Decide What to Do First', 'Everything on the list is urgent, so you do none of it. A few quick ways to sort an overwhelming day into an order you can actually start on.', 'There are fourteen things on the list. Four of them have deadlines. Two of them you have been avoiding for a week, which is why they are now urgent. You have read the list three times and done nothing.

This is not a time management failure. It is what happens when a list exceeds what a person can hold at once: the sorting itself becomes the hardest task, and sorting has no satisfying end point.

So the aim here is not a perfect order. It is to get to one thing you can start.

Get it out of your head first

You cannot prioritize a list you are holding in your memory, because the holding uses the attention you need for the deciding.

So write everything down, fast and badly, including the small things and the things that are only slightly on your mind. Five minutes, no sorting.

Most people find the list is shorter than it felt. A dozen items written down is manageable; a dozen items circling is not. Even if it is long, you can now look at it rather than carry it.

Ask the four questions, in order

Then go through the list once with these, which take about a minute each.

Is this actually mine? Some items belong to somebody else and have attached themselves to you. Hand them back, or at least note who else could own them.

What happens if it is late? Be honest rather than anxious. Some things have real consequences by Friday. Many have none, and the deadline was invented by you or by a long-dead email.

Is anyone else blocked on it? Anything that unblocks somebody else usually goes early, because its cost multiplies while it waits.

Is it quick? Anything under two minutes, do it now rather than ranking it. A list cluttered with tiny items is harder to face than a shorter list of real ones.

That pass alone usually cuts the list in half and puts three or four things at the top.

Pick the one that unlocks the most

If several items survive, the useful tie-breaker is not importance in the abstract. It is which one, once done, makes the others easier or unnecessary.

The call that tells you whether the whole project is going ahead. The decision three people are waiting on. The thing you have to look at before you can estimate anything else.

That is usually the right first task, even when it is not the most urgent, because the rest of the list is partly a fog that it clears.

The avoided one deserves a different rule

Some items are not on the list because they are hard; they are hard because they have been on the list for three weeks.

Those have a cost you are already paying: the low-level dread, the daily decision not to do it, the thing that is quietly getting worse.

So give the oldest avoided item a slot early in the day, at a size you will actually do: fifteen minutes, or just the first step. It pays back more than its size because it stops the drain.

When everything genuinely is urgent

Sometimes the honest answer is that there is more than one person can do in the time, and no order fixes that.

Then the task is not prioritizing, it is telling someone. Go to whoever sets the work with the list and a specific question: here are the five things, here is what I can realistically do by Thursday, which two matter most.

That conversation feels risky and is nearly always welcome. Managers would far rather choose than discover on Friday. And a decision you made alone about what to drop is much harder to defend than one they made with you.

Where you cannot escalate, make the trade visible in writing: I am doing A and B first, which means C moves to next week. Said plainly and in advance, that is almost never a problem.

Protect the first hour

An order is only useful if something gets done in it, and the beginning of the day is where the day is decided.

So put the chosen task first, before messages. Email reorders your list according to other people''s priorities, and once that has happened, your own ranking is gone.

If your work makes that impossible, protect any one consistent hour instead, and spend it on the chosen thing rather than on whatever is loudest.

Re-sort once, not continuously

A list you re-rank six times a day is a way of avoiding all of it.

Do the sorting once in the morning and once at the end of the day, and in between let the order stand even when something new arrives. New items go on the list, not to the front of it, unless something is genuinely on fire.

That one rule saves more time than any system, because the constant re-deciding is where most of the day leaks out.

When the paralysis is the real problem

If you look at the list and cannot start anything, if this happens most days, or if the fog is thick enough that the sorting itself is impossible, the obstacle may not be the workload.

Exhaustion, long-running low mood, high anxiety and the different ways attention works for some people all show up exactly like this. Those are worth a conversation with a doctor or a therapist rather than another system, especially if the list has stopped moving for weeks and the dread about it is affecting your sleep.', array['Decision Making', 'Stress']::text[], 0, '2026-10-05T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
