-- Five articles published 2026-09-24. Generated by:
--   python3 tools/articles_sql.py --since 2026-09-24
-- An upsert on slug, so re-running it refreshes the text and keeps every id.
insert into public.articles (slug, title, excerpt, body_md, tags, min_level, published_at)
values
  ('trying-to-be-a-perfect-parent', 'Trying to Be a Perfect Parent', 'You read the books, you do the gentle voice, and you lie awake cataloging the moments you got it wrong. Why aiming for perfect makes you a worse parent, and what children actually need.', 'You lost your temper at bath time. You gave them the tablet because you could not face another twenty minutes. You said the thing your own mother used to say and heard it land. And now it is eleven at night and you are replaying it, adding it to a list you keep of ways you are damaging them.

No previous generation of parents has had this much information or this much anxiety about getting it right. The information is often good. The anxiety is doing real harm, mostly to you, and some of it to them.

What perfectionism does to parenting

It makes every ordinary moment high stakes. A tired snap becomes evidence. A missed bedtime routine becomes a failure of character. When everything is a test, you parent from fear, and fear makes people rigid, controlling, and unable to enjoy their children.

It also costs you presence. A parent monitoring their own performance is not fully in the room. Children notice the difference between being with you and being watched over by someone who is anxious about how the watching looks.

And it leaves nothing for you. Parents who hold an impossible standard tend to strip out their own rest, friendships, and interests as luxuries, which produces exhaustion, which produces exactly the short temper they were trying to avoid.

What children actually need

Not perfection. Repeatedly, across everything we know about how children turn out, what matters is a good-enough pattern over time: a parent who is mostly warm, mostly predictable, and who repairs things when they go wrong.

That last part is worth dwelling on. Children are not damaged by ruptures; they are shaped by whether ruptures get repaired. You snapping and then coming back twenty minutes later to say I was short with you and that was not about you, I am sorry, teaches more than the snap took away. It shows them that love survives conflict, that adults can be wrong, and how to make an apology.

A household where nothing ever goes wrong would teach a child none of that.

Aim for the pattern, not the moment

Zoom out. Over the last month, has your child been fed, held, listened to, played with, and kept safe more often than not? Have they laughed with you? Do they come to you when something hurts?

If the answer is yes, the pattern is good, and the bad Tuesday is inside a good pattern. That is what your child''s nervous system is averaging, not your worst ten minutes.

Watch what the standard is doing to them

Children of perfectionist parents often learn, without anyone saying it, that mistakes are frightening. They see the anxiety around getting things right and absorb it. Some become cautious and afraid to try; some become very hard on themselves.

If you want to give them permission to be imperfect, the most powerful way is to model it: to make mistakes in front of them, name them lightly, fix them, and move on. What you do with your own errors is the lesson.

Ignore most of the advice

There is an unlimited supply of parenting content, much of it contradictory, all of it implying that if you were doing it right this would be easier. Pick one or two sources you trust, check in with them when you have a specific question, and otherwise stop consuming it. Comparative parenting content mostly generates anxiety, not competence.

The same goes for other parents'' visible lives. You are comparing your whole reality, including bath time, to their edited highlights.

Find the actual source of the snapping

Most of the moments you feel worst about are not parenting failures; they are capacity failures. You snapped because you had slept badly, skipped lunch, and taken a hard call an hour earlier.

That reframes the fix. Getting a bit more sleep, eating properly, and having one hour a week that belongs to you will do more for your parenting than any technique. Looking after yourself is not competing with your children; it is what makes you available to them.

Let some things be ordinary

Not every dinner needs to be balanced and homemade. Not every weekend needs an activity. Screen time on a hard day is not a moral event. Children do not need an enriched childhood; they need a steady one with some fun in it, and they largely remember the atmosphere rather than the itinerary.

Expect to repeat a few things from your own childhood

You will hear your parents come out of your mouth. That is startling and normal. It does not mean you are becoming them; it means those patterns were installed early and take deliberate work to change. Noticing it is most of the work. You can say, out loud, that was my mother talking, I do not mean that, and try again.

When it is more than high standards

If the worry about your parenting is constant, if you cannot enjoy your children for monitoring yourself, if intrusive thoughts about harming them or about something happening to them are frequent and distressing, or if you feel low, flat, or unable to bond, please talk to your doctor or a therapist. Anxiety and low mood after having children are extremely common, very treatable, and not a comment on your love for them. Good enough is not a consolation prize. It is the actual target, and you are probably closer to it than you think.', array['Perfectionism', 'Parenting']::text[], 0, '2026-09-24T14:00:00+00:00'::timestamptz),
  ('when-your-body-hurts-and-no-one-can-say-why', 'When Your Body Hurts and No One Can Say Why', 'The tests come back normal and the pain is still there. What it does to a person to be in pain without an explanation, and how to keep a life while you are living with it.', 'The pain is real. It has been there for months, maybe years. You have had the scans and the blood work, seen several doctors, and the results keep coming back unremarkable. Someone has implied, gently or otherwise, that it might be stress. You went home and wondered whether you are imagining it.

You are not imagining it. Pain that has no clear finding on a test is still pain, and living with it without an explanation is one of the harder things a person can be asked to do.

Why unexplained pain is so hard

It is not only the pain. It is the loss of a story. Most illness comes with a shape: here is what it is, here is what happens next, here is when it ends. Without that, you cannot plan, cannot reassure yourself, and cannot answer the questions everyone asks.

It is the doubt, too, both other people''s and your own. When there is nothing to point to, people quietly wonder whether it is as bad as you say. That includes, on bad days, you. Carrying pain while also defending its existence is exhausting in a way that healthy people find difficult to imagine.

And it is the invisible part. You look fine. So the accommodation you need has to be requested rather than assumed, over and over.

Pain without a finding is not pain without a cause

It helps to know that the absence of a finding is often a limitation of the tests, not proof that nothing is wrong. Many real conditions show nothing on standard imaging. And pain is produced by the nervous system, which can become persistently sensitized after an injury or illness has healed, so that the volume stays up long after the original cause has gone.

That is a physical process, not a psychological one. It does mean the nervous system is part of the picture, which is why approaches that work on that system, including certain kinds of physical therapy, pacing, and pain-focused psychological treatment, can genuinely reduce pain rather than merely helping you cope with it.

Keep looking, without letting the search eat your life

There is a balance here that nobody explains. It is worth continuing to seek answers: a specialist in the relevant area, a pain clinic, a second opinion, a doctor who listens. Keep a written record of symptoms, what makes them worse, and what you have already tried, which makes appointments far more productive.

And it is worth noticing when the search itself becomes the whole life: endless appointments, forums at two in the morning, every week organized around the next possible answer. Many people eventually reach a point where they keep one line of inquiry open and start rebuilding a life alongside the pain rather than waiting until it is solved.

Pace rather than push

The common pattern is boom and bust: on a good day you do everything you have been putting off, then pay for it for three days. Over time that teaches your body that activity leads to punishment, and your range shrinks.

Pacing means doing a consistent, sustainable amount, on good days and bad, below the level that triggers a flare. It feels like underachieving on the good days. It produces more overall activity across a month, and it slowly widens what you can do.

Tell people what you need, specifically

Most people want to help and have no idea how. Give them concrete things: I can do dinner if we sit rather than stand. I need to leave by nine. I cannot carry that. Please do not ask how I am every time, ask me about something else.

You will also encounter unsolicited cures and suggestions that you try yoga. A short, flat response usually ends it: I have a medical team on it, thank you.

Protect the parts of your life that are not pain

Chronic pain expands to fill the available space, in your attention and your calendar. Deliberately keep something that is yours and is not about being unwell: a friendship, a project, something you are learning, anything you would talk about for reasons other than your health. People who keep those fare better, on every measure.

Expect grief

You may be grieving the body you had, the plans you made, the version of your life that was supposed to be happening. That grief is legitimate and it comes in waves, often triggered by seeing other people do easily what now costs you. It is not self-pity. It deserves the same room any other loss would get.

Get pain-informed support

A pain psychologist or a pain management program is not about proving the pain is in your head. It is about the nervous system, pacing, sleep, and the enormous mental load of living like this, and the good programs help with the pain itself and not only with the feelings about it.

When it is affecting your mood

Living with unexplained pain wears people down, and low mood and anxiety commonly arrive alongside it. If you are sleeping badly, withdrawing, or finding it hard to imagine things improving, please tell your doctor, and consider a therapist who works with chronic illness. If you ever have thoughts of not wanting to be here, please reach out that day. In the US you can call or text 988 at any time. You deserve to be believed, and to be helped, whether or not anyone has yet found the name for what is happening.', array['Body', 'Resilience']::text[], 0, '2026-09-24T14:00:00+00:00'::timestamptz),
  ('spending-the-holidays-with-family-you-find-hard', 'Spending the Holidays With Family You Find Hard', 'Four days in the house you grew up in, with the people who can still reduce you to fifteen. How to plan the visit so you leave it intact, and what to do when it goes wrong anyway.', 'The dates are booked. You will be in that house, with those people, for several days, sleeping in a room that still has your old posters in it. And you already know roughly how it will go: the comment about your job, the thing your brother always does, the moment you hear yourself answering in a voice you have not used since you were fifteen.

Family visits are hard in a specific way. Everyone reverts. The roles you were assigned as a child are still lying around the house, and within an hour everyone has picked theirs back up.

Here is how to plan one that costs you less.

Decide in advance what you actually want

Not what a perfect visit looks like. What would count as a good enough one? Usually something modest: I want to see my parents, I want to leave without a fight, I want two real conversations.

Naming that ahead of time is useful, because in the moment you will be tempted by other goals, being understood, winning the argument, getting someone to finally admit something, and those are the goals that turn a visit into a wreck.

Shorten it and get your own exit

The single most effective change most people make is going for less time and staying somewhere else. Three days instead of six. A hotel or a rental instead of the spare room. Your own car rather than being driven.

This feels like a rejection and it usually improves everything, because it means the visit has an end you control and you can leave when you have had enough, which makes the time you are there far more pleasant for everyone.

Plan the day with structure

Unstructured hours in a tense house are where things go wrong. Put things in the day: a walk after lunch, a specific errand, a movie in the evening, an hour when you take the dog out alone. Activity gives everyone something to do besides each other, and gives you a legitimate way to step out.

Have your lines ready

You know which topics come up. Prepare a short, warm, unhooked answer for each, and use it every time rather than engaging.

We are not discussing that this week, but tell me about the garden. I know you see it differently. That is a bigger conversation than today. I am not going to talk about that, I love you, can you pass the salt.

The trick is to be pleasant and completely unmovable, and to change the subject immediately. Do not explain your reasons; explaining invites debate. Repeat the same sentence calmly as many times as needed.

Plan your exits, too

Know in advance where you can go for ten minutes: outside, the store, a walk, the car. Use them before you need them, not after. Most blowups happen at hour six of unrelieved contact.

Watch for the moment you revert

There is usually a specific moment when you drop back into the old role: the peacemaker, the scapegoat, the one who manages everyone''s feelings, the child who defends themselves. When you feel it, try naming it silently: there it is, I am doing the old thing.

That small noticing is often enough to give you a choice about what to do next, which is the whole of it.

Decide what you will not do this year

You do not have to relitigate the past at Christmas dinner. You do not have to correct every false claim about your life. You do not have to attend every event, cook everything, or be the one who smooths it over. Pick one or two things you are letting go of before you arrive.

If you have a partner or children with you

Agree on a signal and a plan before you get there: how long you are staying, what you will do if it gets bad, a word one of you can say that means help me get out of this conversation. A partner who knows the plan is a huge asset. A partner who is surprised in the middle of it is another problem to manage.

If your children are present, remember they are watching how you handle it, and that protecting them from the sharper edges of your family is entirely within your rights.

Plan the landing

The day after can be worse than the visit. Leave a buffer: do not fly home and go straight to work. Arrange something restorative, and arrange to talk to someone who knows what the visit is like for you. Expect to feel flattened for a day or two; that is the cost coming due, not evidence that you handled it badly.

When it is right not to go

Some families are not simply difficult. If visiting means exposure to someone who abused you, to genuine cruelty, or to a level of contempt that leaves you unwell for weeks, you are allowed not to go. Not this year, or not at all. That choice comes with guilt and with pressure from relatives, and it is still yours to make.

When to get help

If the approach of a family visit produces dread for weeks, if you come back from them depressed or unable to function, or if being around your family stirs up memories that are hard to handle, please talk to a therapist, ideally before the trip rather than after. Working out in advance what you will and will not do, with someone who has no stake in your family, makes an enormous difference. You are an adult now, even in that house, and you get to decide the terms.', array['Boundaries', 'Family']::text[], 0, '2026-09-24T14:00:00+00:00'::timestamptz),
  ('drinking-more-than-you-meant-to', 'Drinking More Than You Meant To', 'It is not dramatic. It is one glass becoming three most nights, and a quiet unease about it. How to look at your drinking honestly, without a label, and what to change first.', 'Nothing has gone badly wrong. You hold down your job, nobody has staged an intervention, and by any dramatic standard you are fine. But you have noticed that the one glass while cooking has become three by bedtime, most nights. You have noticed that you plan around it a little. You have had the thought, more than once, that you would like to cut back, and then not cut back.

That quiet unease is worth taking seriously, precisely because nothing dramatic has happened. Most people who change their drinking do it at this stage, not after a catastrophe.

Drop the labels for a minute

A lot of people avoid looking at this because the only frame on offer seems to be a binary: either you have a serious problem or there is nothing to discuss. That framing keeps people stuck, because most drinking sits on a wide range, and you do not need to accept any label to decide you would like less of it.

The only question that matters is this one: is alcohol giving me more than it is costing me, honestly?

Look at what it is doing for you

This is the most useful question, and it is not rhetorical. Alcohol is doing something, or you would not keep reaching for it. Usually one of a few things.

Ending the day. It is the switch between work and home, the signal that the shift is over. For many people this is the whole of it.

Turning the volume down. On anxiety, on a racing mind, on physical tension. It works quickly, which is why it is hard to replace.

Getting through people. Social events, family, anything where being comfortable is difficult.

Not feeling something. Grief, loneliness, boredom, a situation you have not dealt with.

Whatever yours is, that need is real, and it will need another answer, because taking away the drink without meeting the need rarely lasts.

Look at the cost, plainly

Sleep, first. Alcohol puts you to sleep and then fragments the second half of the night, which is why you wake at four and why you are tired regardless of hours in bed.

Mood, second. It reliably raises anxiety the following day, which increases the reason to drink the following evening. A great many people who think they have an anxiety problem plus a drinking habit find the anxiety drops substantially a few weeks after the drinking does.

Then the quieter things: the evenings you do not fully remember, the conversations you were not really present for, the money, the shame that follows you around the next morning and that you cannot quite name.

Get the actual numbers

Estimates are always low. For two weeks, write down every drink, with the real measure rather than the polite one, and the time. Do not change anything yet. Just count.

Almost everyone is surprised. That surprise is the most useful piece of information you will get, and it is much more persuasive than anything anyone else could tell you.

Change one thing first

Not everything. Pick one: no drinking on weeknights, or nothing before eight, or two drinks maximum with the count written down, or three alcohol-free days a week that you choose in advance.

Then notice what happens, and especially notice how hard it is. If a modest limit turns out to be very difficult to keep, that is not a failure; it is important information about how much of a grip the habit has.

Replace the ritual, not just the drink

The glass is often a ritual more than a substance: the sound, the pause, the marker of an ending. Replace the ritual and the change gets much easier. Something in a proper glass. A shower at the end of the day. A walk at six. The first ten minutes of something you look forward to.

Expect the evenings to feel strange

The first couple of weeks of drinking less are often flat and restless, and sleep can be worse before it is better. That is temporary and it is the part where most attempts stop. Knowing it is coming helps.

Tell one person

Shame keeps this private, and private habits are much harder to change. Telling one person what you are trying, and asking them to check in, roughly doubles the odds of it sticking. It also breaks the loop where drinking creates shame which makes you want a drink.

When to get real help

Please talk to a doctor if you drink daily and heavily, if you have ever felt shaky, sweaty, or sick when you stopped, or if you drink first thing. Stopping suddenly after heavy daily use can be genuinely dangerous, and it needs medical supervision rather than willpower.

And please talk to a doctor or a therapist if you have tried to cut back and could not, if drinking is affecting your work or the people you love, or if it is tangled up with low mood, anxiety, or something painful you are keeping at bay. There are effective treatments, including medications many people have never heard of, and support that looks nothing like what you may be imagining. Wanting less of something is a good enough reason to ask for help. You do not need to have lost anything first.', array['Habits', 'Shame']::text[], 0, '2026-09-24T14:00:00+00:00'::timestamptz),
  ('waking-up-in-a-panic', 'Waking Up in a Panic', 'You come out of sleep with your heart hammering and no idea why. Night panic is frightening and poorly understood by most people who have it. What it is, and what to do at three in the morning.', 'You were asleep. Now you are sitting up in the dark with your heart pounding, sweating, short of breath, certain something is terribly wrong. There was no nightmare you can remember. Nothing happened. And the worst part is the conviction, in that moment, that this is a heart attack or that you are about to die.

It passes. Then you lie awake for two hours, and the next night you go to bed slightly afraid of your own sleep.

Night panic is more common than most people realize, and almost nobody talks about it, partly because it sounds unbelievable in daylight.

What is happening

This is a panic attack that begins during sleep, usually in the earlier, deeper part of the night rather than out of dreaming. The same alarm system fires: adrenaline, racing heart, fast breathing, sweating, a feeling of unreality or doom.

Because you were asleep, there is no triggering thought to explain it, which makes it more frightening, not less. Your mind wakes into a body already in full alarm and immediately starts looking for the emergency. Finding none in the room, it concludes the emergency must be inside you: your heart, your breathing, your brain.

It is not dangerous. It peaks within minutes and subsides, the same way a daytime attack does. But the fear of it can quickly reorganize your whole relationship with going to bed.

What to do in the moment

Name it, out loud if you can. This is a panic attack. It is not dangerous. It will pass in a few minutes. Naming it gives the frightened part of you something accurate to hold.

Do not fight it. Trying to force your heart to slow or your breathing to normalize adds effort and usually prolongs it. Let the wave be there.

Breathe out longer than in. In for four, out for six or eight. The long exhale is the part that signals safety to your nervous system. Do not take big gulping breaths; over-breathing makes the dizziness and tingling worse.

Get your feet on the floor. Sit on the edge of the bed. Press your soles down. Name five things you can see in the dark room.

Cool your face or hands. Cold water at the sink is one of the fastest physical interrupts there is.

Get up rather than lying there. Go to another room, low light, something dull. Lying in bed waiting for it to pass teaches your brain to associate the bed with panic.

What to do afterward

Do not go back to bed until you feel sleepy. Sit somewhere quiet with a book or something undemanding, no bright screens, and go back when your body is ready. Twenty minutes of boredom is better than two hours of lying there tense.

In the morning, resist the urge to spend the day analyzing it. Note it and get on with the day. The more significance the episode is given, the more likely it is to repeat.

Reduce the conditions that make it likely

Night panic gets more frequent with a few reliable things: alcohol in the evening, which fragments the second half of the night and spikes adrenaline; caffeine too late; sleep deprivation, which makes the alarm system twitchier; and a stretch of unrelieved stress with no outlet during the day.

Look at all four honestly. Many people find the frequency drops substantially by changing one or two of them.

Stop bracing at bedtime

Once you have had a few, you start going to bed watchful, checking your heart, alert for the first sign. That vigilance is itself arousing and makes an episode more likely, which is the loop that turns two episodes into a pattern.

It helps to have a plan you trust, which is most of what is written above, and then to go to bed intending to sleep rather than to monitor. If it comes, you know what to do. That stance does more than any amount of trying to prevent it.

Get the physical causes ruled out, once

A few physical things can cause similar night-time symptoms, including sleep apnea, thyroid problems, heart rhythm issues, reflux, and some medications. It is worth one conversation with your doctor to check, partly for your health and partly so you can stop wondering at three in the morning. Do this once and then let it be settled.

When it goes further

If the episodes are frequent, if you have started dreading sleep, if you are avoiding going to bed, or if daytime panic has begun too, please talk to your doctor or a therapist. Panic responds extremely well to treatment, usually within months, and the treatment is largely a structured version of the approach above. And if the sleeplessness and fear have you feeling hopeless, or if you ever have thoughts of harming yourself, please reach out that day. In the US you can call or text 988 at any time. Sleep is supposed to be the safest part of your day. It can be that again.', array['Panic', 'Sleep']::text[], 0, '2026-09-24T14:00:00+00:00'::timestamptz)
on conflict (slug) do update set
  title        = excluded.title,
  excerpt      = excluded.excerpt,
  body_md      = excluded.body_md,
  tags         = excluded.tags,
  min_level    = 0,
  published_at = excluded.published_at;
