-- =============================================================================
-- 188 more mandalas, for 200 in all.
-- -----------------------------------------------------------------------------
-- Like the first 12 (mandala_seeds, 2026-08-27), each is drawn in the browser
-- from its seed by site/assets/mandala.js; nothing is stored but the seed, a
-- title and a slug. The seeds were chosen so that every figure has four or
-- five rings, fills the page, has between 40 and 80 colorable shapes, and no
-- two share the same sequence of ring styles.
--
-- Premium, like the others (min_level defaults to 3). Re-running is harmless:
-- a slug that already exists is left alone.
-- =============================================================================

insert into public.mandalas (slug, title, seed) values
  ('still-pond', 'Still Pond', 1537),
  ('gentle-tide', 'Gentle Tide', 1574),
  ('warm-stone', 'Warm Stone', 1611),
  ('long-exhale', 'Long Exhale', 1648),
  ('soft-landing', 'Soft Landing', 1722),
  ('clear-morning', 'Clear Morning', 1759),
  ('low-tide', 'Low Tide', 1796),
  ('deep-roots', 'Deep Roots', 1833),
  ('slow-sunrise', 'Slow Sunrise', 1870),
  ('quiet-garden', 'Quiet Garden', 1907),
  ('open-hands', 'Open Hands', 1944),
  ('evening-calm', 'Evening Calm', 1981),
  ('golden-hour', 'Golden Hour', 2018),
  ('kind-words', 'Kind Words', 2055),
  ('safe-harbor', 'Safe Harbor', 2129),
  ('fresh-start', 'Fresh Start', 2166),
  ('green-meadow', 'Green Meadow', 2203),
  ('wide-horizon', 'Wide Horizon', 2240),
  ('resting-place', 'Resting Place', 2277),
  ('soft-rain', 'Soft Rain', 2351),
  ('night-sky', 'Night Sky', 2388),
  ('inner-light', 'Inner Light', 2425),
  ('slow-bloom', 'Slow Bloom', 2462),
  ('easy-breathing', 'Easy Breathing', 2499),
  ('autumn-leaf', 'Autumn Leaf', 2536),
  ('spring-rain', 'Spring Rain', 2573),
  ('summer-shade', 'Summer Shade', 2610),
  ('winter-hush', 'Winter Hush', 2647),
  ('calm-waters', 'Calm Waters', 2684),
  ('rising-sun', 'Rising Sun', 2721),
  ('full-moon', 'Full Moon', 2758),
  ('new-moon', 'New Moon', 2832),
  ('sea-glass', 'Sea Glass', 2869),
  ('river-stone', 'River Stone', 2906),
  ('mountain-air', 'Mountain Air', 2943),
  ('forest-floor', 'Forest Floor', 2980),
  ('meadow-path', 'Meadow Path', 3054),
  ('orchard-walk', 'Orchard Walk', 3091),
  ('lantern-glow', 'Lantern Glow', 3128),
  ('candle-light', 'Candle Light', 3165),
  ('hearth-fire', 'Hearth Fire', 3202),
  ('morning-tea', 'Morning Tea', 3239),
  ('slow-sunday', 'Slow Sunday', 3276),
  ('blue-hour', 'Blue Hour', 3313),
  ('silver-lining', 'Silver Lining', 3350),
  ('steady-ground', 'Steady Ground', 3387),
  ('open-window', 'Open Window', 3424),
  ('gentle-hands', 'Gentle Hands', 3461),
  ('whole-heart', 'Whole Heart', 3498),
  ('clear-mind', 'Clear Mind', 3535),
  ('soft-focus', 'Soft Focus', 3572),
  ('quiet-strength', 'Quiet Strength', 3609),
  ('patient-growth', 'Patient Growth', 3646),
  ('simple-joy', 'Simple Joy', 3683),
  ('warm-welcome', 'Warm Welcome', 3720),
  ('kind-heart', 'Kind Heart', 3757),
  ('light-step', 'Light Step', 3794),
  ('fair-weather', 'Fair Weather', 3831),
  ('tall-grass', 'Tall Grass', 3868),
  ('wild-clover', 'Wild Clover', 3905),
  ('lavender-field', 'Lavender Field', 3942),
  ('honeycomb', 'Honeycomb', 3979),
  ('dandelion-wish', 'Dandelion Wish', 4016),
  ('sunflower-turn', 'Sunflower Turn', 4053),
  ('lotus-rising', 'Lotus Rising', 4090),
  ('fern-unfurling', 'Fern Unfurling', 4127),
  ('ripple-effect', 'Ripple Effect', 4164),
  ('tidal-pool', 'Tidal Pool', 4201),
  ('sand-dollar', 'Sand Dollar', 4238),
  ('starfish-bay', 'Starfish Bay', 4275),
  ('morning-dew', 'Morning Dew', 4312),
  ('cloud-drift', 'Cloud Drift', 4349),
  ('snowfall', 'Snowfall', 4386),
  ('ember-glow', 'Ember Glow', 4423),
  ('sunlit-room', 'Sunlit Room', 4460),
  ('held-gently', 'Held Gently', 4497),
  ('good-enough', 'Good Enough', 4534),
  ('letting-go', 'Letting Go', 4571),
  ('slowing-down', 'Slowing Down', 4608),
  ('breathing-room', 'Breathing Room', 4645),
  ('homeward', 'Homeward', 4682),
  ('unhurried', 'Unhurried', 4719),
  ('here-now', 'Here Now', 4756),
  ('grounded', 'Grounded', 4793),
  ('at-ease', 'At Ease', 4830),
  ('enough-for-today', 'Enough for Today', 4867),
  ('gentle-reminder', 'Gentle Reminder', 4904),
  ('easy-does-it', 'Easy Does It', 4941),
  ('morning-walk', 'Morning Walk', 4978),
  ('evening-walk', 'Evening Walk', 5015),
  ('harbor-light', 'Harbor Light', 5052),
  ('porch-light', 'Porch Light', 5089),
  ('window-seat', 'Window Seat', 5126),
  ('garden-gate', 'Garden Gate', 5163),
  ('stone-path', 'Stone Path', 5200),
  ('wooden-bridge', 'Wooden Bridge', 5237),
  ('quiet-room', 'Quiet Room', 5274),
  ('warm-blanket', 'Warm Blanket', 5311),
  ('slow-morning', 'Slow Morning', 5348),
  ('late-summer', 'Late Summer', 5385),
  ('early-spring', 'Early Spring', 5422),
  ('first-frost', 'First Frost', 5459),
  ('last-light', 'Last Light', 5496),
  ('soft-dawn', 'Soft Dawn', 5533),
  ('dusk-settling', 'Dusk Settling', 5570),
  ('starlight', 'Starlight', 5607),
  ('moonrise', 'Moonrise', 5644),
  ('sunset-glow', 'Sunset Glow', 5681),
  ('ocean-breath', 'Ocean Breath', 5718),
  ('sea-breeze', 'Sea Breeze', 5755),
  ('shoreline', 'Shoreline', 5792),
  ('driftwood', 'Driftwood', 5829),
  ('pebble-beach', 'Pebble Beach', 5866),
  ('coral-reef', 'Coral Reef', 5903),
  ('kelp-forest', 'Kelp Forest', 5977),
  ('salt-air', 'Salt Air', 6014),
  ('marsh-grass', 'Marsh Grass', 6051),
  ('willow-shade', 'Willow Shade', 6088),
  ('maple-turn', 'Maple Turn', 6125),
  ('pine-needle', 'Pine Needle', 6162),
  ('cedar-grove', 'Cedar Grove', 6199),
  ('birch-bark', 'Birch Bark', 6236),
  ('oak-shelter', 'Oak Shelter', 6273),
  ('wildflower', 'Wildflower', 6347),
  ('clover-field', 'Clover Field', 6384),
  ('poppy-field', 'Poppy Field', 6421),
  ('rose-garden', 'Rose Garden', 6458),
  ('tulip-row', 'Tulip Row', 6495),
  ('daisy-chain', 'Daisy Chain', 6532),
  ('iris-bloom', 'Iris Bloom', 6569),
  ('peony-open', 'Peony Open', 6606),
  ('magnolia', 'Magnolia', 6643),
  ('jasmine-night', 'Jasmine Night', 6680),
  ('chamomile', 'Chamomile', 6717),
  ('mint-leaf', 'Mint Leaf', 6754),
  ('sage-brush', 'Sage Brush', 6791),
  ('rosemary', 'Rosemary', 6828),
  ('thyme-patch', 'Thyme Patch', 6865),
  ('rain-barrel', 'Rain Barrel', 6902),
  ('stone-well', 'Stone Well', 6939),
  ('spring-water', 'Spring Water', 6976),
  ('creek-bend', 'Creek Bend', 7013),
  ('waterfall', 'Waterfall', 7050),
  ('mist-rising', 'Mist Rising', 7087),
  ('fog-lifting', 'Fog Lifting', 7124),
  ('rainbow-arc', 'Rainbow Arc', 7161),
  ('sun-shower', 'Sun Shower', 7198),
  ('thunder-passing', 'Thunder Passing', 7235),
  ('snow-quiet', 'Snow Quiet', 7272),
  ('ice-melt', 'Ice Melt', 7309),
  ('thaw', 'Thaw', 7346),
  ('seedling', 'Seedling', 7383),
  ('sprout', 'Sprout', 7420),
  ('new-leaf', 'New Leaf', 7457),
  ('harvest-moon', 'Harvest Moon', 7568),
  ('wheat-field', 'Wheat Field', 7605),
  ('apple-orchard', 'Apple Orchard', 7642),
  ('pumpkin-patch', 'Pumpkin Patch', 7716),
  ('hay-loft', 'Hay Loft', 7753),
  ('barn-swallow', 'Barn Swallow', 7790),
  ('robin-song', 'Robin Song', 7827),
  ('wren-nest', 'Wren Nest', 7864),
  ('heron-still', 'Heron Still', 7901),
  ('owl-watch', 'Owl Watch', 7938),
  ('butterfly-rest', 'Butterfly Rest', 7975),
  ('firefly-night', 'Firefly Night', 8012),
  ('cricket-song', 'Cricket Song', 8049),
  ('honey-bee', 'Honey Bee', 8086),
  ('ladybug', 'Ladybug', 8160),
  ('snail-pace', 'Snail Pace', 8197),
  ('turtle-shell', 'Turtle Shell', 8234),
  ('koi-pond', 'Koi Pond', 8271),
  ('lily-pad', 'Lily Pad', 8308),
  ('cattail', 'Cattail', 8345),
  ('reed-bed', 'Reed Bed', 8382),
  ('duck-pond', 'Duck Pond', 8419),
  ('swan-lake', 'Swan Lake', 8456),
  ('hummingbird', 'Hummingbird', 8493),
  ('feather-light', 'Feather Light', 8530),
  ('warm-nest', 'Warm Nest', 8567),
  ('kite-day', 'Kite Day', 8604),
  ('paper-boat', 'Paper Boat', 8641),
  ('pinwheel', 'Pinwheel', 8678),
  ('wind-chime', 'Wind Chime', 8715),
  ('hammock', 'Hammock', 8752),
  ('picnic-blanket', 'Picnic Blanket', 8789),
  ('sunday-nap', 'Sunday Nap', 8826),
  ('slow-dance', 'Slow Dance', 8863)
on conflict (slug) do nothing;
